### ISSUE TITLE
Wrong disease mappings because find_term() in OnToma uses lowercase

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/issues#1306]
When mapping disease names to EFO using the [find_term](https://github.com/opentargets/OnToma/blob/master/ontoma/interface.py#L411-L452) method in OnToma, the [query strings are converted into lowercase](https://github.com/opentargets/OnToma/blob/master/ontoma/interface.py#L511) which causes that some perfect matches are mapped to the incorrect id or require further steps to get the right answer:

1. Incorrect mapping: `Dystonia` should be mapped to [HP_0001332 - "Dystonia"](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001332) but it's mapped to [MONDO_0003441 - "dystonic disorder"](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003441) instead because the query is converted to `dystonia`, which is a literal synonym of the latter.

![Screenshot 2020-12-18 at 12 35 09](https://user-images.githubusercontent.com/11410715/102615536-0568fe00-412e-11eb-96bf-3145d4de0d43.png)

2. Further steps needed: When searching for `COVID-19` the mapping is obtained via the OLS API when the mapping to [MONDO_0100096 - "COVID-19"](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100096) should be straighforward.

We need to review whether the conversion to lowercase is needed. If not it should be removed and if it is, some actions should be taken to mitigate the issue.

**Comment by AsierGonzalez** [comment]
As a note, according to Zoe from EFO, ontologically it makes sense for the term labels and synonyms to be in lower-case except when they are acronyms (e.g. `COVID-19`) or derive from names (e.g. `Parkinson's disease`). This is something they want to review in the future.

**Comment by d0choa** [comment]
Can we gather your thoughts on this @tskir? Shall we close it?

**Comment by tskir** [comment]
Just one more comment though to wrap this up. The situation where the same exact string serves both as a name of a term and also as an exact synonym of **another** term is problematic in any case. I can't imagine a valid scenario where this should occur.

This particular example ([dystonia](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001332) vs. [dystonic disorder](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003441)) appears to be a possible duplication bug in EFO, I've reported it here: https://github.com/EBISPOT/efo/issues/1637
