### ISSUE TITLE
Validation steps: overview

### ISSUE THREAD

**Issue by cmalangone** [opentargets/issues#1314]
Validation steps to design and to implement for the new pipeline

**Validation ES - ETL**:
The output of the ETL are json files. These files are loaded into the ES with shell scripts.
Currently there is no mechanism to check if the number of documents is correct.

**Proposal**:
Add to the script a check.
Count the lines of the JSON files and compare it to the number of the documents in the ES

**Check the constrains between index**:
Currently we do not have any mechanisms to check the integrity of the data.
For instance, the disease index contains "HP" terms and these terms must be present in the hpo index.

**Options**:
*) Test the ETL output
*) Test the GraphQL (localhost required: Integrate test)
*) Validation project

The team should discuss the different options.

**Comment by ktsirigos** [comment]
@cmalangone is this still relevant or can be closed?

**Comment by cmalangone** [comment]
Still relevant :)

**Comment by JarrodBaker** [comment]
One way to check ES counts:

```
/**
  * Compare ES index counts
  *
  * Execute `curl --location --request GET 'http://localhost:9201/_cat/indices?v' > file.txt` to get file counts for new
  * and old ES instances. Then run this script.
  */

import scala.io.Source

val oldRelease = "2111.txt"
val newRelease = "2202.txt"

val indexes = (f: String) => Source.fromFile(f).getLines.toList.tail.map(_.split(" ").filter(_.nonEmpty))
  .map(ln => (ln(2), ln(6).toInt)).toMap


val o: Map[String, Int] = indexes(oldRelease)
val n: Map[String, Int] = indexes(newRelease) 

// negative values mean fewer entries in this release than the last.
n.keys.map(k => (k, n(k) - o(k))).toMap
```

**Comment by d0choa** [comment]
Remember a comprehensive list of similar metrics are obtained for the ETL datasets:
 https://github.com/opentargets/ot-release-metrics

**Comment by mbdebian** [comment]
Could we turn the metrics into a black box (docker based would be perfect) that, given an ES server (and potentially a Clickhouse server as well) and the ETL output location, it ways either "Ok" or "ERROR"?

**Comment by mbdebian** [comment]
In any case I think we should close this ticket and rephrase, as new tickets, the validation needs from the point of view of the orchestration architecture that will power the platform lifecycle automation.
@d0choa , @JarrodBaker ?
