### ISSUE TITLE
Merge all manually curated phenotypes mappings

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1400]
_Below summary added and maintained by @tskir_ 

### Done
- [x] Reach out to OntoString about participating in beta testing
- [x] Report the issue with some "replaced by" terms being outside the slim: https://github.com/EBISPOT/efo/issues/1595
- [x] Report the issue with processing "replaced by" terms: https://github.com/althonos/pronto/issues/169
- [x] Write and debug manual mapping database maintenance script: https://github.com/opentargets/curation/pull/3
- [x] Write documentation for maintaining manual mappings
- [x] Aggregate all existing mappings
- [x] Submit the final PR: https://github.com/opentargets/curation/pull/4

**Comment by ireneisdoomed** [comment]
I have updated the spreadsheet in which for each data source the disease mapping process is outlined.
https://docs.google.com/spreadsheets/d/1vtDB7reA8-IDcgJSqjoL5e_JkyqY8728XVYnJW-qBj4/edit#gid=0

In this case, the SPOT team is interested in the tables that we have curated for mapping traits. The current situation is that OT is one of the sources of manual curation available in Zooma, but [the table they are using ](https://github.com/opentargets/platform_semantic/blob/master/resources/zooma/cttv_indications.csv)is essentially obsolete. As you can see in that repo, we have 3 different versions of `cttv_indications`. Of these 3, `cttv_indications_3.txt` is the latest and used by Panel App. I have updated a few of these mappings but none of them is integrated into Zooma.

The idea is to provide them with a table of all the manual mappings that we are using at the moment so they can make use of it. For that, I would merge all the curation efforts from the files referenced in the above-mentioned spreadsheet for the `internal` data sources where the mapping approach is `manual`.

**Comment by ireneisdoomed** [comment]
We also have curated disease mappings in the target safety dataset under the `EFO_mapping` sheet.  

https://docs.google.com/spreadsheets/d/1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0/edit#gid=1717378859

**Comment by DSuveges** [comment]
When this work is done, we have to make sure the data in pooled in one single repository and decide what would happen to other files/repos. eg. [platform-semantic](https://github.com/opentargets/platform_semantic)

**Comment by ireneisdoomed** [comment]
More disease manual curation:

Traits found in the new evidence source for cancer biomarkers have also been mapped to EFO with manual curation. This dataset can be found here `gs://otar000-evidence_input/CancerBiomarkers/data_files/cancer_biomarker_disease.jsonl`.

I have run the latest version of Ontoma on these traits to see if we can avoid using the manual mapping file and while the coverage is very good, around 22 of them still cannot be mapped automatically.

In this table you can find see which of them have been successfully mapped:
[https://app.zenhub.com/files/143733948/ea7fbd99-f2b8-4d7c-a7a0-27b41bff83ad/download](https://app.zenhub.com/files/143733948/ea7fbd99-f2b8-4d7c-a7a0-27b41bff83ad/download)

I propose to include those that are not automatically mapped to the table that integrates all manual curation so that this can then be plugged into OnToma's logic.

**Comment by DSuveges** [comment]
Upon reviewing the mappings, the zooma file needs to be updated and completed with the rest of the mapping. That file is fetched by zooma to improve their mappings.

**Comment by d0choa** [comment]
@DSuveges status on this?

**Comment by ireneisdoomed** [comment]
An important note, as noted by @d0choa, EFO has obsoleted some terms in favor of their MONDO counterparts (more at [#1381](https://github.com/EBISPOT/efo/issues/1381)).

We should make sure we update the manual mappings to the latest ID.

**Comment by tskir** [comment]
Issues with following the "replaced by" links highlighted in https://github.com/EBISPOT/efo/issues/1595, https://github.com/althonos/pronto/issues/169.

Basics for the merging and normalisation of manual mappings set up in https://github.com/opentargets/curation/pull/3.

All suitable manual mapping sources merged in https://github.com/opentargets/curation/pull/4.

Once that PR is closed, this issue may be consedered complete.

However, some ongoing (low-priority) improvement tasks will remain, such as following up with SPOT and EVA/ClinVar team on the OntoString development & integration. These will be tracked separately.

**Comment by ireneisdoomed** [comment]
@tskir About the genetics mappings, [this comment](https://github.com/opentargets/issues/issues/2012#issuecomment-951011289) recapitulates their different locations and how they are processed:

> The disease mapping LUT merges all the curation from 4 diff sources:
  - Finngen mappings are extracted from those tagged as valid in the [spreadsheet](https://docs.google.com/spreadsheets/d/1yrQPpsRi-mijs_BliKFZjeoxP6kGIs9Bz-02_0WDvAA/edit#gid=727861176).
  - UK Biobank mappings are extracted from 2 sources.
  2.1. The initial curation file: gs://genetics-portal-input/ukb_phenotypes/ukb_efo_annotation-2021-10-25.json (updated to add the reported trait in a new column)
  2.2. The reviewed curation [spreadsheet](https://docs.google.com/spreadsheets/d/1PotmUEirkV36dh-vpZ3GgxQg_LcOefZKbyTq0PNQ6NY/edit?usp=sharing) - where some mappings have been updated to EFO3 terms and some have been marked as incorrect.
  The result is: the original mappings + updated mappings - incorrect mappings
  - GWAS Catalog are extracted from the study index.

GWAS Catalog traits are not manual, so you can forget about it.
Finngen's spreadsheet updated since that comment, the one with the version 6 traits is: https://docs.google.com/spreadsheets/d/1RRWfUTLy4TO9XmBzcbJ2wPRdda3qISjRS4PJmEdxE3k/edit#gid=1853278839
