### ISSUE TITLE
Define AOP data model

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#1442]
Validated Adverse Outcome Pathways coming from AOPwiki provide proteins involved in key molecular initiating events (MIEs).  As part of the target safety project, we want to create two different datasets from the information described in AOPwiki, one for AOPs and another for MIEs, to be integrated into the target object.

The plan is to explore with the support of @BZdrazil a schema to accommodate the relevant information coming from AOPwiki.

The ongoing schema review can be found here:
https://docs.google.com/spreadsheets/d/1OZidpR3kQIp1-FOU49PQQXgvSwL2kbM4GPTmvGqhPUU/edit?usp=sharing

**Comment by ireneisdoomed** [comment]
A first iteration of these two datasets has been generated and is available here:
- AOPs dataset: `gs://ot-team/jarrod/aopV1/`
- Key Events dataset: `gs://ot-team/jarrod/keV1/`

Both have been reviewed and although they need minor changes, the proposed schema seems to be compliant with the data. 

More details to follow on [#1605](https://github.com/opentargets/platform/issues/1605)

**Comment by d0choa** [comment]
I consider the data model defined. Action is following in #1605
