### ISSUE TITLE
Updating STRING interactions 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1509]
As the `homology` column is missing from the input file we are using by default (`9606.protein.links.detailed.v11.0.txt.gz`) a patch was applied for the 21.04 release: the manually updated file was uploaded to a google bucket. This practice is not desired and should be phased out. 

Instead the `detailed.` file, the `9606.protein.links.full.v11.0.txt.gz` should be used. The only caveat is that the columns with the direct data and the transferred data need to be summarised to get the actual scores. These values are Bayesian probabilities (multiplied by 1000) summarising them is not trivial. 

This script describes how to do the summary: https://stringdb-static.org/download/combine_subscores.py

**Example:** Let's see the interaction between PAF1 (ENSP00000221265) and CTR9 (ENSP00000355013) 

The STRING [website](https://string-db.org/cgi/network?taskId=bBgKnAaGkdYW&sessionId=bF9sD8BePOmj) shows the following scores (exactly what we have on our website molecular interactions):

* coexpression: 0.308
* Experiments: 0.977
* Databases: 0.900
* Textmining: 0.791
* Combined score: 0.999

This is what the "full" download file has for this interaction:

```
{
    "protein1":"9606.ENSP00000221265",
    "protein2":"9606.ENSP00000355013",
    "neighborhood":0,
    "neighborhood_transferred":0,
    "fusion":0,
    "cooccurence":0,
    "homology":0,
    "coexpression":102,
    "coexpression_transferred":262,
    "experiments":893,
    "experiments_transferred":797,
    "database":900,
    "database_transferred":0,
    "textmining":470,
    "textmining_transferred":622,
    "combined_score":999
  }
```

To get combined scores `textmining`, `databases` etc. needs to be combined with `textmining_transferred`, `database_transferred` etc. counterparts. From the above linked python script I could simplified a function to do the summary:

```python
def bayesian_addition(prob1, prob2, prior=0.041):
    '''
    Adding two Bayesian probabilities together given a known prior applied to both
    '''
    
    if prob1 == 0:
        return prob2
    
    if prob2 == 0:
        return prob1
    
    prob1 = prob1 / 1000
    prob2 = prob2 / 1000
    
    summarized_proability = (prior + prob1 * prob2 - prob2 - prob1)/(prior-1)
    
    return int(summarized_proability*1000)
```

Applying this function on the above example:

```python
scores_dict = {
    "neighborhood":0,
    "neighborhood_transferred":0,

    "coexpression":102,
    "coexpression_transferred":262,

    "experiments":893,
    "experiments_transferred":797,

    "database":900,
    "database_transferred":0,

    "textmining":470,
    "textmining_transferred":622,
}

for x in ['neighborhood', 'coexpression', 'experiments', 'database', 'textmining']:
    sum_prob = bayesian_addition(scores_dict[x], scores_dict[f'{x}_transferred'])
    print(f'{x} => {sum_prob}')
```

We get the expected summarized scores:
```
neighborhood => 0
coexpression => 308
experiments => 977
database => 900
textmining => 791
```

This way we could generate scores for all complex detection methods + get the missing homology. The summarised score based on all sources is already calculated, there's no need to calculate that.

**Comment by DSuveges** [comment]
As the above process is still not yet implemented, we are applying the patch, when the homology column is added from the `full` set from the `detailed` dataset. Then the resulting dataset is saved into a google bucket available for PIS.

```python
# Reading 'detailed' dataset:
detailed_url = 'https://stringdb-static.org/download/protein.links.detailed.v11.0/9606.protein.links.detailed.v11.0.txt.gz'
detailed_df = pd.read_csv(detailed_url, sep=' ', header=0, compression='infer')
print(f'Number of pairs in the "detailed" dataset: {len(detailed_df)}')  # 11_759_454

# Reading 'full' dataset:
full_url = 'https://stringdb-static.org/download/protein.links.full.v11.0/9606.protein.links.full.v11.0.txt.gz'
full_df = (
    pd.read_csv(full_url, sep=' ', header=0, compression='infer')
    [['protein1', 'protein2', 'homology']]
)
print(f'Number of pairs in the "full" dataset: {len(full_df)}') # 11_759_454

## Joining the two dataset:
merged_df = (
    detailed_df
    .merge(full_df, on=['protein1', 'protein2'], how='left')
)

# Number of pairs in the merged dataset: 11_759_454 <-  from v11.0 11_759_455
print(f'Number of pairs in the merged dataset: {len(merged_df)}')

# Saving data:
merged_df.to_csv('9606.protein.links.full_w_homology.v11.5.txt.gz', sep=' ', index=False, compression='infer')
```

File uploaded to `gs://ot-team/dsuveges/interactions/9606.protein.links.full_w_homology.v11.5.txt.gz`

**Comment by d0choa** [comment]
We will revisit this ticket when a new version of STRINGdb is available. Assigning to @DSuveges for the time being.

**Comment by DSuveges** [comment]
We can periodically check the release endpoint: `https://string-db.org/api/json/version` 

```json
[
{
"string_version": "11.5",
"stable_address": "https://version-11-5.string-db.org/"
}
]
```
