### ISSUE TITLE
Evidence review: collection of small-scale schema changes

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1530]
This ticket collects all changes we want to apply on the evidence schema. These changes might be small, but potentially have widespread consequences in the providers pipelines/ OT backend / front-end, so keeping this list together to properly schedule these updates is important.

### 1. Renaming `literature` field to `pmIds`

The rationale behind this update is get a field name that reflects the content better as that field can only contain a list of pubmed identifiers. Also with the introduction of `pmcIds` pubmed identifiers are not the only way we store literature references. This task has numerous consequences:

- [ ] Communicate the update to our providers.
- [ ] Update in house maintained evidence parsers.
- [ ] Update backend to ensure these fields are exposed on graph ql.
- [ ] Update frontend to fetch pubmed identifiers from the updated field.

* [ ] Change CRISPR's `direction` field name to something more specific
* [ ] Sort properties alphabetically inside each datasource definition

**Comment by d0choa** [comment]
I'm lost with this one @DSuveges

**Comment by DSuveges** [comment]
We are not working on this space. Making any change on any fields of the schema that affects data providers poses a lot of risks. When this ticket was opened, we were expecting multiple such issues would emerge and once we'll have enough, we let the providers know to update their pipelines. 

It seems the schema was relatively good, given since the opening of the issue, no other problem surfaced. We can close if we can live with the pmid vs literature vs pmcid inconsistency.
