### ISSUE TITLE
Dockerise evidence datasource parser dependencies

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#1544]

**Comment by tskir** [comment]
Information from @DSuveges -- we can check out this image as a start: https://towardsdatascience.com/optimized-docker-images-for-apache-spark-now-public-on-dockerhub-1f9f8fed1665

**Comment by d0choa** [comment]
@DSuveges what shall we do with this? assign? close?

**Comment by d0choa** [comment]
Please reopen if appropriate
