### ISSUE TITLE
Issue with subsets of diseases, targets and drugs

### ISSUE THREAD

**Issue by cmalangone** [opentargets/issues#1557]
I tried to run the ETL using a subsets of information of diseases, targets and drugs

The pipeline was not able to run due the requirements of few informations.

Report:

- Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve '`safety`' - target
- Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve '`withdrawn_year` - drug
- No such struct field hasBroadSynonym in hasExactSynonym, hasNarrowSynonym, hasRelatedSynonym; line 4 pos 30 - disease
- Search$: generate search objects for drug entity Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve '`childChemblIds` - drug

**Comment by d0choa** [comment]
This has been sitting here for a while @cmalangone. Are we still planning to work with subsets?

**Comment by cmalangone** [comment]
Yes, I am doing right now as part of PIS refactoring.
BE wants to have a CI/CD pipeline and this is a fundamental step to develop in order to achieve it.
