### ISSUE TITLE
Update drug page molecular structure image

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#1558]
On the drug profile page we show the drug molecular structure image on the right hand side.
I suggest removing the box and background around the image, and have it sit against the page background, which I think creates a bit of space, visually. It could have a little zoom icon appearing on roll over (or just be always visible).

<img width="1213" alt="drugprofile_structure_1" src="https://user-images.githubusercontent.com/8592363/118993455-703c9080-b97d-11eb-8723-5e5761ddcd80.png">

<img width="1214" alt="drugprofile_structure_2" src="https://user-images.githubusercontent.com/8592363/118993503-792d6200-b97d-11eb-9fa6-1a15fdfcd9cc.png">

**Comment by d0choa** [comment]
Sounds good to me @LucaFumis

**Comment by buniello** [comment]
The new implementation looks good to me - thank you @LucaFumis!
