### ISSUE TITLE
Document / comment `platform-app` javascript code

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#1559]
The front end React code has mostly little or no comments. I know I am a bit old-school, but I found this to be a bit of a problem especially when starting to work on the rewrite project, often having to go through code to work out the props of a particular component. 
We can discuss what needs to be commented and how (e.g. JSDoc?) to go on about it - this is just to have a reference/note for later...

**Comment by carcruz** [comment]
The FrontEnd team will address the documentation process as part of the new Monorepo implementation

https://github.com/opentargets/issues/issues/2530
