### ISSUE TITLE
Update disease ETL to process OTAR project data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1571]
The [OTAR project and EFO mapping spreadsheet](https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs) has been updated - see https://github.com/opentargets/platform/issues/1114. 

In order to demonstrate value to our consortium partners, this data should only be available for their instances. The data should not be exposed by the public GraphQL API and should not be available from the `diseases` dataset.

However, we will need to update the disease ETL to process the data and also create a front-end summary widget and detail view that will only be shown in "private-partner" deployment contexts - see https://github.com/opentargets/platform/issues/1549 for notes on the front-end work.

**Comment by andrewhercules** [comment]
Further updates to the data have been noted in #1722

**Comment by cmalangone** [comment]
ETL PR for processing the otar projects
https://github.com/opentargets/platform-etl-backend/pull/186

**Comment by cmalangone** [comment]
Next step is adding the download/upload file for otar projects step to PIS
