### ISSUE TITLE
Link target hallmark protein fusion to Ensembl gene id

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1626]
As a user I want to be able to navigate between one target's hallmark protein fusion and a related gene so I can better follow the relationship between the two. 

## Background

This ticket follows from a conversation in opentargets/platform#1537 regarding mapping fusion partners in `hallmarks` to Ensembl IDs (see comments on 12 May (David) and 18 May (Daniel). 

Some targets have an attribute `hallmarks` which contains a field `attributes`. When `hallmarks.attributes.attribute_name` is `fusion_partner` the value of d`hallmarks.attributes.description` contains a gene symbol. We can use the gene symbol to map back to an ENSG ID to link the fusion partner back to a gene. 

To see the a 'snapshot' of the relevant section:
```
val df = ss.read.parquet("<path to data>/*.parquet")

val hallmarks = df.select('id, 'hallmarks)
    .filter('hallmarks.isNotNull)
    .select('id, explode($"hallmarks.attributes"))
    .select('id, $"col.*") 

val pf = hallmarks
    .filter('attribute_name === "fusion partner")
    // some hallmarks have more than one fusion partner in comma separated string
    .withColumn("description", split('description, ",")) 
    .withColumn("description", explode('description))
    .withColumn("description", trim('description))
``` 

## Tasks

- [ ] Update ETL to map hallmarks with related targets to those targets.
- [ ] Update API to allow navigation between one target with a hallmark and another target. 

## Acceptance tests

How do we know the task is complete? 

1. When I examine a gene with a hallmark which includes a fusion protein, there is an ID linking to the fusion partner. Executing `df.select('hallmarks).printSchema` shows:

```
root
 |-- hallmarks: struct (nullable = true)
 |    |-- attributes: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- attribute_name: string (nullable = true)
 |    |    |    |-- fusion_target: string (nullable = true) << New field containing linked target ID
 |    |-- cancerHallmarks: array (nullable = true)
 |    |    |-- element: struct (containsNull = true)
 |    |    |    |-- pmid: long (nullable = true)
 |    |    |    |-- description: string (nullable = true)
 |    |    |    |-- impact: string (nullable = true)
 |    |    |    |-- label: string (nullable = true)
```
 
2. When execute the following query in the GraphQL API it returns valid data:
```
query fusionpartner {
  target(ensemblId: "ENSG00000023445") {
    id
    hallmarks {
      attributes {
        description
        fusion_target { # link to related target
          id
          approvedSymbol
        }
      }
    }
  }
}
```

**Comment by d0choa** [comment]
Only 1 minor comment:
- I would rename `fusion_target` to `fusion_partner`.

For reference a full list of gene fusions in cancer is listed here: https://cancer.sanger.ac.uk/cosmic/fusion
