### ISSUE TITLE
Make error messages emitted by opentargets-validator more helpful

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#1635]
- [ ] Showing which rule was broken
- [ ] Make it not hang
- [ ] Make sure multithreading works
- [ ] Print out the evidence string, not the repr
- [ ] Make sure the validator stays schema agnostic

**Comment by prashantuniyal02** [comment]
@tskir Is this issue still relevant and are you working/going to work on it?

**Comment by tskir** [comment]
@prashantuniyal02 Yes, it's in the backlog currently as it's technical / less prioritised, but it would be important to address at some point
