### ISSUE TITLE
Generate metrics on GraphQL API usage

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1686]
During today's team lead meeting, we discussed how we can generate metrics and reports on how our GraphQL API is used. In order to generate these reports, we would need to process and store API logs. We could then import the data into BigQuery and use Google Data Studio to generate visualisations for reports.

https://cloud.google.com/bigquery/docs/visualize-data-studio

**Comment by ktsirigos** [comment]
is this done?

**Comment by andrewhercules** [comment]
No, this requires considerable work by the back-end team to improve API logging — see #1768 for more details. Once the data has been logged, we can decide where to store it and how to access and generate reports.

**Comment by d0choa** [comment]
Can we have an update on progress on this @cmalangone and @JarrodBaker?

**Comment by d0choa** [comment]
Related to #1768
