### ISSUE TITLE
load_evidences.sh fails to load 58 FINNGEN evidences to ES as float

### ISSUE THREAD

**Issue by fedde-s** [opentargets/issues#1687]
Feeding these OT Genetics Portal-based evidences from [the 21.06 FTP ftp folder](http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.06/output/etl/json/evidence/sourceId%3Dot_genetics_portal/) to [`load_evidences.sh`](https://github.com/opentargets/platform-etl-backend/blob/21.06.5/elasticsearch/load_evidences.sh) results in log messages about exceptions, and despite retries, the 58 JSON lines listed in the exceptions fail to end up in the index. I believe these records to be missing in the public platform; for instance, no row appears [here](https://platform.opentargets.org/evidence/ENSG00000188064/HP_0001943) for the evidence with variant ID **22_45933449_C_T (22_45933449_C_T)** or [here](https://platform.opentargets.org/evidence/ENSG00000096968/EFO_0000479) about **9_5073770_G_T**.

Is this an issue?

**Comment by fedde-s** [comment]
Might be related to https://github.com/opentargets/platform/issues/1617; the exceptions are all about these lines having `oddsRatio` or `oddsRatioConfidenceIntervalUpper` values too large to fit in a single-precision floating point field.

**Comment by fedde-s** [comment]
If it helps, these are the `id` fields of the 58 JSON lines.

<details>
<summary>List of 40-character hexadecimal numbers</summary>

```
8749cf8b8049b5c057a8c0db94df6bbee2939aca
3119b2d2014fbfd1fd01316d0f6142a3594c9016
f14f8d90aadef3d3e2dac3e59e60041c16469ada
ee02c534efbe62c375b20031731434b8e0ace6f5
a6205a714fc214028da83d49844fa78b5d314747
118b5399cf177fe3f561bfb2db923e74e9ed955a
8933565c58a559211c7608c74cf637c86bf2b4eb
faefe2b314e7ae8ff4826abf61c9de4769ff0a9b
73abe7759dadbf364ebb1a36d24f1295aabdb14d
8330242285263ad95f9d2ca6e17c6b2d003b6194
704adc21a55ba19c6a0d8af5b9d57b383467f57e
d05736f8a5e6c73a49544eef37232d266a8a5190
023e38c23630993c7d9ca5311fb9069c848143e4
5359d20098660e21c936eb570e960a30f3101014
0e4c03b87eee7392b5d20af7671dfcf1ec23dc29
f489cb20f9c14f7f5b0d20b2f4fe84b4894dae41
9e8cd860b6710ed02b50d71bde225715d0d46b1a
c0f01d3d181edea34a74767f7a2833b42417559a
64315e283e863757f35bcaa1e2e3ec51bc31b14d
27d8d81cf7f16df1d6ca8525da83dec4c4c08bad
de8fa16235762bb19957235e0eb296cdd144e66e
dd58a6c038759b4196ffe40b47434a8d83324986
25846d4ca6372cd1498549cd96cb48cdfa4af9b2
8733bf832613b264498592470ac77cfbccdb3ca4
9fddd0b4fa7a95241ea84f6d6d27ff3d5679d17e
c321785ac4230aadcc5439f1d7d5d1affb49a745
878e886f968b7d7c3946145002756d64fefdd9fd
1c2cdeb814d4718f7ee8dfad53cc6bbfa1d4421d
4ce53dac2689a3e11f20994d6a7d38dbfa4061ca
dc61c2d4c891321493d43fa63992d14688f17d06
5542cb87d94c6133534796e972979d7711170495
d94e15e1a7747fdd69ed54b8f0c048e50f32bf49
edbef3a8cf9162d2739c8d389f42b30798fdec9d
0c2f8bbfe09ffbbea25258d316ef28ef92da9504
a87a986544353b7a8abf627f9eb093ee5c02ded3
5f7e8dc3b35a8e9ba4bf28df1d86616f33a1990a
5d299af185fb48c28b532bc936efbeedc114fc3e
f3ccbfe053da4cb4c5a6c38d38d76aece8e35cf8
5c517c7fa57c221a79af5059905ff7290c6d3dd2
65864157682ae2df7673136b09d61eadfa166d72
a3e36b23f2479a2e1f1b7278228a142b1c8079ff
662a6f83168af6c808e39dfeed6ec1ca92af6fd7
78383a3bf5aa9ccbfb1d99d1ba1afc3b78b1610c
9076ad5d0d989bebd371ad392c0ecb51f4b2b6ff
0c753eac81ebb247860c93955de8af8bf51195fb
3e6be78f66551bb2179af90d0c9edb6dfa6bf14c
54c41c981f9fe954e6fbb2a19b00b59b77ac845d
97c658b4830646222e213c746581799223606a63
cd3e04306925c354e42d529219c356804b80b779
033d80b213fb837fb5025fca0d4065cab32823c8
b641de83f54a7134500a5cbd1bd26f79d2e63199
2d81614d2e2d78b9b9c8a0c9a5f9eb74ce0c94bf
f8bdd5f466b460fe785d178020c52e8d200bf10c
d1b80add9cafbdd0d34981b6de9f232686a984cc
7330e3105c2632d3ed08932b9f5671e502de83ec
a0a3938eee60fc87c7770e6cab9ae357833390ee
5413f7095fe837be5d2bb7bef3943825ab80f9e5
b5c8e8e267268237da85c495818b1615dfeb1dd8
```

</details>

**Comment by fedde-s** [comment]
I'm not fully sure why the fields of the Elasticsearch index are set to single-precision floating point; I imagine it's [the default](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/dynamic-field-mapping.html) when inferring the type based on the fields in the JSON.

**Comment by d0choa** [comment]
After discussion with @DSuveges, we'll try to deal with this at the data level. We need to figure out a way to best represent these very unusual fields.

Thanks @fedde-s for reporting

**Comment by fedde-s** [comment]
I did still see these error messages when trying to load <https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.11/output/etl/json/evidence/sourceId%3Dot_genetics_portal/> and <https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.02/output/etl/json/evidence/sourceId%3Dot_genetics_portal/>, only the numbers are slightly different (only 52 failing docs instead of 58 as of 22.02). This issue is still present in the current data.

**Comment by fedde-s** [comment]
Isolated example in 22.06:
```json
{
  "datasourceId": "ot_genetics_portal",
  "targetId": "ENSG00000172765",
  "datatypeId": "genetic_association",
  "diseaseFromSource": "Mytonic disorders",
  "diseaseFromSourceMappedId": "Orphanet_206970",
  "oddsRatio": 1.2224956943508018e+60,
  "oddsRatioConfidenceIntervalLower": 6.348499230333605e+49,
  "oddsRatioConfidenceIntervalUpper": 2.354092941470977e+70,
  "pValueExponent": -30,
  "pValueMantissa": 2.32,
  "projectId": "FINNGEN",
  "publicationFirstAuthor": "FINNGEN_R5",
  "publicationYear": 2021,
  "resourceScore": 0.05007006973028183,
  "studyId": "FINNGEN_R5_G6_MYOTDIS",
  "studySampleSize": 217151,
  "targetFromSourceId": "ENSG00000172765",
  "variantFunctionalConsequenceId": "SO_0001628",
  "variantId": "3_130181138_G_A",
  "variantRsId": "rs556230630",
  "diseaseId": "Orphanet_206970",
  "id": "185172d390641478c834eb5b6be1f3a033eb676c",
  "score": 0.05007006973028183
}
```

`"oddsRatio": 1.2224956943508018E60` does not fit in a single-precision floating point number, as the [esbulk](https://github.com/opentargets/platform-output-support/blob/f748c28a49431f374f43180a16e445a790af5660/terraform_create_images/modules/posvm/scripts/load_json_esbulk.sh#L36)-[based](https://github.com/opentargets/platform-output-support/blob/f748c28a49431f374f43180a16e445a790af5660/terraform_create_images/modules/posvm/scripts/load_all_data.sh#L49) loading process apparently infers as the field type. The [association page](https://platform.opentargets.org/disease/Orphanet_206970/associations), if searched for the gene **TMCC1**, does suggest that the AOTF data knows about the evidence, but the evidence page it links to does not show the row in the **OT Genetics Portal** table.

**Comment by fedde-s** [comment]
On the one hand using double-precision floating point numbers could fix it, on the other hand it does not seem to be a problem for any of the other >fourteen million rows of evidence, not even for non-FINNGEN rows from the genetics portal :confused:

**Comment by JarrodBaker** [comment]
There are a small number of genetics evidence entries which are not loaded into ES due to a suspected issue with the odds ratio not fitting into a single precision integer. 

There are approximately 50 entries in the index which are like this. 

When we try and insert one:

```
POST /evidence_datasource_ot_genetics_portal/_doc?refresh=true
{
  "datasourceId": "ot_genetics_portal",
  "targetId": "ENSG00000172765",
  "datatypeId": "genetic_association",
  "diseaseFromSource": "Mytonic disorders",
  "diseaseFromSourceMappedId": "Orphanet_206970",
  "oddsRatio": 1.2224956943508018e+60,
  "oddsRatioConfidenceIntervalLower": 6.348499230333605e+49,
  "oddsRatioConfidenceIntervalUpper": 2.354092941470977e+70,
  "pValueExponent": -30,
  "pValueMantissa": 2.32,
  "projectId": "FINNGEN",
  "publicationFirstAuthor": "FINNGEN_R5",
  "publicationYear": 2021,
  "resourceScore": 0.05007006973028183,
  "studyId": "FINNGEN_R5_G6_MYOTDIS",
  "studySampleSize": 217151,
  "targetFromSourceId": "ENSG00000172765",
  "variantFunctionalConsequenceId": "SO_0001628",
  "variantId": "3_130181138_G_A",
  "variantRsId": "rs556230630",
  "diseaseId": "Orphanet_206970",
  "id": "185172d390641478c834eb5b6be1f3a033eb676c",
  "score": 0.05007006973028183 
}

```

The insert is unsuccessful because of a type error.
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [oddsRatio] of type [float] in document with id 'Ep7G3IEBanvmvDQCW24w'. Preview of field's value: '1.2224956943508018E60'"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [oddsRatio] of type [float] in document with id 'Ep7G3IEBanvmvDQCW24w'. Preview of field's value: '1.2224956943508018E60'",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "[float] supports only finite values, but got [Infinity]"
    }
  },
  "status" : 400
}
```
Because we don't set any specific field mappings when we create the index, Elasticsearch [infers the type mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-dynamic). 

If we update the index mappings to use type `double`:

```
PUT /evidence_datasource_ot_genetics_portal/_mapping
{
  "properties": {
    "oddsRatioD": {
      "type": "double"
    },
    "oddsRatioConfidenceIntervalLowerD": {
      "type": "double"
    },
    "oddsRatioConfidenceIntervalUpperD": {
      "type": "double"
    }
  }
}
```
The documents can be ingested as expected. 

There are 51 records missing in Elasticsearch for the 22.06 release. 

To fix this issue we need to update POS to define a custom mapping for the odds ratio related fields.

## Tasks 

- [ ] Add custom field mappings to POS load scripts for `oddsRatio`, `oddsRatioConfidenceIntervalLower`, `oddsRatioConfidenceIntervalUpper` to use type `double`. 

## Follow-up

It's possible that there are other fields on Evidence that exhibit a similar behaviour. Anything greater that 1E33 seems to be at risk of falling over.  Do you know off the top of your head @DSuveges which fields are likely to be at risk?
  
## Acceptance tests

When I query the index mappings of the effected fields (`GET /evidence_datasource_ot_genetics_portal/_mapping/field/oddsRatio,oddsRatioConfidenceIntervalLower,oddsRatioConfidenceIntervalUpper`) I see that they each have the type `double`.

**Comment by fedde-s** [comment]
In the past ~1½ years of releases, no other fields have failed to load in the same way in practise, including over 90 thousand other lines of evidence evidence with odds ratios as of 22.06. It seems like only these few FINNGEN-sourced genetics portal lines end up with numbers that don't fit in 32 bits.

**Comment by d0choa** [comment]
There are other fields (e.g. fold changes) that under extreme circumstances can go beyond this limit. But I agree with @fedde-s that we should probably protect ourselves against the odd behaviours in the current data, instead of any hypothetical extreme behaviour of the data.

The main data value going beyond 32-bit (or even higher precision) are the p-values and we are well protected by encoding the mantissa and exponent in different fields. If we now cover the very rare odds ratios we should be fine.

**Comment by fedde-s** [comment]
I hadn't fully decided on that conclusion myself yet, past releases just happen to be what I have knowledge to share about. Using 64 bits for these fields across all evidences that have them, as I believe @JarrodBaker's commit does, sounds sensible to me as well and might even be slightly easier to maintain without introducing a breaking change for any users of the GraphQL API.

On the other hand, haven't read enough about how type specifications work in Elasticsearch to know whether the implementation in the commit introduces another use of [deprecated mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html) which would need to be redesigned when updating to Elasticsearch 8.

**Comment by fedde-s** [comment]
Make that 39; I missed `f807aa682e11f090474be2e1049d15b3ec701973` which has an **oddsRatioConfidenceIntervalUpper** of `5.624211048664315E40` and does not show up as a second row [here](https://platform.opentargets.org/evidence/ENSG00000198561/EFO_0000538).

**Comment by fedde-s** [comment]
All 39 docs have `"publicationFirstAuthor":"FINNGEN_R6","publicationYear":2022`.

**Comment by fedde-s** [comment]
For completeness: I have indeed not seen the issue in 23.02 and 23.06, confirming that the index settings fix the issue.
