### ISSUE TITLE
Implement ChemicalProbes dataset into datasource_parsers

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1711]
Follow-up action from [#1536](https://github.com/opentargets/platform/issues/1536)

**Comment by ktsirigos** [comment]
@ireneisdoomed is this done?

**Comment by ireneisdoomed** [comment]
No, still on a Jupyter. Adding it to 22.02.

**Comment by ireneisdoomed** [comment]
The notebook to generate the Probes dataset for 22.02 is now part of the repo ([PR #113](https://github.com/opentargets/evidence_datasource_parsers/pull/113)). 

It is scoped for 22.04 to develop the module that will generate the same file directly by reading the data from the P&D SQL dump.

**Comment by ireneisdoomed** [comment]
The module has been written and we've been able to generate a dataset based on the P&D newest version (#2557).

However there is a bug in the data itself as reported by the ChemicalProbes.org people, which hasn't been solved yet.

I will open the PR with the code as it is now, and we can tackle the data bug in a follow-up ticket.

**Comment by d0choa** [comment]
@ireneisdoomed this can be closed, isn't it?

**Comment by ireneisdoomed** [comment]
Done
