### ISSUE TITLE
Expand disease cross-references to include MalaCards

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1725]
Earlier this week, I met with the MalaCards team to discuss mutual links and referral traffic.

After the meeting, the MalaCards team have generated a [TSV file that maps their disease page slug lines to EFO IDs](https://drive.google.com/file/d/1ht2k0ip02a7p4mP7hXxaeKDwvCWnc9Sy) . For example, the file maps `legionnaire_disease` to `EFO_0007343`.

This mapping file will enable us to generate links to MalaCards's disease profile pages and they will link back to our disease/phenotype profile pages.

Although many of their disease slug lines have a one-to-one EFO mapping (e.g. `legionnaire_disease`), there are a number of diseases where the slug line has a one-to-many mapping. For example, `leukemia_acute_lymphoblastic` has three mapped EFO IDs — `EFO_0000094`, `EFO_0000220`, and `EFO_0009119`. This is because of their "integrated aliases" feature — see the [MalaCards' leukemia_acute_lymphoblastic profile page](https://www.malacards.org/card/leukemia_acute_lymphoblastic#aliases_descriptions) for an example. Other examples with one-to-many mappings include breast cancer and lung cancer.

Due to the one-to-many mapping, we would encounter scenarios where the MalaCard link label would not match the disease/phenotype profile page. For example, on the [precursor lymphoblastic lymphoma/leukemia (EFO_0009119) profile page](https://platform.opentargets.org/disease/EFO_0009119), the MalaCard link would be labelled "leukemia, acute lymphoblastic".

And so I have identified two potential approaches:

1. In the ETL pipeline or front-end, we filter out and only show the cross-reference where the mapped EFO ID matches the EFO ID for the given disease/phenotype profile pag.

Using the same [precursor lymphoblastic lymphoma/leukemia (EFO_0009119) profile page](https://platform.opentargets.org/disease/EFO_0009119) example, the MalaCard link would not appear on that page. It would only appear on the [acute lymphoblastic leukemia (EFO_0000220) profile page](https://platform.opentargets.org/disease/EFO_0000220).

2. We show every mapping and instead of using the MalaCards disease label as the hyperlink text, we show a string of all of the EFO IDs.

Using the same [precursor lymphoblastic lymphoma/leukemia (EFO_0009119) profile page ](https://platform.opentargets.org/disease/EFO_0009119) example as above, we would show "EFO_0000094, EFO_0000220, EFO_0009119" as the hyperlink label. This hyperlink could then appear on all three disease/phenotype profile pages.

What do you think @d0choa?

**Comment by d0choa** [comment]
I would suggest to give it to @tskir and try to see how many of the mappings we can confirm using Ontoma. Depending on the outcome agreement/coverage we can go way or another. @andrewhercules  you know if they had pages they couldn't map to EFO?

**Comment by andrewhercules** [comment]
I have asked the MalaCards team about this and will post their response.

For now, I think we can start with the original mapping file they provided and see what Ontoma returns.

**Comment by andrewhercules** [comment]
MalaCards has responded to my email and confirmed that they have mapped IDs for 2,337 disease pages (out of a total of 21,837 disease pages).

They also shared a ZIP file - `MalaCards_diseases.zip` - that contains:

1. A file of all their disease terms and disease page slug lines — `MalaCards_diseases_without_EFO.txt` (note: the column with underscores is their disease page slug line used to construct page links)
2. A file with disease terms and disease page slug lines that mapped to EFO IDs — `MalaCards_diseases.txt`

@tskir, can we please process the `MalaCards_diseases_without_EFO.txt` using Ontoma to see if we can map EFO to more pages?

**Comment by ktsirigos** [comment]
@andrewhercules how do you want to proceed here? Maybe it does not add so much value?

**Comment by d0choa** [comment]
@buniello feature request document

**Comment by buniello** [comment]
closing as added to feature document
