### ISSUE TITLE
Bucket-hosted static files not working in main as a result of paywalling

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#1727]
The static files used in the `main` branch of the platform-app are no longer available because we have paywalled the buckets. This is resulting in certain components (ontology widget, bubbles, graph) not loading in this branch.

We need to resolve how to maintain a healthy FE development while ingesting these files dynamically in the deployment context.

**Comment by cmalangone** [comment]
We can provide a different public url for this few resources.
What do you think?
@mirandaio @d0choa

**Comment by d0choa** [comment]
IMO that could work as long as POS overwrites the files. The files need to be always in synch with the `master` branch of the GraphQL API.

**Comment by d0choa** [comment]
We are tentatively scheduling this for 22.02

**Comment by andrewhercules** [comment]
I have scoped this for 22.04. Ensuring that static files work in `main` will help with the generation of the Data Downloads page in #1971 as the page will require two static files noted in the ticket.

**Comment by LucaFumis** [comment]
Is work on this issue complete? Can it be closed, or is it needed for reference?
