### ISSUE TITLE
Add types to PIS

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1747]
As a developer, I want to be able to quickly see what a method/function does in PIS by having type annotations.

## Background

Since Python 3.5 the standard library has included type annotations (https://docs.python.org/3/library/typing.html) through the `typing` package. The challenges presented by lacking type annotations are well known, and Dropbox has [documented their experience](https://dropbox.tech/application/our-journey-to-type-checking-4-million-lines-of-python) with type annotations in Python.

## Actions for all PIS developers

The migration to typing is to be done gradually. When you update a module it is your responsibility to update the type annotations for that file. 

- At a minimum method signatures should include type annotations. 
- When writing new functions type annotations should be used in the method body

**Comment by mbdebian** [comment]
This will be followed as a guideline for ongoing and future works on PIS
