### ISSUE TITLE
Refactor PIS

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1765]
The purpose of this epic is to refactor and tidy PIS so that it only generates the files we need, in the way that we need them.

## Background

The purpose of PIS is to provide a configurable way to obtain the raw file needed to run the ETL. PIS has grown in an adhoc manner as more resources have been added. Since its inception we have deprecated the data pipeline and introduced a separation of concerns were PIS is responsible for providing and saving raw data, and all (within reason) processing happens in the ETL. 

## Design decisions 

-  When PIS tries to download a file that already exists, should it overwrite the existing file?
-  How to handle cases when two ETL steps use the same input file?
-  Agree on output structure of PIS logging/configuration.

## Tasks / Goals

 -  Refactor to reduce redundancy, eg. helper methods to download similar file types or perform similar tasks (such as checking whether system utilities are available `jq path` for instance)
 -  Ensure a consistent use of libraries: Dict in the standard library or Addict approach
 -  Improve coverage of Python annotations (see opentargets/platform#1747)
 -  Update Homologues in target
 - Update Safety in Target (see opentargets/platform#1756)

**Comment by cmalangone** [comment]
* Many file are zipped and the ETL config request unzipped file. We need to discuss a standard
