### ISSUE TITLE
Map oligonucleotide drug targets in MoA dataset

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#1787]
Oligonucleotides like [NUSINERSEN](https://platform.opentargets.org/drug/CHEMBL3301572) or [GOLODIRSEN](https://platform.opentargets.org/drug/CHEMBL4297762) target human mRNAs instead of human proteins.

For this reason, ChEMBL reports other IDs different than UniProt as their ChEMBL targets. In the NUSINERSEN MoA example, they provide the Ensembl gene ID as the main identifier for the [ChEMBL target](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL3826841/).

We are at the moment ignoring the Ensembl gene ID and not mapping the targets to our entities. Could we please rescue these targets?

**Comment by d0choa** [comment]
As a side note, we are not the only ones having issues handling this exception:
 
<img width="535" alt="Screenshot 2021-09-28 at 13 40 41" src="https://user-images.githubusercontent.com/5097586/135088938-52a76dd6-c490-4793-80ca-d5121a8b95e7.png">

**Comment by JarrodBaker** [comment]
Ok, so the 'human target' field for Golodirsen should be ENSG00000198947 (mapped via Dystrophin), with similar logic for the other mrna entries?

**Comment by d0choa** [comment]
there is no extra mapping required. The information is all available in ChEMBL. MoA -> Chembl Target CHEMBL3826841 -> ENSG00000198947. Normally we have to map Uniprots to Ensembl in the last step, but ChEMBL reports Ensembl directly for these cases.

**Comment by d0choa** [comment]
This work would resolve #1575
