### ISSUE TITLE
Handle unavailable Clickhouse/Elasticsearch instances

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1836]
As a developer I want to ensure that GQL queries do not fail when a backend service is not available because the application should be sufficiently resilient to handle failure until service is restored.

## Background

Executing a query on the GraphQL API will result in an internal server error is ES or CH cannot be reached. We either should handle these exceptions gracefully, or provide more information in the error message provided to the API about what the problem is. 

## Acceptance tests

Given a running instance of the API which cannot communicate with either ES or CH, a query should return either a valid response (ideal, but perhaps misleading?), or a 5xx error with sufficient detail to identity the problem without consulting the application log. Sufficient detail means that I know which of the services is unavailable.

**Comment by remo87** [comment]
I also think it could be misleading but I think it would depend on how often is the data updated?

**Comment by remo87** [comment]
The status code is going to be a 200 because the error is occurring while executing the query. So we will need to send a response message with errors object populated. This is how it would look like for Clickhouse: 

`{
    "data": {
        "target": null
    },
    "errors": [
        {
            "message": "Error connecting to the Clickhouse db. Contact system administrator",
            "path": [
                "target",
                "literatureOcurrences"
            ],
            "locations": [
                {
                    "line": 6,
                    "column": 5
                }
            ]
        }
    ]
}`

and this is how it would look like for elastic search:

`{
    "data": {
        "target": null
    },
    "errors": [
        {
            "message": "Error connecting to Elastic Search. Contact system administrator",
            "path": [
                "target"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ]
        }
    ]
}`

what do you think? is the message ok? should I change it to something else? @JarrodBaker

**Comment by JarrodBaker** [comment]
That looks good to me @remo87. 

Realistically we're the only people who are likely to see these messages, and the purpose is so we can quickly identify if we've got an infrastructure issue or there is a problem in the API logic.
