### ISSUE TITLE
Improve Association page load times

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1840]
As a user I want the associations page to load quickly because I've been conditioned to expect fast page load times.

## Background

One of the key pages of the Platform is the [Associations page](https://platform.opentargets.org/target/ENSG00000232810/associations). This page relates either a target to diseases or a disease to targets. Page load times are very slow. The following was taken when loading the associations page for psoriasis:

![image.png](https://images.zenhubusercontent.com/5ec7caaa0e8174edc9bdf7a6/9fd17d16-b2d4-467f-ba76-2eae2c122a62)

We can see that there are two requests which are both slow, and both take approximately the same time. 

The two requests are (similar logic applies to diseases):

```
query DiseaseFacetsQuery(
  $efoId: String!
  $aggregationFilters: [AggregationFilter!]
) {
  disease(efoId: $efoId) {
    id
    name
    associatedTargets(aggregationFilters: $aggregationFilters) {
      count
      aggregations {
        uniques
        aggs {
          name
          uniques
          rows {
            key
            uniques
            aggs {
              key
              uniques
            }
          }
        }
      }
    }
  }
}
```

And 

```
query DiseaseAssociationsQuery(
  $efoId: String!
  $index: Int!
  $size: Int!
  $filter: String
  $sortBy: String!
  $aggregationFilters: [AggregationFilter!]
) {
  disease(efoId: $efoId) {
    id
    associatedTargets(
      page: { index: $index, size: $size }
      orderByScore: $sortBy
      BFilter: $filter
      aggregationFilters: $aggregationFilters
    ) {
      count
      rows {
        target {
          id
          approvedSymbol
          approvedName
        }
        score
        datatypeScores {
          componentId: id
          score
        }
      }
    }
  }
}
```
One is used to populate the association scores, and the other is to create the filter metadata used to populate the panels on the left-hand side. 

Internally in the API both of these requests resolve to the method `Backend.getAssociationsDiseaseFixed` and we evaluate the facets and the associations on every request, that is, twice for our cases.  

## Discussion 

It doesn't seem possible to use a combined query in the FE at the moment due to the interaction of pagination of the facet results. 

It might be possible to put a flag in the GQL query regarding whether faceting information is required with the request which would speed up the association query, but we'd still be recomputing the associations twice. 

Long term a solution needs to split these concerns. 

## Acceptance tests 

1. When I go to an association page and open web developer tools 'network' page and load a target/disease, I see two queries: one for faceting and one for association scores. When I look in the logs from the API I see that these queries are being resolved to different helper methods to avoid duplicate work.

**Comment by ktsirigos** [comment]
assigning this so that the ticket does not remain orphan

**Comment by remo87** [comment]
Not applicable anymore
