### ISSUE TITLE
Bug in EPMC reported sections 

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1841]
**Describe the bug**
There are sections present in EPMC evidence that:
1. fall out of the scope of their analysis
2. are expected to be present however missing.

**Expected behaviour**
As described in EPMC's pipeline [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5461726/) (Table 2), these are the sections of interest for the analysis:
```
Title
Abstract
Results
Figure
Table
Discussion
Conclusion
Introduction
Case Study
Appendix
Other
```

**Observed behaviour**
Based on their September submission,  these are the current possible section listed in the evidence:
```
+---------+-------+
|        s|  count|
+---------+-------+
| abstract|4982175|
|  discuss|4037666|
|  results|3902100|
|    other|2169899|
|    intro|1641653|
|    title| 730833|
|  methods| 404377|
|    concl| 224418|
|    suppl|  40116|
|     abbr|  33984|
|     case|  27541|
|      ref|   6672|
| appendix|    973|
| comp_int|    394|
|auth_cont|    328|
| ack_fund|     85|
+---------+-------+
```
Hence we should study if:
- `suppl`, `comp_int `, `methods `, `ref`, `auth_cont`, `ack_fund`: should be there.
- ~~`figure`, `table`: should be missing.~~ These sections are present in EPMC submission, but not evidence.

**To Reproduce**
Steps to reproduce the analysis:
1. Download `gs://otar000-evidence_input/EPMC/json/epmc-2021-10-25`: EPMC evidence extracted from the 21.09 submission
2. Extract all the distinct sections from the `textMiningSentences` array

**Notes**
This is relevant because the score given for those associations takes the section as a parameter. A score outside the sections of interest might not be trustworthy.

**Comment by ireneisdoomed** [comment]
@saha-shyamasree @tsantosh7

**Comment by DSuveges** [comment]
The situation was the same in the last release as well:

| section   |   new_data (2021-10-25) |   old_data (2021-09-28) |
|:----------|------------------------:|------------------------:|
| abbr      |         33984           |         34038           |
| ack_fund  |            85           |            83           |
| auth_cont |           328           |           330           |
| discuss   |             4.03767e+06 |             4.02736e+06 |
| title     |        730833           |        991228           |
| intro     |             1.64165e+06 |             1.63348e+06 |
| concl     |        224418           |        223338           |
| other     |             2.1699e+06  |             2.16016e+06 |
| appendix  |           973           |           973           |
| ref       |          6672           |          6587           |
| methods   |        404377           |        402691           |
| comp_int  |           394           |           389           |
| case      |         27541           |         27646           |
| results   |             3.9021e+06  |             3.89002e+06 |
| abstract  |             4.98218e+06 |             6.16218e+06 |
| suppl     |         40116           |         40001           |

**Comment by ireneisdoomed** [comment]
We have discussed this issue during today's EPMC monthly meeting:
1. Sections outside the scope of the disease/target association will be removed in the evidence generation step.
Actions:
- [ ] OT: to update the EPMC parser +.validator
- [ ] @saha-shyamasree to investigate whether these extra sections were part of the category "Other".
2. EPMC will still provide those matches outside the above-mentioned sections since it is of interest for OT to include them in our Bibliography pipeline. **With the one exception of `references`**, which will be excluded since it essentially reflects (and explodes) established knowledge and will reduce the size of the mining task.
Actions: 
- [ ] @saha-shyamasree to exclude `references` from the analysis.
@saha-shyamasree, it would be good if you could apply a filter or assertion on your code to make sure only the correct sections are used. Also, for those which fall out of the evidence scope, you can study the possibility of not providing a score for them.
3. I have corroborated that `figure` and `table` are present in the EPMC submission, so nothing else to do here. These sections are not found in evidence because there are no grounded co-occurrences.

**Comment by saha-shyamasree** [comment]
@ireneisdoomed : I find it really hard to believe that no evidence from FIG and TABLE. FIG and TABLE evidences are high value evidences, and if they do not normalize to the DB ids, thats rather odd.

**Comment by saha-shyamasree** [comment]
@ireneisdoomed @DSuveges I can confirm that the extra sections are NOT 'Other'. From the previous code, what I can see is that, those sections are simply dropped from the evidence report, similar to the evidences from the method section. The 'OTHER' basically represents sentences mostly from (as many as I checked) odd XML structured files. For example, an article XML, generally has three sections in the root tag (<article>), <front>, <body> and <back>. But if you check PMC7200337 [https://europepmc.org/article/MED/32358609] doesn't have typical article structure and all the text is simply wrapped within a <p> tag that belong to the the root <article> tag. So the section tagger fails to assign a section type to those sentences, hence mark it as 'OTHER'. This clearly shows that the new implementations is removing those evidences. I will add them for the next submission.
