### ISSUE TITLE
Add SwissBioPics visualisation to subcellular location section

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1875]
With the introduction of the new `target` object, the Platform API now provides the SL ontology terms for the subcellular location data -- see #1710.

### Sample query

Query: [PTEN](https://api.platform.opentargets.org/api/v4/graphql/browser?query=query%20SLdataForPTEN%20{%20target(ensemblId:%20%22ENSG00000171862%22)%20{%20id%20subcellularLocations%20{%20location%20source%20termSL%20}%20}%20})

```
query SLdataForPTEN {
  target(ensemblId: "ENSG00000171862") {
    id
    subcellularLocations {
      location
      source
      termSL
    }
  }
}
```

### API response

```
{
  "data": {
    "target": {
      "id": "ENSG00000171862",
      "subcellularLocations": [
        {
          "location": "Cytoplasm",
          "source": "uniprot",
          "termSL": "SL-0086"
        },
        {
          "location": "Nucleus",
          "source": "uniprot",
          "termSL": "SL-0191"
        },
...
```

With the SL terms, it is now possible to visualise the subcellular location data using the SwissBioPics visualisations (e.g. [animal cell](https://www.swissbiopics.org/name/Animal_cell)). These visualisations are available in an NPM package -- [swissbiopics-visualizer](https://www.npmjs.com/package/%40swissprot/swissbiopics-visualizer)

Some initial considerations from @d0choa:

- Since some of the subcellular location terms might not be mapped to SL-terms, it would be good to keep the the current text-based version side by side
- Since we have 3 different sources: `HPA_main` and `HPA_additional` and `uniprot` and they might not necessarily agree on the locations and we might need to separate them. Tabs/Dropdown with `HPA_main` been the default comes to my mind but other options might work as well.   

References:
- [NPM package](https://npm.io/package/@swissprot/swissbiopics-visualizer)
- [Component embedded in uniprot](https://www.uniprot.org/uniprot/Q14533)
- [Component embedded in uniprot beta - React](https://beta.uniprot.org/uniprotkb/Q14533/entry#subcellular-location)

**Comment by andrewhercules** [comment]
Further details, including a full design specification TBC

**Comment by andrewhercules** [comment]
Rescoped for the 22.04 release

**Comment by LucaFumis** [comment]
Done and merged: https://github.com/opentargets/ot-ui-apps/pull/16
