### ISSUE TITLE
Incorporation of predicted protein structures (from AlphaFold/RoseTTAFold) in tractability scores

### ISSUE THREAD

**Issue by eric-czech** [opentargets/issues#1886]
Hi, do you all have any plans/ideas on ways to incorporate new structure prediction models in the current tractability scoring system?  I was curious if you're aware of any leading efforts to this end via AlphaFold or RoseTTAFold.

**Comment by DSuveges** [comment]
Hi @eric-czecha, currently we are in the process of enriching our data with structure based information, although it has a slightly different angle than your comment. 

We are also exploring how we could harness the wast knowledge the advent of such sophisticated methods brought as Alphafold. We saw in a recent [Science paper](https://www.science.org/doi/10.1126/science.abm4805) a combined application of Alphfold and rosettafold to predict therapeutically relevant protein complexes. This is certainly on our radar and we are exploring the possibilities of sourcing interactions from the corresponding [modelarchive page](https://modelarchive.org/doi/10.5452/ma-bak-cepc). 

If you have anything particular application in mind, please raise it, we are always open for suggestions!

**Comment by buniello** [comment]
Hi @eric-czech, we have now released a "Feature Request" functionality within our [Open Targets Community](https://community.opentargets.org/c/feature-requests/16).
I wonder whether you would be willing to post this suggestion there? That would be very useful to us!

**Comment by eric-czech** [comment]
Ok @buniello, moved it to https://community.opentargets.org/t/incorporate-predicted-protein-structures-in-tractability-scores/1073.

Feel free to copy any of my posts in this repo into that discourse.
