### ISSUE TITLE
Extract drug ligands from protein structures

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1891]
This epic collects the different pieces of work that @MarineGirardey will touch during her internship at Open Targets.

**Comment by MarineGirardey** [comment]
## Statistical results for ticket #1892 and #1894 

| Stats                                                                             | Count     |
| -------------------------------------------------- | -------- |
|Total molecules in UniChem database                       | 14452    |
|Molecules in parquet                                                    | 12594   |
|Molecules from parquet found in UniChem                | 3657     |
|Percentage of parquet molecule found in UniChem  | 29         |
|Total structures                                                             | 137175  |
|Molecules without structure                                        | 12          |
|Total targets                                                                  | 136404 |
|Human target                                                                | 74007    |
|None human target                                                       | 62397   |
|Total time running (1)                                                    | 944       |
|Time for scrap structure on API (2)                             | 919       |

(1) 944 sec ≈ 15.7 min
(2) 919 sec ≈ 15.5 min
