### ISSUE TITLE
Removing PheWAS from OpenTargets Platform

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1899]
Given the static nature and the advancement of novel methods since it's release, PheWAS disease/target evidence is now considered obsolete. To remove this dataset the following tasks should be completed:

- [x] Data team: Remove PheWAS from the [evidence datasource parser](https://github.com/opentargets/evidence_datasource_parsers) pipeline. 
- [x] Backend team: Remove PheWAS from the platform input support.
- [x] Backend team: Remove PheWAS from ETL config.
- [x] ~Backend team: Remove `studyCase` field from Evidence in API~ `studyCase` is used by `gene_burden`
- [x] Frontend team: Remove PheWAS widget.
- [ ] Remove PheWAS from documentation

**Comment by JarrodBaker** [comment]
There are potential evidence fields in the API which might need to be removed.

**Comment by d0choa** [comment]
From memory, I believe `studyCases` should be removed. But it would be good to confirm @DSuveges

**Comment by DSuveges** [comment]
That's correct. `studyCases` is the one and only field that is provided only by the PheWAS catalog. It can be removed from ETL.

**Comment by ireneisdoomed** [comment]
@mbdebian This no longer affects the API endpoints, as `studyCases` is also used by the new `gene_burden` source.

[PR#244](https://github.com/opentargets/platform-etl-backend/pull/244) removes PheWAS from the ETL.

**Comment by mbdebian** [comment]
PheWAS is now removed from the ETL.

**Comment by mbdebian** [comment]
@d0choa  , we can probably close this issue if the documentation is up to date, it is my understanding that the latest merge by @carcruz removed the widget.
