### ISSUE TITLE
Autogeneration of ETL configuration from PIS

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1900]
As someone running a release I want [PIS](https://github.com/opentargets/platform-input-support) to generate an input configuration for the [ETL](https://github.com/opentargets/platform-etl-backend/) to make the release process faster.

## Background

PIS is responsible for downloading all the inputs necessary for the ETL to run. After PIS has run, the ETL must be configured separately to consume these inputs. This configuration is manual and error prone, and should be automated. 

The ETL has a default configuration bundled with the jar file. Individual fields can be overridden by providing a partial configuration file which overwrite those fields. An example configuration file which updates the ETL configuration based on PIS outputs can be found [here](https://github.com/opentargets/platform-etl-backend/commit/4c55f4517ba6ff79fce01fe04e1bf1aac1a16cdc).

It might be easier for the output to take the form of a collection of environment variables and use [variable substitution](https://github.com/opentargets/platform-etl-backend/commit/4c55f4517ba6ff79fce01fe04e1bf1aac1a16cdc) in the default configuration file. 

## Acceptance tests

1. When I run PIS a file is created which allows me to easily run the ETL with the newly created inputs.

**Comment by mbdebian** [comment]
We'll be taking a pull approach on this, by triggers related to each step of the release pipeline.
