### ISSUE TITLE
Update evidence API fields for Partner Preview Platform data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1902]
To ensure that the front-end can display the Validation Lab data as noted in #1898, we will require changes to the API to expose new fields.

# Fields to add

| Field | Source |
| --- | --- |
| `biomarkerList` | Validation lab, Encore |
| `expectedConfidence` | Validation lab |
| `projectDescription` | Validation lab, ot_crispr|
| `validationHypotheses` | Validation lab|
| `geneInteractionType` | Encore |
| `targetRole` | Encore |
| `interactingTargetRole` | Encore |

# Fields to update

| Field | Task |
| --- | --- |
| `cellLineBackground` | Rename to `diseaseCellLines` |

**Comment by JarrodBaker** [comment]
This can probably be closed @DSuveges, as @ireneisdoomed has created a ticket with the necessary field (unless there are more than are specified in 1903?

**Comment by ireneisdoomed** [comment]
No @JarrodBaker, this belongs to a different dataset! Validation Lab and ChEMBL endpoints are decoupled. I just mentioned the ticket for you to know that the tasks are very similar so they can be done at the same time. Sorry for the confusion ^^

**Comment by DSuveges** [comment]
### Validation lab

Schema:

```
root
 |-- biomarkers: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- description: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |-- confidence: string (nullable = true)
 |-- contrast: string (nullable = true)
 |-- datasourceId: string (nullable = true)
 |-- datatypeId: string (nullable = true)
 |-- diseaseCellLines: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- tissue: string (nullable = true)
 |    |    |-- tissueId: string (nullable = true)
 |-- diseaseFromSource: string (nullable = true)
 |-- diseaseFromSourceMappedId: string (nullable = true)
 |-- expectedConfidence: string (nullable = true)
 |-- projectDescription: string (nullable = true)
 |-- projectId: string (nullable = true)
 |-- resourceScore: double (nullable = true)
 |-- statisticalTestTail: string (nullable = true)
 |-- studyOverview: string (nullable = true)
 |-- targetFromSource: string (nullable = true)
 |-- validationHypotheses: struct (nullable = true)
 |    |-- description: string (nullable = true)
 |    |-- hypothesis: string (nullable = true)
```

**New fields**:
* `biomarkers` now have an extra field called `description`. It's nullable, other sources might not provide description.
* `expectedConfidence`
* `projectDescription`
* `validationHypotheses` - this is a complicated case, because we still didn't have the data from the Validation lab, but for this release we can stick with this model.

**Comment by DSuveges** [comment]
### ot_crispr studies

Schema:

```
root
 |-- cellLineBackground: string (nullable = true)
 |-- cellType: string (nullable = true)
 |-- contrast: string (nullable = true)
 |-- crisprScreenLibrary: string (nullable = true)
 |-- datasourceId: string (nullable = true)
 |-- datatypeId: string (nullable = true)
 |-- diseaseFromSourceMappedId: string (nullable = true)
 |-- log2FoldChangeValue: double (nullable = true)
 |-- projectDescription: string (nullable = true)
 |-- projectId: string (nullable = true)
 |-- resourceScore: double (nullable = true)
 |-- statisticalTestTail: string (nullable = true)
 |-- studyId: string (nullable = true)
 |-- studyOverview: string (nullable = true)
 |-- targetFromSourceId: string (nullable = true)
```

**New fields not yet in exposed**:

* `projectDescription`
* `log2FoldChangeValue`

**Comment by DSuveges** [comment]
### ENCORE dataset

There are slight updates on the schema.

**Comment by DSuveges** [comment]
Hi @JarrodBaker, there's a slight update on the encore evidence schema: the frontend will no longer infer the interaction type, instead this value is directly exposed in the `geneInteractionType` field. Thank you!

**Comment by DSuveges** [comment]
As of Feb 15, these fields are missing:

* `biomarkerList`
* `targetRole`
* `interactingTargetRole`
* `projectDescription`
* `geneInteractionType`
* `validationHypotheses`
* `expectedConfidence`

Field no longer needed:

* `cellLineBackground `

**Comment by JarrodBaker** [comment]
@LucaFumis, @carcruz: I'm updating the API according to the specification in this ticket. Note that when I remove `cellLineBackground` field the following query breaks in testing: `/src/sections/evidence/OTCRISPR/OTCrisprQuery.gql`

**Comment by JarrodBaker** [comment]
Can this be closed @DSuveges ?
