### ISSUE TITLE
Update Open Targets Projects widget on disease profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1907]
Can we please adjust the Open Targets Projects widget shown on the disease profile page in the Partner Preview Platform?

### Summary widget

![Screenshot 2022-01-27 at 15 48 11](https://user-images.githubusercontent.com/7490258/151530168-9734e10c-c152-4dfc-ad5a-e6e6e5dcecca.png)

- [x] Instead of showing the number of active and closed projects, please display the total number of projects

### Detail view

- [x] Remove the "Open Targest Intranet Link" column
- [x] Remove the "Status" column
- [x] In the "Project name" column, add a link to the Intranet using the following construct: `http://home.opentargets.org/` + `otarCode`

**Comment by DSuveges** [comment]
We got this. Check widget [here](https://partner-platform.opentargets.org/disease/EFO_0005842).
