### ISSUE TITLE
Update OT CRISPR evidence data table

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1913]
To prepare for the `beta` launch of the Partner Preview Platform, can we please adjust the "Open Targets CRISPR" detail widget on the evidence page?

- [x] Remove the "CRISPR screen library" column
- [x] Remove the up/down caret and tooltip in the "Significance" column 
- [ ] Between the "Cell type" and "Significance" column, add a new column called "log2 fold change" and display the `log2FoldChangeValue`
- [x] ~~In the [tooltip shown in the "Cell type" column](https://github.com/opentargets/platform-app/blob/4c27fda8663084b1dad04dd2b84917082962b2a4/src/sections/evidence/OTCRISPR/Body.js#L75), use the value in `diseaseCellLines[x].name` instead of showing the `cellLineBackground` field~~

**Comment by andrewhercules** [comment]
@carcruz can we please revert the change to the tooltip column? The API will continue to return the `cellType` field and if available, we can show the `cellLineBackground` field in the tooltip.

**Comment by DSuveges** [comment]
These tasks are completed.
