### ISSUE TITLE
Open Targets backend consolidation

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1921]
As a developer, I want to reduce duplication to minimise bugs, maximise code reuse, and make it easier for new people to start working on the Open Targets project.  So as not to duplicate common logic and to make it easier for everyone to work on all projects, a number of consolidation tasks need to take place. 

## Background

A number of previously loosely related projects (Platform, Genetics, Literature, Partner Previews) are becoming more of a consolidated whole. There is significant duplication in the input/output support and pipeline projects. This requires that we maintain multiple sets of documentation, fix the same bugs in multiple projects, and update dependencies in several places. 

### Platform
- [PIS](https://github.com/opentargets/platform-input-support)
- [ETL](https://github.com/opentargets/platform-etl-backend)
- [Literature](https://github.com/opentargets/platform-etl-literature)
- [API](https://github.com/opentargets/platform-api)
- [POS](https://github.com/opentargets/platform-output-support)
- [Web app](https://github.com/opentargets/platform-app)
- [Sitemaps](https://github.com/opentargets/ot-sitemap-cli)
- [Infrastructure - Terraform](https://github.com/opentargets/terraform-google-opentargets-platform)

### Genetics

- [GIS](https://github.com/opentargets/genetics-input-support)
- [Pipeline](https://github.com/opentargets/genetics-pipe)
- [GOS](https://github.com/opentargets/genetics-output-support)
- [Backend](https://github.com/opentargets/genetics-backend)
- [Infrastructure - deprecated](https://github.com/opentargets/infrastructure)
- [Infrastructure - Terraform](https://github.com/opentargets/terraform-google-genetics-portal)
- [Web app](https://github.com/opentargets/genetics-app)

### Summary of repository functionality
- Platform/Genetics Input Support are for collecting input files from third parties and placing them in a staging area for further processing by our internal tools.
- ETL/Pipeline are ETL tasks implemented in Spark to turn the inputs into the outputs necessary for BQ and the web apps.
- POS/GOS are used to move the outputs create by the ETLs into GCP virtual machine images (used for our web applications), Big Query and FTP.
- Sitemaps is used to generate metadata for the Open Targets Platform 
- Infrastructure (Terraform) is used to deploy the outputs from POS/GOS into GCP.
- Web apps are the front-end applications for our web presence.  

## Potential consolidations

- Literature should be combined into the ETL
- Infrastructure should be properly deprecated. This is more or less already the case, but there are a few bash scripts which were being used to deploy the Genetics platform.
- Genetics pipeline should be combined into the ETL
- Genetics Input Support should be combined into Platform Input Support.
	- Platform Input Support should be renamed to 'Open Targets Input Support' so the acronym sounds like a pet otter rather than a bodily function.
	- Currently GIS is a shell and largely not implemented. The functionality is provided through a collection of bash scripts which are hard to configure and maintain.
- Genetics Output Support should be combined into Platform Output Support.
	- GOS is only partially implemented   
- Genetics Backend, GOS, and "Infrastructure - deprecated" are should all be moved into the Output Support project. 
	- The three projects together provide the functionality for Genetics which on the Platform is provided by POS.

### Repositories  to deprecate

- [Literature](https://github.com/opentargets/platform-etl-literature)
- [GIS](https://github.com/opentargets/genetics-input-support)
- [Pipeline](https://github.com/opentargets/genetics-pipe)
- [GOS](https://github.com/opentargets/genetics-output-support)
- [Backend](https://github.com/opentargets/genetics-backend)
- [Infrastructure - deprecated](https://github.com/opentargets/infrastructure)

**Comment by prashantuniyal02** [comment]
@mbdebian Can we close this ticket?

**Comment by mbdebian** [comment]
> @mbdebian Can we close this ticket?

Yes, we need to revisit this from a different point of view.
