### ISSUE TITLE
Updating and unifying biomarker representation across parsers

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1923]
## Background

@JarrodBaker drew my attention to the fact that there’s a discrepancy on how `biomarkers` are represented in different evidence sets. In the cancer_biomarkers there are `biomarkerName ` and `biomarkers`, which is not a list, but an object in which there are two properties: `variant` (array) and a `geneExpression` (array). In the new evidence set prepared for the partner preview, `biomarkers` is a list with objects with properties `name` and `description` . This discrepancy needs resolved. 

On the partner preview front-end biomarkers are shown as chips, where the descriptions are shown upon hover-over. In case of cancer_biomarker evidence is displayed on a more detailed way.

## Tasks

- [ ] Solidify a consistent schema for both use cases
- [ ] If reasonable unify the front-end visualisation of biomarkers across all evidence.

## Acceptance tests

1. Get JSON schema that describe the biomarker object 
2. Update all relevant parsers to accommodate the updated schema
3. Validate evidence against the new schema

**Comment by d0choa** [comment]
@DSuveges close?

**Comment by DSuveges** [comment]
This issue is not yet ready to be closed. The two schemas are still divergent, but it is not so important at the moment jump on it. 

To be honest, I am not 100%sure how to properly model biomarkers.
