### ISSUE TITLE
Use PIS to gather inputs for Genetics pipeline

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1927]
As a developer I was an easy to use way to gather all of the files necessary for the Genetics pipeline.

## Background

Currently the inputs needed by the genetics pipeline are prepared using a very rough [bash script](https://github.com/opentargets/genetics-pipe/blob/master/scripts/prepare_inputs.sh). This is not easy to configure and is very difficult to rerun only a portion of the inputs. 

This capability should be built into PIS in the same way as other inputs. 

An overview of the location of the majority of the input/output locations can be found in the [documentation](https://github.com/opentargets/genetics-pipe/blob/a91ec474e94bce614e9a32fec6538664e8821bc5/documentation/ot_genetics_deployment.md?plain=1#L15). Consider the most recent release as a guide to the output structure desired (gs://genetics-portal-dev-data/22.01.2/inputs).

The inputs directory should have the structure:
```
lut/
v2d/
v2g/
variant-annotation/
```
This does not show the summary statistics as they are not used in the pipeline, but we do need them for later processing. The should be moved by PIS into the outputs directory under `sa`. See `gs://genetics-portal-dev-data/22.01.2/outputs` for an example.

## Acceptance tests

1. After running the appropriate stages of PIS all of the inputs required for running the genetics pipeline are present in a google storage bucket.
2. After running the appropriate stages of PIS all of the static inputs required for preparing the CH and ES images are available in a google storage bucket.

**Comment by d0choa** [comment]
The next is a log of all the inputs @JarrodBaker required in the latest genetics release:

```
Preparing to copy genetics resources
copy static files from previous release
Copy [gs://genetics-portal-dev-data/21.10/inputs/lut/biofeature_labels.json]() to [gs://genetics-portal-dev-data/22.02.4/inputs/lut]()
Copy [gs://genetics-portal-dev-data/21.10/inputs/lut/vep_consequences.tsv]() to [gs://genetics-portal-dev-data/22.02.4/inputs/lut]()
Copy [gs://genetics-portal-dev-data/21.10/inputs/lut/v2g_scoring_source_weights.141021.json]() to [gs://genetics-portal-dev-data/22.02.4/inputs/lut]()
Add date versioned LUT inputs
Copy [gs://genetics-portal-dev-staging/lut/biofeature_labels/220105/biofeature_labels.w_composites.json]() to [gs://genetics-portal-dev-data/22.02.4/inputs/lut/biofeature_lut_220105.w_composites.json]()
Add versioned v2d inputs
Copy [gs://genetics-portal-dev-staging/v2d/220210/studies.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/studies.parquet]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/ld_analysis_input.tsv]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/ld_analysis_input.tsv]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/locus_overlap.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/locus_overlap.parquet]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/trait_efo-2021-02-14.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/trait_efo-2021-02-14.parquet]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/finemapping.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/finemapping.parquet]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/toploci_betas_fixed.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/toploci_betas_fixed.parquet]()
Copy [gs://genetics-portal-dev-staging/v2d/220210/ld.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d/ld.parquet]()
Add colocation files to v2d inputs
Copy [gs://genetics-portal-dev-staging/coloc/220127/coloc_processed_w_betas_fixed.parquet]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2d]()
Add versioned v2g inputs
Copy [gs://genetics-portal-dev-staging/v2g/interval]() to [gs://genetics-portal-dev-data/22.02.4/inputs/v2g/interval]()
Copy [gs://genetics-portal-dev-staging/v2g/qtl/220105]() [gs://genetics-portal-dev-data/22.02.4/inputs/v2g/qtl/]()
Add variant annotations from previous release
copy [gs://genetics-portal-dev-data/21.10/inputs/variant-annotation/190129]() to [gs://genetics-portal-dev-data/22.02.4/inputs/variant-annotation]()
COPY STATIC INPUTS: SUMSTATS AND CREDSET
Copy sumstats -- not used in pipeline, only for clickhouse
Copy [gs://genetics-portal-dev-sumstats/filtered/pvalue_0.005/gwas/220208]() to [gs://genetics-portal-dev-data/22.02.4/outputs/sa/gwas]()
Copy [gs://genetics-portal-dev-sumstats/filtered/pvalue_0.005/molecular_trait/220105]() to [gs://genetics-portal-dev-data/22.02.4/outputs/sa/molecular_trait]()
Copy credset -- not used in pipeline
Copy [gs://genetics-portal-dev-staging/finemapping/220113_merged/credset/*]() to [gs://genetics-portal-dev-data/22.02.4/outputs/v2d_credset/]()
Done downloading
gsutil ls [gs://genetics-portal-dev-data/22.02.4/inputs]()
```

The new implementation does not need to be backwards compatible. @opentargets/be-team is also flexible to propose how the inputs should look like: structure, filename, timestamps, etc.

@mbdebian could you help with this?

**Comment by JarrodBaker** [comment]
We're closing this ticket for the time being (it might be revisited in the future). 

The justification for having PIS is to create a snapshot of the inputs to the ETL at the time of the release. Since we rely on many external data providers for inputs, and these are not always versioned, it is necessary for us to keep a copy to ensure reproducibility of the platform. In the case of genetics, we control the universe of inputs, so there is not the same need to create a snapshot of the data. 

In future the BE team will liaise with the data team to select the correct input files for the data joining (ETL) step.
