### ISSUE TITLE
Coalesce target index in Genetics and Platform

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1931]
We want to collect all the tasks necessary to unify the target dataset in Platform and the gene dataset in Genetics.

At the moment we maintain both separately, which entails:
- Duplicated effort when generating and maintaining them.
- Because of avoiding duplication we are losing value in both platforms. For example, the Genetics team has reported that it would be interesting to show the genetic constraint widget in the Portal. We don't want to replicate the code we already have for that in Platform for Genetics. The same applies the other way around.
- Possible discrepancies between the two.

**Comment by d0choa** [comment]
So far being handled as individual issue in #1947
