### ISSUE TITLE
Define location of evidence file for the partner preview

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1933]
As a developer I want to have a defined location from which the evidence files for the partner preview can be picked up/deposited. 

## Background

The output of the platform evidence parsers are deposited to defined google buckets, and the same buckets are defined in the PIS configuration too, so ELT can further process them.

The same definitions are expected to exist for the evidence files for the partner preview. Currently we have three data sources: validation lab, encore and ot_crispr.

## Tasks

- [ ] Create buckets 
- [ ] Make sure the buckets are not publicly accessible 
- [ ] Let data team and backend team know about these location so configurations can be updates.

**Comment by DSuveges** [comment]
As a start the location of the three evidence files are:
1. `gs://ot-team/dsuveges/partner_preview/encore/encore-2022-02-05.json.gz`
2. `gs://ot-team/dsuveges/partner_preview/validation_lab/validationLab_2022-02-12.json.gz`
3. `gs://ot-team/dsuveges/partner_preview/ot_crispr/ot_crispr_2022-02-14.json.gz`

I'll update this ticket if new files will be deposited.

**Comment by andrewhercules** [comment]
Also, the list of OTAR projects and EFO codes used in [`opentargets-projects.sc`](https://github.com/opentargets/platform-etl-backend/blob/master/scripts/opentargets-projects.sc) can be found at:

1. `gs://ot-team/dsuveges/partner_preview/otar_projects/otar-projects-efo-mapping_2022-02-14.tsv`

This file is an updated version of the file noted in [lines 115-118 of the opentargets-projects.sc file](https://github.com/opentargets/platform-etl-backend/blob/4fadac76677cfe7b4380582f8563d9625513aaa3/scripts/opentargets-projects.sc#L115).

**Comment by DSuveges** [comment]
The files in the above listed buckets are updated. Those links point to the most recent files.

**Comment by ktsirigos** [comment]
@DSuveges can this be closed?
