### ISSUE TITLE
Update front end to show MR evidence

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#1958]

**Comment by andrewhercules** [comment]
Low-fidelity mockups for MR data in the Genetics Portal have been uploaded to the [team Google Drive](https://drive.google.com/drive/folders/1FJcHLyGxVd9DChEi_kqPc4jrf5nEGacW). Some of the features (e.g. a PheWAS plot showing the data) could be reused for the Platform front-end integration.

**Comment by d0choa** [comment]
Not happening in the short term
