### ISSUE TITLE
Decrease loading times for ES and CH for Genetics

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#1961]
As a developer I want to quickly prepare production-ready infrastructure so we can iterate quickly. 

## Background

The data for the Genetics Platform is produced by the genetics pipeline and the genetics team. This data is then loaded into Elasticsearch (ES) and Clickhouse (CH) for use by the API. Loading the data into these data sources takes over 17 hours. Coupled with a slow ETL, this means that it's impracticable to run the full process more than twice per week during development cycles. 

The data is currently loaded using a [bash script](https://github.com/opentargets/genetics-backend/blob/master/loaders/clickhouse/create_and_load_everything_from_scratch.sh) (script). 

There are two areas of obvious improvement that can be made:

1. The input file formats are a combination of json, compressed json, and parquet. The reason for this is that output formats are hard coded in the genetics pipeline. [Benchmarking](https://tech.marksblogg.com/faster-clickhouse-imports-csv-parquet-mysql.html) has shown that Parquet is between 2-5x faster than json.
1. The script runs on a machine _a_ to load data to CH running on machine _b_. The data is stored in Google Storage (GS). The script requests the data from storage (loading it onto _a_), and then sends it to CH. This means that we have twice the network traffic (and latency) than is required. 
1. The CH tables do not interact with one another but the load scripts are executed sequentially. Each table could be loaded in parallel.
1. ES is loaded only after CH has finished loading. This is because the data for ES is extracted from CH and then inserted into ES. This also suffers from the issue that the data is requested from CH by a machine _a_, collected there, and then sent on to ES. The inputs to ES are the study, gene and variant indexes from the pipeline. These can be prepared by the pipeline in the correct format (json) and shape (partitioned by chromosome) for direct insertion into ES. 

## Tasks

- [ ] Update the pipeline to have configurable output formats so we can have parquet for CH and json for ES
- [ ] Creating a loading system so that data is not passed through an intermediary (one idea would be to have CH and ES load the data as part of their start-up script)

**Comment by d0choa** [comment]
More details on my previous comment here:
https://github.com/opentargets/genetics/issues/543

**Comment by d0choa** [comment]
No more work is scoped
