### ISSUE TITLE
Improve column that displays evidence confidence

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1963]
## Actions

- [ ] when `sourceId == "gene2phenotype"`, we want to add a tooltip to the `Confidence category` column with the following text: `As defined by the [GenCC Guidelines](https://thegencc.org/faq.html#validity-termsdelphi-survey)` 
- [ ] when `sourceId == "clingen"`, we want to add a tooltip to the `Classification` column with the following text: `As defined by the [GenCC Guidelines](https://thegencc.org/faq.html#validity-termsdelphi-survey)`
- [ ] when `sourceId == "expression_atlas"`, we want to add a tooltip to the `Experiment confidence` column with the following text: `As defined by the [Expression Atlas Guideline](https://www.ebi.ac.uk/gxa/FAQ.html)` 
- [ ] when `sourceId == "genomics_england"`, we want to add a tooltip to the `Gene rating` column with the following text: `As defined by the [Panel App Guidelines](https://panelapp.genomicsengland.co.uk/#!Guidelines)` 

## Context

<details>
<summary>Dropdown with the sources that need a tooltip:</summary>

### ClinGen
- All different values:
```
+-----------------------------+
|confidence                   |
+-----------------------------+
|Refuted                      |
|No Known Disease Relationship|
|Strong                       |
|Definitive                   |
|Moderate                     |
|Disputed                     |
|Limited                      |
+-----------------------------+
```
- Action: tooltip linking to https://thegencc.org/faq.html#validity-termsdelphi-survey

### Gene2Phenotype
- All different values:
```
+--------------+
|confidence    |
+--------------+
|definitive    |
|both RD and IF|
|strong        |
|limited       |
|moderate      |
+--------------+
```
- Action: tooltip linking to https://thegencc.org/faq.html#validity-termsdelphi-survey

### Panel App
- Alll different values:
```
+----------+
|confidence|
+----------+
|green     |
|amber     |
+----------+
```
- Action: tooltip linking to https://panelapp.genomicsengland.co.uk/#!Guidelines

### Expression Atlas
- All values:
```
+----------+                                                                    
|confidence|
+----------+
|low       |
|high      |
|medium    |
+----------+
```
- Action: tooltip linking to https://www.ebi.ac.uk/gxa/FAQ.html
</details>

<details>
<summary>Dropdown with the sources that do not need a tooltip:</summary>

### Uniprot/Uniprot literature
- All values:
```
+----------+
|confidence|
+----------+
|high      |
|medium    |
+----------+
```
- Action: none. Values are self explanatory and I haven't found specific documentation about them.

### Orphanet
- All values:
```
+----------------+
|confidence      |
+----------------+
|Not yet assessed|
|Assessed        |
+----------------+
```
- Action: none. Values are self explanatory and I haven't found specific documentation about them.

### EVA/EVA Somatic
- Here confidence refers to the review process of the evidence..
```
+----------------------------------------------------+
|confidence                                          |
+----------------------------------------------------+
|criteria provided, conflicting interpretations      |
|practice guideline                                  |
|no assertion provided                               |
|reviewed by expert panel                            |
|criteria provided, single submitter                 |
|no assertion criteria provided                      |
|criteria provided, multiple submitters, no conflicts|
+----------------------------------------------------+
```
- Action: tooltip linking to https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/

### Cancer Biomarkers
- Here confidence refers to the source of the evidence. Values are self explanatory and link out to the relevant resource.
```
+--------------------+                                                          
|          confidence|
+--------------------+
|     NCCN guidelines|
|         Case Report|
|        Pre-clinical|
|         Late trials|
|      FDA guidelines|
|         Case report|
|     CPIC guidelines|
|European Leukemia...|
|        Early trials|
|     Clinical trials|
| NCCN/CAP guidelines|
|        Early Trials|
+--------------------+
```
Action: none
</details>

**Comment by andrewhercules** [comment]
Ticket scoped for `22.04` release and added to [release intentions document](https://docs.google.com/document/d/1DcQ1CVg0jgQpJlKSvVCQkcYznwaAKiUcY0khToA0Ubg/edit#heading=h.eu86k7xr40xz)

**Comment by remo87** [comment]
Thanks a lot @ireneisdoomed !
