### ISSUE TITLE
Update how Data Downloads page is generated

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1971]
Currently, the Platform Data Downloads page requires two files that are stored in the front-end `platform-app` codebase:

* [downloadData.json](https://github.com/opentargets/platform-app/blob/main/src/pages/DownloadsPage/downloadData.json)
* [dataset-mappings.json](https://github.com/opentargets/platform-app/blob/main/src/pages/DownloadsPage/dataset-mappings.json)

The `downloadData.json` file is produced by the ETL pipeline and lists the datasets available in JSON and Parquet formats. The `dataset-mappings.json` file is a JSON version of the [dataset mapping spreadsheet](https://docs.google.com/spreadsheets/d/1_266iRiVlCRii9cVLJ6__GCQVCw88QypEp6kXz8OcfQ) that gives a readable label for each dataset and indicates if the dataset should be listed on the Data Downloads page and included in our BigQuery `open-targetes-prod` instance
 
As noted in #1790, the management and updating of these files is manual and can sometimes lead to errors.

Instead, the Data Downloads page should be refactored to query a Google Cloud bucket and download a version of the `downloadData.json` file automatically generated by the ETL pipeline. Additionally, the `dataset-mappings.json` file should be made available in the same bucket as this file is also used by `platform-output-support` to decide which datasets are uploaded to our `open-targets-prod` BigQuery instance. 

Additionally, a future piece of work would be to expose the dataset schemas available in the `downloadData.json` file so that users can understand the fields that are available in each dataset.

**Comment by mbdebian** [comment]
A download.json file is now prepared by POS for as part of the web application static data context, which will be picked up by the web application provisioner at infrastructure level, and deployed as part of the web application.
See opentargets/platform-output-support#11 and opentargets/platform-etl-backend#247

**Comment by d0choa** [comment]
One less thing to worry about in future releases
