### ISSUE TITLE
Add relevant tags to Google Tag Manager container in Partner Preview Platform

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#1974]
Currently, the Partner Preview Platform (PPP) has an empty Google Tag Manager (GTM) container. Depending on the approach taken with the release of the PPP, we may want to include the following tags:

- [ ] Google Analytics (will require setting up a separate property within the Open Targets Google Analytics account)
- [ ] HubSpot (to make release/new data announcements)
- [ ] Cookie Banner (can be amended to link to Terms of Use and Partner Platform Data Policy)

All of these tags have been implemented within the Platform and Genetics GTM containers and can be copied to the Partner Preview GTM container. When adding new tags to the Partner Preview GTM container, ensure that tags fire on "All Pages" and on "History Change" (note: the "History Change" trigger has already been created).

**Comment by buniello** [comment]
As a first step, I plan to write a short text for the partners about how we use the PPP traffic information, which can be added as a "disclaimer note" on the intranet.
This may be helpful to reach a final decision on tracking PPP traffic with Analytics.
