### ISSUE TITLE
Move L2G workflow into the Genetics ETL

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#1977]
## Context

Currently the L2G workflow consists of:
1. The Genetics team generates a series of data: V2D, fine-mapping, coloc pipelines.
2. The BE team takes these data as inputs and processes them in the ETL.
3. The Genetics team runs the L2G pipeline from several of the ETL outputs.
4. The BE team stores and exposes the data generated in step 2) and 3) to be ingested by the API, BigQuery, ES.

We want to improve the management of dependencies in this pipeline and minimise the back and forth between the Genetics team and those processes that can be automated in the ETL in order to make the process of releasing a new version of Genetics less dependent on human resources.

## Proposal
We want to transfer the logic of the L2G pipeline (point 3) to the ETL, ideally written in Python, as the dependencies at this point are mostly products already generated by the ETL. After studying how the pipeline works, we identified two main processes:
1. Annotation of all the variants on which we are interested in running the pipeline on with the features required by the model.
2. Implementation of the model.

The second step is straightforward and should be easy to implement in Scala. The challenge is in step 1), which implies annotation of the variants with data from external sources to the ETL itself. This logic exceeds the purposes of ETL. For that reason, we want to write this logic in Python and integrate these scripts into the ETL.

## Actions
I want to run the `predict.py` script in the ETL to intercept in a first phase what are the complications and requirements of such integration. I am interested to know:
- Do the inputs have to follow a specific model?
- Do the outputs have to follow a specific model?
- Are dependencies in Python a problem? What is the best way to indicate them in order to integrate them in the ETL?

Once these things are cleared out, I can keep developing the script taking into account the particularities that the BE can find.

## Workflow
- To setup the Python environment I have followed the current README (I install the dependencies on a conda environment)
- The code we want to integrate is available at: https://github.com/opentargets/genetics-l2g-scoring/blob/il-l2g-predictions/production/predict.py
This is how I ran it on my local machine:
```bash
python3 production/predict.py \
  --feature_matrix data/featurematrix_w_goldstandards.full.220212.parquet \
  --classifier data/model/xgboost-full_model-high_medium-0.model.joblib.gz \
  --output_file output/predictions-2022-03-08.parquet
```
- The script inputs are available here:
    - feature_matrix: `gs://genetics-portal-dev-staging/l2g/220212/gold_standards/featurematrix_w_goldstandards.full.220212.parquet`
    - classifier: `gs://genetics-portal-dev-staging/l2g/220128/models/xgboost-full_model-high_medium-0.model.joblib.gz`

**Comment by DSuveges** [comment]
I'm not sure if it makes sense to write a Python script to do the annotations of the variants by picking up output of the ELT then use the ETL to run the model. However it could be an intermediate stage until the logic is not implemented in scala. It would potentially relieve the @opentargets/be-team for the time being.

Also not sure keeping this process somewhat separated from the ETL could help reducing duplication when considering the tools required to retrain the model.

**Comment by ireneisdoomed** [comment]
Thank you for your comments @DSuveges.

@JarrodBaker's opinion is that we should aim to execute jobs on a Dataproc cluster regardless of whether the code is written in Python or Scala.
I have therefore adapted the script in such a way that it can be run from Dataproc, so this approach is easy to test. Instructions on how to create the cluster and submit the job are available in the [production README](https://github.com/opentargets/genetics-l2g-scoring/blob/il-l2g-predictions/production/README.md).

**Comment by ireneisdoomed** [comment]
Updated instructions on how to run the above script.
Based on a conversation with @JarrodBaker, it is preferable to use an approach where arguments are read from a configuration file that gets updated with every release. This makes the process more transparent as we will be always sure what arguments were given to run the job.

Therefore the script has been adapted to parametrise it from a YAML file rather than from a CLI parser. I've decided to use [Hydra](https://hydra.cc) rather than more common solutions because it has nice features like:
- the possibility of overriding the configuration from the command line
- Nice integration with Python's logging
- Automatic generation of a log per run
- the possibility of easily pointing to different configurations depending on the context (experimental vs production)

The instructions to run the job by adding this configuration file to the Dataproc context have been updated in the [README](https://github.com/opentargets/genetics-l2g-scoring/tree/il-l2g-predictions/production). @JarrodBaker, can you give it a go and let me know if everything works as expected?

**Comment by JarrodBaker** [comment]
Thanks @ireneisdoomed . Thanks for extracting the configuration. I haven't run it yet, but looking at the code/readme I expect to be able to integrate it. One thing we'll be doing is creating our own initialisation action script to manage the dependencies as the examples provided by Google are just for demonstration purposes and are subject to change without notice. 

Nice work. I'll circle back to this issue when I'm back from leave.

**Comment by ireneisdoomed** [comment]
After investigation on how this process should be done, I've converted this issue into an epic and created more isolated tickets to discuss what the process should consist of.

### Current process
The current pipeline is quite complex and to run it a lot of human intervention is required. 
5 steps, all described in the [README](https://github.com/opentargets/genetics-l2g-scoring/blob/il-l2g-predictions/README.md):
1. Feature engineering. 
- Fine mapping + Functional genomics features.
2. Gold standard processing.
3. Model training (XGBoost)
4. Model validation.
5. Model prediction on all loci.

### New process
Will consist of 4 steps which will be submitted as jobs to a Dataproc clusters. The dependencies will come from the ETL, hence solving the graph of dependencies.
1. Feature engineering (#2608). The output will be a table with the feature matrix.
2. Gold standard processing (#2609). The output will be a table collecting the GS to train the classifier.
3. Model training (#2610). The output will be the XGBoost model.
4. Model prediction (#2611). The output will be a table with all variants and their annotation.
