### ISSUE TITLE
FAERS dataset (Significative ones) contains entries where the MedDRA term is null

### ISSUE THREAD

**Issue by mkarmona** [opentargets/issues#1983]
The significative Adverse Drug reactions dataset, version `220204`, contains entries where the MedDRA term is `NULL`. Exploring a bit further, there are 269 nullified entries. Those entries correspond to a `225` unique chembl ids.

```Scala
otSigAEsDF.filter($"meddraCode".isNull).count
otSigAEsDF.filter($"meddraCode".isNull).select("chembl_id", "meddraCode").distinct.count
```

I expect a dataset with 0 nullified entries. As a reference, the used dataset is [this](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.02/output/etl/parquet/fda/significantAdverseDrugReactions/).

**Comment by mbdebian** [comment]
We have just released 22.09 ^_^
