### ISSUE TITLE
You can’t search for some study IDs

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2052]
There are some study IDs where if you type in the exact ID, nothing shows up in the search result list.
E.g. NEALE2_30190_raw
You can search for “monocyte percentage” and you find the study and can go to the study page. But you can’t search by the exact ID. Why not?
If you enter less text, e.g. “NEALE2_30190”, it also works, i.e. it shows in the search bar, so it’s the text after the number that makes it fail.

**Comment by buniello** [comment]
added to feature doc
