### ISSUE TITLE
Implement zooming in PheWAS plot

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2061]
In many cases, there is one association for a variant that is vastly stronger than the others. As a result, this one dominates the scale of the plot, and it is difficult to see whether other associations are above or below the significance threshold. Indeed, their labels often overlap because of this, so it is unreadable.
Here are two examples:
1_154453788_C_T (the example on our homepage)
1_55055436_G_A

![image](https://user-images.githubusercontent.com/11073896/143046402-6bdc3b7b-3027-4781-9818-61b0f9277faa.png)

**Comment by buniello** [comment]
added to feature doc
