### ISSUE TITLE
Loci with strong associations are fine-mapped incorrectly

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2062]
I thought I would make an issue here so that we keep track of this.

our current approach is to use GCTA-cojo to identify independent signals, using LD from 10,000 UK Biobank samples as a reference panel. (We only do fine-mapping for European GWAS so far.)
 
There is a problem with this though – at loci with strong associations, the fine-mapping can go wrong due to differences in LD between the reference panel and the GWAS sample. You can see this at almost any locus with a strong signal – e.g. APOE in Alzheimer’s disease. For example, this is a GWAS for family history of AD in UK Biobank samples:
https://genetics.opentargets.org/study/GCST005921

You can see that the genetics portal is reporting 20 independent signals, but 15 of these are at the APOE locus. Most likely, these all simply reflect the APOE4/APOE3/APOE2 haplotypes, but we are nominating different genes at these different “signals”. This occurs even though our reference panel is from the same population as the GWAS sample.
If you want to find more examples, look at any GWAS with strong associations, such as blood cell counts, or pQTLs.
Indeed, I’m concerned about integrating more pQTL datasets, because with the increasing sample size, this problem will get worse.

We need to determine a good solution.
My suggested approach is that we only do fine-mapping for GWAS with exclusively UK samples (e.g. UK Biobank), and use a larger reference panel (at least 50,000 UKB samples?). We could still perform colocalisations using the full marginal summary stats at each locus where we don't perform fine-mapping.

**Comment by buniello** [comment]
closing as added to feature doc
