### ISSUE TITLE
GWAS catalog entries with multiple SNPs in a row fail to import

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2063]
Jae Hoon Sul noticed that we are missing some GWAS catalog entries - mainly older ones.
Examples present in GWAS catalog but absent in OT Genetics:
https://www.ebi.ac.uk/gwas/studies/GCST001449
https://www.ebi.ac.uk/gwas/studies/GCST008413

On investigation I found that these all have multiple SNPs listed in a single row in the GWAS catalog (https://www.ebi.ac.uk/gwas/api/search/downloads/alternative), i.e. haplotypes.  Annalisa said that they are in the process of phasing out support for putting haplotypes as the associated SNP entry. On looking through the catalog, I can see that the last study which did this was 2020-9-29, and before that 2018-11-1, so they are very rare recently. In all this affects 60 studies, and the vast majority of the entries come from the Oncotarget study listed above (which is of poor quality).

It should be possible to check for the presence of multiple SNPs and then just take the first one in these cases.

**Comment by d0choa** [comment]
@DSuveges done, isn't it?
