### ISSUE TITLE
Define criteria for whether to include new GWAS

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2066]
More publications are producing hundreds of GWAS at once and submitting the summary statistics to GWAS catalog. But some of these are of questionable value for Open Targets Genetics, and each sumstat-based GWAS added has a computational cost to analyse and to maintain. We need to define criteria to determine whether GWAS from a new study should be included in OT Genetics. We could consider that we only process sumstats for studies of significant value, and that for other studies we are happy to get their reported associations (top loci) but without a sumstat-based analysis.

Examples of studies with questionable value, relative to the scale of GWAS data:

- New methods applied to existing data: 2989 GWAS on UKB with another method (http://europepmc.org/article/MED/34737426)

- Computationally derived phenotypes of questionable medical value: 1048 GWAS on facial traits (http://europepmc.org/article/MED/33983923)

- Studies that are underpowered relative to the number of GWAS done: (Orru et al, PMID 32929287, 731 GWAS and a couple hundred associations; Rühlemann et al, PMID 33462482, 430 GWAS and 38 total associations; many more examples)

- GWAS with problematic interpretation: e.g. PMID 33893285: 110 GWAS for 22 age-related diseases in GERA cohort, but with 5 GWAS models on each disease (additive, dominant, etc), and no way to distinguish which is which

- New (or old) GWAS of lower quality than existing GWAS. E.g. which pQTL studies should we keep once we have pQTLs from 56,000 UKB participants?

**Comment by d0choa** [comment]
My hope is that by streamlining the process we won't have to take this decision.
But the points raised above are all valid.
Closing because there is no immediate action but we should keep this in mind for the future
