### ISSUE TITLE
Map 171 new Finngen endpoints in DF6 to EFO 

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2068]
A new table with the 171 extra endpoints that require mapping to EFO, as well as all the other previous mappings. EFO suggestions are all made by ontoma using the 3.19.0 version of EFO.

https://docs.google.com/spreadsheets/d/1RRWfUTLy4TO9XmBzcbJ2wPRdda3qISjRS4PJmEdxE3k/edit#gid=1853278839

Messy scripts used to assist with the task are now in a repo [finngen2efo](https://github.com/opentargets/finngen2efo)

**Comment by ireneisdoomed** [comment]
This has been done and implemented.
