### ISSUE TITLE
Variant pQTL studies remove `Sun et al` data/BE

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2069]
Right now the FE is parsing the `genesForVariantSchema` field in `variant` to remove **(Sun, 2018)** 
This should be handled by the data/BE

**Comment by buniello** [comment]
I have modified the OTG [Metadata Schema](https://github.com/opentargets/genetics-api/blob/master/resources/v2g_display_labels.json) at the source - deleted the (Sun, 2018) text from the pQTL header.

**Comment by buniello** [comment]
closing as added to feature doc
