### ISSUE TITLE
No betas should equal 0.0 in the coloc tables

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2075]
For example, the gwas-gwas results here:

https://genetics.opentargets.org/study-locus/NEALE2_20002_1453/12_111427245_C_G

They should be null.

**Comment by d0choa** [comment]
@remo87 could you have a quick look at this very old ticket? I'm assuming nulls are converted to 0s in the GWAS Study Colocalisation table.

**Comment by remo87** [comment]
> @remo87 could you have a quick look at this very old ticket? I'm assuming nulls are converted to 0s in the GWAS Study Colocalisation table.

That's correct what would be the correct way to show nulls? a blank space or the N/A value?

**Comment by d0choa** [comment]
You can use `N/A` for consistency

**Comment by remo87** [comment]
Ok!

**Comment by buniello** [comment]
hi @remo87 are you happy for me to close this issue?
