### ISSUE TITLE
No option to add custom logo next to open targets genetics title

### ISSUE THREAD

**Issue by forus** [opentargets/issues#2078]
I need to add an organization logo to the left from the open targets genetics titles everywhere in the application. The logo's height has to be adjusted with respect to the title font size.

![Screen Shot 2019-06-17 at 11 15 33](https://user-images.githubusercontent.com/492175/59593077-99997580-90f1-11e9-8797-6e35bc1dad06.png)

**Comment by d0choa** [comment]
Closing as PRs were discussed and closed. Please raise if there is something I'm missing.
