### ISSUE TITLE
Michailidou (2015) top loci irregular

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2080]
Study ID: GCST007236

https://dev--genetics-app.netlify.com/study/GCST007236 

Symptoms:
- Many top loci on chroms 20 and 21
- There is another study ID for Michailidou (2015): https://dev--genetics-app.netlify.com/study/GCST004950

Have checked toploci table and the problem exists there. Need to check the credible set table:

```
gsutil -m cat gs://genetics-portal-data/credible_sets/190430/part-\*-e86fcb17-55d9-4eb8-84a1-6861c2742d01-c000.json.gz | zgrep GCST007236 > credible_sets.GCST007236_only.json
```

I should also check the raw sumstat data: `gs://genetics-portal-sumstats-b38/unfiltered/gwas/GCST007236.parquet`

**Comment by d0choa** [comment]
Data has been updated since last comment, so assuming the problem is fixed. Please raise if not
