### ISSUE TITLE
Document clickhouse requirements and custom settings to get data loaded

### ISSUE THREAD

**Issue by forus** [opentargets/issues#2081]
I get all kind of errors while loading data with [create_and_load_everything_from_scratch.sh](https://github.com/opentargets/genetics-backend/blob/master/loaders/clickhouse/create_and_load_everything_from_scratch.sh) script to `ot` database when I use the default settings of clickhouse (v19.5.3.8).

Here discovered issues so far:
- `Too many partitions for single INSERT block (more than 100).` Reported in [this PR](opentargets/issues#2082)
- `Memory limit (for query) exceeded: would use 9.31 GiB`
- By default, CH does not fall back using disk when a query result does not fit in the memory.

It would help a great deal to document CH requirements (e.g. how much RAM on the server is required) and custom settings that have to be changed above [these](https://clickhouse.yandex/docs/en/operations/tips/) to be able to load the data.

**Comment by JarrodBaker** [comment]
We're revamping the loading of genetics and this issue appears to have been resolved.
