### ISSUE TITLE
Access to v2g_scoring_source_weights.tsv

### ISSUE THREAD

**Issue by forus** [opentargets/issues#2084]
@afaulconbridge, @edm1, @mkarmona, @pieterlukasse

Hi guys, 
while loading data to clickhouse I've discovered that [external dictionary source file](https://github.com/opentargets/genetics-backend/blob/master/loaders/clickhouse/dictionaries/weights_dictionary.xml#L6) is absent in the project.

Would it be possible to publish this file?
e.g. [here](https://github.com/opentargets/genetics-backend/tree/master/loaders/clickhouse/dictionaries) or gs:///open-targets-genetics-releases/19.03.03

gs://genetics-portal-data/ seems to be private.

**Comment by d0choa** [comment]
Please raise it if still valid. I'm assuming this was resolved
