### ISSUE TITLE
Exclude studies from clustering step in V2D pipeline

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2085]
Email from Daniel Seaton suggests GCST005922 should not have clustering step applied to it. We should maybe have a list of studies to exclude from the clustering step.

**Comment by d0choa** [comment]
@DSuveges please consider this when reviewing V2D. Please close if appropiate

**Comment by DSuveges** [comment]
I think this is not an issue anymore as we are changing the clustering logic, so it is no longer distance based but LD based. The cited study is quite interesting: out of the 220 associations 138 are on chromosome 19 in a very narrow region.
