### ISSUE TITLE
Implement consistent styling of internal and external links and buttons

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#2086]
Following on the last Genetics Portal meeting on Friday 15 March 2019 and based on work for the Platform rewrite project, I have updated the design pattern for internal links and external links and buttons.

## External links

All external links should be styled in Open Targets Corporate Blue - `#3489ca`. If there is a unique identifier available from the Genetics Portal API response, the interface should display the name of the linked web resource and the unique identifier, with the unique identifier as the link. See below for an example of the links that would appear at the top of the variant and study pages:

![Screen Shot 2019-03-25 at 15 25 24](https://user-images.githubusercontent.com/7490258/54932559-e9153e80-4f12-11e9-99a2-33b960d6d35b.png)

If there is no unique identifier available from the Genetics Portal API response, then the interface could display the name of the linked web resource as the clickable link.

## Internal links

All internal links to other pages within the Genetics Portal should be styled in Open Targets Corporate Blue - `#3489ca`.

## Buttons

**Locus Plot buttons**

To improve readability and recognition, I have [updated the locus plot icon](https://drive.google.com/open?id=1mnSMZHrBC6Zc07CY8j4AOKku2469qlk7) to better reflect the structure of the plot and to optimise the icon for use with different sized buttons

All locus plot buttons should be flat and in Open Targets Open Targets Corporate Blue - `#3489ca`. A flat button style in one colour will improve contrast and readability of the text and icons, especially for smaller buttons found in data tables

![Screen Shot 2019-03-25 at 15 58 01](https://user-images.githubusercontent.com/7490258/54935189-b3bf1f80-4f17-11e9-88dd-ada24cce89d5.png)

**Download data table buttons**

The design for these buttons can remain as-is - white with a light grey background on-hover.

**Comment by d0choa** [comment]
We will address this in separate tickets/work
