### ISSUE TITLE
Gene-level annotations

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2087]
Something for the future.

Gene-level annotations to be displayed alongside gene labels (e.g. in V2G table on variant page, or the locus plot). These could include:
- [ ] Whether drugs are available
- [ ] Tissues expression and tissue specificity
- [ ] Gene constraint (e.g. pLi scores, loftee)

**Comment by d0choa** [comment]
The data/BE part of this will be tackled as part of #1944. FE improvements can be derived from this work.
