### ISSUE TITLE
Develop and implement consistent data table design pattern across Genetics Portal

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/issues#2092]
Currently, if a user is on a laptop screen with a resolution of <1280px, it can be difficult to see that there are additional columns - see below for an example.
 
![screen shot 2018-10-08 at 15 58 40](https://user-images.githubusercontent.com/7490258/46616736-1d3aa580-cb13-11e8-83b1-b3435c164a3a.png)

Can we please give users a visual cue that there are columns that can be viewed in they scroll horizontally? For example, can we have the scroll bar visible?

**Comment by d0choa** [comment]
@carcruz we are planning to work on this. But we are closing the ticket as @ktsirigos and I think the work will happen organically as part of the monorepo activities
