### ISSUE TITLE
Highlight independent loci in the credible set track

### ISSUE THREAD

**Issue by edm1** [opentargets/issues#2094]
This is an idea for a future post-ESHG release.

It would be really useful if we could highlight where independent loci for the same study are, in the title (top) credible set / regional plot track.

For example, for Hypercholesterolemia locus A:

https://dev--genetics-app.netlify.com/study-locus/SAIGE_272_11/1_55039974_G_T

We can see this single variant is the primary single:

![Screen Shot 2019-06-07 at 11 45 30](https://user-images.githubusercontent.com/1938268/59098981-ca232780-8919-11e9-9e59-3e8d22be696e.png)

However, there is another independent locus nearby, lets call it locus B:

https://dev--genetics-app.netlify.com/study-locus/SAIGE_272_11/1_55023869_C_T

![Screen Shot 2019-06-07 at 11 42 45](https://user-images.githubusercontent.com/1938268/59098853-6ac51780-8919-11e9-909f-b9284d0966d0.png)

When on locus B's page, it would be useful to be able to tell that the locus A variant has a page of its own that we can visit.

E.g., something along these lines

![Screen Shot 2019-06-07 at 12 23 13](https://user-images.githubusercontent.com/1938268/59100813-13c24100-891f-11e9-9f79-1ebac09c2411.png)

Note: this problem is usually solved by showing the LD between a selected variant and all other variants in the plot. We currently don't have the data to be able to do this.

**Comment by d0choa** [comment]
No plans to work on this in the short term.
