### ISSUE TITLE
Consider mendelian gene enrichment as feature for GWAS locus prioritization

### ISSUE THREAD

**Issue by eric-czech** [opentargets/issues#2103]
As an L2G feature, have you all ever considered or evaluated methods like [Sobczyk et al. 2021](https://academic.oup.com/bioinformatics/article/37/1/1/6102570)?  This would prioritize genes near GWAS hits based on enrichment of Mendelian disease for those genes.

This particular paper uses DO, ClinVar and HPO to establish these links so I imagine you could do something quite similar with EVA in place of DO+ClinVar.

**Comment by d0choa** [comment]
@buniello could you add this to the feature requests/prioritisation document?

**Comment by buniello** [comment]
Closing as added to feature document

**Comment by eric-czech** [comment]
> add this to the feature requests/prioritisation document

Thanks guys.  Is that doc public by chance?

**Comment by buniello** [comment]
Hi Eric - good point, the current list is not public but I will make sure its content is soon shared with all our users (e.g. through our community page).

**Comment by buniello** [comment]
Hi @eric-czech, me again! 
We have now released a "Feature Request" functionality within our [Open Targets Community](https://community.opentargets.org/c/feature-requests/16).
I wonder whether you would be willing to post this suggestion there? That would be very useful to us!
