### ISSUE TITLE
Strange coloc / variant results for PCSK9 & FinnGen

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2109]
I was exploring associations for PCSK9, and I found that some of the "Gene prioritisation" pages linked from the bottom section (Associated studies: Colocalisation analysis) don't load.

Go to the PCSK9 gene page: https://genetics.opentargets.org/gene/ENSG00000169174
Go to the bottom section (Associated studies: Colocalisation analysis) and go to the last page of this table. You should see rows for FINNGEN_R5_RX_STATIN with lead variant 1_55026029_T_C. Clicking on the link for Gene Prioritisation (https://genetics.opentargets.org/study-locus/FINNGEN_R5_RX_STATIN/1_55026029_T_C) shows a page that is blank, i.e. won't load.

Is this because 1_55026029_T_C isn't a locus lead variant in this FinnGen study? Why is it shows as the lead variant in the table?  FINNGEN_R5_RX_STATIN has a nearby lead variant that is much rarer, 1_55039974_G_T.

What is puzzling is why this coloc was present at all? If you go to the study locus for 1_55039974_G_T, https://genetics.opentargets.org/study-locus/FINNGEN_R5_RX_STATIN/1_55039974_G_T, then no colocalisations are shown, presumably because there was no overlap in credible sets between any gene QTL and this locus.

It seems like this coloc shouldn't exist, since 1_55026029_T_C isn't a lead variant in this FinnGen study. But in BigQuery, I can see that there are rows in the variant_disease_coloc table:

Row | left_study | left_chrom | left_pos | right_study | right_bio_feature | right_phenotype | coloc_h4 | left_var_right_isCC
1 | FINNGEN_R5_RX_STATIN | 1 | 55026029 | HIPSCI | IPSC | ENSG00000169174 | 3.7144894219737405E-10 | false |  
2 | FINNGEN_R5_RX_STATIN | 1 | 55026029 | GTEX_v7 | UBERON_0002048 | ENSG00000169174 | 6.724936786090025E-7 | false

**Comment by d0choa** [comment]
The data generation and processing has changed so much that I don't think this should be a problem anymore. Also filters around colocalisation have been lifted and study-locus of size one are now allowed which should impact all of the above
