### ISSUE TITLE
Keep both Jung et al and Javierre et al. 

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2110]
In the past, Jung et al. 2019 replaced Javierre et al. 2016. We want to keep both datasets. @MayaGhoussaini commented on this:

> We integrated Jung et al in 2019 after Takeda pointed it. It looks at long-range chromatin interactions  in 27 human cell/tissue types as opposed to Javierre et al 2016 which only focused on blood (It looks for PCHIC in 17 human primary hematopoietic cell types) so very relevant to study immune diseases and other blood related phenotypes. So i would keep both.

**Comment by JarrodBaker** [comment]
@d0choa: is any action needed on this? If the decision is to keep both that is what we currently have so no changes are required.
