### ISSUE TITLE
include a new  score in the weights table

### ISSUE THREAD

**Issue by mkarmona** [opentargets/issues#2111]
The new weight is for the source sQTL

```
{"type_id": "fpred", "weight": 1.0}
{"type_id": "sqtl", "weight": 1.0}
{"type_id": "eqtl", "weight": 0.66}
{"type_id": "pqtl", "weight": 0.66}
{"type_id": "pchic", "weight": 0.33}
{"type_id": "pqtl", "weight": 0.33}
{"type_id": "fantom5", "weight": 0.33}
{"type_id": "dhscor", "weight": 0.33}
{"type_id": "distance", "weight": 0.33}
```

**Comment by ktsirigos** [comment]
@remo87, keep it in mind for whenever you start working on this

**Comment by mbdebian** [comment]
@remo87 , this issue is pretty old, have you got any more details on this?
Maybe @ireneisdoomed ?
Thanks!

**Comment by ireneisdoomed** [comment]
Sorry for missing this.
@remo87 @mbdebian, the mentioned update is already in place for production ([config](https://github.com/opentargets/genetics-pipe/blob/6b88c877bbb72b5b72bcf4bb8f7274a242d9ccc6/src/main/resources/reference.conf#L55))
From now on, this configuration falls within the space of the new Genetics ETL.
mQTLs have not yet been resolved, but these weights will be part of the configuration of the V2G step. In principle, we'll follow what has been established previously: `sQTL: 1.0; pQTL and eQTL: 0.66`
