### ISSUE TITLE
Missing L2G data for some variants

### ISSUE THREAD

**Issue by BjornWouters** [opentargets/issues#2118]
I came across a couple of variants that are in the credible set of at least 1 study but there was no L2G data. I queried the database to get all the variants with no L2G data that are in a credset of one or multiple studies. For chromosome 1, the following variants are found that have no data:

```
1:5342365:C:T
1:49291596:A:C
1:49317100:A:G
1:49321583:T:A
1:49413450:A:G
1:57610121:C:A
1:57746070:C:T
1:72817008:G:T
1:72818154:C:T
1:72840099:G:A
1:72980562:G:A
1:72984806:T:C
1:73160130:A:T
1:73322049:CT:C
1:79529059:G:A
1:79767058:T:C
1:79986467:A:G
1:80330080:GA:G
1:80330491:C:T
1:80346335:G:C
1:80346644:T:C
1:82793397:G:T
1:82835042:T:A
1:87979232:G:A
1:88175380:A:G
1:95756097:C:T
1:95808433:T:C
1:95815904:C:T
1:95817296:C:A
1:95819829:G:T
1:95825813:G:A
1:95883952:CA:C
1:95948779:T:G
1:96033038:AT:A
1:96189144:T:G
1:104300059:A:G
1:104310488:G:T
1:104487844:C:T
1:105498755:T:G
1:105547842:A:G
1:106027048:A:G
1:106426000:A:C
1:163904997:A:G
1:163906282:C:A
1:163978463:A:C
1:164046655:G:C
1:188504467:C:G
1:188689549:AGTGTGTGTGTGTGT:A
1:188831956:A:C
1:188963528:A:G
1:191010062:C:T
1:191356013:G:A
1:191366220:T:C
1:195022605:G:A
1:195060488:C:CT
1:195083807:T:C
1:195175451:G:A
1:208833731:A:G
```

Is there a particular reason that these variants do not have L2G scores?

**Comment by Sjoerd-van-Hagen** [comment]
@ktsirigos am I correct in assuming that you are moving all issues from genetics into this repo to centralize the issue tracking?

@BjornWouters is this still relevant?

**Comment by d0choa** [comment]
That's correct @Sjoerd-van-Hagen. Trying with an even more centralised approach.

Without looking at the specific variants that @BjornWouters raised, it's likely this problem still holds. #2073 documents some of the potential reasons (which unfortunately are a few). We will be addressing them one by one in the near future

**Comment by d0choa** [comment]
Addressing this in https://github.com/opentargets/genetics_etl_python
