### ISSUE TITLE
Overall OT UI theme changes unexpectedly when you tweak a single setting

### ISSUE THREAD

**Issue by forus** [opentargets/issues#2119]
Steps to reproduce:
1. Specify the following in `platform-app/src/public/theme.js`:
```
const theme = {
  shape: {
    borderRadius: 3,
  }
}
```
2. Build and start the application.
3. Navigate to the landing page.
**ACTUAL:** the rest of the styling (e.g. color scheme) has changed.
**EXPECTED:** only the border-radius has to change. The rest of the styling has to remain as it was.

**Comment by carcruz** [comment]
Not an issue anymore due to the monorepo refactor
