### ISSUE TITLE
Unavailable clinical trials start dates seem to be displayed incorrectly as 1970

### ISSUE THREAD

**Issue by ellimilial** [opentargets/issues#2528]
**Describe the bug**
Some clinical trials start dates are incorrectly displayed as 1970 in the evidences / drugs view on the OT platform.

**Observed behaviour**
A surprisingly large amount of clinical trials are dated as 1970. 

**Expected behaviour**
A correct or no date should be displayed for each clinical trial.

**To Reproduce**
Go to [https://platform.opentargets.org/evidence/ENSG00000100804/EFO_0000191](https://platform.opentargets.org/evidence/ENSG00000100804/EFO_0000191)
Scroll down to ChEMBL section
Look at *Start date* column.
Row referring to *NCT00373906* has *Start date* set to 1970.

**Additional context**
Also visible at [https://platform.opentargets.org/evidence/ENSG00000165731/EFO_0000311](https://platform.opentargets.org/evidence/ENSG00000165731/EFO_0000311) where more data is present.
The clinical trial does not seem to contain a start date - verified by downloading a TSV file from the interface. 
*Speculation: 1970 is the start of UNIX time epoch, perhaps a none is mishandled.*

**Comment by d0choa** [comment]
The problem is that nulls are not nicely handled in this [line of code](https://github.com/opentargets/platform-app/blob/411bb92198cdccb0ef96b586f9cf1662684f8383/src/sections/evidence/Chembl/Body.js#L156).

API query example and response for APP-Alzheimer evidence [page](https://platform.opentargets.org/evidence/ENSG00000142192/MONDO_0004975):

```
query{
  target(ensemblId: "ENSG00000142192"){
    evidences(efoIds: "MONDO_0004975", datasourceIds: ["chembl"]){
      rows{
        studyStartDate
      }
    }
  }
}
``` 

```
{
  "data": {
    "target": {
      "evidences": {
        "rows": [
          {
            "studyStartDate": null
          },
          {
            "studyStartDate": "2009-12-01"
          },
          {
            "studyStartDate": "2017-03-29"
          },
          {

```

**Comment by d0choa** [comment]
Thanks, @ellimilial for reporting and @remo87 for the fix!
This will go live in the upcoming April Platform release
