### ISSUE TITLE
Integrate gene_burden into the ETL

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2546]
We are adding the results of gene burden analyses as a new evidence source for the upcoming release (22.04). We need to make the necessary changes in the ETL for it to be integrated.

### 1. Schema
The current schema is in a mature state and no changes are expected. This is an example piece of evidence:</summary>

```python
{
	"datasourceId": "gene_burden",
	"datatypeId": "genetic_association",
	"targetFromSourceId": "ACAP3",
	"diseaseFromSource": "6mm weak meridian left (5097)",
	"diseaseFromSourceMappedId": "EFO_0004731",
	"pValueMantissa": 9.25,
	"pValueExponent": -12,
	"beta": -0.148,
	"betaConfidenceIntervalLower": -0.191,
	"betaConfidenceIntervalUpper": -0.106,
	"oddsRatio": null,
	"oddsRatioConfidenceIntervalLower": null,
	"oddsRatioConfidenceIntervalUpper": null,
	"resourceScore": 9.250000e-12,
	"ancestry": "EUR",
	"ancestryId": "HANCESTRO_0009",
	"literature": ["34662886"],
	"projectId": "REGENERON",
	"cohortId": "UK Biobank",
	"studyId": "GCST90083260",
	"studySampleSize": 89735,
	"studyCases": 89735,
	"statisticalMethod": "ADD-WGR-FIRTH_M3.0001",
	"statisticalMethodOverview": "Burden test carried out with pLOFs and deleterious missense with a MAF smaller than 0.001%",
	"urls": null
}
```

#### 1.1 New fields
This source is bringing a few of new fields that need to be exposed in the API, namely:
- [x] `ancestry`: str: "Genetic origin of a population."
- [x] `ancestryId`: str: "Identifier of the ancestry in the HANCESTRO ontology"
- [x] `statisticalMethod`: str: "The statistical method used to calculate the association."
- [x] `statisticalMethodOverview`: str: "Overview of the statistical method used to calculate the association."
- [x] `studyCasesWithQualifyingVariants`: str: "Number of cases in a case-control study that carry at least one allele of the qualifying variant."

### 3. Source config
A PR to the config file is still pending. 

### 4. Evidence location
Evidence strings will follow the same pattern as the other sources found in `otar000-evidence_input`. They will be in a compressed JSON file here: gs://otar000-evidence_input/geneBurden/json, with the filename following the pattern: `gene_burden-YYYY-MM-DD.json.gz`

The evidence generation is still WIP, a temporary file with how the evidence shall look like is available at: `gs://ot-team/irene/gene_burden/regeneron-2022-03-30.json.gz`

**Comment by mbdebian** [comment]
PIS is now up to date to get the gene burden data, I'm now trying to find out more about this error in the ETL when processing the input data.

```
22/04/06 11:36:26 INFO io.opentargets.etl.backend.Evidence$: Validate each evidence: generating a hash to check for duplicates
22/04/06 11:36:26 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@7023812c{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
Exception in thread "main" org.apache.spark.sql.AnalysisException: Can't extract value from urls#127502: need struct type but got string; line 1 pos 0
	at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:74)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.$anonfun$resolve$1(package.scala:348)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
```

**Comment by ireneisdoomed** [comment]
@mbdebian This error indicates that `urls` is not a struct but a string. This bug is coming from the data, apologies for that. I fixed it later but didn't update the file. The updated `gs://otar000-evidence_input/GeneBurden/json/gene_burden-2022-04-05.json.gz` is fixed.

However, I just had a discussion with @d0choa and this field will be removed from the evidence. You can expect an update of the data this afternoon.

**Comment by mbdebian** [comment]
> @mbdebian This error indicates that `urls` is not a struct but a string. This bug is coming from the data, apologies for that. I fixed it yesterday but didn't update the file. The updated `gs://otar000-evidence_input/GeneBurden/json/gene_burden-2022-04-05.json.gz` is now correct.
> 
> However, I just had a discussion with @d0choa and this field will be removed from the evidence. You can expect an update of the data this afternoon.

That's what I thought @ireneisdoomed , but I was going to double check the data and the ETL in case it was a legitimate change in the data.

Please, let me know when the data update is ready and I'll pull it down with PIS.

**Comment by mbdebian** [comment]
I just gave it another round with the fixed version of the gene burden file and the ETL was successful.
This basically means that no data schema is broken, but it doesn't mean the results are ok, we'll have to evaluate them

**Comment by mbdebian** [comment]
Everything is up to date now, except for the API new fields.
I'll have a look at that and try to release a new API version.
I'll need to update POS configuration file to create the new images, and then the development deployment context for all this to be seen

**Comment by ireneisdoomed** [comment]
@mbdebian We've made changes to the schema. There is one new field that needs to be added to the API: `studyCasesWithQualifyingVariants`. See specifications in the first comment of the issue.

Data has been regenerated and validated to bring this change and can be found in `gs://otar000-evidence_input/GeneBurden/json/gene_burden-2022-04-11.json.gz`.

**Comment by mbdebian** [comment]
BTW, is there anything to do about?
```
gs://ot-team/irene/gene_burden/regeneron-2022-03-30.json.gz
```
I didn't really get that part of the issue, as PIS is now collecting the gene_burden file from its new 'impc' location.
