### ISSUE TITLE
Integrate new `variantHgvsId` in the Platform

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2549]
### Context
We will be having a new variant representation in the disease/target evidence coming from the EVA team for this release.
`variantHgvsId` will host the genomic location for single and complex variants in HGVS form as reported directly in ClinVar. It is important to note that this field **is not required**.

### Actions

- [X] Data: Add field to the JSON Schema
- [x] BE: Create the API endpoint
- [ ] FE: ~Fit new notation in the `Variant ID (RSID)` column at the `ClinVar` and `ClinVar (somatic)` tables.~ Alternatively, we could display the different notations in different columns. TBD.

**Comment by ireneisdoomed** [comment]
Specification for the new endpoint

field name: “variantHgvsId”
type: str 
description: “Identifier in HGVS notation of the disease-causing variant.”

**Comment by mbdebian** [comment]
So, it's not a new endpoint in the API but a scheme extension, right?

**Comment by mbdebian** [comment]
This is implemented in opentargets/platform-api/pull/107

**Comment by d0choa** [comment]
Entry with ClinVar widget:
https://platform.opentargets.org/evidence/ENSG00000001626/Orphanet_586

Entry with ClinVar somatic widget:
https://platform.opentargets.org/evidence/ENSG00000157764/EFO_0000756

**Comment by d0choa** [comment]
As today, `variantHgvsId` returns `null` in the development API, but we can expect this data to be populated soon
