### ISSUE TITLE
Rename Phenodigm

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/issues#2551]
We want to rename PhenoDigm as a data source to IMPC. This is a more accurate name since IMPC is the actual service that maintains the data, Phenodigm is rather the algorithm that establishes the link between phenotypes in mice and humans.

## Actions

- [x] Data: Change `phenodigm` to `impc` in the evidence_data_source_parsers.
- [X] Data: Change `phenodigm` to `impc` in the JSON schema.
- [ ] Data: Change documentation.
- [x] BE: Change `phenodigm` to `impc` in PIS.
- [x] BE: Change `phenodigm` to `impc` in the 
- [x] BE: Change `phenodigm` to `impc` in the API.
- [x] FE: Change `PhenoDigm` to `IMPC` in the evidence widget.
- [x] FE: Change `PhenoDigm` to `IMPC` in the facets.
- [x] FE: Change `PhenoDigm` to `IMPC` in the Platform codebase.
- [x] FE: Change source linkout from `https://www.sanger.ac.uk/tool/phenodigm/` to `https://www.mousephenotype.org`

**Comment by ireneisdoomed** [comment]
Phenodigm has already been renamed in the data team's codebase.
@mbdebian PIS should be picking up the evidence from the new location: `gs://otar000-evidence_input/IMPC/json`. The new filename follows the pattern `impc-YYYY-MM-DD.json.gz`

**Comment by mbdebian** [comment]
PIS is not up to date with this. I'll work on it

**Comment by mbdebian** [comment]
I have just updated PIS to reflect this change
