### ISSUE TITLE
Update the Platform's scoring documentation

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2552]
## Background

Several users, either through the Open Targets Community or the helpdesk, have asked us to clarify how the data in the Platform is scored.

The Platform documentation explains how scores are obtained for individual data sources, but does not currently contain enough information for the users to be able to reproduce the data type or overall data scoring, and so needs to be updated. 

## Tasks

Update the documentation. This could include:
- How evidence scores are normalised (e.g. for Europe PMC, resource scores are normalised between 0 and 1)
- How the theoretical maximum is handled at different scoring levels (and why)
- Direct/indirect scoring and exceptions (Expression Atlas)
- (Scoring in the PPP)

**Comment by adamsardar** [comment]
Perhaps related: I was reading your recent paper '_Open Targets Platform: new developments and updates two years on_', which makes frequent mention of the documentation link https://docs.targetvalidation.org/getting-started/scoring. However, it does not lead anywhere! Just a gitbook account that I do not have access too. I'm really keen to understand how the overall score is calculated and to get a feeling for if higher scores are more certain than lower scores. 

Does a better link for the documentation exist?

Thank you for all of your hard work compiling the information available through OpenTargets. You have saved me so much time over the last few years!

**Comment by d0choa** [comment]
@mjfalaguera do you think you could help us with this? The missing things are the bits that you have investigated, like the division by 1.6, etc.
