### ISSUE TITLE
Display `studyStopReasonCategories` in the ChEMBL evidence table

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2553]
As a **user** I want **to see the result of the classification of why a clinical trial has stopped early** to foster further analyses or hypothesis.

## Background

In 22.02 we added `studyStopReasonCategories ` to the ChEMBL evidence to display the assigned categories from analysing the reason why a clinical trial had stopped early (`studyStopReason`). In addition to displaying it in the API, we want to display this information on the ChEMBL evidence table.
 
- This is an example of how a piece of evidence between [PAH/Lesch-Nyhan syndrome/SAPROPTERIN](https://platform.opentargets.org/evidence/ENSG00000171759/Orphanet_510)
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/beb29323-ae01-44c3-a7be-f1be86f6abb3)

- This is the API response for that same piece of evidence:

```json
{
  "data": {
    "disease": {
      "id": "Orphanet_510",
      "evidences": {
        "count": 1,
        "rows": [
          {
            "disease": {
              "id": "Orphanet_510",
              "name": "Lesch-Nyhan syndrome"
            },
            "target": {
              "id": "ENSG00000171759",
              "approvedSymbol": "PAH"
            },
            "drug": {
              "id": "CHEMBL1201774",
              "name": "SAPROPTERIN",
              "drugType": "Small molecule",
              "mechanismsOfAction": {
                "rows": [
                  {
                    "mechanismOfAction": "Phenylalanine-4-hydroxylase activator",
                    "targets": [
                      {
                        "id": "ENSG00000171759",
                        "approvedSymbol": "PAH"
                      }
                    ]
                  }
                ]
              }
            },
            "targetFromSourceId": "P00439",
            "clinicalPhase": 2,
            "clinicalStatus": "Withdrawn",
            "studyStartDate": "2009-04-01",
            "studyStopReason": "Contractual issues",
            "studyStopReasonCategories": [
              "Business or administrative"
            ],
            "urls": [
              {
                "niceName": "ClinicalTrials",
                "url": "https://clinicaltrials.gov/search?id=%22NCT00935753%22"
              }
            ]
          }
        ]
      }
    }
  }
}
``` 

## Tasks

- [ ] Display `studyStopReasonCategories`in the tooltip in the `Status` column of the ChEMBL evidence table using the chip component.

Design:
- **Inside the tooltip in `Status`**, the content of `studyStopReasonCategories` will be displayed in a different line after the text from `studyStopReason`
-  **Each element of the `studyStopReasonCategories` array** will be displayed by using the **"chip" component** that is found in other parts of the Platform like [the IntOGen evidence page](https://platform.opentargets.org/evidence/ENSG00000141510/EFO_1000218):
![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/bdae7cb9-f24e-49a3-9e24-d6ec464adbf1)

- [ ] Add `studyStopReasonCategories ` to the [ChEMBL API response schema](https://github.com/opentargets/platform-app/blob/411bb92198cdccb0ef96b586f9cf1662684f8383/src/sections/evidence/Chembl/ChemblQuery.gql)

## Acceptance tests

How do we know the task is complete? 

1. When I go to [PAH/Lesch-Nyhan syndrome evidence page](https://platform.opentargets.org/evidence/ENSG00000171759/Orphanet_510), I see a chip saying `Business or administrative` when hovering the tooltip on `Withdrawn`. 
2. When I go to [NDUFA10/body weight gain](https://platform.opentargets.org/evidence/ENSG00000130414/EFO_0004566), I see two chips saying `Negative` and `Another study´ when hovering the tooltip on `Terminated`.

**Comment by d0choa** [comment]
Looking great. In some occasions, the chips look too close to the text. @remo87 could you please ensure the chip shows up in a new line. Or any alternative solution that makes the ?

https://main--platform-app.netlify.app/evidence/ENSG00000134460/EFO_0000729
 
![Screenshot 2022-04-19 at 14.59.52.png](https://images.zenhubusercontent.com/5ce3b95baba90a6b4d8b6ff8/4834ea34-c56a-4379-a7d1-6b90e2e76469)

**Comment by remo87** [comment]
Irene pointed out that the Tooltip spacing doesn't look quite right with the new items I agree with that observation here are two images that show the tooltip as it is now and with some spacing in the borders and between the text and the chips 
![tooltip1](https://user-images.githubusercontent.com/15823008/164244896-4785458f-a521-42f7-b17e-63fcebc1b63d.png)
![Tooltip2](https://user-images.githubusercontent.com/15823008/164244901-6e7beae7-0419-4c07-b29d-e2cfae577a75.png)

**Comment by d0choa** [comment]
Same here

**Comment by remo87** [comment]
ok!

**Comment by remo87** [comment]
just checked in and push the changes
