### ISSUE TITLE
Write blogpost with an analysis of the gene burden associations

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2554]
## Context
In 22.04, we will be integrating evidence of association from the application of burden analyses on 450k UK Biobank Exome sequences. For the time being, `gene_burden` will pool the results of the analyses available through REGENERON and in the AZ PheWAS Portal with the idea that the list of integrated sources and cohorts will continue growing.

We want to publish in a blogpost an analysis that gives an example and showcases the possibilities of what can be done with this new data source and how it integrates with the other Open Targets sources.

## Summary
@d0choa and I have drafted what can be an interesting structure and scope for the analysis. We want to do something that is useful for the community but at the same time, we don't want to end up in rabbit holes.

1. Introduction
	1. UK Biobank
	2. Exome sequencing analysis
		1. AZ
		2. REGENERON
	2. The analysis itself. 
	3. Data availability through GWASCat
	4. Comparative analysis between both burden analyses. Brief sentence showing why this is useful.
	5. What is the novelty. Brief sentence showing what are the data possibilities.

2. Comparative analysis between both results
	1. General statistics (table).
		1. Nº assocs binary/quant, genes, binary/quant phenotypes, overlaps.
	2. Model comparison.
	3. Ancestry specificity.

3. Where is the novelty?
	1. Overlap of assocs with OTP excluding literature.
		1. Breakdown per data source in REGENERON and AZ
		Figure: 2x2 horizontal bar plots (X-axis: % overlap; Y-axis: sources) broken down by trait type.
	2. PheWAS plot with p values of AZ and REGENERON (probably not very informative).
	3. PheWAS plot with all data sources. (X-axis: traits ordered by TA; Y-axis:-log2 assoc score)

---
I'll be working on the post on this document, any comments are welcome: https://docs.google.com/document/d/1bIj8FIGPPFcenQRSAQWX4QuLXdhDXeCJKQUlS5jEsoA/edit?usp=sharing

@HelenaCornu In terms of timing, I expect to have it ready at the latest in the week following the announcement of the release.

**Comment by ireneisdoomed** [comment]
Preview link with the draft: https://blog.opentargets.org/p/ed1aea58-2a36-4939-9a8f-1c48c9fb20b2/

**Comment by d0choa** [comment]
@HelenaCornu and @ireneisdoomed we need to make a decision here

**Comment by ireneisdoomed** [comment]
Done
