### ISSUE TITLE
22.04 attempt picking old phenodigm data

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2558]
The current attempt is picking up the old phenodigm data:

`gs://open-targets-pre-data-releases/22.04/output/etl/parquet/evidence/`

Because we have renamed the ETL to use the new `impc` name, the configuration is not being applied and things look ugly. (e.g. scores not divided by 100, therefore being in the 0-1 range).

All this will be fixed the moment PIS/ETL picks the latest IMPC data

**Comment by mbdebian** [comment]
@d0choa , let me have a look at this, as PIS is already collecting this information, and I recall that our latest ETL round run on an evidence dataset that included impc.

**Comment by mbdebian** [comment]
We have now released 22.04 which includes the refactored _impc_ dataset.
