### ISSUE TITLE
Incorrect formatting of some PMCIDs in EPMC's submission

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2562]
**Describe the bug**
Some PMC references in the EPMC data are not formatted properly.

**Observed behaviour**
The data team has generated evidence from grounded co occurrences based on `22.01`EPMC submission.
Of the 9 746 463 evidence strings, 2 of them have failed validation due to the `pmcIds` field.

An example: `'pmcIds': ['PMCPMC7610745']`. The duplication of `PMC` is causing the error in both cases.

**Expected behaviour**
No validation error should be returned. We want to have the right prefix for the PMCIDs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the 21.04 branch of the evidence data source parsers (https://github.com/opentargets/evidence_datasource_parsers/tree/il-22.04/modules)
2. Follow the instructions to reproduce the environment
3. Run the EPMC evidence generation rule like `snakemake epmc --cores all`

**Additional context**
Although the impact of the error is minimal, this causes our evidence generation pipeline to fail because we do not allow any validation error to occur.
We have decided that we do not want to write specific logic to address this in the code, we rather expect this fix to come from the data.

**Comment by ireneisdoomed** [comment]
@saha-shyamasree I haven't checked how frequent this is on the whole co occurrences/matches sets. Could you please investigate?

**Comment by saha-shyamasree** [comment]
@DSuveges @ireneisdoomed: I just checked the data. It's coming from the original XML provided by the PMC. 
As I mentioned during the monthly meeting, the XML file formats have changed while implementing the incremental approach. I can confirm that the new file does not have this issue. So I will request to get back to this example when I submit the new data and check/confirm you are getting these anymore.
