### ISSUE TITLE
Error when downloading Genetics files through the FTP

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2564]
Users trying to download files through the Genetics FTP are getting errors, either saying the files are not readable or writable, or being unable to access the server. 

We have recommended a temporary fix of trying “lftp” as the client in the terminal, but it seems that there have been several issues with the FTP in the past few months, so this merits further investigation.

**Comment by mbdebian** [comment]
@HelenaCornu and @d0choa , I'm working on this at the same time I'm working on opentargets/issues#1516, as they are intimately related

**Comment by mbdebian** [comment]
I've corrected all file permissions across all our FTP file tree, but I'm still having problems with some FTP clients when accessing our data.
I'm investigating this issue deeper, with the help of IT

**Comment by mbdebian** [comment]
After liaising with TSC on finding out what could be the problem, these are the resulting recommendations:
- **lftp** is the way to go for command line client
- When using tools like _wget_, _curl_, etc., _https://_ should be use, instead of _ftp://_

Cheers,
Manuel
