### ISSUE TITLE
Main branch of platform-app crashes due to impc renaming

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2566]
Example page:
https://main--platform-app.netlify.app/evidence/ENSG00000001626/Orphanet_586

Console error:

> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'Object(Q.a)($i.fragments.PhenodigmSummaryFragment).data.impc.count')

**Comment by carcruz** [comment]
Main branch working now after merge of https://github.com/opentargets/platform-app/pull/539
