### ISSUE TITLE
Metrics for 22.04 release

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2567]
Some questions I have for the release blog post:

### General metrics

- How many targets are associated with at least one disease?
- How many diseases are associated with at least one target?

### Gene burden widget

- Has this added new associations? (And is it possible/does it make sense to separate these for Regeneron/AZ?)
- How many associations/evidence strings did this contribute? (I see 18,715 as evidence count for gene burden, do some associations have multiple evidence strings? The AZ paper found 1,703 significant gene-phenotype associations, and the Regeneron paper found 564 genes with significant trait associations. Do we import all of these? How do we get 18,715 evidence strings?)
- Are there any interesting examples? For example based on the paper it looks like MAP3K15 is a new association?
- Anything I’m missing?

### ChEMBL30 and drug label mining

- Are there metrics to report here?
- Any interesting examples e.g. new or strengthened associations?

### Miscellaneous

- Are there more associations from Behan et al or did I get that wrong? 1,828 in 22.02; 1,846 in 22.04?

**Comment by HelenaCornu** [comment]
Additional question: 

### Clinical trials stop reason

- I have 28,833 as the number of classified clinical trials. Is that correct?

**Comment by ireneisdoomed** [comment]
**Stop reasons**
- 55 308 evidence with this information 
(`evd.filter(F.col('datasourceId') == 'chembl').filter(F.col('studyStopReasonCategories').isNotNull()).count()`)
- ... Which is the result of classifying 8 044 different clinical trials 
(`evd.filter(F.col('datasourceId') == 'chembl').filter(F.col('studyStopReasonCategories').isNotNull()).withColumn('url', F.explode('urls')).filter(F.col('url.niceName') == 'ClinicalTrials').select('url.url').distinct().count()`)

I think we didn't feature this in the last blog post. You can extract the previous notes from the 22.02 planning ticket #1889

**Comment by ireneisdoomed** [comment]
**ChEMBL30 and drug label mining**
1. In the ChEMBL30 release more than 90k different references are integrated to establish 594 375 evidence (33 813 more than in the last release). Out of that 90k, almost 76k are references of Clinical Trials and 10k of DailyMed.

DailyMed references are particularly important in this release because we've seen a significant increase of them thanks to the automatic extraction by NLP means, as part of Tim's project.
This is the coverage of evidence per data source in 22.04:
```
evd.filter(F.col('datasourceId') == 'chembl').withColumn('url', F.explode('urls')).groupBy('url.niceName').count().show()
+--------------+------+
|      niceName| count|
+--------------+------+
|           ATC|  4482|
|      DailyMed| 83639|
|           FDA| 21532|
|ClinicalTrials|484722|
+--------------+------+
```

VS the coverage in 22.02:
```
+--------------+------+
|      niceName| count|
+--------------+------+
|           ATC|  4431|
|      DailyMed| 63672|
|           FDA| 21483|
|ClinicalTrials|470976|
+--------------+------+
```
