### ISSUE TITLE
EPMC text corrupted with references

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2570]
### Describe the bug
The text provided in EPMC's January submission pipeline is inserting information about the references as reported text, therefore causing the text to no longer correspond to the original manuscript.
This "enrichment" of the analysed text is causing an explosion in the number of evidence, potentially leading to relationships between targets and diseases that are artificial.

### Observed behaviour
EPMC's Sentencizer has been improved lately to shorten the length of the analysed texts.
However, a bug has been introduced that was not there in the previous submission (December 2021): **reference metadata and titles are being inserted as part of the reported text, causing the text to no longer correspond to the original manuscript.**

An example is the [PMID 11448986](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2196855/). This is the reported text as in **the January 2022 submission**, which will feed 22.04 evidence:

```
Limb-girdle muscular dystrophy type 2G is caused by mutations in the gene encoding the sarcomeric protein telethonin., Myotilin is mutated in limb girdle muscular dystrophy 1A., Telethonin/T-CAP has taken on added importance due to its causal role in limb-girdle muscular dystrophy type 2G (Moreira et al., 2000)., Myotilin, a novel sarcomeric protein with two Ig-like domains, is encoded by a candidate gene for two limb-girdle muscular dystrophy.
```

And this is the reported text as in **the September 2021 submission**, which is feeding 22.02 evidence:
```
Telethonin/T-CAP has taken on added importance due to its causal role in limb-girdle muscular dystrophy type 2G (Moreira et al., 2000).
```

The Jan 2022 piece of text, analysed as a whole in the pipeline consists of chunks of text from different parts:
1. _"Limb-girdle muscular dystrophy type 2G  ... in limb girdle muscular dystrophy 1A.,"_
-> In the article, this is the title of the Moreira et al reference:
![image](https://user-images.githubusercontent.com/45119610/165363590-d7def493-5143-4d16-a066-1e03378125c8.png)

2. _"Telethonin/T-CAP has taken ... dystrophy type 2G (Moreira et al., 2000)."_3. 
-> In the article, this is the valid sentence that is analysed from the text:
![image](https://user-images.githubusercontent.com/45119610/165363938-f47c945c-593c-4458-a6ad-5a23bc3466db.png)

3. _"Myotilin, a novel sarcomeric protein ... two limb-girdle muscular dystrophy"_4. 
-> In the article, this is the title of the Salmikangas et al reference:
![image](https://user-images.githubusercontent.com/45119610/165364355-e31d0954-28a2-4175-8553-2ae7392c18fd.png)

### Expected behaviour
We shouldn't be inserting any parts of the text. This "enrichment" of the analysed text is causing an explosion in the number of evidence, potentially leading to relationships between targets and diseases that are artificial.

@saha-shyamasree We need to investigate whether these Frankensteinian sentences are the result of the newer sentencizer algorithm or whether the problem comes from the source XML files.

### Additional context
I've compared the February 2022 cooccurrences dataset (gs://open-targets-pre-data-releases/22.02.4/output/literature/parquet/cooccurrences) with the one that is going to be used in the April 2022 release (gs://open-targets-pre-data-releases/22.04/output/literature/parquet/cooccurrences).

**Comment by saha-shyamasree** [comment]
Example 1 and 3 will bot be there any more. For 2, lets have a chat. I didn’t insert any reference text, simply didn’t remove them.

**Comment by ireneisdoomed** [comment]
@saha-shyamasree Great. Parts 1 and 3 are the problematic ones. Part 2 is fine as it sticks to the original text, but we can discuss about it.

**Comment by DSuveges** [comment]
It seems the current dataset looks good:
```python
(
    spark.read.parquet('gs://open-targets-data-releases/23.02/output/etl/parquet/evidence/sourceId=europepmc/')
    # Filtering for the relevant publication:
    .filter(f.array_contains(f.col('literature'), '11448986'))
    # Exploding textmining sentences:
    .select(
        'diseaseId', 'targetId',
        f.explode(f.col("textMiningSentences")).alias('textMiningSentence')
    )
    # Explode struct:
    .select('diseaseId', 'targetId', 'textMiningSentence.*')
    .show(2, vertical=True, truncate=False)
)
```

gives:
```text
-RECORD 0--------------------------------------------------------------------------------------------------------------------------------------------
 diseaseId | MONDO_0011170                                                                                                                           
 targetId  | ENSG00000173991                                                                                                                         
 dEnd      | 111                                                                                                                                     
 dStart    | 73                                                                                                                                      
 section   | other                                                                                                                                   
 tEnd      | 10                                                                                                                                      
 tStart    | 0                                                                                                                                       
 text      | Telethonin/T-CAP has taken on added importance due to its causal role in limb-girdle muscular dystrophy type 2G (Moreira et al., 2000). 
-RECORD 1--------------------------------------------------------------------------------------------------------------------------------------------
 diseaseId | MONDO_0011170                                                                                                                           
 targetId  | ENSG00000173991                                                                                                                         
 dEnd      | 111                                                                                                                                     
 dStart    | 73                                                                                                                                      
 section   | other                                                                                                                                   
 tEnd      | 16                                                                                                                                      
 tStart    | 11                                                                                                                                      
 text      | Telethonin/T-CAP has taken on added importance due to its causal role in limb-girdle muscular dystrophy type 2G (Moreira et al., 2000).
```

There's a seemingly duplicated cooccurrence, due to both Telethonin and T-CAP are grounded to the same entity: [TCAP](https://platform.opentargets.org/target/ENSG00000173991).

Therefore I'm closing this ticket.
