### ISSUE TITLE
PIS output folder is inconsistent

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2577]
**Describe the bug**
Running PIS using the `-output` parameter behaves differently than using `-o`.

**Observed behaviour**
I use PIS to fetch the most up to date evidence files from the buckets and save them to a folder named `output` like so:

```
python platform-input-support.py -gkey ../key.json -steps evidence -output output
```

**Instead data are stored in a folder called `utput`.**

This doesn't happen when you use `-o` like so:
```
python platform-input-support.py -gkey ../key.json -steps evidence -o output
```

**Expected behaviour**
I expect to store the output data in a directory with the name that is specified with either the `-o` or `-output` flags.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://github.com/opentargets/platform-input-support
2. Create the conda env
3. Run evidence step with the command pasted above

**Additional context**
This step is used by the data team to generate pre pipeline metrics.

**Comment by JarrodBaker** [comment]
Thanks for raising this @ireneisdoomed and for the detailed ticket. I'll have to look at the code, but I'm fairly sure that we are using a library for command line parsing. The bug you describe (getting confused when the input to the `-output` flag is also `output`) might be an issue with the library itself. 

We'll look into it!

**Comment by mbdebian** [comment]
I have corrected the documentation to point out that the two ways of specifying an output folder are
```
-o <output_folder>
--output <output_folder>
```
As the library used for parsing the commando line arguments, when specifying _-output folder_name_ it interprets the parameter to be '-o' and the folder name 'utput', ignoring 'folder_name'.
