### ISSUE TITLE
Genetics portal should support chrX variants

### ISSUE THREAD

**Issue by Jeremy37** [opentargets/issues#2579]
As a user I want to see associations for variants on the X chromosome.

## Background

Luca and Gosia were investigating a variant (https://genetics.opentargets.org/variant/X_12900169_G_A) which is associated with SLE in a GWAS (https://www.ebi.ac.uk/gwas/studies/GCST011956) that doesn't include sumstats.

The variant is present in OT genetics, but no lead or tag variants are shown.

The code for fine-mapping currently has a note saying that it fails for chrX/Y:
https://github.com/opentargets/genetics-finemapping#notes

The same problem would be present for coloc, which relies on getting independent sumstats using GCTA-cojo in the same way as for fine-mapping.

**Comment by buniello** [comment]
Feature added to the partners feedback doc
