### ISSUE TITLE
Associated studies table appears empty when filtering for a trait with few results

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2580]
**Describe the bug**
When looking at a gene page in Open Targets Genetics, the associated studies table appears empty when looking at late results and filtering for a trait with few results. 

It should be displaying the filtered result. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://genetics.opentargets.org/gene/ENSG00000105246'
2. In the Associated Studies: Locus-to-Gene pipeline table, click on the right arrow to move the result table to a late result, say result 40
3. Filter to a trait with few results, for example "age at menopause"
4. See error: the table is empty as it sticks to a late result page even though there is only one filtered result. Counter shows "31-1 of 1"

<img width="1267" alt="Screenshot 2022-05-03 at 10 50 47" src="https://user-images.githubusercontent.com/73692302/166434208-bf99d8e9-ee9c-46bd-94cb-ab0a07b51a72.png">

**Comment by DSuveges** [comment]
On the table in your example the user is on the 3rd page (result showing 31-1), however there's not enough data to fill three pages. So the use sees nothing. I think the expected behaviour here could be resetting the page counter to 0 any time a new filter is set.

**Comment by d0choa** [comment]
This will be addressed with the improvements in the table component. Keep this in mind @carcruz
