### ISSUE TITLE
Can't download TSV or JSON files for certain disease association pages

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2586]
**Describe the bug**
For certain disease association tables, such as [autoimmune disorder of the cardiovascular system](https://platform.opentargets.org/disease/MONDO_0000603/associations), I am unable to download the TSV and JSON files. 

**Observed behaviour**
When I click on the JSON or TSV buttons, it says "preparing data..." but the file doesn't download. However, this is not a generalised issue since I am able to download other associations tables. 

**Expected behaviour**
The file should download. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[...](https://platform.opentargets.org/disease/MONDO_0000603/associations)'
2. Click on 'JSON' or 'TSV', at the top right hand corner of the associations table
3. Wait indefinitely 

**Additional context**
I am having the same issue with other MONDO terms — [autoimmune disorder of the GI tract](https://platform.opentargets.org/disease/MONDO_0000588/associations) and [autoimmune disorder of the endocrine system](https://platform.opentargets.org/disease/MONDO_0000569/associations), and it’s not a file size thing because [inflammatory bowel disease](https://platform.opentargets.org/disease/EFO_0003767/associations) (5,000+ targets) is working just fine.

**Comment by DSuveges** [comment]
Oh, I noticed too late that there's already a ticket for this bug. Same as #2587
