### ISSUE TITLE
Primary color not used on scroll-up in PPP

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2589]
When scrolling up in PPP primary colour is not shown. Instead, the blue shows up

![Screenshot 2022-05-12 at 16 28 21](https://user-images.githubusercontent.com/5097586/168113625-bd6fa3db-8687-4035-a290-e385b7eb1a71.png)

**Comment by LucaFumis** [comment]
I can't replicate the issues (ironically, my old version of Safari is not affected by this). 
@d0choa have a look at this example (not PPP) - does the scroll background look blue or white?
https://deploy-preview-21--ot-platform.netlify.app/

**Comment by d0choa** [comment]
Looks white in Safari, as opposed to the blue in production.
In Chrome looks white, the same as the production version

**Comment by d0choa** [comment]
Feel free to close the ticket once resolved.

I think this is the way to set it up, but it's not really consistent across browsers:
https://www.tempertemper.net/blog/scroll-bounce-page-background-colour
