### ISSUE TITLE
Incorrect EFO disease id formatting

### ISSUE THREAD

**Issue by zdorman** [opentargets/issues#2590]
**Describe the bug**
40 diseases in 22.04 disease dataset have an `id` prefix of `//www.ebi.ac.uk/EFO/EFO_` instead of `EFO_`. This makes them inaccessible on the Platform. 

**Observed behaviour**
The following 40 disease ids do not fit the standard diseaseId format. This causes 404 errors on the platform when trying to access the disease pages. 
  '//www.ebi.ac.uk/EFO/EFO_0020866',
   '//www.ebi.ac.uk/EFO/EFO_0020859',
   '//www.ebi.ac.uk/EFO/EFO_0020868',
   '//www.ebi.ac.uk/EFO/EFO_0020857',
   '//www.ebi.ac.uk/EFO/EFO_0020904',
   '//www.ebi.ac.uk/EFO/EFO_0020877',
   '//www.ebi.ac.uk/EFO/EFO_0020893',
   '//www.ebi.ac.uk/EFO/EFO_0020907',
   '//www.ebi.ac.uk/EFO/EFO_0020888',
   '//www.ebi.ac.uk/EFO/EFO_0020891',
   '//www.ebi.ac.uk/EFO/EFO_0020901',
   '//www.ebi.ac.uk/EFO/EFO_0020892',
   '//www.ebi.ac.uk/EFO/EFO_0020890',
   '//www.ebi.ac.uk/EFO/EFO_0020896',
   '//www.ebi.ac.uk/EFO/EFO_0020879',
   '//www.ebi.ac.uk/EFO/EFO_0020887',
   '//www.ebi.ac.uk/EFO/EFO_0020908',
   '//www.ebi.ac.uk/EFO/EFO_0020869',
   '//www.ebi.ac.uk/EFO/EFO_0020883',
   '//www.ebi.ac.uk/EFO/EFO_0020885',
   '//www.ebi.ac.uk/EFO/EFO_0020903',
   '//www.ebi.ac.uk/EFO/EFO_0020881',
   '//www.ebi.ac.uk/EFO/EFO_0020872',
   '//www.ebi.ac.uk/EFO/EFO_0020884',
   '//www.ebi.ac.uk/EFO/EFO_0020905',
   '//www.ebi.ac.uk/EFO/EFO_0020886',
   '//www.ebi.ac.uk/EFO/EFO_0020882',
   '//www.ebi.ac.uk/EFO/EFO_0020894',
   '//www.ebi.ac.uk/EFO/EFO_0020875',
   '//www.ebi.ac.uk/EFO/EFO_0020906',
   '//www.ebi.ac.uk/EFO/EFO_0020873',
   '//www.ebi.ac.uk/EFO/EFO_0020880',
   '//www.ebi.ac.uk/EFO/EFO_0020871',
   '//www.ebi.ac.uk/EFO/EFO_0020878',
   '//www.ebi.ac.uk/EFO/EFO_0020895',
   '//www.ebi.ac.uk/EFO/EFO_0020876',
   '//www.ebi.ac.uk/EFO/EFO_0020889',
   '//www.ebi.ac.uk/EFO/EFO_0020874',
   '//www.ebi.ac.uk/EFO/EFO_0020867',
   '//www.ebi.ac.uk/EFO/EFO_0020870'

**Expected behaviour**
I would expect these ids to drop the `//www.ebi.ac.uk/EFO/` from the beginning. This would match existing diseaseId formats. 

**To Reproduce**
Steps to reproduce the behaviour, using the first listed id as an example (EFO_0020866):
1. Searching EFO_0020866 on the platform shows no results (404 error)
2. Searching the disease name of EFO_0020866: high density lipoprotein particle size change measurement returns results matching results. Clicking on any of the links returns a 404 error
3. Manually entering a url of: https://platform.opentargets.org/disease///www.ebi.ac.uk/EFO/EFO_0020866/associations or the expected https://platform.opentargets.org/disease/EFO_0020866/associations both return 404 errors. 

**Additional context**
Note that this seems to be separate from an issue in the 22.02 disease dataset, in which 62 disease had a different incorrect prefix of `//ebi.ac.uk/efo/EFO` (though I expect it is also due to a formatting error in EFO). 

Thank you for looking into this!

**Comment by d0choa** [comment]
Caused by https://github.com/EBISPOT/efo/issues/1522 (which seems to be resolved). The fix will cascade to the 22.06 Platform release.

Thanks, @zdorman for reporting. We will keep an eye to make sure the changes cascade. We will also try to double-check there are no additional problems with URIs in the next release, because as you said there have been problems in the next couple of releases.
