### ISSUE TITLE
Requested Changes for PPP Front End

### ISSUE THREAD

**Issue by emcdonagh-OT** [opentargets/issues#2597]
Please note, this list is a work in progress...

**OT VL**
- [x] OTVL: Change ‘Hit’ to ‘OTVL Hit’. Add hover over (tool tip) here that says “Binary assessment of gene perturbation effect in contrast”
- [x] OTVL: Add hover over for the primary project “Binary assessment of gene perturbation effect in primary project screen”
- [x] OTVL: Biomarker glossary: change colours - see mock up, and order alphabetically (but with PAN-CO being listed last)
- [x] ‘?’ hover over explanation for each biomarker - there will be a new biomarker and so Panos or Stuart will provide wording for this. 
- [x] Hover over explanation for the "OTVL biomarker assessment for x" - wording provided by Panos or Stuart. 
- [x] Display additional column for the data version

**Data tables**
- [x] Display additional column for the data version (this should now be within the data model)

**Association pages**
- [x] Association pages - can we add a lock icon in the column headings ‘OTAR projects’ and ‘OTAR validation lab’ to make it even clearer that this is the non-public data? 
- [x] Association pages - need to add evidence-specific filter for ‘OTAR Validation Lab’ 
- [ ] When sorting by OTAR Validation Lab data hits, show tested but not validated before not tested _(Backend issue)_. 

**Homepage**
- [x] Homepage search box: can we edit the example list to provide diseases/genes/drugs that are of particular interest for the PPP? (list to be provided seperately)
- [x] Homepage: please add to the wording on the homepage for the PPP - see Google doc link. 
- [ ] browser tab: is it possible to have a lock icon or chnagethe blue icon to green to distinguish between the public and preview version when browsing and going in between the two? (non-urgent) 
- [x] Use the 'Beta' icon - see from Helena

**ENCORE**

- [x] Enable sorting by Target B...is this possible?
- [ ] Display additional column for the data version
- [ ] Display warning icon with tooltip message

**Comment by LucaFumis** [comment]
> Association pages - need to add evidence-specific filter for ‘OTAR Validation Lab’
The filter _should_ be there: I also noticed this morning they were missing (CCNB1 associations), however  they were there after reloading the page. Unfortunately I didn't get to see the API response when it failed. I'll keep an eye on it...

**Comment by emcdonagh-OT** [comment]
Hello Luca - I see these now on the UI.

**Comment by LucaFumis** [comment]
Quick questions on the last two points of the OT VL widget:

>  ‘?’ hover over explanation for each biomarker - there will be a new biomarker and so Panos or Stuart will provide wording for this.
currently the API response serves also a description for each biomarker, shown in a tooltip - so it seems that this will essentially just be addressed in the data

> Hover over explanation for the "OTVL biomarker assessment for x" - wording provided by Panos or Stuart.
As I understand the text is being reviewed - will add in when finalized (or could add what we have now and update later when ready)

**Comment by LucaFumis** [comment]
I understand, chatting to @buniello, that the ENCORE "Display warning icon with tooltip message" might no longer be required? Is that correct @buniello and @d0choa ?

**Comment by buniello** [comment]
@LucaFumis I have checked also with @DSuveges and Ellie and I confirm that the warning for the ENCORE data is no longer needed
