### ISSUE TITLE
Updates for evidence fields for PPP

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2598]
From the previous release there are some updates on the evidence object:

**New fields**:
 - `releaseVersion`: string, nullable, should be populated for each PPP evidence based on @sarahyoung3 's table.
- `releaseDate`: string, nullable, filled based on the same source.
- `warningMessage`: string, nullable, text description to notify users about concerning data. Coming from providers.

**Removed field:**
- `geneticInteractionMethod`: this field got removed as the same information is captured by the `statisticalMethod` field.

**Comment by remo87** [comment]
Do we have a desired description of the fields? @DSuveges @JarrodBaker

**Comment by mbdebian** [comment]
A PR related to this has now been approved and merged.
