### ISSUE TITLE
Service account for Europe PMC for automated data submission (upload) to the Google bucket.

### ISSUE THREAD

**Issue by saha-shyamasree** [opentargets/issues#2603]
As a **[user|developer|etc]** I want **<describe feature>** because **<reason>**

## Background

Provide any necessary background information to provide context on the issue. 

## Tasks

- [] Update ...
- [] Configure ...

## Acceptance tests

How do we know the task is complete? 

1. When I go to page XX I see YY. 
2. When I click on 'foo' I see pop-up 'bar'

**Comment by d0choa** [comment]
The intention here is to have a service account for ePMC to be able to upload data to the OT GCP bucket `gs://otar025-epmc/`

Historically, we added individual members of the ePMC team, but now they built an automatic process that uploads the data directly to GCP. Having a service acount will make more sense from now on

**Comment by mbdebian** [comment]
Done, please, try out the account, as it has fined tuned ACLs for the aforementioned bucket.
