### ISSUE TITLE
Add more sources to gene_burden 

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2604]
We want to study the inclusion of more resources that report relevant burden analyses results.

## Context
The gene_burden source currently collates the results of 2 analyses: REGENERON and AZ PheWAS Portal. However, more research is being published on the topic.

Although we do not intend to collect all results that are being published, the idea is to identify key resources or research that:
a) are findings of high quality
b) the integration and maintenance can be done automatically and nearly painless (no changes to the schema, no excessive parsing,...)

This way Open Targets could become a go-to resource for the most relevant collapsing studies and perhaps make the case for the creation of a new catalogue.

## Actions
Interesting ExWAS results to investigate
1. Association of 10 genes with schizophrenia. https://www.nature.com/articles/s41586-022-04556-w.pdf
    - Data is available in a nice format at the Schizophrenia Exome Sequencing Meta-analysis (SCHEMA) consortium website: https://schema.broadinstitute.org
    - There are 3 similar initiatives from which we could also pull data from:
        - Autism Sequencing Consortium (ASC): https://asc.broadinstitute.org
        - The Epilepsy collaboration: https://epi25.broadinstitute.org
        - The bipolar exome sequencing project (BipEx): https://bipex.broadinstitute.org
2. 4 novel associations with CKD. https://jasn.asnjournals.org/content/30/6/1109
3. OTAR project with associations between 27 genes and 38 metabolites. https://www.cell.com/ajhg/fulltext/S0002-9297(22)00157-4?s=09#sectitle0025
    - Measurement of metabolites have already been added to EFO (https://github.com/EBISPOT/efo/issues/1257)
4. Burden results on metabolites using Nightingale's NMR on the INTERVAL cohort https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008605

**Comment by ireneisdoomed** [comment]
Some notes and questions on the new data:

### Schizophrenia Consortium
Manuscript: https://www.nature.com/articles/s41586-022-04556-w.pdf

- Whole exomes of 24,248 schizophrenia cases and 97,322 controls
- 7 continental populations
- 10 gene associations that implicate ultra rare coding variants (MAC ≤ 5 - MAF ≤ 0,005% given a sample size of 121,570)
	- Class 1 variants: PTVs and missense variants with a MPC pathogenicity score > 3
	- Class 2 variants: missense variants with a MPC between 2 and 3
- Burden tests were performed:
	- separately for Class I and Class II variants
	- together using Stouffer's weighted Z-score method
- Significance threshold set at P < 2.14 × 10−6
- The Q-value is the P-value adjusted for the False Discovery Rate.
- Last updated: Sept. 2020

#### Questions
- Do we want to report the Q number?
- What should we do with the ancestries?
- Cohort is the aggregation of 11 collections of schizophrenia patients. 

Data:

```
 # Sample row
 gene_id                   | ENSG00000006283
 group                     | meta
 Case PTV                  | 10
 Ctrl PTV                  | 13
 Case mis3                 | 8
 Ctrl mis3                 | 4
 Case mis2                 | 55
 Ctrl mis2                 | 134
 P ca/co (Class 1)         | 3.1600e-06
 P ca/co (Class 2)         | 3.1700e-02
 P ca/co (comb)            | 4.5700e-07
 De novo PTV               | NA
 De novo mis3              | NA
 De novo mis2              | 1
 P de novo                 | 2.7900e-01
 P meta                    | 4.5700e-07
 Q meta                    | 1.5400e-03
 OR (PTV)                  | 3.0900e+00
 OR (Class I)              | 4.2500e+00
 OR (Class II)             | 1.6800e+00
 OR (PTV) lower bound      | 1.2100e+00
 OR (PTV) upper bound      | 7.6300e+00
 OR (Class I) lower bound  | 2.0700e+00
 OR (Class I) upper bound  | 8.7800e+00
 OR (Class II) lower bound | 1.2100e+00
 OR (Class II) upper bound | 2.3100e+00

# Translated to the schema

{
    "datasourceId": "gene_burden",
    "datatypeId": "genetic_association",
    "diseaseFromSourceMappedId": "MONDO_0005090",
    "pValueMantissa": 4.57,
    "pValueExponent": -7,
    "oddsRatio": ?,
    "oddsRatioConfidenceIntervalLower": ?,
    "oddsRatioConfidenceIntervalUpper": ?,
    "resourceScore": 4.57e-7,
    "ancestry": ?,
    "ancestryId": ?,
    "literature": [
        "35396579"
    ],
    "projectId": "SCHEMA consortium",
    "cohortId": null,
    "studyId": null,
    "studySampleSize": 121570,
    "studyCases": 24248,
    "studyCasesWithQualifyingVariants": 73,
    "statisticalMethod": ?,
    "statisticalMethodOverview": "Burden test carried out with PTV and missense variants with a MAF smaller than 0.005%."
}
 ```

### Autism Sequencing Consortium data
Manuscript: https://www.biorxiv.org/content/10.1101/484113v3

- De novo variants called in family-based data consisting of 6,430 probands with ASD and 2,179 unaffected siblings as well as rare variants called in 5,556 ASD cases and 8,809 ancestry-matched controls
- Collapsing method is by using TADA, a Bayesian model
- Last updated: ?

#### Questions
The data looks quite different. No OR, no P value... How should we go around it?
```json
{
  "gene_id": "ENSG00000000938",
  "group": "All",
  "xcase_dn_ptv": 0, <--- cases with de novo PTVs
  "xcont_dn_ptv": 0,
  "xcase_dn_misb": 0, <--- cases with de novo missense variants with MPC between 1 and 2
  "xcont_dn_misb": 0,
  "xcase_dn_misa": 0, <--- cases with de novo missense variants with MPC > 2
  "xcont_dn_misa": 0,
  "xcase_dbs_ptv": 0, <--- cases with PTVs in the iPSYCH cohort
  "xcont_dbs_ptv": 0,
  "xcase_swe_ptv": 0, <--- cases with PTVs in the Swedish cohort
  "xcont_swe_ptv": 0, 
  "xcase_tut": 0, <--- Protein-truncating variants transmitted to probands
  "xcont_tut": 2, <--- Protein-truncating variants not transmitted to probands
  "qval": 0.91586
}
```

### 4.2. Bipolar Exome sequencing project

Manuscript: https://www.medrxiv.org/content/10.1101/2021.03.09.21252930v2 - still a preprint

- Exome sequencing of 14,210 bipolar cases with different subtypes and 14,422 controls
- Qualifying variants are 2 types of ultra rare coding variants: PTVs and damaging missense variants (MAC ≤ 5 - MAF < 0,015% given a sample size of 28,632)
	- They are also only interested in variants not observed in a large control repository (gnomAD non-neuro).
- Collapsing method is by using Fisher's test in each gene to test for case-control enrichment
- **No test hits the GWAS significance threshold** (P < 2.14 × 10−6)
- They also perform a metaanalysis with the Bipolar and the Schizophrenia cohorts, given their strong overlap in common variation, revealing one exome-wide significant gene, AKAP11 (P = 2.83 × 10-9), and one suggestive gene, ATP9A (P = 5.36 × 10-6).
- Last updated: ?

#### Questions
- Since the data in the portal won't show any significant results, we should be using the meta analysis from the preprint. Do we want to do that?

```json
{
  "gene_id": "ENSG00000000003",
  "group": "Bipolar Disorder without Psychosis",
  "n_cases": 3812,
  "n_controls": 14422,
  "damaging_missense_case_count": 0,
  "damaging_missense_control_count": 1,
  "damaging_missense_fisher_gnom_non_psych_pval": 1,
  "damaging_missense_fisher_gnom_non_psych_OR": 0,
  "damaging_missense_fisher_gnom_non_psych_case_count": 0,
  "damaging_missense_fisher_gnom_non_psych_case_no_count": 3812,
  "damaging_missense_fisher_gnom_non_psych_control_count": 0,
  "damaging_missense_fisher_gnom_non_psych_control_no_count": 14422,
  "ptv_case_count": null,
  "ptv_control_count": null,
  "ptv_fisher_gnom_non_psych_pval": null,
  "ptv_fisher_gnom_non_psych_OR": null,
  "ptv_fisher_gnom_non_psych_case_count": null,
  "ptv_fisher_gnom_non_psych_case_no_count": null,
  "ptv_fisher_gnom_non_psych_control_count": null,
  "ptv_fisher_gnom_non_psych_control_no_count": null
}
```


### Epilepsy collaboration
Aimed at characterizing the contribution of rare genetic variation to a spectrum of epilepsy syndromes to identify individual risk genes.
Manuscript: https://www.cell.com/ajhg/fulltext/S0002-9297(19)30207-1

- Gene burden results of 9,170 cases and 8,364 controls broken down by three primary epilepsy types:
	- developmental and epileptic encephalopathy (DEE, N=1,021)
	- genetic generalized epilepsy (GGE, N=3,108)
	- non-acquired focal epilepsy (NAFE, N=3,597)
- Qualifying variants are 3 types of ultra-rare deleterious variants: PTVs, missense variants with MPC≥2, and inframe indels not present in the DiscovEHR database.
- Results show 2 genes trespassing the GWAS statistical significance: ENSG00000050030, ENSG00000144285
- European ancestry
- Last updated: 2018

#### Questions
- Do we want to split the evidence by type of qualifying variants? For the following evidence, we could report the aggregation of the PTVs and missense, or report them one by one.

```json
{
  "gene_id": "ENSG00000004139",
  "group": "DEE",
  "xcase_lof": 0,
  "xctrl_lof": 0,
  "pval_lof": 1,
  "xcase_mpc": 0,
  "xctrl_mpc": 2,
  "pval_mpc": 1,
  "xcase_infrIndel": 0,
  "xctrl_infrIndel": 0,
  "pval_infrIndel": null,
  "pval": 1
}

```

**Comment by ireneisdoomed** [comment]
### Notes about the OTAR associations

Manuscript: https://www.cell.com/ajhg/fulltext/S0002-9297(22)00157-4?s=09#sectitle0025
Blogpost: https://blog.opentargets.org/using-blood-metabolites-to-find-new-drug-targets/

- WGS or WES of blood samples from healthy individuals from the [INTERVAL cohort](https://www.intervalstudy.org.uk) (English population)
- 40 novel associations implicating rare coding variants (27 genes and 38 metabolites), of which 28 (15 genes and 28 metabolites) were replicated. 
	- Of these, 16 gene-metabolite associations were completely novel. 
	- 28 of these associations were also replicated using a non-overlapping sample of participants with WGS data from the INTERVAL study.
- 3 types of collapsing analyses:
	- "CODING": all coding region variants plus untranslated regions (UTRs) and essential splice sites
	- "MLOF": LoF and missense variants
	- "LOF": LoF variants predicted as high confidence by LOFTEE (loss-of-function transcript effect estimator) <-- this is coming from VEP
- Data is available in the Supplementary Table 5, in the "Gene-based results" sheet.

#### Questions
- Do we want to report the metabolic pathway?
- The INTERVAL study is carried on English people. We would expect to have different ancestries covered, right?
- The analyses is done on WES data and further replicated on WGS. We want to capture all associations statistically significant in WES, regardless they have been replicated, right?
- If I understand correctly, the "Gene based results" and the "Strongest gene metabolite" tables differ in that the latter reports variant level summary stats.
- Do we want to capture the direction of effect?

```json
# Data in the Gene based results table
{
  "approach": "MLOF",
  "Gene_name": "ACADS",
  "P-value": 2,16E-12,
  "Test": "burden",
  "Biochemical": "butyrylcarnitine",
  "SuperPathway": "Lipid",
  "Pathway": "Fatty Acid Metabolism (also BCAA Metabolism)"
}

# Data in the strongest gene/metabolite table
{
  "Gene_Symbol": "ACADS",
  "Best_metabolite": "butyrylcarnitine",
  "Number of Metabolites": 2,
  "Additional Metabolites": "ethylmalonate",
  "SuperPathway": "Lipid",
  "Pathway": "Fatty Acid Metabolism (also BCAA Metabolism)",
  "N_driver_variant": 10,
  "Driver_variant_GRCh38": "12:120738329:G:A;12:120738416:TG:T;rs199717731;rs375272147;rs28941773;rs368469075;rs371934737;rs28940875;rs537072819;rs767774362",
  "Driver_variant_GRCh37": "12:121176132:G:A;12:121176219:TG:T;rs199717731;rs375272147;rs28941773;rs368469075;rs371934737;rs28940875;rs537072819;rs767774362",
  "N_informative": 3881,
  "EAF": "0.000128833;0.000130582;0.000128866;0.000128866;0.000257666;0.000257666;0.000128833;0.000128833;0.000257666;0.000129099",
  "Beta_SE": "2.0877 (1.0008);1.8332 (1.0008);2.9025 (1.0008);1.6642 (1.0008);2.6497 (0.7078);1.7352 (0.7078);1.967 (1.0008);1.1825 (1.0008);1.5426 (0.7078);1.6843 (1.0008)",
  "P-value": "3.69727e-02;6.69987e-02;3.72962e-03;9.63434e-02;1.81255e-04;1.42202e-02;4.93612e-02;2.37377e-01;2.92875e-02;9.23806e-02",
  "Best_RVT": "ACADS.w2_burden_naive",
  "Best_RVT_p-value (full model)": 2.3e-9,
  "Best_RVT_p-value (driver variants model)": 2,80567E-12,
  "Consequence": "missense_variant;frameshift_variant;missense_variant;synonymous_variant;missense_variant;missense_variant;missense_variant;missense_variant;missense_variant;stop_gained",
  "Gene Overlap Shin et al": "IEM(Shin)",
  "reported in mGWAS": "yes",
  "Mendelian Disease": "ACYL-CoA DEHYDROGENASE, SHORT-CHAIN, DEFICIENCY OF; ACADSD {OMIM:https:\\/\\/www.omim.org\\/entry\\/201470}",
  "Inheritance": "AR",
  "direction of effect": "pos",
  " consistent direction of effect": "yes",
  "biochemical explanation": "increased butyrylcarnitine level consistent with elevated butyrylcarnitine in patients with acyl-CoA dehydrogenase"
}

# Proposed schema

{
    "datasourceId": "gene_burden",
    "datatypeId": "genetic_association",
    "diseaseFromSourceMappedId": "EFO_0020010",
    "pValueMantissa": 2.16,
    "pValueExponent": -12,
    "resourceScore": 2,16E-12,
    "literature": [
        "35568032"
    ],
    "projectId": "OTAR022",
    "cohortId": "INTERVAL",
    "ancestry": null,
    "ancestryId": null,
    "studyId": null,
    "studySampleSize": 3881,
    "studyCases": null,
    "studyCasesWithQualifyingVariants": null,
    "statisticalMethod": "MLOF",
    "statisticalMethodOverview": "Burden test carried out with LoF and missense variants with a MAF smaller than 0.1%."
}

```

**Comment by ireneisdoomed** [comment]
Genebass made a new release of its portal last week. In it their analysis was expanded from 280k UK Biobank samples to 450k, matching the sample size of REGENERON and AZ PheWAS Portal.
https://www.medrxiv.org/content/10.1101/2021.06.19.21259117v4

Since the portal is a reference for the community, we want these gene-based analyses to be part of the gene_burden source. The results are available as a Hail-processable MatrixTable at `gs://ukbb-exome-public/500k/results/results.mt`

## Methods

We have been able to process the data and generate 8808 evidence strings out of it. The p value of statistical significance has been set to **6.7e-07**, based on the methodology explained in their preprint. 

| Stats       |  |
|----------------------|------|
| Evidence count       | 8808 |
| Associations count   | 7238 |
| Targets count        | 2645 |
| Traits count (EFO)   | 715  |
| Traits count (Trait) | 2358 |

They have done 4 different burden tests based on 4 sets of variants:
- 'pLoF': 'Burden test carried out with rare pLOF variants.',
 - 'missense|LC': 'Burden test carried out with rare missense variants including low-confidence pLOF and in-frame indels.',
 - 'synonymous': 'Burden test carried out with rare synonymous variants.',
 - 'pLoF|missense|LC': 'Burden test carried out with pLOF or missense variants.',

### Trait mapping
These traits had to be mapped to EFO and for that purpose we did a multi step strategy to come up with the better suggestion so that the manual mapping process became easier.
1. common_label. Suggestion is extracted from a previous mapping already present in OTP. The label of the trait is exactly the same.2. 
2. ontoma. High quality suggestion from ontoma. 
3. zooma. Medium and high quality suggestion from zooma. 
4. burden_association. Suggestion is extracted from a known gene burden association for the target the trait is associated with. This causes a big explosion.

Here is the working sheet: https://docs.google.com/spreadsheets/d/1SjYXtfqUGJAipXly3RnD3tb0aEPd55BSdDwDGlxdZSM/edit#gid=581323175

This has been the most time consuming step (thanks to @d0choa, @DSuveges). The mappings tagged as valid in the spreadsheet have been imported to [our disease curation table](https://github.com/opentargets/curation/blob/master/mappings/disease/manual_string.tsv).

**Comment by ireneisdoomed** [comment]
For 22.06 release we will be integrating all the ExWAS burden results described in the original post except for point # 4, the analysis on metabolites using Nightingale's NMR. This is expected to be in the next release and will also require effort in the mapping of the metabolomics traits.

So here is the extract on how the gene_burden evidence is split:
```
+--------------------+-----+
|           projectId|count|
+--------------------+-----+
|AstraZeneca PheWA...|17785|
|                null|    3| --> These are the CKD associations (point # 2) 
|             OTAR022|   21|
|            Genebass| 8808|
|   SCHEMA consortium|    9|
|           REGENERON| 7755|
|Autism Sequencing...|  102|
| Epi25 collaborative|    2|
+--------------------+-----+
```

**Comment by HelenaCornu** [comment]
@ireneisdoomed I have some questions... 

- Does the new evidence bring in any new associations? (If so, from which study?)
- Where the papers reported more associations than we imported, why were some of the associations dropped? e.g. Schizophrenia paper, 10 reported in the paper but 9 evidence strings; CKD paper, 4 reported but 3 evidence strings; Bomba et al. found 40 associations but we import 21...

**Comment by ireneisdoomed** [comment]
@HelenaCornu I have some answers...

1. We have 1 465 new disease/target pairs that not only gene_burden is the only source supporting them, but that these come exclusively from the new burden analyses. Here's a breakdown of the contribution per study:

```
+--------------------+-----+
|           projectId|count|
+--------------------+-----+
|             OTAR022|   14|
|            Genebass| 1392|
|   SCHEMA consortium|    3|
|Autism Sequencing...|   55|
| Epi25 collaborative|    1|
+--------------------+-----+
```

2. Reasons why their reported associations and what we include are not the same differ:
- Schizophrenia. I missed including the [TRIO association](https://schema.broadinstitute.org/gene/ENSG00000038382). This will be available in the next release.
- CKD. Only PKD1, PKD2, and COL4A5 show study-wide significance, the other reported 2 genes show suggestive signals. So we only cover the first 3.
- Bomba et al. The data is based on Table 1 of their publication. 2 reasons:
    - Not all of the 27 associated genes result from burden tests, as SKAT is a regression-based approach that differs from the burden family analyses. We are not integrating SKAT results.
    - 4 metabolite measurements were not in EFO and therefore we had to request them. Our disease index is based on the second to last EFO version, so the new terms are not yet part of the Platform but will be there for the next release.

**One important note** is that unfortunately, we shouldn't mention the Cameron-Christie et al publication (CKD) for now. The reported disease is specifically a congenital subtype of kidney disease. This term was not yet in EFO so we'd requested it. This is the same situation as above, this new term is not yet part of the disease index and therefore the evidence from this paper won't make it for this release.

Tomorrow I'll give you a nice example that you can mention.

**Comment by ireneisdoomed** [comment]
We are expecting this work to be integrated in 22.06. I will close it for now and we'll bear it in mind for the 22.09 release - so that we integrate results from the Nightingale's NMR measurements (and perhaps more).

**Comment by ireneisdoomed** [comment]
@HelenaCornu I think it would be nice to cite the examples mentioned in the publication.

We have examples of known associations, all captured in the Platform:

> First, we recapitulate many known associations from previous studies, including associations between PCSK9 and LDL cholesterol (pLoF burden p = 3.5 x 10-132), COL1A1 and bone density (pLoF burden p = 2 x 10-9) (Mann et al., 2001), KLF1 and several red blood cell traits (pLoF burden < 2 x 10-12) (Perkins et al., 2016), and LRP5 (Wnt coreceptor) and bone density and osteoporosis phenotypes (pLoF burden < 5 x 10-7) (Baron and Rawadi, 2007).

And an example of a novel one, between [SCRIB and white matter microstructure measurement](https://deploy-preview-13--ot-platform.netlify.app/evidence/ENSG00000180900/EFO_0005674),  which they claim to capture essentially thanks to the increment in statistical power of the burden test

> We highlight novel biological signals identified in the exome dataset, enabled by the Genebass browser. In particular, we find an association between predicted loss-of-function of SCRIB and white matter integrity of tapetum. Notably, this association is not significant at any single pLoF variant, but when aggregated into a SKAT-O or burden group test.

![image](https://user-images.githubusercontent.com/45119610/175051603-eda16f21-89a1-4b20-b6ab-f33dd64bbe35.png)
