### ISSUE TITLE
etl and literature-etl

### ISSUE THREAD

**Issue by shubihu** [opentargets/issues#2605]
Hi, What is the difference and connection between the two directories（etl and literature-etl）? Thanks!
![image](https://user-images.githubusercontent.com/36021958/170806240-06b25efe-34bd-43db-a58d-de95ae847782.png)

**Comment by JarrodBaker** [comment]
This is nothing significant about the directory names. The `etl` directory contains the outputs generated through the [ETL](https://github.com/opentargets/platform-etl-backend) project, and the `literature-etl` outputs are generated through the [ETL Literature](https://github.com/opentargets/platform-etl-literature) project. At some point the ETL Literature code will be migrated into the ETL and we'd expect from that point on only to have a single output directory (see: opentargets#1793).
