### ISSUE TITLE
Consolidating OTAR project study / disease mapping tables.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2607]
There are two spreadsheets that needs to be collated into one:
* [EFO_spreadsheet](https://docs.google.com/spreadsheets/d/1RFerhFa_wwLtoyuMUWeZwIM7u_AGElXmcgxPXjUhvL8/edit#gid=833193390) - maintained by @sarahyoung3 
* [OTAR project EFO mappings for disease profile pages](https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs/edit#gid=72910172) - it is used by the ETL in the release process.

Also disease mappings and study/project metadata should be separated to two different tables to make sure it is easier to maintain.

**Comment by DSuveges** [comment]
- EFO_spareadsheet is depricated. Should be no updates there.
- From EFO_spreadsheet disease annotation for OTAR036 is moved to the other spreadsheet, as that is more up-to-date table.
- The `master` worksheet is removed from the [OTAR project EFO mappings for disease profile pages](https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs/edit#gid=72910172) table, because that's a join between the `project2disease` and `metadata` worksheets.
- New studies with EFOs were not in `project2disease` worksheet. This annotation is copied from `metadata`. 
- From the `metadata` worksheet, the disease columns (`efo_disease_label`, `efo_disease_id`) will be removed.

Question:
-[ ] How and where the joining of the two tables will happen?
-[ ] Where will the disease label coming from?
-[ ] How will this table be updated in the future?

**Comment by DSuveges** [comment]
* In the meta data OTAR2059 was listed 3 times. I collated all the data in to one single row.
 * Some of the fields (array fields were multiple values were expected to concatenated with `|` characters) were cleaned from spaces and empty strings.

**Comment by mbdebian** [comment]
Collection of this data is implemented by [this](https://github.com/opentargets/platform-input-support/pull/72) PR
