### ISSUE TITLE
Adapt the metrics script to work with remote data

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2613]
See #2612 for reference.

**Comment by d0choa** [comment]
Sorry if I'm saying something obvious but this generally works for me. To make this work the dataproc compute account required access to Google Storage, but this has been sorted already.

```
    sparkConf = (
        SparkConf()
        .set("spark.hadoop.fs.gs.requester.pays.mode", "AUTO")
        .set("spark.hadoop.fs.gs.requester.pays.project.id", "open-targets-eu-dev")
    )
    
    ....
    
   spark.read.parquet("gs://........")
   
```

This will make the code bound to google cloud infrastructure. I don't think it's a problem, but keep it in mind.

**Comment by ireneisdoomed** [comment]
@d0choa Not obvious for me at all. So if you provide that configuration, you can simply work with GCS data natively? So far I have been using [GCSFS](https://github.com/fsspec/gcsfs).

**Comment by d0choa** [comment]
Dataproc is configured to have native access to GCS. If you work in this way you won't ever need to move a dataset again.

**Comment by ireneisdoomed** [comment]
@d0choa Ok, I misinterpreted your original message. You're saying we would be bound to GC because the script would only run on the cloud. Whereas GCSFS is useful to refer to GCS locations while you're developing outside any GC services.

I see the benefit of being able to fire up the script locally and avoiding being locked in GC. At the same time, we'd be adding a dependency and a certain layer of complexity in the script to do so. I am not sure what is the best approach here.

**Comment by DSuveges** [comment]
@ireneisdoomed  I think this ticket can be closed as well.
