### ISSUE TITLE
Parametrise the metrics script with a configuration file

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2614]
See #2612 for reference.

We can follow the lessons learned in #1977 and use Hydra.

**Comment by ireneisdoomed** [comment]
Note: We should parametrise the output bucket of the metrics and stop hardcoding the data_folder variable https://github.com/opentargets/ot-release-metrics/blob/99ec5e64c9fb47b03755bcda59500ef5c826720c/app.py#L33

**Comment by prashantuniyal02** [comment]
@ireneisdoomed are we working on it or is it done?
