### ISSUE TITLE
Migrating Open Targets Google Analytics to GA4

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2616]
## Background

Currently, we are using Universal Google Analytics GA360; however, this version will stop tracking data on October 1, 2023 and will be replaced by Google Analytics 4 (GA4)

## Tasks

- [] We should migrate OT GA360, including all the current projects and functionalities, to GA4.

Current GA360 link here: https://analytics.google.com/analytics/web/?authuser=1#/report-home/a101860681w176880194p175737841

## Acceptance tests

How do we know the task is complete? 

1. When all our tracking data are migrated and functional on GA4

**Comment by buniello** [comment]
Link from Google Support with instructions on how to perform the migration: 
[Make the switch to Google Analytics 4](https://support.google.com/analytics/answer/10759417?hl=en)

**Comment by mbdebian** [comment]
@carcruz , would you like to have a chat about this?

**Comment by buniello** [comment]
Successfully migrated so far to GA4 (through Google Tag Manager): 
- [Genetics Portal](https://analytics.google.com/analytics/web/?authuser=1#/p318115781/reports/reportinghub?params=_u..nav%3Dmaui); 
- [Open Targets Platform](https://analytics.google.com/analytics/web/?authuser=1#/p318079319/reports/reportinghub?params=_u..nav%3Dmaui)

**Comment by buniello** [comment]
There is a blocker for migration of the following pages from UA to GA4:

Platform Documentation
Genetics Portal Documentation
Open Targats Community Page (Discourse)
Open Targets Blog (Ghost?)

For the above, I need to paste a piece of code into the source code + GitHub commit in order to "tag" them for migration. 
I am however not familiar with the source code location for these pages in the Open Targets repository and need some help to identify them please @carcruz @HelenaCornu @d0choa.

Code to paste in the <head> section of the above web pages:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5HZBD9Z');</script>

**Comment by buniello** [comment]
I have now successfully migrated our Google Analytics to Google Analytics GA4 for all our tagged/tracked websites.
