### ISSUE TITLE
PIS completion manifest / report

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#2619]
As a developer, I would like to have a PIS completion manifest / report that I can process programmatically.

## Background
The most important aspect of running PIS is whether the data collection was completed successfully or not, and, when a destination google cloud bucket has been specified, I also need to know if the data transfer was completed successfully.

Currently, PIS produces an extensive log output that can be analyzed to find out more on the success of the data collection, and possibly data upload, process. But, as a developer, thinking about further automating this process, I'd like to have some information that can be process programmatically to decide whether a PIS session was successful or not.

A _report output file_ with a completion digest on the PIS session, e.g. in json format, could be used to implement this report's data model, with the following information:
- Session wide information: e.g. command line arguments, running timestamp, duration, requested steps, etc.
- A completion descriptive message
- An overall completion status: OK | ERROR
- For the data collection aspect of PIS:
    - Information on possible missing data that was not possible to be collected
- For the GCP upload process
    - Information on possible errors that may have happened when trying to optionally upload the data to a given GCP bucket

This report can be processed manually or programmatically in order to take a decision on what to do next.

## Acceptance tests
When every PIS session produces a report where the overall completion status agrees with whether the result can be moved forward to the next stage (ETL) or not.

**Comment by buniello** [comment]
Feedback from the [Molecular Targets Platform](https://moleculartargets.ccdi.cancer.gov/) team: they would like to have checksums available for each file they download from our FTP. This would be a validation of whether they have accessed the complete dataset. Within FAIR principles (as pointed out by @mbdebian).
This implementation would be part of the manifest - therefore posting this note here.

**Comment by mbdebian** [comment]
This feature computes checksums for the input data produced by PIS.

Release-wide data checksum will be computed by POS.
