### ISSUE TITLE
Incorrect variant consequence in Platform L2G evidence

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2620]
As reported by @fedde-s in [Community](https://community.opentargets.org/t/mismatched-variant-consequences-between-ot-genetics-vep-data-and-the-ot-platform-evidence-page/656)

> The VEP (Ensembl) tab on https://genetics.opentargets.org/variant/1_169681903_G_A lists that, in the gene C1orf112 (ENSG00000000460), that variant’s most severe consequence is that it is intronic. The GWAS lead variants table on the same page shows that the variant came up in (among others) a study titled “Acne (severe) [fixed effect model]”. This association does appear [in the platform 1](https://platform.opentargets.org/evidence/ENSG00000000460/EFO_0003894), but listing it as being intergenic near that gene. [gnomAD itself](https://gnomad.broadinstitute.org/variant/1-169681903-G-A?dataset=gnomad_r3) agrees with OT Genetics.
> 
> The discrepancy suggests to me that the ‘variant annotation’ (referenced on https://github.com/opentargets/evidence_datasource_parsers#processing-genetics-portal-evidence) used to generate https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.04/input/evidence-files/genetics-portal-evidences-2022-04-12.json.gz was less complete/up-to-date than https://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/22.02.01/v2g/; the input files I linked currently match what their respective applications say.

**Comment by d0choa** [comment]
@DSuveges reported differences in the way canonical transcripts or all transcripts are considered for VEP in different parts of our codebase

Pointers to relevant code chunks representing slightly different logics to handle VEP:

V2G VEP
https://github.com/opentargets/genetics-pipe/blob/4fdbbfb06d902f83a77418f9e90aedcb384cc025/src/main/scala/ot/geckopipe/VEP.scala#L92

Evidence datasource parsers
https://github.com/opentargets/evidence_datasource_parsers/blob/4e2ea54f928041dd78e21febabbafc477db19260/modules/GeneticsPortal.py#L352

L2G
https://github.com/opentargets/genetics-l2g-scoring/blob/09b7beb7793adc728b0b0c5ce683552d0fe861d9/1_feature_engineering/1_prepare_inputs.py#L434

**Comment by DSuveges** [comment]
**My proposal**: 
- As running VEP for all variants is too expensive, we should continue relying on the consequences provided by gnomAD.
- As gnomAD provides all transcript consequences together with the flag `canonical`, we should drop all non-canonical transcript consequences upon generating the [variant annotation](https://github.com/opentargets/genetics-variant-annotation).

**pros:**
- Considering only the canonical transcript for consequences allows a biologically more relevant annotation, which by propagating to l2g calculation would potentially give us a more accurate locus to gene assignment.
- Process-wise this would make the release more robust and more consistent, as all downstream processes can assume the transcript consequences are interpreted in the canonical transcript.

**cons:**
- Larger scale discrepancies against big databases (gnomAD, Ensembl)
- An existing issue is the discrepancy between the evolving Ensembl gene set we use on the Platform and on the Portal, while the Ensembl gene set used to calculate VEP for gnomAD is frozen. This problem existed before, but most likely has a very minor impact. Internalising VEP is not an option at the moment.

**Comment by ireneisdoomed** [comment]
Note: this has implications to the L2G work (#2608)

**Comment by fedde-s** [comment]
What did you mean to imply by closing the issue? Has there been progress since [you proposed a solution](https://github.com/opentargets/issues/issues/2620#issuecomment-1151621278), that has either been included in release 22.06 (I have not spend time reproducing it yet) or should be in an upcoming one? Or did you internally agree that this is not an issue for EBI to address any further?
