### ISSUE TITLE
Integrating and displaying splice QTL (sQTL) data into the Genetics Portal 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2623]
As a developer/owner, I should pin down the best way to integrate and display to the users the new splice QTL datasets into the Genetics Portal.

The sQTLs contribute to the new V2G pipeline.

- [ ] BE team to make available development ES and CH images with sQTLs. 

## sQTLs in the Gene Page (from Jeremy's ppt)

- [ ] Add as rows in gene page colocalisation analysis

<img width="828" alt="Screenshot 2022-06-09 at 16 20 28" src="https://user-images.githubusercontent.com/30833755/172883556-27df4f0e-8012-4834-a977-b7fdcfb1b4b8.png">

## sQTLs in the Variant Page (from Jeremy's ppt)

- [ ] Add as a column in the assigned genes summary

- <img width="808" alt="Screenshot 2022-06-09 at 16 22 59" src="https://user-images.githubusercontent.com/30833755/172884050-e06990a7-0079-46ab-96e4-fa7413b5d212.png">

- [ ] Add as a tab in the assigned genes

<img width="808" alt="Screenshot 2022-06-09 at 16 25 11" src="https://user-images.githubusercontent.com/30833755/172884555-ee4f9e7e-770a-4000-9872-740e5147782a.png">

## sQTLs in the Study-Locus page (from Jeremy's ppt)

-  [ ] Add as rows in heatmap and in table

<img width="808" alt="Screenshot 2022-06-09 at 16 27 48" src="https://user-images.githubusercontent.com/30833755/172885174-33a212db-cd80-4c08-8602-163f17032a00.png">
<img width="808" alt="Screenshot 2022-06-09 at 16 28 56" src="https://user-images.githubusercontent.com/30833755/172885602-60d40dc0-9bf1-49e4-bf54-edbe206ceae3.png">

-  [ ] Add as rows in as rows in the credible set overlap

<img width="739" alt="Screenshot 2022-06-09 at 16 30 12" src="https://user-images.githubusercontent.com/30833755/172885894-0171770b-57e6-49ea-9c7b-65d94ee4acb3.png">

- [ ] Incorporated into L2G scores, but no visible change

<img width="739" alt="Screenshot 2022-06-09 at 16 39 40" src="https://user-images.githubusercontent.com/30833755/172888095-bf468325-ceb8-404c-bac6-282e99327769.png">

## Acceptance tests

How do we know the task is complete? 

1. When sQTL data are integrated into the Genetics Platform  
2. When all relevant tables and tabs clearly display sQTL data to users

**Comment by buniello** [comment]
Added new record with the metadata about the sQTLs in [v2g_display_labels.json](https://github.com/opentargets/genetics-api/blob/master/resources/v2g_display_labels.json) - this include text for tooltip.

**Comment by buniello** [comment]
Latest update on this task: @xyg123 is currently investigating whether the prototype shown above covers all use cases for sQTLs. 
g. does each cluster only map to one gene in our dataset? Can one gene host multiple clusters?
If so, how do we display these odd datasets?

**Comment by JarrodBaker** [comment]
I will be out of the office until 1 August 2022. 
    
    If your matter is urgent and related to Open Targets please seek
      assistance from ***@***.*** .
    Kind regards
    
    -- 
Jarrod Baker
Backend Team Lead / Senior Software Developer
Open Targets
+44 7842 523 531

**Comment by buniello** [comment]
From @xyg123:
Here are the [results for sQTL merging](https://docs.google.com/presentation/d/1Tf2ZPQqPhLQwPAvy2Ew-H7K20KUTSRD5P0En9VIOqIA/edit#slide=id.g1402894752c_0_12), I think merging it should be fine for now, although we should re-visit this data when we add additional sources in the future.

**Hovering text**: `chr1^54605209^54607134^clu_47022_log2(H4/H3):, H3:, H4:, QTLbeta: `

**Comment by buniello** [comment]
Discussed with the team:
the API will be slightly modified so that the sQTL data can conform to the schema. 
This means that the current `phenotypeId` filed will be split into two columns:
`phenotypeId`: ENSGID
`spliceId`: chr1^54605209^54607134^clu_47022
**Hovering text**: log2(H4/H3):, H3:, H4:, QTLbeta:, spliceId

**Comment by ireneisdoomed** [comment]
@buniello Just a very minor opinion as a user. What do you think if the tooltip showed the metrics in separate rows instead of having them separated by commas? Btw, for eQTL and pQTLs the metrics are just separated by a space.

**Comment by buniello** [comment]
@ireneisdoomed this is a good observation! - You suggest having `spliceId` in a separate row right?
We have commas also for eQTLs and pQTLs i think? A hovering example from other QTLs is in one of the screenshots above.

**Comment by ireneisdoomed** [comment]
@buniello No, I was proposing for the hovering text to be:
```
log2(H4/H3): {value}
H3: {value}
H4: {value}
QTL beta: {value}
spliceId: {value}
```

My main argument is that the splice ID is a fairly long string. However, I don't know if with a longer hover text we would frequently obstruct the visibility of other circles.

**Comment by buniello** [comment]
Discussed with @remo87 already:

- [ ] all tables displaying sQTL data  (locus page/coloc table, gene page/coloc) should also show just the gene "id" without the custer/splice "Id" for each independent row (representing different tissues). 
-- The 'splice id' (not hugely meaningful to users anyway) will only be displayed in the heatmap tooltips for each point in the aggregation.

Example below of locus page/coloc table:
![Screenshot 2022-08-25 at 09.48.11.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/bcb3e5fa-be76-41e0-a0e4-7f48fb985493)
