### ISSUE TITLE
Displaying sumstats info (yes/no) for each study to facilitate data sorting for users 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2627]
Following up from the feedback on OTG functionalities provided by BMS on 8-6-22.

As a user, I need to be able to select/sort studies with summary stats even before clicking on the "gene prioritisation" tab. 
This will allow a better user experience with quicker navigation through the data. This should be a straightforward task.

## Tasks

- [] Add the sumstats info (yes/no) next to each study.

- Specifications:

**1) On the Target/gene page: add this next to each row in the L2G table and the coloc table (see example below)**

![Screenshot 2022-06-13 at 09 56 06](https://user-images.githubusercontent.com/30833755/173324129-0a4df7bf-4f87-450b-8a64-182cfa6c75c9.png)

2) **On the Variant page: add this in the tables (see example below)**

![Screenshot 2022-06-13 at 10 09 37](https://user-images.githubusercontent.com/30833755/173324306-ab8f4f64-3d32-4e67-94b4-caa6cb2520b0.png)

3) **On the gene prioritisation page: add this in the ‘Association Summary’ section, under "study details" (see example below)**

![Screenshot 2022-06-13 at 10 25 09](https://user-images.githubusercontent.com/30833755/173323670-21e20879-905b-4658-86c7-b7fe3c935999.png)

## Acceptance tests

How do we know the task is complete? 

1. When the pages/tables mentioned above display the "has sumstats - yes/no" field  
2. Test

**Comment by bruno-ariano** [comment]
On the cloud and also in this link:  ftp://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/latest/lut/study-index/

there are the annotations for each study. In this table there is also a column called "has_sumstats" which indicates whether a study has summary statistics or not

**Comment by buniello** [comment]
For use-case #3 above: **Gene prioritisation page (evidence page) -add sumstats info in the Association Summary’ section, under "study details":**
-this is possible as endpoint "hasSumstats" is queried 
**API query:**
query StudyLocusHeaderQuery($studyId: String!, $variantId: String!) {
  studyInfo(studyId: $studyId) {
    studyId
    traitReported
    pubAuthor
    pubDate
    pubJournal
    pmid
    nInitial
    nReplication
    nCases
    hasSumstats
    __typename
  }
  variantInfo(variantId: $variantId) {
    rsId
    id
    __typename
  }
}
**Example response:**
{
  "data": {
    "studyInfo": {
      "studyId": "GCST002222",
      "traitReported": "LDL cholesterol",
      "pubAuthor": "Willer CJ",
      "pubDate": "2013-10-06",
      "pubJournal": "Nat Genet",
      "pmid": "PMID:24097068",
      "nInitial": 94595,
      "nReplication": 93982,
      "nCases": null,
      "hasSumstats": true,
      "__typename": "Study"
    },
    "variantInfo": {
      "rsId": "rs7254892",
      "id": "19_44886339_G_A",
      "__typename": "Variant"
    }
  }
}

**Comment by buniello** [comment]
Visualisation specs (for consistency with current style of table in Portal):
HEADER: Sumstats 
VALUE: yes/no

N.B.: currently, the studies with sumstats are also visualised in blue in the searchbox dropdown when searching for a study. This visualisation will not be modified for now.

**Comment by LucaFumis** [comment]
I can see the data (hasSumstats) is available - I'll start working on this
