### ISSUE TITLE
Create a data bucket that is publicly available/available to partners on Sanger Farm (OTG)

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2632]
Following up from the feedback on OTG functionalities provided by BMS on 8-6-22.

Request from partners:

 - [] Create a bucket that is publicly available/available to partners on Sanger Farm where the team can share the existing fine-mapping and coloc data for studies without sumstats.

## Acceptance tests

How do we know the task is complete? 

1. When requested data is successfully shared on Sanger Farm.

**Comment by sarahyoung3** [comment]
Unfortunately, I don't believe this is possible. Sanger policy does not allow partner access to the Sanger Farm - only those with an @sanger email. The current process is that they request the data and I provide it to them via a wget url. Is this an ok solution for this, as well? Happy to change to whatever is easier!

**Comment by buniello** [comment]
Thanks @sarahyoung3, I also add @MayaGhoussaini to this conversation

**Comment by d0choa** [comment]
All genetics portal runs in Google Cloud now. There is no need to deal with the Sanger farm

**Comment by buniello** [comment]
Does it mean that it would be enough for Jack @xyg123 to create a directory on the Cloud with the requested fine-mapping and coloc data and provide access to the BMS data team? @d0choa

**Comment by d0choa** [comment]
Ideally, we should not create anything new. Just grant access to the relevant person (hopefully one) that would pull the data.

Just to say, this data is not produced to be shared so it lacks documentation and it requires some understanding of how the pipelines work.

**Comment by d0choa** [comment]
V2D in the FTP is the result of joining all the variant-to-disease information. Therefore, it contains data from studies with and without summary statistics.

Generally speaking, everything on the FTP is the result of data joining steps that are generated for the benefit of the genetics portal application. The intermediate outputs are on other locations e.g. `gs://genetics-portal-dev-staging/` that are not publicly available for operative reasons.

In some cases (e.g. coloc), the datasets suffer not much transformation and it's exposed to the FTP in a similar format to the intermediate result. But that's not the case for most of the datasets including V2D.

Long-term we can work out what is the set of relevant datasets that are meaningful and have a reasonable size to be shared. In the meantime, we can provide selective access to the relevant individuals in GCP once the datasets they are interested in have been identified.

**Comment by buniello** [comment]
@d0choa @MayaGhoussaini do you think this can be closed for now?

**Comment by d0choa** [comment]
For the time being, we can make any data available to partners upon request.

It will take us some time to organise everything, so we are in a state in which we can share intermediate datasets that are not necessarily the inputs or outputs of our pipelines and still be able to communicate that properly
