### ISSUE TITLE
Adding nullifiedScore to metrics comparison

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2638]
- [ ] Adding `nullifiedScore` reasons for being invalid. Currently we have
   - All invalid evidence
   - Duplicated evidence
   - Unresolved disease
   - Unresolved target.

However there are 5 reasons:
```
 |-- resolvedTarget: boolean (nullable = true)
 |-- resolvedDisease: boolean (nullable = true)
 |-- excludedBiotype: boolean (nullable = true)
 |-- nullifiedScore: boolean (nullable = true)
 |-- markedDuplicate: boolean (nullable = true)
```
The `excludedBiotype` is not interesting.

**Comment by ireneisdoomed** [comment]
Done
