### ISSUE TITLE
Maintain an up to date gold standard for the associations benchmark

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2642]
I want the mappings between indication and EFO that we use to benchmark our associations to come out of our central mappings table to make sure the EFOs are up to date and synchronised.

## Context
The generation of the metrics includes a step in which the associations are benchmarked by data source against a gold standard of associations based on approved drugs.

The indications of this GS are originally described as MeSH terms which have been mapped to EFO. Every time we run the metrics, we ingest this [MeSH to EFO table](https://github.com/opentargets/ot-release-metrics/blob/master/gold-standard/mesh_mappings.tsv) to build the GS associations and calculate the enrichment.

We've observed a drop in the enrichment of the 22.06 associations for sources like PanelApp which can be affected by the fact that EFO has recently made obsolete a big number of terms while at the same time we have not adapted the GS mapping table to accommodate these changes.

After taking a look, the impact is lower than expected: **out of 417  unique EFOs, only 27 have turned out to be obsoleted.**

## Actions

- [ ] Import the content of the [MesH to EFO table](https://github.com/opentargets/ot-release-metrics/blob/master/gold-standard/mesh_mappings.tsv) to the [central disease mappings table](https://github.com/opentargets/curation/blob/master/mappings/disease/manual_string.tsv)
- [ ] At the moment of calculating the metrics,  the mappings for the GS indications  will be pulled from the table either by: 1) instantiating ontoma, or 2)reading the remote file from GitHub

**Comment by d0choa** [comment]
@opentargets/data-team any actions here?

**Comment by ireneisdoomed** [comment]
We haven't done any follow up here.
