### ISSUE TITLE
ClinVar's evidence widget is not loading

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2644]
**Describe the bug**
ClinVar's evidence widget isn't loading. 

**Observed behaviour**
ClinVar has evidence of association between IL7R and multiple sclerosis. However, when i go to the evidence page the widget is not loading due to a problem.
I've checked 5 evidence pages and this is not an isolated bug.

**Expected behaviour**
For the widget to load the one piece of evidence between IL7R and multiple sclerosis.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.dev.opentargets.xyz/evidence/ENSG00000168685/MONDO_0005301
2. Click on ClinVar's summary widget which says there is one piece of evidence
3. See error

**Comment by ireneisdoomed** [comment]
...And the correspondent piece of evidence to the offending query:
```
-RECORD 0----------------------------------------------
 datasourceId                   | eva
 targetId                       | ENSG00000143631
 alleleOrigins                  | [germline]
 clinicalSignificances          | [pathogenic]
 cohortPhenotypes               | [Atopic dermatiti...
 confidence                     | criteria provided...
 datatypeId                     | genetic_association
 diseaseFromSource              | Atopic dermatitis 2
 diseaseFromSourceId            | C1853965
 diseaseFromSourceMappedId      | EFO_0000274
 studyId                        | RCV000763246
 targetFromSourceId             | ENSG00000143631
 variantFunctionalConsequenceId | SO_0001587
 variantHgvsId                  | NC_000001.11:g.15...
 variantId                      | 1_152313385_G_A
 variantRsId                    | rs61816761
 diseaseId                      | EFO_0000274
 id                             | b6a345946e69defb5...
 score                          | 0.95
 sourceId                       | eva
```

**Comment by JarrodBaker** [comment]
This issue was caused by the SO index not being loaded by POS and has now been resolved.
