### ISSUE TITLE
Remove production.conf from API

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2650]
As a developer I want a single place to update API configuration to reduce the risk of errors.

## Background

The API uses the Play framework which has a [hierarchy of configuration variables](https://www.playframework.com/documentation/2.8.x/ConfigFile). We package the jar with an `application.conf` file, and this is overwritten by the `production.conf` file __or__ an environment variable provided by Terraform. 

For our purposes this is needlessly complex when we only ever want to update the URL of the Elasticsearch and Clickhouse machines. We want to have the `application.conf` file providing all sensible defaults, with Terraform providing the necessary run-time configuration. 

## Tasks

- [ ] Update `application.conf` to scan the environment for variables to configure: 

- Elasticsearch and Clickhouse ports and uris; 
- the play secret

- [ ] Update Terraform provisioner to provide those values.

**Comment by d0choa** [comment]
Not sure how urgent this is. But assigning to you @remo87. Feel free to close if not appropiate
