### ISSUE TITLE
FTP data pending for 22.06

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2652]
As [reported by a user in community](https://community.opentargets.org/t/the-latest-release-22-06-is-now-live/675/2), the 22.06 data is not yet available in the EBI FTP. 

```
ls /ebi/ftp/pub/databases/opentargets/platform
...
drwxr-sr-x 6 otftpuser opent 4.0K Nov 24  2021 21.11
drwxr-sr-x 7 otftpuser opent 4.0K Mar  2 02:05 22.02
drwxrwsr-x 7 otftpuser opent 4.0K May  4 01:21 22.04
lrwxrwxrwx 1 mbernal   opent    5 May  5 04:59 latest -> 22.04
```

**Comment by mbdebian** [comment]
Data sync has run from the bucket to the internal file system behind the EBI FTP service, and I'm afraid that we have a problem.
Google Cloud reports 1.3TiB of data, while both the internal file system and EBI FTP service only report 910GiB, I need to follow this up with the TSC.

**Comment by mbdebian** [comment]
The release data is now available at ftp://ftp.ebi.ac.uk:/pub/databases/opentargets/platform/22.06
