### ISSUE TITLE
pQTL studies not listed in genetics portal documentation

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2657]
The documentation from Genetics Portal contains an outdated list of pQTL studies (only Sun et al.):

I replied to a user in the community with the most recent list:
https://community.opentargets.org/t/ukb-ppp-pqtl-data-online/670/2

Since we will be soon adding the sQTLs, can we please also update the pQTLs?

**Comment by buniello** [comment]
I noticed earlier that also the [metadata schema](https://github.com/opentargets/genetics-api/blob/master/resources/v2g_display_labels.json) is outdated for pQTLs:
{"key":"sun2018","value":{"display_label":"pQTL (Sun, 2018)",....}. -- 

though headers in UI don't display the (Sun, 2018) part anymore.

**Comment by d0choa** [comment]
@buniello updating this will fix this issue: https://github.com/opentargets/issues/issues/2069
We hacked it in the FE to hide the `(Sun, 2018)` part.

**Comment by buniello** [comment]
Modified both:
 - Genetics Portal [Docs](https://app.gitbook.com/o/-LC3OlEMulAutIN2QOro/s/-LIksz47AbnCef_uSkAf/our-approach/data-sources#overview-of-data-sources)
 - [Metadata Schema ](https://github.com/opentargets/genetics-api/blob/master/resources/v2g_display_labels.json)
