### ISSUE TITLE
Add assessment of directionality of the t/d association in the Platform

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2660]
We want to estimate what is the mechanism of action that describes the relationship between a target and a disease. For example, we know PCSK9 has a role in the metabolism of cholesterol, but what is its mechanism of action? Should I target it with an inhibitor or should I develop an agonist?

We want to try to make an algorithm where we predict this feature. Therefore we will be able to enrich the disease/target evidence for all data sources so that our users will be able to formulate more complex therapeutical hypothesis.

## Direction of effect definition

I define directionality as an assessment of how the target influences the disease from the point of view of how I should modulate it. Therefore this is the model that I follow to make the assesment:
- **Loss of Function**: The presence of a target decreases the trait (protective factor).
	- Absence increases the trait
- **Gain of Function**: Presence of a target increases the trait (risk factor)
	- Absence decreases trait

## Data
This information is present in several different places of the Platform, encoded in different ways as well, therefore the strategy to make the assessment is usually dependent from the source.
> **A list of sources is provided and described in the working document https://docs.google.com/document/d/1eFyeldLWZtoX2oNYNNf2VqNnrWCQQepEJtVG4380VBw/edit#**

<div>
    <a href="https://plotly.com/~irenelopezs/47/" target="_blank" title="doe_all" style="display: block; text-align: center;"><img src="https://plotly.com/~irenelopezs/47.png" alt="doe_all" style="max-width: 100%;width: 1000px;"  width="1000" onerror="this.onerror=null;this.src='https://plotly.com/404.png';" /></a>
    <script data-plotly="irenelopezs:47" src="https://plotly.com/embed.js" async></script>
</div>
(Note: if you click of the plot you will be able to interact with it)

In the chart the flow of all information present in all sources is represented to give an idea of what is the level of coverage we have per direction. I'll add the same diagram per source in subsequent comments to make it more readable.

**Comment by bruno-ariano** [comment]
The loss of function (LOF) information can be taken from the gnomad dataset under the column "lof". You should in this column for values "HC" that stands for high confidence.

This information was generated by McArthur lab using the tool LOFTEE. Here you can find more details https://github.com/konradjk/loftee. 

The variant annotation has now been updated to include also this information and is in:
gs://genetics_etl_python_playground/XX.XX/output/python_etl/parquet/variant_annotation

**Comment by d0choa** [comment]
This has been superseded by the work from @Juanmaria-rr
