### ISSUE TITLE
inclusion of OTAR sceQTL study in genetics portal 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2663]
In a very recent [publication](https://www.nature.com/articles/s41588-022-01066-3) Soskic *et al* performed eQTL studies in a series of T cell lines in different activation states. This dataset then was colocalized with a selected set of GWAS studies. The resulting dataset can be used to infer association between targets (identified by the QTL) and diseases (from GWAS study) in the context of cellular background and activation state and its direction of effect.

The scope of this ticket is to explore
 - Available dataset
- Difficulties to model the right evidence object
- Assess difficulties around mapping target/disease/cell line etc.

**Comment by ireneisdoomed** [comment]
We've included this through the eQTL Catalogue (with a study name of `cytoimmgen`).
More [here](https://github.com/opentargets/issues/issues/3332)
