### ISSUE TITLE
Locus plot not loading for a gene: ENSG00000109919

### ISSUE THREAD

**Issue by saurabhgayali** [opentargets/issues#2672]
**Describe the bug**
No Plot Generated for gene: ENSG00000109919
url: https://genetics.opentargets.org/locus?chromosome=11&end=48629961&selectedGenes=ENSG00000109919&start=46629961
Page shows no association.
Grahql query gives 502 error.
Same graphql called through an external tester agent gives a json file of 54 mb which has large amount of data.

**Observed behaviour**
The web page shows no association data while the graphql when called through API Talend tester generates json file of 54mb.

**Expected behaviour**
Either wait longer to load complete data, generating the plot 
or
Show error that query has timed out due to large data instead of showing general error that there is no association.

**To Reproduce**
1. Go to url: url: https://genetics.opentargets.org/locus?chromosome=11&end=48629961&selectedGenes=ENSG00000109919&start=46629961
2. Open inspect element to see api calls
**Additional context**
Same graphql called through an external tester agent gives a json file of 54 mb which has large amount of data.

**Comment by d0choa** [comment]
We are not planning to patch this behaviour, so we will need to do some ground work to make it work properly.
Apologies in the meantime
