### ISSUE TITLE
Unify colocalization analysis

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2674]
As a **developer** I want to **unify the different approaches to do a colocalization analysis under a same pipeline** so that the whole process is well documented and consistent in other parts of the Genetics Portal.

## Background

The standard colocalisation analysis is based on the identification of overlapping variants between credible sets after doing fine mapping. For this, summary stats are required. This pipeline is described [here](https://github.com/opentargets/genetics-colocalisation) and it has been recently revisited by @d0choa to make it a much more performant process.

At the same time, when working on #2608, I have realised that the L2G pipeline integrates a different way of doing colocalization analysis for those studies for which we don't have summary statistics. This is based on the LD expanded GWAS Studies and QTLs.

The conclusion is that we want to bring this second approach to the colocalization pipeline, so that L2G only is responsible for extracting features, not adding more business logic to the Genetics pipelines.

You can see the current implementation of this in the production branch: [pics_coloc.py
](https://github.com/opentargets/genetics-l2g-scoring/blob/master/1_feature_engineering/2_make_features/pics_coloc.py)
And my attempt so far to improve this pipeline: [coloc.py](https://github.com/opentargets/genetics-l2g-scoring/blob/il-l2g-predictions/production/src/1_make_feature_matrix/scripts/coloc.py). Once the main logic is moved to `coloc`, the part of L2G that processes this input will be obviously better.

## Tasks

After a discussion today with the Genetics team, we have conveyed in a plan to integrate these two approaches. Based on @DSuveges comments:

- We should create a big credible set dataframe with Finngen, GWAS Cat w sumstats, QTLs, + GWAS Cat no sumstats
- Do a full join to get all pairs of peaks to tests.
- There are two different pairs to condition on:
`col(logABF_study1).isNotNull() & col(logABF_study2).isNotNull()`
`col(logABF_study1).isNull() | col(logABF_study2).isNull()`
- For a, where both studies have logABF, we run the new coloc.
- For b, where at least one of the study doesn’t have logABF, we do the same coloc as it is now happening in l2g.
- The output of the two runs should be concatenated with a flag indicating which pipeline generated the coloc.

Benefits:
This would allow us the keep all code/process at one place
We would have coloc data on all gwas loci even across all studies.
We would not depend on Finngen’s LogABF value to phase in the new coloc.

**Comment by buniello** [comment]
Irene has discussed this with Ian and Maya at the latest Genetics Team meeting -- it was decided that this implementation will be applied to the new coloc pipeline (David's coloc, which is waiting for the new FinGenn data to be utilised). 
No further implementation will be applied to the current coloc pipeline.

**Comment by ireneisdoomed** [comment]
The proposed workflow might have a caveat that I recently became aware of. 

The PICS based colocalization uses the colocalization posterior probability (CLPP) value to describe the amount of support for a variant being responsible in both studies.
This value is proposed in the eCAVIAR method, and from its [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5142122/), this framework is in principle only valid between GWAS and eQTL studies. Therefore we wouldn't be able to apply this approach between Finngen studies as proposed above.

I don't know whether there are protocols that use eCAVIAR between other types of signals, so any input is appreciated @MayaGhoussaini
