### ISSUE TITLE
Adding an additional column to the OTAR projects table on the PPP disease profile page 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2678]
This is an issue that came up multiple times during the PPP/demo sessions.

The users are expressing concerns on the table shown on the profile page for a fixed disease in the PPP e.g. Alzheimers Disease:

1-- it takes some clicking to identify which OTAR projects in the list integrates data into the PPP. 
See proposed  additional column in the screenshot attached.
NOTE: the API is ready for this. Fixing a disease, knowing whether there is OTAR data it is possible with the OTAR projects endpoint.

2 -- Project code "OTAR 0xxxx" does not mean much as it is for a "quick-eyed" user. We could swap the two columns -- project name first on left with link to project page THEN project code on second column for reference. We could also add a bit more context to the project name e.g. a summary (Panos' suggestion since we have space in the table).

![Screenshot 2022-11-09 at 15.33.05.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/0af21108-91fd-4e89-8759-79ceb1f87e90)

**Comment by LucaFumis** [comment]
The OT Projects data comes from the `disease` API endpoint:
```
    otarCode
    status
    projectName
    reference
```
From the conversation with @buniello it seems the API does not account for a "Data integrated into PPP" field, so two options:
1. Ideally we get that field into the API
2. as a _quick fix_, we could add the list of integrated projects into the front end code (I understand this is a short list)

**Comment by buniello** [comment]
List pf OTAR project with data integrated into the PPP so far:
OTAR033 
OTAR035 
OTAR036 
OTAR2054 
OTAR2059
OTAR2062

**Comment by buniello** [comment]
Discussed with David in the office - option 1 is the "must go" avenue. 
I will start by adding an "integrates data into PPP" field to the [OTAR project spreadsheet](https://docs.google.com/spreadsheets/d/1CV_shXJy1ACM09HZBB_-3Nl6l_dfkrA26elMAF0ttHs/edit#gid=1179867447), which i will update in the future as well. 
This new field should be exposed in the API and FE should pick that up to populate new column

**Comment by buniello** [comment]
adding @remo87 to the discussion as well

**Comment by buniello** [comment]
Discussed with @LucaFumis and @remo87 today --
the new API filed and table header with be both named
`integrates in PPP`
