### ISSUE TITLE
Input of the L2G matrix doesn't include sQTLs

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2681]
**Describe the bug**
The QTL credible set that is used as an input to build the L2G feature matrix doesn't include sQTLs.
function that preprocesses the credible set to build the QTL cred set in the L2G pipeline. This dataset doesn’t include sQTLs although they are present in the credset.
This is because there is no assigned gene_id for the phenotype in the LUT. There is a step t[hat filters out the records ](https://github.com/opentargets/genetics-l2g-scoring/blob/1751a39336b0d102fea01738b4d61bc979f205ca/1_feature_engineering/1_prepare_inputs.py#L715)without an ENSGID, and this is when we lose the sQTLs. This has a downstream impact when we extract the features.

**Observed behaviour**
The QTLs in the intermediary output of the L2G pipeline that processes the credible set dataset is only of type `pqtl` and `eqtl`.

```python
credset_qtl = spark.read.json('gs://genetics-portal-dev-staging/l2g/220712/features/inputs/credsets_qtl.parquet)

credset_qtl.select('type').distinct().show()
+----+
|type|
+----+
|pqtl|
|eqtl|
+----+
```

This processed file is based on the credible set containing the causal variants for GWAS and molecular QTL studies (). This dataset does include sQTLs, therefore we must be doing something wrong in the function that processes this dataset to generate `credset_qtl`.

**Reason**

Specifically we are losing the sQTLs in the line that drops any record without an assigned gene id ([code](https://github.com/opentargets/genetics-l2g-scoring/blob/1751a39336b0d102fea01738b4d61bc979f205ca/1_feature_engineering/1_prepare_inputs.py#L715)). At the moment the process populates the `gene_id` from `phenotype_id` column in 2 ways:
1. Whenever the phenotype is an Ensembl ID, this will be the gene ID.
2. If not, we map from phenotype to gene IDs by using a LUT (`gs://genetics-portal-input/luts/phenotype_id_lut.190629.json')

sQTLs don't fall under any of those scenarios, therefore we end up dropping them.

**Solution**

For sQTLs, Ensemble IDs are present in the `phenotype_id` column, only that later in the string. @xyg123 has suggested adding a third condition to the step that parses the gene_id. When an Ensembl ID is present in the string, extract it.
This way we won't be filtering them out.

**Comment by ireneisdoomed** [comment]
**Note**: This has downstream implications for the extraction of the sQTL related features, therefore we will have to rerun the whole pipeline.

**Comment by xyg123** [comment]
There are two downstream scripts which join tables based on the [phenotype ID](https://github.com/opentargets/genetics-l2g-scoring/blob/1751a39336b0d102fea01738b4d61bc979f205ca/1_feature_engineering/2_make_features/fm_coloc.py#L46-L67), and the [gene ID](https://github.com/opentargets/genetics-l2g-scoring/blob/master/1_feature_engineering/2_make_features/pics_coloc.py#L74-L85).  

If we can add an additional condition [here](https://github.com/opentargets/genetics-l2g-scoring/blob/master/1_feature_engineering/1_prepare_inputs.py#L700-L717
): such that phenotype IDs which contain ENSG can be stripped to just the ENSG ID (maybe split by ":" and grep ENSG?), then the downstream table joins should work fine.

**Comment by JarrodBaker** [comment]
@ireneisdoomed, @xyg123: I don't think that the right approach is to update the filters to accommodate bad data. Where are these sQTL phenotype ID values coming from? If we need to retain the additional information encoded in the string we should have that information in a separate column/structure. Working around the bad data here propagates the problem downstream.

**Comment by ireneisdoomed** [comment]
@JarrodBaker In the new implementation of L2G this parsing is not done anymore because it reads from the v2d-coloc dataset produced in the ETL. So I can imagine that the step of parsing the phenotype ID is happening in the ETL.

However it is true that this parsing could be happening before. @xyg123 knows better how the raw data is coming.

**Comment by ireneisdoomed** [comment]
The immediate issue has been solved, and now sQTLs are processed in L2G.
However, as @JarrodBaker has proposed, the raw data will also be processed in the initial stages so that all phenotype IDs follow the same pattern.

**Comment by buniello** [comment]
Document with specifications for API changes:
https://docs.google.com/document/d/1vkoU7QHTRTCbltxIpmarbXvuU7DyUbjtIjfBPBOHJPc/edit
