### ISSUE TITLE
Data loss in dev environment for credible set overlap table in Study Locus Page 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2682]
Ricardo and Irene reported a loss of data in the section of the study/locus page where the credible set overlap is displayed.
This in an [example of a working page](https://genetics.opentargets.org/study-locus/GCST002221/19_44886339_G_A) in production that currently has no data --- the Manhattan plots that are visible from this page are missing in the dev page.
The offending endpoint is `gwasCredibleSet`. 
Here is the query we use to pull that data:
In [production](https://api.genetics.opentargets.org/graphql/browser?query=query%2520CredibleSetsQuery%2520%257B%250A%2520%2520gwasCredibleSet__GCST000759__19_44886339_G_A%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST000759%2522%252C%2520variantId%253A%2520%252219_44886339_G_A%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__GCST000760__19_44886339_G_A%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST000760%2522%252C%2520variantId%253A%2520%252219_44886339_G_A%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__GCST002221__19_44886339_G_A%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST002221%2522%252C%2520variantId%253A%2520%252219_44886339_G_A%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__GCST005921__19_44893972_G_A%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST005921%2522%252C%2520variantId%253A%2520%252219_44893972_G_A%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__GCST005923__19_44905307_A_T%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST005923%2522%252C%2520variantId%253A%2520%252219_44905307_A_T%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__NEALE2_23119_raw__19_44908822_C_T%253A%2520gwasCredibleSet(studyId%253A%2520%2522NEALE2_23119_raw%2522%252C%2520variantId%253A%2520%252219_44908822_C_T%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__GCST90010233__19_44909976_G_T%253A%2520gwasCredibleSet(studyId%253A%2520%2522GCST90010233%2522%252C%2520variantId%253A%2520%252219_44909976_G_T%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%250A%2520%2520%2520%2520postProb%250A%2520%2520%2520%2520MultisignalMethod%250A%2520%2520%2520%2520logABF%250A%2520%2520%2520%2520is95%250A%2520%2520%2520%2520is99%250A%2520%2520%2520%2520__typename%250A%2520%2520%257D%250A%2520%2520gwasCredibleSet__NEALE2_21002_raw__19_44921921_G_A%253A%2520gwasCredibleSet(studyId%253A%2520%2522NEALE2_21002_raw%2522%252C%2520variantId%253A%2520%252219_44921921_G_A%2522)%2520%257B%250A%2520%2520%2520%2520tagVariant%2520%257B%250A%2520%2520%2520%2520%2520%2520id%250A%2520%2520%2520%2520%2520%2520rsId%250A%2520%2520%2520%2520%2520%2520position%250A%2520%2520%2520%2520%2520%2520__typename%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520pval%250A%2520%2520%2520%2520se%250A%2520%2520%2520%2520beta%25)--> data is there
In [dev](https://api.genetics.dev.opentargets.xyz/graphql/browser?query=query%20CredibleSetsQuery%20%7B%0A%20%20gwasCredibleSet__GCST000759__19_44886339_G_A%3A%20gwasCredibleSet(studyId%3A%20%22GCST000759%22%2C%20variantId%3A%20%2219_44886339_G_A%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__GCST000760__19_44886339_G_A%3A%20gwasCredibleSet(studyId%3A%20%22GCST000760%22%2C%20variantId%3A%20%2219_44886339_G_A%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__GCST002221__19_44886339_G_A%3A%20gwasCredibleSet(studyId%3A%20%22GCST002221%22%2C%20variantId%3A%20%2219_44886339_G_A%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__GCST005921__19_44893972_G_A%3A%20gwasCredibleSet(studyId%3A%20%22GCST005921%22%2C%20variantId%3A%20%2219_44893972_G_A%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__GCST005923__19_44905307_A_T%3A%20gwasCredibleSet(studyId%3A%20%22GCST005923%22%2C%20variantId%3A%20%2219_44905307_A_T%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__NEALE2_23119_raw__19_44908822_C_T%3A%20gwasCredibleSet(studyId%3A%20%22NEALE2_23119_raw%22%2C%20variantId%3A%20%2219_44908822_C_T%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__GCST90010233__19_44909976_G_T%3A%20gwasCredibleSet(studyId%3A%20%22GCST90010233%22%2C%20variantId%3A%20%2219_44909976_G_T%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20beta%0A%20%20%20%20postProb%0A%20%20%20%20MultisignalMethod%0A%20%20%20%20logABF%0A%20%20%20%20is95%0A%20%20%20%20is99%0A%20%20%20%20__typename%0A%20%20%7D%0A%20%20gwasCredibleSet__NEALE2_21002_raw__19_44921921_G_A%3A%20gwasCredibleSet(studyId%3A%20%22NEALE2_21002_raw%22%2C%20variantId%3A%20%2219_44921921_G_A%22)%20%7B%0A%20%20%20%20tagVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20rsId%0A%20%20%20%20%20%20position%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20pval%0A%20%20%20%20se%0A%20%20%20%20b) --> data is absent

-- Jarrod looked into this issue and reported an error in the DB. Unfortunately the API fails silently so doesn't really help indicating that something has gone wrong. He has manually fixed the DB so it will work until the DB is restarted. 
Proper fix requires us to rebuild the infrastructure.

**Comment by JarrodBaker** [comment]
The problem is in Clickhouse where one of the columns has the wrong name. This has been temporarily fixed using the command  `ALTER TABLE ot.v2d_credset RENAME COLUMN "assumeNotNull(logABF)" TO logABF`. 

The permanent fix needs to be in the `v2d_credset.sql` file in `genetics-infrastructure.
