### ISSUE TITLE
Genetics API dropping credset results

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2689]
Of the ~60m rows in the `v2d_credset` data, an estimated ~21m records are not able to be displayed in the front-end due to an API/data bug. 

The `v2d_credset` contains a field `phenotype_id` which sometimes contains an ENSG ID value. The API assumes that this column _always_ contains an ENSG ID and uses it to map to variants. When this field is not an ENSG ID the mapping cannot occur. 

Estimated number of records effected by data type:
```
┌─data_type─┬──count()─┐
│ eqtl      │  4522843 │
│ pqtl      │    53132 │
│ sqtl      │ 20989335 │
└───────────┴──────────┘
```
The `sqtl` records will be resolved in opentargets/platform#2688 . 

As an example, consider:

```
SELECT DISTINCT
    study_id,
    phenotype_id,
    lead_variant_id,
    data_type
FROM v2d_credset
WHERE startsWith(phenotype_id, 'ILMN') AND (lead_variant_id = '4_270769_G_A')
LIMIT 10

Query id: 58dcaedb-2d52-4579-a7ee-07f552e4e32f

┌─study_id─┬─phenotype_id─┬─lead_variant_id─┬─data_type─┐
│ CEDAR    │ ILMN_1719158 │ 4_270769_G_A    │ eqtl      │
└──────────┴──────────────┴─────────────────┴───────────┘

```
Navigating to the web UI (https://genetics.opentargets.org/variant/4_270769_G_A) we can see that there is no listed eQTL data for this study. 

Ticket #2688 will add a column `gene_id` to the database. 

This only solves the issues of `sQTL`s, however all molecular traits should have an ENSG ID to allow these to be displayed on the FE. 

Currently the `credset` data is used as an input to the `coloc` data pipeline. `coloc` uses the `phenotype_id` information to annotate the record with a `gene_id`. This annotation should be moved up-stream to `credset` (and potentially further) so that we can reliably link `credset` data to genes. 

No change should be required on the FE or API. The requested changes in opentargets/platform#2688 should automatically apply to this change.

This issue effects production as well as the development environment.

**Comment by JarrodBaker** [comment]
> we are dropping phenotype_id in favour of gene_id.

@ireneisdoomed we want to keep the `phenotype_id` field, and _add_ the `gene_id` field. We use the `phenotype_id` field in the FE.

**Comment by ireneisdoomed** [comment]
@JarrodBaker File is fixed now. `gene_id` and `phenotype_id` are complete. Thanks ^^

@xyg123 Since the credible set is one of L2G's inputs, this means that we will have to rerun L2G, right?

**Comment by d0choa** [comment]
We will work on this in the new pipeline
