### ISSUE TITLE
Add `pics_95perc_credset` to V2D

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2695]
As a **member of the data team** I want **to have the flag `pics_95perc_credset` included in the V2D dataset produced in the ETL** because **this field is relevant in the L2G pipeline**.

## Background

I am currently working on #2608. In the process of updating the L2G dependencies, the features that we used to extract from the LD table (`gs://genetics-portal-dev-staging/v2d/220401/ld.parquet`) will now be processed from the V2D dataset (`gs://genetics-portal-dev-data/22.05.2/outputs/v2d`).

The LD table has a field called `pics_95perc_credset` that is dropped in the [ETL](https://github.com/opentargets/genetics-pipe/blob/4fdbbfb06d902f83a77418f9e90aedcb384cc025/src/main/scala/ot/geckopipe/index/V2DIndex.scala#L67). I need this field because it is used in several places of [L2G](https://github.com/opentargets/genetics-l2g-scoring/blob/a3ec5da2fc7a98e22d66d02435b1cfb5a6865624/1_feature_engineering/1_prepare_inputs.py#L639).

## Tasks

- [ ] Remove the line of the V2D generation that drops the field (see [line](https://github.com/opentargets/genetics-pipe/blob/4fdbbfb06d902f83a77418f9e90aedcb384cc025/src/main/scala/ot/geckopipe/index/V2DIndex.scala#L67))

## Acceptance tests

How do we know the task is complete? 

1. When I inspect the V2D schema, the boolean flag `pics_95perc_credset` is present

**Comment by JarrodBaker** [comment]
How is this being used in L2G @ireneisdoomed ? The only input I knew about for L2G was V2G?

**Comment by ireneisdoomed** [comment]
It is not used at the moment, but the new implementation will be using all the outputs of the ETL, so we will be using the V2D dataset instead of the LD table. Afaik, V2D's main dependencies are the LD, studies, and top loci tables.
