### ISSUE TITLE
2022 approved drugs without MoA in ChEMBL 31

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2699]
3 approvals in 2022 [Q1](https://www.nature.com/articles/d41573-022-00063-9) and [Q2](https://www.nature.com/articles/d41573-022-00123-0) have no mechanism of action in ChEMBL 31. I include the proposed MoA for ChEMBL's review based on the NRDD articles complemented with information available online (e.g. Drugbank).  

1. Mavacamten - [CHEMBL4297517](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL4297517/)
Suggested MoA - Cardiac myosin inhibitor - MYH7 - [P12883](http://www.uniprot.org/uniprot/P12883)

1. Vutrisiran - [CHEMBL4594511](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL4594511/)
Suggested MoA - Transthyretin-targeted siRNA - TTR mRNA - [ENSG00000118271](https://identifiers.org/ensembl:ENSG00000118271)

1. Mitapivat - [CHEMBL4299940](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL4299940/)
Suggested MoA - Pyruvate kinase activator - PKLR - [P30613](http://www.uniprot.org/uniprot/P30613)

**Comment by ireneisdoomed** [comment]
Thank you for the suggestions.
I've let Paula and Fiona know, I guess these will be available in ChEMBL32.
