### ISSUE TITLE
Create API playground page in GeneticsPortal

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2700]
As OpenTargets, we will like to have the same API page as Platform in Genetics.

Technically, explore the implementation of a shared package component if make sense. Keep in mind that this may affect the implementation of the Platform API page. 

- Parent component: https://github.com/opentargets/ot-ui-apps/tree/main/apps/platform/src/pages/APIPage

** The queries need to be defined by the data/product team.

**Acceptance criteria**:
- The API page URL is `/api`
- The API link in the navbar points to the commented API page url 
- The UI of the page matches the current UI of the platform 

This query can be used as an example for testing purposes:
```
query study {
  studyInfo(studyId:"SAIGE_740_1"){
    studyId
    traitReported
    source
    traitEfos
    pmid
    pubDate
    pubJournal
    pubTitle
    pubAuthor
    hasSumstats
    numAssocLoci
  }
}
```

**Comment by buniello** [comment]
**Example API queries for this page** - to be modelled on [Platform API page](https://platform.opentargets.org/api).

<details>
<summary>Study info query</summary>

```

query study {
  studyInfo(studyId:"SAIGE_740_1"){
    studyId
    traitReported
    source
    traitEfos
    pmid
    pubDate
    pubJournal
    pubTitle
    pubAuthor
    hasSumstats
    numAssocLoci
  }
}

```
</details>

<details>
  <summary>Which studies and lead variants are associated with Jak2?</summary>

```

query Jak2variants {
studiesAndLeadVariantsForGene (geneId:"ENSG00000096968")
  {
      indexVariant {
        id
      }
      study {
        source
        pmid
        traitReported
        pubDate
        pubTitle
        pubAuthor
        hasSumstats
        numAssocLoci
      }
    }
    }

```
</details>
<details>
<summary>Which studies have evidence of colocalisation with molecular QTLs for Jak2?</summary>

```

query Jak2coloc {
colocalisationsForGene(geneId: "ENSG00000169174") {
    leftVariant {
      id
      rsId
      __typename
    }
    study {
      studyId
      traitReported
      pubAuthor
      pubDate
      pmid
      hasSumstats
      __typename
    }
    qtlStudyId
    phenotypeId
    tissue {
      id
      name
      __typename
    }
    h3
    h4
    log2h4h3
    __typename
  }
}

```

</details>
<details>
<summary>Which genes were prioritised by L2G pipeline at this locus from a given study?</summary>

```

query StudyLocus2Gene ($studyId: String!, $variantId: String!, $chromosome: String!, $start: Long!, $end: Long!) {
  studyLocus2GeneTable(studyId: $studyId, variantId: $variantId) {
    rows {
      gene {
        symbol
        id
        __typename
      }
      yProbaModel
      yProbaDistance
      yProbaInteraction
      yProbaMolecularQTL
      yProbaPathogenicity
      hasColoc
      distanceToLocus
      __typename
    }
    __typename
  }
genes(chromosome: $chromosome, start: $start, end: $end) {
    id
    symbol
    tss
    start
    end
    exons
    __typename
  }
}
Query variables:
{
  "studyId": "GCST009240_9",
  "variantId": "1_55052794_A_G",
  "chromosome": "1",
  "start": 54802794,
  "end": 55302794
}

```
</details>

<details>
<summary>Independent associated loci from a given study</summary>

```

query StudyVariants {
  manhattan (studyId: "GCST90002369")  {
    associations {
      variant {
        id
        rsId
        chromosome
        position
        nearestCodingGene {
          id
          symbol
          __typename
        }
        nearestCodingGeneDistance
        __typename
      }
      pval
      credibleSetSize
      ldSetSize
      oddsRatio
      oddsRatioCILower
      oddsRatioCIUpper
      beta
      betaCILower
      betaCIUpper
      direction
      bestGenes {
        score
        gene {
          id
          symbol
          __typename
        }
        __typename
      }
}
  }
}

```
</details>
<details>
  <summary>Variant to gene query</summary>

```

query variant {
  genesForVariant(variantId: "1_55058182_G_A") {
    gene {
      id
      symbol
      __typename
    }
  }
}

```
</details>
<details>
  <summary>Which variants tag (through LD or fine-mapping) a given lead variant?</summary>

```

query Variant {
  tagVariantsAndStudiesForIndexVariant(variantId: "1_55058182_G_A") {
    associations {
      tagVariant {
        id
        rsId
        __typename
      }
      study {
        studyId
        traitReported
        pmid
        pubDate
        pubAuthor
        __typename
      }
      pval
      nTotal
      overallR2
      posteriorProbability
      __typename
    }
    __typename
  }
}

```

</details>


<details>
<summary>Which molecular traits colocalise with this High cholesterol  study (GCST90038690) at a given locus?</summary>

```

query StudyLocus ($studyId: String!, $variantId: String!) {
  qtlColocalisation(studyId: $studyId, variantId: $variantId) {
    indexVariant {
      id
      rsId
      chromosome
      position
      refAllele
      altAllele
      __typename
    }
    gene {
      id
      symbol
      chromosome
      start
      end
      bioType
      __typename
    }
    phenotypeId
    tissue {
      id
      name
      __typename
    }
    qtlStudyName
    beta
    h3
    h4
    log2h4h3
    __typename
  }
}
Query variables
{
  "studyId": "GCST90038690",
  "variantId": "1_55025188_T_C"
}

```
</details>

**Comment by buniello** [comment]
@chinmehta - the PR for the new Genetics API page looks good!
Please find below the final schema for the example queries headers and sub-headers:

Study info query
Find details on a specific study.

Studies and lead variants query
Which studies and lead variants are associated with Jak2?

Colocalisation query
Which studies have evidence of colocalisation with molecular QTLs for Jak2?

Prioritised genes from study locus
Which genes were prioritised by L2G pipeline at this locus from a given study?

Study variants query
Independent loci associated to a given study.

Tag variants query
Which variants tag (through LD or fine-mapping) a given lead variant?
