### ISSUE TITLE
Refactor Genetics FE codebase

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2702]
Currently, the UI codebase of genetics has a mix of inconsistencies and anti-patterns that need to be refactored.

Some of the Key tasks will be:
- Refactor pages to simple components that only refer to sections
- Split big pages queries into atomic section queries
- Separate and identify data transformation logic (name functions correctly -  move to specific utils files)
- Unify components folders (`src/components` `src/ot-ui-components`)

**Comment by d0choa** [comment]
Not immediate
