### ISSUE TITLE
UI components package

### ISSUE THREAD

**Issue by chinmehta** [opentargets/issues#2707]
As a developer I want to move all reusable ui components to common ui package 

## Background

To take the full advantage of mono-repo will be to move reusable components among both application to ui package.

Component List:

- [x] Loading backdrop
- [ ] Link

**Comment by buniello** [comment]
Hi @chinmehta - can this be closed? Please do take a look for me

**Comment by carcruz** [comment]
Closed - Loading backdrop work done, need to create a new issue for other components
