### ISSUE TITLE
Near identical terms for ADHD in the Platform

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2711]
**Describe the bug**
[A user reported in the Community](https://community.opentargets.org/t/why-are-there-near-identical-disease-terms-in-the-platform-adhd-and-how-to-collate-the-evidence/746) that there are two terms in the Platform for attention deficit hyperactivity disorder (ADHD), which differ only by a hyphen. Why are they different terms? 

**Observed behaviour**
There are two terms for ADHD in the Platform: 

- [attention deficit hyperactivity disorder](https://platform.opentargets.org/disease/EFO_0003888) (EFO_0003888) 
- [attention deficity-hyperactivity disorder](https://platform.opentargets.org/disease/MONDO_0007743) (MONDO_0007743)

EFO_0003888 is listed as a child term of MONDO_0007743.

**Expected behaviour**
I would expect these to be the same disease?

**Comment by HelenaCornu** [comment]
I've added it as a comment to the efo ticket, so I will close this issue. Thanks for investigating @DSuveges!

**Comment by ppearson988-prog** [comment]
Autism and ADHD often have similar symptoms, which makes it difficult for adults to understand their differences. Online tests help structure symptoms and take the first step towards self-diagnosis. The TestLibrary platform offers detailed reports on neurodifferencies. However, before buying, it is worth reading the reviews at [https://www.reddit.com/r/icoreviews/comments/1v3a3g3/is_testlibrary_worth_paying_for/](https://www.reddit.com/r/icoreviews/comments/1v3a3g3/is_testlibrary_worth_paying_for/). This will help you understand whether it is worth paying for the results.
