### ISSUE TITLE
Match Codebase Evidence sections ids with the API dataSource providers

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2713]
There is a bug in our Evidence sections ids that they do not match with the API associations API provider. 

An example query to get evidence ids:

```
query q {
  target(ensemblId: "ENSG00000133703"){
    associatedDiseases{
      rows{
        datasourceScores{
          id
        }
        datatypeScores{
          id
        }
      }
    }
  }
}
```

Affected sections: https://github.com/opentargets/ot-ui-apps/tree/main/apps/platform/src/sections/evidence

**Comment by LucaFumis** [comment]
I think this query could also be used:
```query q {
  associationDatasources{
    datatype
    datasource
  }
}```

**Comment by carcruz** [comment]
> I think this query could also be used:
> 
> ```
> query q {
>   associationDatasources{
>     datatype
>     datasource
>   }
> }
> ```

Much better query! Thanks 👍

**Comment by LucaFumis** [comment]
It would be good to review the PR together when you have a moment @carcruz - I suspect there might be additional changes required in order for that to fit with your work on associations.

**Comment by LucaFumis** [comment]
The changes from PR 54 have actually been merged in the AOTF branch `cc-aotf-mvp`.

**Comment by LucaFumis** [comment]
The corresponding PR could probably also be closed.

**Comment by LucaFumis** [comment]
All done and PR https://github.com/opentargets/ot-ui-apps/pull/54 closed - can close issue.
