### ISSUE TITLE
Significance overlaps with right-hand column in the PPP UI

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2724]
**Describe the bug**
The digits of the significance are overlapping with the right-hand column in the OTAR CRISPR widget of the PPP UI. 

**Observed behaviour**
In the Open Targets CRISPR widget of the PPP, for example in [the association between TYMS and psoriasis](https://partner-platform.opentargets.org/evidence/ENSG00000176890/EFO_0000676), the significance is a long string of numbers which overlaps onto the next column.

![Screenshot 2022-09-13 at 13 00 40](https://user-images.githubusercontent.com/73692302/189895502-e16a5ebf-faec-45e6-b7c0-d4482523e1bd.png)

**Expected behaviour**
The significance should be contained within its own column. Consider rounding up or truncating the significance at a certain number of digits after the decimal point. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://partner-platform.opentargets.org/evidence/ENSG00000176890/EFO_0000676'
2. Scroll down to 'Open Targets CRISPR' widget
3. See error

**Comment by buniello** [comment]
I found [another example](https://partner-platform.opentargets.org/evidence/ENSG00000102710/MONDO_0005180)
