### ISSUE TITLE
Removing the "Beta" label from the PPP homepage

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2728]
As a Product Manager, I would like to remove the ["Beta" label from the PPP homepage](https://partner-platform.opentargets.org/) for the upcoming 22.09 release.
This was discussed with @emcdonagh-OT as well. 
We think removing the "beta" sign will increase the perception/confidence the Partners may have in the data we are providing with this second release.

**Comment by JarrodBaker** [comment]
This is obviously a product decision, but I like Beta as a simpler thing to say than PPP which in the context of Open Targets also means public private partnership.

**Comment by d0choa** [comment]
Let's discuss. Coming out of beta implies certain maturity of the project that affects both product and technical aspects. We all need to be comfortable with this decision

**Comment by buniello** [comment]
yes, sounds good - let's discuss all together next week

**Comment by buniello** [comment]
Discussed amongst the team leads and decided to keep the "beta" label until processes are more streamlined --
to be reviewed.
