### ISSUE TITLE
Duplicated target IDs due to incorrect canonical transcript

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2732]
**Describe the bug**
As reported by @ireneisdoomed 46 targets in the 22.09 run have been duplicated. The main identified symptom was evidence being duplicated to later be marked as duplicates.

**Observed behaviour**
After an investigation by @DSuveges, the IDs are duplicated because of the genomic location of their `canonicalTranscript` being wrongly assigned to 2 different chromosomes X and Y.

```
+---------------+---------------------------------------+----------------------+
|id             |canonicalTranscript                    |genomicLocation       |
+---------------+---------------------------------------+----------------------+
|ENSG00000228572|{ENST00000431238, X, 253743, 255091, +}|{X, 253743, 255091, 1}|
|ENSG00000228572|{ENST00000431238, Y, 253743, 255091, +}|{X, 253743, 255091, 1}|
+---------------+---------------------------------------+----------------------+
```

The problem is confirmed to be in the upstream gencode data which we believe it's wrong, and not in the recently implemented logic in #2591 

```
❯ gzcat gencode.gff3.gz | grep ENSG00000228572 | grep -P '\stranscript\s'
chrX	HAVANA	transcript	253743	255091	.	+	.	ID=ENST00000431238.7;Parent=ENSG00000228572.7;gene_id=ENSG00000228572.7;transcript_id=ENST00000431238.7;gene_type=unprocessed_pseudogene;gene_name=ENSG00000228572;transcript_type=unprocessed_pseudogene;transcript_name=ENST00000431238;level=2;transcript_support_level=NA;ont=PGO:0000005;tag=basic,Ensembl_canonical;havana_gene=OTTHUMG00000046372.2;havana_transcript=OTTHUMT00000107057.2
chrY	HAVANA	transcript	253743	255091	.	+	.	ID=ENST00000431238.7_PAR_Y;Parent=ENSG00000228572.7_PAR_Y;gene_id=ENSG00000228572.7;transcript_id=ENST00000431238.7;gene_type=unprocessed_pseudogene;gene_name=ENSG00000228572;transcript_type=unprocessed_pseudogene;transcript_name=ENST00000431238;level=2;transcript_support_level=NA;ont=PGO:0000005;tag=basic,Ensembl_canonical,PAR;havana_gene=OTTHUMG00000046372.2;havana_transcript=OTTHUMT00000107057.2
```

A potential fix would be to ensure that the chromosome in the `genomicLocation` corresponds with the chromosome in the `canonicalTranscript`:

```
.filter(canonicalTranscript.chromosome == genomicLocation.chromosome)
```

Beware as this work might be superseeded by #1947 if we bring the canonical transcripts directly from the Ensembl JSON.

**Expected behaviour**
The `id` field in the target dataset is unique.

**Comment by JarrodBaker** [comment]
There is a PR ready to fix this @d0choa, but it wasn't in time for the latest ETL run. I was going to merge right away, but that will mean that the Platform and PPP of the same release will potentially have different Target indexes. Shall I hold off with the merge?

**Comment by d0choa** [comment]
I would merge. The more correct things we have the better :)
Thanks @JarrodBaker
