### ISSUE TITLE
22.09 Metrics and questions

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2735]
Another release, another set of questions for @ireneisdoomed 💛  

### Release notes:

The main points from @buniello are: 

- New data: we have ingested new data from Open Targets Genetics, ClinVar, the Genomics England PanelApp, as well as new Gene Burden datasets
- Data source update: Probes and Drugs is now the only data source for Chemical Probes
- New example query for API search endpoint

### Questions: 

- We lost about 3,000 diseases — is this because of the duplication? Or is there anything else to report? 
- Where are the new Gene burden datasets coming from? 
- Anything interesting to report in the new data from OTG, ClinVar, or PanelApp?

**Comment by HelenaCornu** [comment]
Probes and drugs new curation hyperlink

**Comment by ireneisdoomed** [comment]
Re P&D: we were only pulling from this resource already, but now it is clearer than we are using their data and we are not referencing primary sources like ChemicalProbes.org. 
We have also updated the data to their latest release 02.2022 https://www.probes-drugs.org/news#45

**Comment by ireneisdoomed** [comment]
Re burden studies: we have curated 2 studies, one for autism (PMID:35982159) and one regarding protective associations to body fat (PMID:35999217). I remember a lot of buzz on Twitter when the autism study was out.
You have more information about each in the ticket https://github.com/opentargets/issues/issues/2701

**Comment by ireneisdoomed** [comment]
Re: decrease in the number of diseases. Yes, this is due to a bug. There are not any major updates from them since June.

**Comment by ireneisdoomed** [comment]
Re: Genomics England. This source has been updated after 2 years. This version includes less panels but of a better quality. The thing to mention here is that we include the panels signed off by the NHS in their genomic testing strategy to identify rare and inherited diseases.

These panels are like a more curated version of what you can find in Panel App and is available in an independent website https://nhsgms-panelapp.genomicsengland.co.uk. We integrate associations from here.
