### ISSUE TITLE
Investigating possible integration of DNA Damage CRISPR data into the PPP

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2743]
The project team from [OTAR2072 _DNA Damage ](http://home.opentargets.org/OTAR2072)(CRISPR data) have submitted results to @sarahyoung3, who is currently following up with them re possible integration into PPP and results interpretation.

This ticket is for Sarah, myself and the Data Team to have a record of this for the next PPP release.

**Comment by DSuveges** [comment]
To prepare disease/target evidence we need the following things:
- [ ] Gene summaries in MAGeCK format.
- [ ] Metadata for the experimental conditions.

Once we have all this in place I can prepare the evidence parsers to ingest the new datasets.

**Comment by buniello** [comment]
The OTAR2072 have submitted the gene summaries to us. 
Discussions are ongoing to enable submission of metadata to finalise integration into PPP 22.11

**Comment by DSuveges** [comment]
As of Nov 16, all pieces of the puzzle are in place. We have double checked some details with the providers, and got  green light. Now the following action items needs to be ticked out:

- [ ] Update study table.
- [ ] Update config file in the PPP parameters repo. Create new release.
- [ ] Run parsers to generate new evidence
- [ ] Upload files to google bucket.

**Comment by DSuveges** [comment]
- The number of ot_crispr evidence went from 8574 to 8600. 
- Evidence file now located here: `gs://ot-team/dsuveges/partner_preview/ot_crispr/ot_crispr_2022-11-18.json.gz`
