### ISSUE TITLE
OT Genetics v8 — metrics and examples

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2744]
I have some questions regarding the upcoming release — 

### Priority

- Is there an interesting sQTL that I could feature in the blog post? 
- Can you give me some examples of new studies with summary statistics from GWAS Catalog that I can show?
- We have integrated the data from FinnGen R6, correct? What does that add to Genetics?

### General stats update

We provided [some general stats on OTG with v5](https://blog.opentargets.org/open-targets-genetics-version-5/). Would it be possible to get the latest numbers for this?

- `#` of genes
- `#` of variants
- `#` EFO IDs, across `#` therapeutic areas
- `#` of studies, of which `#` have fine-mapping
- `#` independent disease/trait-associated loci
- `#` of trait-trait colocalisation tests
- `#` unique genes with L2G score > 0.8

**Comment by xyg123** [comment]
(Will update as I go)

# of genes
# of variants

57,244 studies , of which 8,894 has full summary stats / finemapping.
6,344 trait EFOs, across 24? theraputic areas.

# independent disease/trait-associated loci

3,842,564 trait/disease - molecular trait colocalisations.
3,912 Unique genes with L2G score >0.8

**Comment by HelenaCornu** [comment]
Thanks both!
