### ISSUE TITLE
46 allosomal target IDs appear twice in the 22.09 data

### ISSUE THREAD

**Issue by fedde-s** [opentargets/issues#2745]
**Describe the bug**
In [the target data for release 22.09 of the platform](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.09/output/etl/json/targets/), 46 ENSG gene IDs appear twice: once with a **canonicalTranscript** field on chromosome X and once on Y or vice versa. It looks like these are the genes that map to [pseudoautosomal regions](https://en.wikipedia.org/wiki/Pseudoautosomal_region) and the chromosome-Y coordinates are the gene's corresponding PAR. However, when these JSON files are loaded into Elasticsearch, only one of the two targets with the same ID ends up in the index. As of 22.09.4, the GraphQL API never accesses the Elasticsearch field that differs between the two.

<details>
<summary>List of 46 IDs each starting with <code>ENSG</code></summary>

```
ENSG00000002586
ENSG00000124333
ENSG00000124334
ENSG00000167393
ENSG00000169084
ENSG00000169093
ENSG00000169100
ENSG00000178605
ENSG00000182162
ENSG00000182378
ENSG00000182484
ENSG00000185203
ENSG00000185291
ENSG00000185960
ENSG00000196433
ENSG00000197976
ENSG00000198223
ENSG00000205755
ENSG00000214717
ENSG00000223274
ENSG00000223484
ENSG00000223511
ENSG00000223571
ENSG00000223773
ENSG00000225661
ENSG00000226179
ENSG00000227159
ENSG00000228410
ENSG00000228572
ENSG00000229232
ENSG00000230542
ENSG00000234622
ENSG00000234958
ENSG00000236017
ENSG00000236871
ENSG00000237040
ENSG00000237531
ENSG00000237801
ENSG00000265658
ENSG00000270726
ENSG00000275287
ENSG00000277120
ENSG00000280767
ENSG00000281849
ENSG00000289007
ENSG00000289620
```

</details>

**Observed behaviour**
When loading the JSON files into Elasticsearch as per [`platform-output-support`](https://github.com/opentargets/platform-output-support/blob/35744abdce0b843d5844af0e1324de2f4051e91b/terraform_create_images/modules/posvm/scripts/load_all_data.sh#L12), the `target` index ends up with 46 fewer docs then there are JSON lines in `output/etl/json/targets/*.json`. The docs missing from the index have the same **id** field as another doc (the very next or previous line in the JSON file, it seems), but differ in subfields of the **canonicalTranscript** field. As of 22.09.4, this field name does not occur in the platform-api code.

**Expected behaviour**
I expected one doc to end up in Elasticsearch for each JSON line in [output/etl/json/targets/](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.09/output/etl/json/targets/).

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the target data from the FTP server, or at least [one of the files containing the problematic genes](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.09/output/etl/json/targets/part-00032-59282e94-06db-4882-8fe8-1759dd6022d0-c000.json) .
2. Run `jq -r .id *.json | sort | uniq -d`.
3. See a list of **id** values that occur on more than one JSON line.
4. Confirm that [output_etl_struct](https://github.com/opentargets/platform-output-support/blob/35744abdce0b843d5844af0e1324de2f4051e91b/terraform_create_images/modules/posvm/scripts/output_etl_struct.jsonl#L18) specifies the **id** field to be [used as the ID of each document](https://github.com/opentargets/platform-output-support/blob/35744abdce0b843d5844af0e1324de2f4051e91b/terraform_create_images/modules/posvm/scripts/load_json_esbulk.sh#L36) within the Elasticsearch index.

**Additional context**
None that I can think of.

**Comment by JarrodBaker** [comment]
The issue has been resolved and will be fixed in the next release. See #2732

**Comment by fedde-s** [comment]
Sorry for overlooking that issue report and thanks for pointing it out!

**Comment by JarrodBaker** [comment]
Better to double up and guarantee it's resolved!
