### ISSUE TITLE
Incorrect Score button in Interactions widget

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2747]
**Describe the bug**
There is a `Score` button in the interactions widget (String tab) that links to the associations documentation - so nothing to do with the molecular interactions data.

**Observed behaviour**
![image](https://user-images.githubusercontent.com/45119610/195378536-c84bbe15-f217-4ac5-b73f-2a84bef22614.png)

The String data is displayed using the same heatmap component that we use for associations. In it there is a link to the documentation regarding the associations score. We should remove it from the interactions widget.

**Comment by d0choa** [comment]
The right URL would be:
https://string-db.org/cgi/info

**Comment by LucaFumis** [comment]
I've updated the url for the "Score" link to https://string-db.org/cgi/info but can change the label (i.e. "score") or remove it altogether.
