### ISSUE TITLE
UI global search reimplementation

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#2765]
This ticket describes the scope of the work to improve the global search component. The idea is to create a new shareable package between the Platform and Genetics. 

Examples of inspiration:
 - [MUI docs](https://mui.com/)
 - [Bootstrap docs](https://getbootstrap.com/docs/5.2/getting-started/introduction/)

Acceptance criteria:
- The component should be able to manage the two different API endpoints and responses (Genetics - Platform). Consider to expose UI primitives and to create a Search component inside each app.
- The component should redirect on click to the option the same as is done in the current implementation.
- The component should show be able to display the same indicators as in the current implementation:
	- Genetics:
		![Screenshot 2022-10-21 at 10.39.18.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/e0efd850-071b-4629-bfd6-dac2a43c97a1)
	- Platform:
		![Screenshot 2022-10-21 at 10.46.16.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/6143f94a-789d-41dc-890f-120758665c8f)
- The component should be flexible enough to be used either in the Navbar (as a modal) or in the HomePage

Mockups (by @chinmehta):
![Search_UI_1.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/1bea5c49-eb76-470d-86bb-491740c459da)
![Search_UI_2.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/0d7828c6-d85a-4574-b10c-67ca4c3056fb)
![Search_UI_3.png](https://images.zenhubusercontent.com/603fafbd7ac89a71a94c50f6/3005a871-f1e9-4ee0-8576-d71adeaebcca)

**Comment by buniello** [comment]
Worked with Chintan on second iteration of new search functionality for both Genetics and Platform - it is looking really good and polished.
The priority now is to discuss how to implement a "search results" functionality for both Platform and Genetics, as discussed with @chinmehta

**Comment by chinmehta** [comment]
Links to preview: 
1. Genetics: https://deploy-preview-85--ot-genetics.netlify.app/
2. Platform: https://deploy-preview-85--ot-platform.netlify.app/

**Comment by buniello** [comment]
@HelenaCornu - when you have some time - could you please test the new searches from link shared above and let us know what you think? I think your feedback is important!

**Comment by HelenaCornu** [comment]
Thanks for sharing — this is **SO COOL**. I particularly love that you can ⌘K to search and that you can see your recent pages. 

Some things I noticed:

### Genetics

- For studies with no associated loci, results in the search bar show "0" rather than "0 associated loci" or nothing. Users will understand in context but I was initially confused. 

### Platform

- Something is bothering me about the way the results appear when you type something in the search bar; I think it looks crowded. It could be the spacing or the difference in how the sections (target, disease...) are delineated compared to the current implementation. I like the way that the full name of the protein is in a lower case in the current implementation, I think it looks cleaner.
- In the current implementation, I like that there is a symbol to indicate which entity the top hit is, because it's a quick way of checking that it's the result you're searching for.

**Comment by buniello** [comment]
Feedback from @xyg123 on the **Genetics** search:

- Seems everything is there! Very nice to include study ID, each entry takes up a lot more space than before.
- Header text for ‘journal’ and ‘author’ can be removed (redundant). 
- Number of loci should be bold (as per production version), not n study

**Comment by LucaFumis** [comment]
Collecting below feedback from offline conversations.

- Text looks pretty balanced and clear - I guess previous feedback has been addressed
- Love the cmd + K option to enter the search.
- Also like the lightbox effect: search results panel stands out a lot
- Just as a note, we're showing the gene/disease ids: I'd personally imagine that's handy/useful. If I remember correctly in early iterations it was decided to not show those to the user.

On the homepage

- search results panel sort of “blends” with the white background, which I find confusing. 
- Also the results, starting from the middle of the page, run off screen a bit (although it does the same in production). Currently Google is also using that approach, with the results pop up panel just bleeding off screen. But with a small light shadow/border around it).
- Was also thinking of trying the default page search component also on the homepage - i.e. search results panel is positioned near the top of the page with the lightbox behind it. @chinmehta has tried implementing a quick test, but it doesn't quite work as is, without any additional tweaking.

**Comment by ireneisdoomed** [comment]
I love it, sharing some thoughts:
- It is less clear now which are the searchable entities - I agree that the message is clearer now with “Search…“, but when a user lands here for the first time, the fact that we inform about what types of search you can do is very useful to understand the product.
- “Clear all” button in history would be nice
- Top Hit doesn’t stand out from the rest of the results. This is my main concern - I don’t know if highlighting it in a diff colour is the way, but I find it very easy to miss what is the most exact return.

**Comment by buniello** [comment]
HI @carcruz @chinmehta I have a couple of comments/feedback on the search feature before we release to the public. I hope these are feasible fixes.

- [ ] The "clear all" tab does not work/respond (priority)
![Screenshot 2023-02-16 at 14.53.00.png](https://images.zenhubusercontent.com/5ef1da283f096f8317c9ca44/9b64ba0a-c52d-423a-8476-1d1bc0f92117)

- [ ] The command+K initiated from from keyboard does not work (only from homepage - it works from all other pages) - lower priority

**Comment by carcruz** [comment]
I think another thing to add, maybe for a soft release of the UI, is the primary colors on PPP, they should be green.

<img width="1625" alt="Screenshot 2023-02-16 at 8 36 49 PM" src="https://user-images.githubusercontent.com/2972633/219481507-bb817c0d-a67a-4098-be38-398859bbaa5f.png">

**Comment by carcruz** [comment]
I think another thing to add, maybe for a soft release of the UI, is the primary colors on PPP, they should be green.

<img width="1623" alt="Screenshot 2023-02-16 at 8 39 07 PM" src="https://user-images.githubusercontent.com/2972633/219481745-ea2d5688-ed98-48b2-a4cb-de08d92a43a9.png">

**Comment by carcruz** [comment]
https://github.com/opentargets/ot-ui-apps/pull/96 addressed: 
- "clear all" button
- styles on PPP 

For some extra styling fixes and the cmd+k from homePage I'll create a new issue
