### ISSUE TITLE
Adding a tooltip to the `BLISS score` header in the ENCORE widget

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2769]
As a PPP user/demo presenter, I would like to have an intuitive understanding of what the `BLISS score` column means without having to click back to the documentation page.

Me and @sarahyoung3 discussed the option of adding a tooltip on the header with text: `We used the Bliss independence model to define synergy between gRNA pairs`.

The tooltip was also suggested as helpful addition to the data table by the ENCORE team during the demo.

**Comment by LucaFumis** [comment]
Tooltip added - will share preview link separately

**Comment by buniello** [comment]
Thank you @LucaFumis, it looks good!
