### ISSUE TITLE
Feedback on ENCORE evidence on PP Platform

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2774]
We get the following comments on the encore data:

1. The Bliss scores that have positive values are annotated as synergistic and the negative ones as antagonistic. In the dataset we generate it is the opposite way. I remember talking about this and at some point I think in the platform the values are multiplied by -1 I guess. 
2. Can you make sure that the sign of the bliss scores are correct with respect to their status (antagonistic/synergistic)
3. Also, some of the values seem a little bit different from what I have. Did you use the Scaled Exact version?

**Comment by DSuveges** [comment]
Datasets used by the parser:
```json
{
    "dataset": "COLO1",
    "diseaseFromSourceMappedId": "EFO_1001951",
    "diseaseFromSource": "colorectal carcinoma",
    "logFoldChangeFile": "ANALYSIS/GENERAL_STATS/ENCORE_COLO1_ANCHOR2/SCALED_EXACT/FINAL_SAMPLES/AVERAGE_CELL_LINE/gene.stats.annotated.txt",
    "geminiFile": "ANALYSIS/GEMINI_STATS/ENCORE_COLO1_GUIDE2/EXACT_SCALED/STRONG_ALL.annotated.txt",
    "blissFile": "ANALYSIS/BLISS_STATS/ENCORE_COLO1/EXACT_SCALED/COLO1_EXACT_SCALED_4_ZSCORE_annotated.txt",
    "skipStudy": false,
    "warningMessage": null
},
```

**Comment by buniello** [comment]
Notes from the ENCORE meeting [here](https://docs.google.com/document/d/1GXNJrlstAczLLF7TrgmnxX7z3y6ULsL6RJ57vJIpDCs/edit#), with reference to Daniel's comments above.

**Comment by DSuveges** [comment]
Logic generating genetic interaction fields. Example gene pair: [TYMS ~CHEK1](https://partner-platform.opentargets.org/evidence/ENSG00000176890/EFO_1001951) measured in cell line: SIDM00192. 

The evidence shows this:
```json
  "geneticInteractionPValue": 0.008395962,
  "geneticInteractionScore": -2.6357174019235305,
  "geneInteractionType": "antagonistic",
```
The corresponding raw bliss data looks like this:
```
+----------+-----------+------------+------------+
|        id|     zscore|cellLineName|experimentId|
+----------+-----------+------------+------------+
|TYMS~CHEK1| -1.7645358|   SIDM00193|    CPID1065|
|TYMS~CHEK1|-0.34784037|   SIDM00193|    CPID1068|
|TYMS~CHEK1| -2.4528203|   SIDM00193|    CPID1071|
+----------+-----------+------------+------------+
 ```
Then we average the replicates z-score by sum(z)/sqrt(n), which gives:
```
+----------+------------+------------------+----------------+-----------------------+
|        id|cellLineName|         sumzscore|experiment_count|geneticInteractionScore|
+----------+------------+------------------+----------------+-----------------------+
|TYMS~CHEK1|   SIDM00193|-4.565196454524994|               3|    -2.6357174019235305|
+----------+------------+------------------+----------------+-----------------------+
 ```
Then calculating p-value from z-score gives the following fields that are shown on the website:
```
+----------+------------+-----------------+------------------------+-----------------------+
|        id|cellLineName|statisticalMethod|geneticInteractionPValue|geneticInteractionScore|
+----------+------------+-----------------+------------------------+-----------------------+
|TYMS~CHEK1|   SIDM00193|            bliss|             0.008395962|    -2.6357174019235305|
+----------+------------+-----------------+------------------------+-----------------------+
```

**Comment by DSuveges** [comment]
We got back to the encore team with the above observation. Asked for feedback on the approach, but got no reply. I assume all looked good.
