### ISSUE TITLE
Missing JSON files from the platform data download table 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2780]
**Describe the bug**
The [platform download page](https://platform.opentargets.org/downloads) should host both parquet and JSON formatted files; however, the current version of the page lists parquet files ONLY.

**Expected behaviour**
The [platform download page](https://platform.opentargets.org/downloads) should host both parquet and JSON formatted files.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '(https://platform.opentargets.org/downloads)'
2. See Format(s) column in data table
5. See bug - JSON files are missing

**Comment by LucaFumis** [comment]
It appears as the content in https://platform.opentargets.org/data/downloads.json in incomplete and contains half the rows (only those for "parquet")

**Comment by LucaFumis** [comment]
The version of `downloads.json` in GitHub is correct - need to understand why the version deployed with the release appears to be different

**Comment by LucaFumis** [comment]
Chatting to @carcruz it seems that BE handles the `public/data/downloads.json` file: is that the case @mbdebian ? We only tag the frontend code for release, so not sure where/how that is updated.

**Comment by mbdebian** [comment]
I'll have a look at it

**Comment by d0choa** [comment]
Looks like a pipeline thing rather than a deployment thing:
```
❯ gsutil ls gs://open-targets-data-releases/22.09/output/etl/json/metadata
CommandException: One or more URLs matched no objects.

❯ gsutil ls gs://open-targets-data-releases/22.06/output/etl/json/metadata
gs://open-targets-data-releases/22.06/output/etl/json/metadata/AOTFClickhouse/
gs://open-targets-data-releases/22.06/output/etl/json/metadata/AOTFElasticsearch/
gs://open-targets-data-releases/22.06/output/etl/json/metadata/adverseDrugReactions/
gs://open-targets-data-releases/22.06/output/etl/json/metadata/adverseTargetReactions/
...
```

**Comment by buniello** [comment]
@mbdebian @JarrodBaker are there any updates in this?

**Comment by mbdebian** [comment]
> @mbdebian @JarrodBaker are there any updates in this?

I haven't looked into this yet

**Comment by mbdebian** [comment]
> Chatting to @carcruz it seems that BE handles the `public/data/downloads.json` file: is that the case @mbdebian ? We only tag the frontend code for release, so not sure where/how that is updated.

I have checked the deployment code for the web application, and the _download.json_ file is part of the platform bundle that we download from GitHub for provisioning.

Open Targets Platform is running on _v0.2.5_ front end release, as _v0.2.8_ was requested to be deployed for PPP.
Could that☝🏻 be the problem?

**Comment by mbdebian** [comment]
I'll check POS to find out whether it could be doing anything with that file

**Comment by mbdebian** [comment]
Yep, POS is the one putting together that file this way:
```
terraform_create_images/modules/posvm/scripts/load_data.sh:34:echo "---> Create the downloads information file object, metadata collection from 'gs://${GS_ETL_DATASET}/etl/*/metadata/**/*.json' to 'gs://${GS_DIRECT_FILES}/webapp/downloads.json'"
terraform_create_images/modules/posvm/scripts/load_data.sh:35:gsutil cat 'gs://${GS_ETL_DATASET}/etl/*/metadata/**/*.json' > /tmp/data/webapp/downloads.json
terraform_create_images/modules/posvm/scripts/load_data.sh:36:gsutil cp /tmp/data/webapp/downloads.json gs://${GS_DIRECT_FILES}/webapp/downloads.json
```
So @d0choa is right.

**Comment by mbdebian** [comment]
Having said that, there actually is metadata in the ETL output:
```bash
gsutil ls -alh gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/                                                                                    ✔  10061  13:32:37
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/AOTFClickhouse/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/AOTFElasticsearch/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/adverseDrugReactions/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/adverseTargetReactions/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByDatasourceDirect/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByDatasourceIndirect/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByDatatypeDirect/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByDatatypeIndirect/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByOverallDirect/
                                 gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/associationByOverallIndirect/
...
```

An example of the content for
> gs://open-targets-data-releases/22.09/output/etl/parquet/metadata/AOTFClickhouse/part-00000-c779b7c3-441c-4ec7-8f33-0be72b421aa5-c000.json

```json
{"id":"AOTFClickhouse","resource":{"format":"parquet","path":"/AOTFClickhouse","generateMetadata":true},"serialisedSchema":"{\"type\":\"struct\",\"fields\":[{\"name\":\"row_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"disease_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"target_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"datasource_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"datatype_id\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"row_score\",\"type\":\"double\",\"nullable\":true,\"metadata\":{}},{\"name\":\"disease_data\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"target_data\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}]}","columns":["row_id","disease_id","target_id","datasource_id","datatype_id","row_score","disease_data","target_data"],"timeStamp":"2022-09-26T17:52:58.080Z"}
```

**Comment by mbdebian** [comment]
My last comment basically confirms both @LucaFumis and @d0choa findings 😅

**Comment by buniello** [comment]
Discussed in the office on 9/11/22 -@jarrod is trying to work on a fix linked to the ETL for this coming release.

**Comment by t0masoni** [comment]
I still see this problem, in the downloads page I find only parquet data format.
How can I download in json format?
