### ISSUE TITLE
Gene2Phenotype evidence widget has missing literature data

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/issues#2781]
**Describe the bug**
Gene2Phenotype evidence widget has missing literature data, showing as N/A

**Observed behaviour**
Navigating to any evidence page with Gene2Phenotype data, the literature column it the G2P widget always shows no data.

**Expected behaviour**
I would expecting to see publications displayed as appropriate (in a literature "drawer" component).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/evidence/ENSG00000157764/MONDO_0015280
2. Scroll down to Gene2Phenotype widget
3. See literature column showing N/A

**Additional context**
Data is available - appears to be a front end issue.

**Comment by buniello** [comment]
Reviewed PR -- looks good, data available for literature field.
