### ISSUE TITLE
studiesAndLeadVariantsForGene endpoint returns empty response

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2791]
**Description of the bug**

Our users [reported on the community portal](https://community.opentargets.org/t/studiesandleadvariantsforgene-query-not-working/833) that the `studiesAndLeadVariantsForGene` GraphQL endpoint in the genetics portal returns no data. Whatever gene ids we are requesting in the following [graphQL](https://api.genetics.opentargets.org/graphql/browser?query=query%20Jak2variants%20%7B%0A%20%20studiesAndLeadVariantsForGene(geneId%3A%20%22ENSG00000096968%22)%20%7B%0A%20%20%20%20indexVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20study%20%7B%0A%20%20%20%20%20%20source%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20traitReported%0A%20%20%20%20%20%20pubDate%0A%20%20%20%20%20%20pubTitle%0A%20%20%20%20%20%20pubAuthor%0A%20%20%20%20%20%20hasSumstats%0A%20%20%20%20%20%20numAssocLoci%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=Jak2variants) request, the response is always empty. 

Returned data:
```json
{
  "data": {
    "studiesAndLeadVariantsForGene": []
  }
}
```

Interestingly the same request returns correct dataset in the [dev instance](https://api.genetics.dev.opentargets.xyz/graphql/browser?query=query%20Jak2variants%20%7B%0A%20%20studiesAndLeadVariantsForGene(geneId%3A%20%22ENSG00000096968%22)%20%7B%0A%20%20%20%20indexVariant%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20study%20%7B%0A%20%20%20%20%20%20source%0A%20%20%20%20%20%20pmid%0A%20%20%20%20%20%20traitReported%0A%20%20%20%20%20%20pubDate%0A%20%20%20%20%20%20pubTitle%0A%20%20%20%20%20%20pubAuthor%0A%20%20%20%20%20%20hasSumstats%0A%20%20%20%20%20%20numAssocLoci%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=Jak2variants).

**Expected behaviour**
The query should return something like this:
```json
{
  "data": {
    "studiesAndLeadVariantsForGene": [
      {
        "indexVariant": {
          "id": "9_2622134_C_T"
        },
        "study": {
          "source": "FINNGEN",
          "pmid": null,
          "traitReported": "\"Type 2 diabetes, definitions combined\"",
          "pubDate": "2022-01-24",
          "pubTitle": null,
          "pubAuthor": "FINNGEN_R6",
          "hasSumstats": true,
          "numAssocLoci": 79
        }
      },
      {
        "indexVariant": {
          "id": "9_2622278_G_A"
        },
        "study": {
          "source": "GCST",
          "pmid": "PMID:27863252",
          "traitReported": "Platelet count",
          "pubDate": "2016-11-17",
          "pubTitle": "The Allelic Landscape of Human Blood Cell Trait Variation and Links to Common Complex Disease.",
          "pubAuthor": "Astle WJ",
          "hasSumstats": true,
          "numAssocLoci": 325
        }
      },
```

**Comment by DSuveges** [comment]
As [reported by](https://community.opentargets.org/t/issue-with-studiesforgene-graphql-query/834) a user, another query shows a similar behaviour:
```
query study {
  studiesForGene(geneId:"ENSG00000169174") {
    study {
      source
      pmid
      pubDate
      pubJournal
      pubTitle
      pubAuthor
      hasSumstats
      nInitial
      nReplication
      nCases
      traitCategory
      numAssocLoci
    }
  }
  }
```

Most likely the problem has a common underlying issue. Once this issue is fixed, both endpoint will work just fine.

**Comment by JarrodBaker** [comment]
It isn't really clear what is going on. Each CH instance is given it's own complete copy of the database on start-up. The instances running in the US and in our development environments return the expected results. The instance in the EU contains errors. 

They are all using the same disk image `ch-disk-jldgdj65-image-v2` to start the database. When I ssh into the EU node and go into the database I can see:
```
SELECT
    name,
    code,
    value,
    last_error_message
FROM system.errors
WHERE value > 0
ORDER BY code ASC

Query id: b15dc9a7-c090-4cff-9a49-5a6aa19c45cc

┌─name──────────────┬─code─┬─value─┬─last_error_message──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CANNOT_OPEN_FILE  │   76 │     1 │ Cannot open certificate file: /etc/clickhouse-server/server.crt.                                                                                                │
│ FILE_DOESNT_EXIST │  107 │     1 │ Cannot open file /var/lib/clickhouse/store/e9d/e9d00a82-974a-4cbb-b378-ba608f972522/all_4951_5496_4/lead_pos.bin, errno: 2, strerror: No such file or directory │
└───────────────────┴──────┴───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
The `FILE_DOESNT_EXIST` error is what is causing the problem in the API.

Compared with the US:
```
SELECT
    name,
    code,
    value,
    last_error_message
FROM system.errors
WHERE value > 0
ORDER BY code ASC

Query id: ec88c3c2-f56b-426b-a389-70868ac584b4

┌─name─────────────┬─code─┬─value─┬─last_error_message───────────────────────────────────────────────┐
│ CANNOT_OPEN_FILE │   76 │     1 │ Cannot open certificate file: /etc/clickhouse-server/server.crt. │
└──────────────────┴──────┴───────┴──────────────────────────────────────────────────────────────────┘
```
When the instance starts up it mounts the disk and then starts Clickhouse in a Docker container. My best guess is that while it is mounting the data something goes wrong. I just can't see why it would effect some instances and not others.

**Comment by DSuveges** [comment]
If the data got somehow corrupted, wouldn't we expect missing data/tables from the UI? However `https://genetics.opentargets.org/gene/ENSG00000169174` and `https://genetics.dev.opentargets.xyz/gene/ENSG00000169174` show the same table with same values? 

(assuming `studiesForGene` and `studiesAndLeadVariantsForGene` fills tables on the gene page)

**Comment by JarrodBaker** [comment]
The assumption is wrong (as far as I can tell) :smile: .

That page appears to be using the `geneInfo` and `colocalisationsForGene` endpoints.

**Comment by DSuveges** [comment]
As @d0choa pointed out these endpoints are not used anywhere in the UI, they are only listed in the API documentation as examples.

**Comment by JarrodBaker** [comment]
I'm glad we spent the day fixing that then...somewhat deflating.

**Comment by d0choa** [comment]
We still have an issue in the API, but we will ignore it from now as it's not used in production
