### ISSUE TITLE
Curate associations with Parkinson from burden analysis

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2805]
Article: https://www.medrxiv.org/content/10.1101/2022.11.08.22280168v1.full.pdf

Largest genome-wide analysis of rare variation in PD.
- Whole genome and exome data
- 7,184 PD cases, 6,701 proxy-cases (defined as having a parent or sibling with PD), and 51,650 neurologically healthy controls
- Multiple cohorts, all **European**: Accelerating Medicines Partnership Parkinson's disease (AMP-PD) initiative, the National Institutes of Health, the UK Biobank, and Genentech
- Variant inclusion criteria:
	- missense variants as defined by SnpEff
	- moderate or high impact variants as defined by SnpEff/SnpSift
	- high confidence LoF variants as defined by LOFTEE
	- variants with either a CADD PHRED score > 20 or high confidence LoF variants as defined by LOFTEE
- 2 collapsing algorithms:
	- SKAT-O (Sequence Kernel Association Test – Optimal)
		- Has proven to detect genes more reliably than a burden or SKAT test
		- aggregates the associations between variants and the phenotype of interest while allowing for SNP-SNP interactions
	- Combined and Multivariate Collapsing (CMC) Wald
		- collapses and combines all rare variants and then performs a Wald test, where only an alternative model is fit and the effect size is estimated

They have performed a number of collapsing tests on the individual datasets and then a **meta analysis** of the combined results (Fisher's test). I have curated the results of the meta analysis for simplicity purposes. However, we could break down these associations per cohort.

This has however a caveat: we lose associations that have shown significancy on a specific cohort but not on the meta analysis. There are not many of these, OR1G1 (Table 3) is an example.

**I haven't found on the supplementary tables information about the direction of the effect.**

**Comment by ireneisdoomed** [comment]
These are the results of curating Table 2 and 3. The evidence is broken down by the type of filters applied to select the qualifying variants.

![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/e7e5aac6-1833-4fbe-982a-41abd176b915)

This evidence will be added to the curation table in https://github.com/opentargets/curation/blob/master/gene_burden/curated_evidence.tsv

**Comment by ireneisdoomed** [comment]
As @d0choa commented, we do not want to neglect to include the new associations that the authors report in the abstract. 3 of the novel associations did not show statistical significance in the meta-analysis, therefore I am reporting them independently only considering the cohorts they are based on.

![image](https://user-images.githubusercontent.com/45119610/201957175-fb1adefd-3dfc-4947-be53-29e22c7ae756.png)
(Blue: meta analysis hits / orange: independent analysis hits)

One relevant note about the associations for TUBA1B and OR1G1 is that the whole comparison is based using proxy individuals, not actual cases. These are people with a parent or sibling with Parkinson. This is not captured in the evidence because we don't model the proxies.

**Comment by ireneisdoomed** [comment]
New evidence file with the new associations as proposed above: `gs://otar000-evidence_input/GeneBurden/json/gene_burden-2022-11-15.json.gz`
(+ the modification that the projectId has been set to `AMP-PD`)

This evidence illustrates the association for LRRK2
```
 ancestry                  | EUR
 ancestryId                | HANCESTRO_0005
 datasourceId              | gene_burden
 datatypeId                | genetic_association
 diseaseFromSource         | parkinson disease
 diseaseFromSourceMappedId | MONDO_0005180
 literature                | [PPR569774]
 pValueExponent            | -7
 projectId                 | AMP-PD
 statisticalMethod         | meta-analysis
 statisticalMethodOverview | Meta-analysis of burden tests carried out with variants predicted to be deleterious or LOF and with a MAF smaller than 1%
 studyCases                | 7184
 studySampleSize           | 58834
 targetFromSourceId        | ENSG00000188906
```

**Comment by buniello** [comment]
Hi @LucaFumis, as discussed also in the 22.11 slack channel today, there is an issue with these new gene burden data - there is a `null (projectId)` displayed for the `cohort/project` field -- [see example](https://platform.dev.opentargets.xyz/evidence/ENSG00000179913/MONDO_0005180).
![Screenshot 2022-11-21 at 10 40 41](https://user-images.githubusercontent.com/30833755/203071346-9f3665ee-6ee1-4e45-82e9-ecfb24735922.png)

We would like to have just `AMP-PD` displayed in the FE, no `null` and no brackets. Could you please take a look for us?
