### ISSUE TITLE
Missing one2one orthologue in comparative genomics widget

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2809]
One of the key objects in the OT ecosystem is the `target` object, representing a gene. There are ~60k in the Platform at present. 

One of the fields they include is `homologues` which tells us which other species also have this target in their genome. We get this information from [Ensembl](https://www.ensembl.org/index.html) which is another EMBL-EBI project. We use their raw data and develop a 'view' to meet the requirements of our users. 

This is a sample of the final object (truncated to only show `id` and `homologues` fields):
```
{
  "id": "ENSG00000008311",
  "homologues": [
    {
      "speciesId": "9598",
      "speciesName": "Chimpanzee",
      "homologyType": "ortholog_one2one",
      "targetGeneId": "ENSPTRG00000023614",
      "isHighConfidence": "1",
      "targetGeneSymbol": "AASS",
      "queryPercentageIdentity": 99.676,
      "targetPercentageIdentity": 99.676,
      "priority": 1
    },
    ...
    {
      "speciesId": "6239",
      "speciesName": "Caenorhabditis elegans (PRJNA13758)",
      "homologyType": "ortholog_one2one",
      "targetGeneId": "WBGene00019819",
      "isHighConfidence": "1",
      "targetGeneSymbol": "aass-1",
      "queryPercentageIdentity": 46.4363,
      "targetPercentageIdentity": 45.1681,
      "priority": 12
    }
  ]
}
```
All of these entries come from files ([protein](https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/homo_sapiens/Compara.108.protein_default.homologies.tsv.gz), [ncrna](https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/homo_sapiens/Compara.108.ncrna_default.homologies.tsv.gz)) provided by Ensembl.

We had assumed that these files contained all of the homologues for homo_sapiens, but this isn't the case. Consider two species A and B. Each species has its own homologies dataset stored in TSV format. The homologies between A and B _are only included in one of the two TSV files_ in order to reduce data redundancy. To construct a complete list of homologues between A and B we need to process both files and extract the relevant entries.

As far as we know, the relationship will be displayed in the genome where the internal gene_stable_id is higher. One of the records we are missing is a mouse homologue with a [record](https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/mus_musculus/Compara.108.protein_default.homologies.tsv.gz):

```
gene_stable_id                ENSMUSG00000003420
protein_stable_id             ENSMUSP00000147496
species                             mus_musculus
identity                                 66.1247
homology_type                   ortholog_one2one
homology_gene_stable_id          ENSG00000104870
homology_protein_stable_id       ENSP00000221466
homology_species                    homo_sapiens
homology_identity                        66.8493
dn                                           NaN
ds                                           NaN
goc_score                                  100.0
wga_coverage                               99.11
is_high_confidence                           1.0
homology_id                             90347170
```
In this case, the internal id for ENSMUSG00000003420 is higher than for ENSG00000104870, therefore the homology is found in the mouse TSV.

As we want to display all homologues present on homo_sapiens we need to:
- download all the necessary species files
- update the ETL to extract all the homologues we're missing and assign them to the correct target.

Update PIS:
- We need the files from [ensembl for each species of interest](https://github.com/opentargets/platform-input-support/blob/27c08c3e9186d83706f3f98dcb93953330f55dbd/config.yaml#L220) from [Ensembl](Update PIS to get necessary files for each species: https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/)
- PIS uses a 'plugin' model, and the relevant file for this is [Homologues.py](https://github.com/opentargets/platform-input-support/blob/master/plugins/Homologues.py)

Update ETL:
- The relevant section of the configuration file (`src/main/resources/reference.conf` are the [homology inputs on the target step](https://github.com/opentargets/platform-etl-backend/blob/f9a9c6a5608eceddb3fc1803a37cdfe5258cd577/src/main/resources/reference.conf#L346).
    - We use the [Pureconfig library](https://pureconfig.github.io/docs/) if you want to get some more background on how the configuration is resolved.  
- The most relevant file is `src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala`. 
- For each species we're going to have to identify the homologues which link to homo_sapiens and the target species, harmonise the data structure and the new homologies to the correct target. 

This issue could related to #2795 and was originally raised by @iandunham:

> Someone was looking for the mouse orthologue for FCGRT. It doesn't seem to be present in our comparative genomics widget

- [FCGRT Platform profile page](https://platform.opentargets.org/target/ENSG00000104870) with absent mouse orthologue.

- one2one orthologue in [Ensembl compara](http://www.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog/Alignment?db=core;g=ENSG00000104870;g1=ENSMUSG00000003420;hom_id=90347170;r=19:49506816-49526428).

**Comment by d0choa** [comment]
@mbdebian there seems to be a consistent lack of information for 3 species on 2 of our releases and 2 ensembl releases:

Platform 22.09 -> Ensembl 107
```
❯ gsutil ls -l gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107
   1239643  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-caenorhabditis_elegans.tsv
    807793  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-canis_lupus_familiaris.tsv
    713501  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-cavia_porcellus.tsv
   1157788  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-danio_rerio.tsv
    522255  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-drosophila_melanogaster.tsv
         0  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-homo_sapiens.tsv
         0  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-macaca_mulatta.tsv
         0  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-mus_musculus.tsv
    759966  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-oryctolagus_cuniculus.tsv
    907579  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-pan_troglodytes.tsv
    850774  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-rattus_norvegicus.tsv
    913764  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-sus_scrofa.tsv
    707445  2022-09-13T13:19:39Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-sus_scrofa_usmarc.tsv
    662638  2022-09-13T13:19:38Z  gs://open-targets-pre-data-releases/22.09/input/target-inputs/homologue/107/107-xenopus_tropicalis.tsv
TOTAL: 14 objects, 9243146 bytes (8.81 MiB)

```

Platform 22.11 -> Ensembl 108
```
❯ gsutil ls -l gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/
   1239434  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-caenorhabditis_elegans.tsv
    780366  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-canis_lupus_familiaris.tsv
    713494  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-cavia_porcellus.tsv
   1153149  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-danio_rerio.tsv
    522255  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-drosophila_melanogaster.tsv
         0  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-homo_sapiens.tsv
         0  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-macaca_mulatta.tsv
         0  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-mus_musculus.tsv
    690663  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-oryctolagus_cuniculus.tsv
    907656  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-pan_troglodytes.tsv
    846471  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-rattus_norvegicus.tsv
    913224  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-sus_scrofa.tsv
    707445  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-sus_scrofa_usmarc.tsv
    662702  2022-11-09T14:10:54Z  gs://open-targets-pre-data-releases/22.11/input/target-inputs/homologue/108/108-xenopus_tropicalis.tsv
TOTAL: 14 objects, 9136859 bytes (8.71 MiB)
```

**Comment by JarrodBaker** [comment]
This looks like it might be a problem in PIS:

```
gsutil du gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107

1239643      gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-caenorhabditis_elegans.tsv
807793       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-canis_lupus_familiaris.tsv
713501       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-cavia_porcellus.tsv
1157788      gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-danio_rerio.tsv
522255       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-drosophila_melanogaster.tsv
0            gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-homo_sapiens.tsv
0            gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-macaca_mulatta.tsv
0            gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-mus_musculus.tsv
759966       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-oryctolagus_cuniculus.tsv
907579       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-pan_troglodytes.tsv
850774       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-rattus_norvegicus.tsv
913764       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-sus_scrofa.tsv
707445       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-sus_scrofa_usmarc.tsv
662638       gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/107-xenopus_tropicalis.tsv
9243146      gs://open-targets-data-releases/22.09/input/target-inputs/homologue/107/
```
The same files weren't downloaded as part of the preparation for the 22.11 release. Can you have a look at the PIS logs @mbdebian ?

**Comment by mbdebian** [comment]
I can see in PIS that we apply a JQ filter for _homologues_ dataset:
```yaml
homologues:
  uri: https://ftp.ensembl.org/pub/release-{release}/json/
  path: target-inputs/homologue
  release: 108
  jq: ".genes[] | [.id, .name] | @tsv"
  resources:
      - 'caenorhabditis_elegans'
      - 'canis_lupus_familiaris'
      - 'cavia_porcellus'
      - 'danio_rerio'
      - 'drosophila_melanogaster'
      - 'macaca_mulatta'
      - 'mus_musculus'
      - 'oryctolagus_cuniculus'
      - 'pan_troglodytes'
      - 'rattus_norvegicus'
      - 'sus_scrofa'
      - 'sus_scrofa_usmarc'
      - 'xenopus_tropicalis'
      - 'homo_sapiens'
```
Up until now, most of the errors happening in PIS are undetected, as there was no error handling apart from producing a massive log file, so the data had to be, basically, eyeballed.

I'll re-run that step to find out what may be going on.

My guess, is that the JQ filter process was killed when running in the GCP VM, and PIS didn't detect the event.

**Comment by mbdebian** [comment]
I'm re-running the step and I can see the data being collected, it's not finished yet, but I can confirm that it was a JQ issue as I guessed, not so much related to memory as it is related to the combination of machine architecture and cpu cores usage.
Taking into account that there's also been changes in evidence files, etc., I would recommend a PIS re-run, maybe on a different folder, as I can get feedback from the _manifest/reporting_ subsystem on whether everything was actually collected or not.
@d0choa and @JarrodBaker , what are your views on this?

**Comment by mbdebian** [comment]
Ok, I just confirmed what I suspected, it was JQ that failed, but it is possible to get the data.
I'll do a full run of PIS and put all the data here 👉🏻 22.11.1/input, within out data pre-releases bucket.

**Comment by mbdebian** [comment]
@d0choa , @JarrodBaker , the data is there now (22.11.1/input), no empty files, I've checked the resources manifests and they are flagged as completed so, although the _manifest_ feature still is in **alpha** stage, I'm trust that we can be more confident about having collected all the data that PIS is supposed to collect.

**Comment by JarrodBaker** [comment]
To generate the orthologues on the target object we use a pair of files (protein coding and non-coding rna):
```
https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/homo_sapiens/Compara.108.protein_default.homologies.tsv.gz
https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/homo_sapiens/Compara.108.ncrna_default.homologies.tsv.gz
```
We use individual species files to augment this information (which was what the discussion in prior comments above relates to). 

The mouse gene in question `ENSMUSG00000003420` is not in the homology files:

`grep -in ENSMUSG00000003420 cpd.tsv crna.tsv` returns nothing. 

Steps to reproduce:

```
mkdir ~/tmp
cd ~/tmp
gsutil -m cp \
gs://open-targets-pre-data-releases/22.11.1/input/target-inputs/homologue/cpd.tsv.gz \
gs://open-targets-pre-data-releases/22.11.1/input/target-inputs/homologue/crna.tsv.gz .
gunzip cpd.tsv.gz crna.tsv.gz
grep -in ENSMUSG00000003420 cpd.tsv crna.tsv
```
Any idea why the gene would be missing @d0choa ?

**Comment by ireneisdoomed** [comment]
Ensembl has followed up with me to clarify that the homologies between 2 species are only dumped to **one of the TSV files** in order to reduce data redundancy. The orthology that we see in the Ensembl UI is present in the `mus_musculus` dataset (https://ftp.ensembl.org/pub/release-108/tsv/ensembl-compara/homologies/mus_musculus/Compara.108.protein_default.homologies.tsv.gz)
```
gene_stable_id                ENSMUSG00000003420
protein_stable_id             ENSMUSP00000147496
species                             mus_musculus
identity                                 66.1247
homology_type                   ortholog_one2one
homology_gene_stable_id          ENSG00000104870
homology_protein_stable_id       ENSP00000221466
homology_species                    homo_sapiens
homology_identity                        66.8493
dn                                           NaN
ds                                           NaN
goc_score                                  100.0
wga_coverage                               99.11
is_high_confidence                           1.0
homology_id                             90347170
```

So 1) we need to process all homology files that are specific to the species (which we already do); 2) we need to know for which genome the relationship is reported. For this, apparently, the relationship will be displayed in the genome where the **internal `gene_member_id`** is higher. In this case, the internal id for ENSMUSG00000003420 is higher than for ENSG00000104870.
I haven't seen in the TSVs any reference to the internal IDs, I have asked if there is any LUT we could use, but what we could do is just search for ENSGIDs in the `homology_gene_stable_id` column of the non-human datasets. How does that sound?

**Comment by mbdebian** [comment]
Hi @ehsanb29 , *sus_scrofa_usmarc* doesn't have the Ensembl Compara files that we are using for all the species, and we have decided that we don't need its gene mapping information files, so we can just remove it from the list of _species of interest_
