### ISSUE TITLE
Unclassified clinical trial causes ChEMBL evidence to be invalid

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2811]
**Describe the bug**
There are 914 invalid ChEMBL evidence due to a null score. This corresponds to 601 unique associations.

**Observed behaviour**
These set of evidence are all based on clinical trials that stopped early. Therefore we run the reasons to stop the classifier to assign them a class.
The problem is that the classifier is not able to provide an assessment, so the `studyStopReasonCategories` will be an empty array.

This fact causes a problem downstream in the ETL when the evidence is scored, as the assigned category may cause a down-weight of the score. I guess that the ETL does not expect to have an empty array, therefore the score of the evidence is null.

**Expected behaviour**
~I would treat the absence of an assigned category the same way we deal with evidence that has not stopped early, i.e. `studyStopReasonCategories` is only populated if the classifier could successfully assign a class.~
- [x] To avoid the empty array, we will add an extra label `Uncategorised` to distinguish these studies from those that haven't stopped early.
- [x] The ETL config will also need to be changed.

**To Reproduce**
Steps to reproduce the behaviour:

```python
# all of the offending have an empty array
errors = spark.read.parquet("gs://open-targets-pre-data-releases/22.11/output/etl/parquet/errors/evidence/sourceId=chembl")
errors.filter(f.col("nullifiedScore") == True).select("studyStopReasonCategories").distinct().show()
+-------------------------+
|studyStopReasonCategories|
+-------------------------+
|                       []|
+-------------------------+

# No valid evidence has an empty array
evd = spark.read.parquet("gs://open-targets-pre-data-releases/22.11/output/etl/parquet/evidence/sourceId=chembl")
evd.filter(f.size("studyStopReasonCategories") == 0).count()
0

```

**Comment by JarrodBaker** [comment]
Looking at the scoring statement of the ETL config: 

```
     score-expr: """
        element_at(map(0, 0.09, 1, 0.1, 2, 0.2, 3, 0.7, 4, 1.0), clinicalPhase) *
        case
        when studyStopReasonCategories is null then
          double(1.0)
        else
          array_min(
            transform(
              studyStopReasonCategories,
                x -> element_at(
                  map(
                      'Another study', double(1.0),
                      'Business or administrative', double(1.0),
                      'COVID-19', double(1.0),
                      'Ethical reason', double(1.0),
                      'Insufficient data', double(1.0),
                      'Insufficient enrollment', double(1.0),
                      'Interim analysis', double(1.0),
                      'Invalid reason', double(1.0),
                      'Logistics or resources', double(1.0),
                      'Met endpoint', double(1.0),
                      'Negative', double(0.5),
                      'No context', double(1.0),
                      'Regulatory', double(1.0),
                      'Safety or side effects', double(0.5),
                      'Study design', double(1.0),
                      'Study staff moved', double(1.0),
                      'Success', double(1.0)
                  ),
               x)
             )
           )
        end
      """
```
it looks like the `when` clause is the issue.

**Comment by ireneisdoomed** [comment]
After discussing it with @d0choa, we decided it is better to add an `Uncategorised` label for those instances where the classifier does not return anything. This new label won't affect the scoring of the evidence string. 

We are scoping it for 23.02 and the config will also be changed accordingly. Thank you @JarrodBaker for the context.

**Comment by d0choa** [comment]
@ireneisdoomed is this done?

**Comment by ireneisdoomed** [comment]
No, but thank you for reminding me.

I've made the changes so that the predictions do not contain any empty predictions in this [commit](https://github.com/ireneisdoomed/stopReasons/commit/27b3050d7160416a53fae0d6bc10b17647ca7ddc).

The dependency in the evidence parsers is also updated ([commit](https://github.com/opentargets/evidence_datasource_parsers/pull/154/commits/f980ff36b8fce39cedf9404b5c733865c014880b)), the new evidence set does not have this problem.
```
new_chembl = spark.read.json("gs://otar000-evidence_input/ChEMBL/json/chembl-2023-01-31.json.gz")
new_chembl.filter(f.size("studyStopReasonCategories") == 0).count()
>>> 0
```

The 914 (now 917) unclassified evidence have now a class:
```
+--------------------+-----+
|               class|count|
+--------------------+-----+
|Insufficient enro...|26758|
|Business or admin...|17242|
|            Negative| 9019|
|        Study design| 4314|
|Logistics or reso...| 3981|
|      Invalid reason| 3919|
|Safety or side ef...| 3903|
|       Another study| 3093|
|   Study staff moved| 2269|
|          Regulatory| 1601|
|          No context| 1176|
|       Uncategorised|  917| <---
|            COVID-19|  859|
|    Interim analysis|  142|
|   Insufficient data|   40|
|             Success|   27|
+--------------------+-----+
``
