### ISSUE TITLE
No data displayed when changing pagination in bibliography widget

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/issues#2816]
When I look at the bibliography widget of a disease (https://platform.opentargets.org/disease/HP_0030148) and execute the following steps I generate an error condition:

1. Go to bibliography widget
2.  Select next page to view records 6-10
3.  Change rows per page to 25
4. Observe error `No data`.

I would have expected all 13 records to be displayed. 

Tested on: 
- Chrome Version 107.0.5304.87 (Official Build) (64-bit)
- Firefox 107.0 (64-bit)

**Comment by buniello** [comment]
This issue can be linked to this one on bibliography filter behaviour: (https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/issues/2578)
