### ISSUE TITLE
Gnomad constraint in OT platform shows “Z” where it should be “pLI”

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2817]
As reported in [community](https://community.opentargets.org/t/gnomad-constraint-in-ot-platform-shows-z-where-it-should-be-pli/790/1).

> Synonymous and missense constraint are represented as Z scores, but pLOF constraint is represented as “pLI” - probability of loss of function intolerance. The platform currently shows e.g. Z=1 when it should be pLI=1. Example:

[Platform Example](https://platform.opentargets.org/target/ENSG00000186487). Visit [Gnomad](https://gnomad.broadinstitute.org/gene/ENSG00000186487) to see the expected behaviour.

**Comment by LucaFumis** [comment]
This has been merged in the code base and will be included in the next release.
