### ISSUE TITLE
Evidence data source specific filters are not updating

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2820]
**Describe the bug**
The faceting menu to filter associations is not updating between searches, if they are already opened. 

**Expected behaviour**
I would expect the available data sources, shown on the `Data types selection` menu, would automatically re-fresh when a new set of associations is loaded.

**To Reproduce**
1. Go to [MAPK3 association page](https://platform.opentargets.org/target/ENSG00000102882/associations).
2. On the `Evidence-specific filters`, click on `data types`. It folds down all the data types. 
3. Click on, and folds down `genetic associations`. As you'll see, the gene only has OT GeneticsPortal based associations.
3. Now, without leaving the page, search for `NOTCH1` gene. Open associations.
4. As you will see, seemingly only Genetics Portal provides evidence for this gene, however this gene has evidence from most genetic data sources.

**Context**
- Platform release 22.11
- OS: 13.0.1 (22A400)
- Browser: Chrome 107.0.5304.110 (Official Build) (x86_64) , Firefox 107.0 

![Screenshot 2022-11-28 at 23.18.02.png](https://images.zenhubusercontent.com/5e300ebec23d5d8f8285c0ce/30fc0265-82c3-486d-91db-49aa355e0ff4)
![Screenshot 2022-11-28 at 23.18.16.png](https://images.zenhubusercontent.com/5e300ebec23d5d8f8285c0ce/5187c734-75c0-4ef3-83c6-acac6fe3201e)

**Comment by LucaFumis** [comment]
Thanks @DSuveges. It's quite a "subtle" bug - looks possibly the same as https://github.com/opentargets/issues/issues/1633 for which we looked into a solution based on the disease page (for which the filters work correctly)

**Comment by d0choa** [comment]
We will try to take this into consideration in the new on-the-fly page.
