### ISSUE TITLE
Investigating possible integration of publicly available Brain CRISPR data into the Platform

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2821]
As discussed in the Data meeting on 28/11/22, we intend to investigate whether data and metadata from the publicly available [Brain CRISPR ](https://crisprbrain.org/)resource conform to our schema for integration into the Platform.

**Comment by DSuveges** [comment]
Conclusions from the first review:

- Most of the screens on crispr brain dataset were done on baseline, healthy tissues, however there are screens, where a [healthy tissue was compared with a knocked out version](https://crisprbrain.org/background/). These screens might be used to generate disease target evidence if the contrast can be interpreted as a disease model.
- The screen data is shared publicly on google cloud locations, however the study metadata is only available via a REST API. The API is not publicly exposed but [via a Python package](https://crisprbrain.org/api/guide/). It is a separate decision if we want to introduce another dependency in the evidence parser repo. Alternatively the API can be deciphered and used as it is.
- The study design metadata [available for all studies](https://gist.github.com/DSuveges/9d097f2ef324ac021abc032c07902849), but it needs to be reviewed to find out which can be ingested as disease/target evidence

**Comment by iandunham** [comment]
You will need to review the phenotypes of the assays. For instance a screen on a normal cell for phagocytosis is relevant to disease if phagocytosis is a process that is decreased or increased in disease. Similarly if there is a FACS marker - if that marker protein is up- or down-regulated in disease you can use the normal cell screen as a disease relevant assay.

**Comment by DSuveges** [comment]
@iandunham thank's it's a good point. So the mapping seems to be a quite complicated process. Should the relevant tissue also be considered: if the phenotype is phagocytosis, can we extrapolate to all diseases with increased/decreased phagocytosis where the implicated tissue is not brain?

**Comment by iandunham** [comment]
There are a lot of ways this could go, but perhaps the most straight forward way to resolve this is to ask our neuro scientists what disease they think each assay is relevant for. If we can get the trait/phenotype/assay  that is done for each screen we could then run it past Andrew Bassett, Lewis Evans and Panos' team as to how they would map the assay

**Comment by DSuveges** [comment]
Oh, great, I can easily assemble a table with these details and we can circulate.

**Comment by DSuveges** [comment]
I have [created a Google sheet](https://docs.google.com/spreadsheets/d/1Gg8v0F88fvtC2sEUcLInem7Ky_xsO1dj1mmCUOjKwIQ/edit?usp=sharing) with all the screens + phenotypes (with all other relevant metadata). I think this should be enough details to make the link with the disease.

**Comment by DSuveges** [comment]
This task is pulled back from release 23.02. However keep process going, hopefully by the April release we will make enough progress.
