### ISSUE TITLE
Remove helpdesk@ from Platform/Genetics error message

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2823]
Related to #2749 

When there is an error message on the Platform (e.g. missing data), it tells users to contact helpdesk@opentargets.org. This email address is no longer active, so please could you point them to community.opentargets.org instead? 

I'm assuming the error message is the same for Genetics, in which case this should also be changed.

<img width="1274" alt="Screenshot 2022-11-29 at 16 04 11" src="https://user-images.githubusercontent.com/73692302/204580555-548882a9-6477-4ba5-b3bb-1e4b63f86de0.png">

**Comment by LucaFumis** [comment]
Happy to look into it.
I guess the error messages experience could also be improved: for examples as pointed out by @d0choa when summary widgets fail, the widget is rendered in red. Similarly it would be helpful to have the widget header there (otherwise one has to somewhat guess which one failed). I haven't actually tested it yet, so might not work well.

**Comment by LucaFumis** [comment]
Hi @HelenaCornu could the message be something like "Something went wrong. Please see our Open Targets Community at https://community.opentargets.org" ?

**Comment by HelenaCornu** [comment]
Yes, I think that would make sense! Ideally, it would link to the bug report page (https://community.opentargets.org/c/community-feedback/bug-reports/34) :)

**Comment by LucaFumis** [comment]
Thank you Helena - yes, the option to submit bug is great. I'll double check the component supports links etc (it should, but for some reasons it's a simple string at the moment).

Will PPP/partners want a different message (that would have to be configured) ? So far they could customise the help-desk email address.

**Comment by HelenaCornu** [comment]
Yes, I think it would make sense for the PPP to point to our partner helpdesk email

**Comment by HelenaCornu** [comment]
The Platform error message looks good 😄 

For the PPP message, what about: 
"Something went wrong. Please contact Open Targets at _partner helpdesk email_."

We could point to both the helpdesk and the Community? e.g.
"Something went wrong. Please contact Open Targets at _partner helpdesk email_, or [submit a bug report](https://community.opentargets.org/c/community-feedback/bug-reports/34) on the Open Targets Community."

**Comment by buniello** [comment]
Yes, the two options Helena is proposing are perfect

**Comment by LucaFumis** [comment]
Thanks @buniello - yes it's all done; it should also already be in production. Good to close.
