### ISSUE TITLE
null variantFunctionalConsequence in both OTGenetics and EVA evidence from API

### ISSUE THREAD

**Issue by fedde-s** [opentargets/issues#2824]
**Describe the bug**
On evidence pages of the platform, the **variantFunctionalConsequence** fields returned by the API queries for the OTGenetics and EVA/ClinVar  are `null` instead of objects with `.id` and `.name` fields.

**Observed behaviour**

When I opened the evidence page on <https://platform.opentargets.org/evidence/ENSG00000167207/EFO_0003767>, the **Functional Consequence** column of the **OT Genetics Portal** section showed _N/A_ for all rows. The **ClinVar (EVA)** section immediately below it did not display at all and showed an error instead; it does not have logic to show N/A labels in the corresponding column.

**Expected behaviour**

The evidence rows [on the FTP server](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.11/output/etl/json/evidence/) do list `variantFunctionalConsequenceId` fields. I believe that the `platform-api` service should be able to [format these IDs](https://github.com/opentargets/platform-api/blob/22.11.1/app/models/entities/Evidence.scala#L136) into the JSON objects I described above by [referencing the Elasticsearch index `so`](https://github.com/opentargets/platform-api/blob/22.11.1/app/models/gql/Fetchers.scala#L22). 

**To Reproduce**
Steps to reproduce the behaviour: see **Observed behaviour** above.

**Additional context**
I suspect that something has gone wrong loading data into the `so` index for the production server. Given that the data model used in [the data loading code](https://github.com/opentargets/platform-output-support/blob/464e9e2f43a0642790f7da99cc3f6ec2e1ab9533/terraform_create_images/modules/posvm/scripts/load_all_data.sh#L55) has always put this data type in a different place than the data model of [the FTP server](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.11/input/so-inputs/), perhaps something broke in one of [the recent revisions of the `load_data.sh`/`startup.sh` script that is supposed to put the data in place for data loading](https://github.com/opentargets/platform-output-support/compare/35744abdce0b843d5844af0e1324de2f4051e91b...464e9e2f43a0642790f7da99cc3f6ec2e1ab9533#diff-82448d3355b6d24816515ea3439bca2383c90f950af94f5e4886ef487405c399)?

If I point [the platform-api code](https://quay.io/repository/opentargets/platform-api?tab=tags&tag=22.11.0) to an Elasticsearch database in which the `so` index contains the data from [so-inputs/](https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/22.11/input/so-inputs/), the tables show functional consequence links as I would expect. If I then delete the `so` index, the sections look like they do on the production server.

**Comment by d0choa** [comment]
@fedde-s thanks for reporting! The wrong images were picked to build the production instances. We don't anticipate any problems with the codebase but let us know otherwise. cc @JarrodBaker

**Comment by fedde-s** [comment]
Great, I can see that it all looks to be fixed now! We didn't spot or run into code bugs in the release either so far, but if they pop up we'll of course want to collaborate to resolve them for everyone!
