### ISSUE TITLE
Filter `associatedTargets`/`associatedDiseases` by lists of genes/diseases

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2830]
We would like to be able to extend the `associatedTargets` endpoint so it can be queried based on a predefined list of targets or diseases, so that a number of UI features can be implemented.

When fixing a disease (or a target) the `associatedTargets` (or `associatedDiseases`) endpoint returns a paginated list of results.

```
query associatedTargets {
  disease(efoId: "EFO_0000349") {
    id
    name
    associatedTargets {
      count
      rows {
        target {
          id
          approvedSymbol
        }
        score
      }
    }
  }
}
```

The `associatedTargets` endpoint can currently be paginated (`page: Pagination`) or searched (`BFilter: string`) in order to filter the returned results. 

We would like to expand this functionality by filtering the results by a predefined list of targets (`ensemblIds: [String!]!`) in the case of the `associatedTargets` or a predefined list of diseases (`efoIds: [String!]!`) in the `associatedDiseases`. It would be acceptable to limit the number of targets that can be queried if that's required to proctect the API. A maximum between 25 and 100 would probably capture most of the functionalities.

The assumption is that the scores are already computed and we will only be filtering the resulting results.

One of the use cases from @carcruz and @buniello is to be able to bookmark targets of interest in the new UI and update them as new requests are performed. Long term this will protect the API as less traffic will be required

**Comment by JarrodBaker** [comment]
It looks like this functionality already exists. One of the argument options is `Bs`, which accepts an array of strings.
In this case the string should be a target ID. 

For example, I can run the query:

```
query associatedTargets {
  disease(efoId: "EFO_0000349") {
    id
    name
    associatedTargets(Bs: ["ENSG00000163930"]) {
      count
      rows {
        target {
          id
          approvedSymbol
        }
        score
      }
    }
  }
}
```
And receive the response:
```
{
  "data": {
    "disease": {
      "id": "EFO_0000349",
      "name": "clear cell renal carcinoma",
      "associatedTargets": {
        "count": 1,
        "rows": [
          {
            "target": {
              "id": "ENSG00000163930",
              "approvedSymbol": "BAP1"
            },
            "score": 0.6397181071209104
          }
        ]
      }
    }
  }
}
```

A possible explanation of the naming, `Bs` is Miguelese: some `A` is the disease, and the `B`
some target. This is how the query is encoded in the backend. 

I'd propose that we rename the parameter into something more intuitive. We don't use the field 
at present, but it's possible some other users already make use of the feature. 

Any thoughts @dOchoa or @carcruz?

**Comment by d0choa** [comment]
I think this is it. @carcruz close the ticket if you think this endpoint does the job.
