### ISSUE TITLE
Adapt ETL to ingest target safety input generated by data team

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2836]
As a **member of the data team** I want **to have ownership over the target safety liabilities data that is built in the target object** because **this is a dataset that is likely to receive iterations and I want to remove the pressure of generating the data to the ETL.**

## Background

Historically the ETL used to parse the raw data that was initially curated in the context of the target safety project. With the redefinition of the data model and in light of the potential new iterations, the data team was responsible for the generation of a dataset that parsed the data to follow the model.
The logic in the ETL that processes the safety files: https://github.com/opentargets/platform-etl-backend/blob/a06f414e1cdc225b621a09df4d0edabb51ada1a7/src/main/scala/io/opentargets/etl/backend/target/Safety.scala
The logic in the evidence parsers to apply very similar steps: https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/TargetSafety.py

## Tasks

- [x] Change PIS to collect the data generated by the data team. This is deposited in `gs://otar001-core/TargetSafety/json` fith a filename that follows the pattern: `gs://otar001-core/TargetSafety/json/safetyLiabilities-YYYY-MM-DD.json.gz`
- [x] Adapt the ETL to ingest this data. The data will come following practically the same schema as the final one, with the additional requirement that the targets have to be normalised (more details to follow)

## Acceptance tests

1. Around 456 unique targets should have safety information.
2. GRIN3A (ENSG00000198785) should have 17 liabilities only sourced by Lynch et al.
3. APP (ENSG00000142192) has no target safety evidence.

**Comment by ireneisdoomed** [comment]
<details open>
<summary>Schema of the final safety object after ingesting it inside target</summary>
<br>

```
root
 |-- id: string (nullable = true)
 |-- safetyLiabilities: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- event: string (nullable = true)
 |    |    |-- eventId: string (nullable = true)
 |    |    |-- effects: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- direction: string (nullable = true)
 |    |    |    |    |-- dosing: string (nullable = true)
 |    |    |-- biosample: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- tissueLabel: string (nullable = true)
 |    |    |    |    |-- tissueId: string (nullable = true)
 |    |    |    |    |-- cellLabel: string (nullable = true)
 |    |    |    |    |-- cellFormat: string (nullable = true)
 |    |    |    |    |-- cellId: string (nullable = true)
 |    |    |-- datasource: string (nullable = true)
 |    |    |-- literature: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |    |    |-- study: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- name: string (nullable = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
```
</details>

<details open>
<summary>Schema of the data generated by the data team</summary>
<br>

```
root
 |-- biosample: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- cellFormat: string (nullable = true)
 |    |    |-- cellLabel: string (nullable = true)
 |    |    |-- tissueId: string (nullable = true)
 |    |    |-- tissueLabel: string (nullable = true)
 |-- datasource: string (nullable = true)
 |-- effects: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- direction: string (nullable = true)
 |    |    |-- dosing: string (nullable = true)
 |-- event: string (nullable = true)
 |-- eventId: string (nullable = true)
 |-- id: string (nullable = true)
 |-- literature: string (nullable = true)
 |-- study: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- description: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- type: string (nullable = true)
 |-- targetFromSourceId: string (nullable = true)
 |-- url: string (nullable = true)
```
</details>

As it can be noted, both are very similar with some particularities:
- The raw data contains `id`, which usually holds an ENSGID when it could be mapped.
    - This ID might differ from the latest ENSEMBL (it is not normalised to the target index)
    - It can be null (ToxCast evidence) - in this case we want to map the ID by using the gene symbol inside `targetFromSourceId` (like we do for evidence). 
- The data is not aggregated, each row is an evidence.
    - Data should be aggregated on the target, so the function `groupByEvidence` should be applied. 
- Other than that, the data does not need any other logic.

**Comment by JarrodBaker** [comment]
I've run the Target step with the new data and updated ETL (outputs [here](gs://open-targets-pre-data-releases/jarrod/output/etl/parquet/targets/)). The new schema looks like:

```
root
 |-- id: string (nullable = true)
 |-- safetyLiabilities: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- event: string (nullable = true)
 |    |    |-- eventId: string (nullable = true)
 |    |    |-- effects: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- direction: string (nullable = true)
 |    |    |    |    |-- dosing: string (nullable = true)
 |    |    |-- biosamples: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- cellFormat: string (nullable = true)
 |    |    |    |    |-- cellLabel: string (nullable = true)
 |    |    |    |    |-- tissueId: string (nullable = true)
 |    |    |    |    |-- tissueLabel: string (nullable = true)
 |    |    |-- isHumanApplicable: boolean (nullable = true)
 |    |    |-- datasource: string (nullable = true)
 |    |    |-- literature: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |    |    |-- studies: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- description: string (nullable = true)
 |    |    |    |    |-- name: string (nullable = true)
 |    |    |    |    |-- type: string (nullable = true)
```

And the outputs of the acceptance tests:
```
Targets with safety data
df.filter('safetyLiabilities.isNotNull).count    
res5: Long = 503L

GRIN3A
df.filter('id === "ENSG00000198785").select(size('safetyLiabilities)).show    
+-----------------------+  
|size(safetyLiabilities)|  
+-----------------------+  
|                     17|  
+-----------------------+

APP
df.filter('id === "ENSG00000142192").select(size('safetyLiabilities)).show    
+-----------------------+  
|size(safetyLiabilities)|  
+-----------------------+  
|                     -1|  
+-----------------------+
```
