### ISSUE TITLE
Add `isHumanApplicable` field to `safetyLiabilities`endpoint

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2837]
As a **user** I want **to know if the described safety event reports are applicable to humans** whenever that information is available because **we want to distinguish it from measurements seen on other species**.

## Background

We have new data that links a target to a safety event from AOPWiki. This new data practically adapts to the current `safetyLiabilities` model,  with the exception of one field that we want to add. `isHumanApplicable` is a boolean flag that reports if the human target is relevant in the reported adverse outcome pathway.

Since this new data will be available, we want to also expose it in the API.

The current GraphQL schema:
```
query Safety($ensemblId: String!) {
  target(ensemblId: $ensemblId) {
    id
    safetyLiabilities {
      event
      eventId
      biosample {
        cellFormat
        cellLabel
        tissueLabel
        tissueId
      }
      effects {
        dosing
        direction
      }
      study {
        name
        type
        description
      }
      datasource
      literature
      url
    }
  }
}
```

## Tasks

- [ ] Add `isHumanApplicable` as a new field to the `safetyLiabilities` array of structs
Metadata for this endpoint is: 
- type: `boolean`
- description: `flag that reports whether a target is relevant in the reported adverse outcome pathway`

## Acceptance tests

1. When I query the safetyLiabilities endpoint for ENSG00000278540, an AOPWiki evidence should appear where this flag is set to True. 

**Note:** this data is still not integrated in the latest safetyLiabilities dataset, but will be produced in the next days.

**Comment by JarrodBaker** [comment]
@ireneisdoomed: In cases when this value isn't available should we return `null` or `false`?

**Comment by ireneisdoomed** [comment]
@JarrodBaker Good point. It should return null, as it refers to lack of evidence. I will change the input dataset so that only True or null is possible. Thanks for pointing it out.

**Comment by ireneisdoomed** [comment]
@mbdebian As discussed in the release channel, `biosample` and `study` will also have to be renamed to `biosamples` and `studies`

**Comment by mbdebian** [comment]
@ireneisdoomed , I remember some work around this issue last year, would you say we can close it?
Thanks!

**Comment by ireneisdoomed** [comment]
@mbdebian This is no longer applicable. What needs to be done is to remove any reference to this field in the ETL. The data team will remove it from the data (see #2851 )
