### ISSUE TITLE
Benchmarking the impact of removing US based machines

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2842]
To benchmark the impact of removing GCP machines that are deployed in the US geographical zone as there is additional cost incurred for continuously running these machines.
The impact can be measured by using the dev deployment.
If there are no major impacts, we can shut down these.

**Comment by mbdebian** [comment]
There is a health check endpoint in the API that I need to change so it skips any possible cache, this way it could be used for measuring networking parameters.

**Comment by mbdebian** [comment]
Tasks:
- [] Promote Open Targets Platform development deployment to stable machines
- [] Take networking metrics on API health check endpoint from US and EU
- [] Expand the deployment to US region
- [] Repeat the networking metrics on API health check endpoint from US and EU
- [] Compare both metrics

**Comment by mbdebian** [comment]
We are taking a more straight forward approach on this, so the process, as depicted here, doesn't apply any more.
