### ISSUE TITLE
Consolidating our json_schema repository

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2844]
As the shape of an increasing number of data types are described as json schemas in the [json-schema](https://github.com/opentargets/json_schema) repository, there's a need to organize and standardize:
- Format (eg. indenation) 
- Location root vs /schemas folder
- Naming: prefix should be removed. Should be indicated if a schema describes an output, by default we should test for input.
- The current `opentargets.json` file should be renamed to `target-disease-evidence.json`. However this update needs to be circulated with our providers, who are constantly using this file to validate the evidence set they send to us.
- The `.travis.yaml` file needs to be updated to make sure all json schemas are tested against the draft schema definitions.  Currently the tests are defined manually, but this is not the right practice.
- We can consider writing pydantic logic to generate the schemas automatically.

**Comment by d0choa** [comment]
do we have an assignee for this task?

**Comment by DSuveges** [comment]
@d0choa I kind of did it already, however I don't want to get [the branch](https://github.com/opentargets/json_schema/pull/165/files) merged before the new release is out. In the meantime we can think about other ways to make the repo more sensible. We can scope under this ticket.

**Comment by d0choa** [comment]
great! I was going through the most recent tickets with @buniello and @prashantuniyal02 and we were wondering about ownership.

**Comment by DSuveges** [comment]
As most of these tasks are already done I'm closing the ticket. If further updates are proposed, we'll capture those efforts in a different ticket.
