### ISSUE TITLE
Ontoma doesn't know the efo version of the cache

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2847]
This is kind of a bug: [ontoma](https://github.com/opentargets/OnToma) doesn't update the cache even though it supposed to use the latest release. 

So there should be a mechanism that ensures Ontoma knows which efo version has the cached data. If the applied efo version is different, the cache should be dropped and re-generated.

**Comment by ireneisdoomed** [comment]
The most straightforward fix that I see is to version the cached files. Caching consists of storing the OWL itself and a couple of look up tables between names with the filenames hardcoded ([as follows](https://github.com/opentargets/OnToma/blob/e78ece6cc9af357fda9b5a1192414239abdfa2c1/ontoma/owl.py#L15)).

We could move those variables inside preprocess_owl and append their EFO version properly named [here](https://github.com/opentargets/OnToma/blob/e78ece6cc9af357fda9b5a1192414239abdfa2c1/ontoma/owl.py#L53).

**Comment by DSuveges** [comment]
Yes, sounds reasonable... would allow the presence of multiple versions, which I'm not sure if would be a feature or bug. This issue should be addressed together with 
- [ ] Logs levels on mappings turned into debug from info.
- [ ] Log formatting should be inherited from the calling application.

I don't think either of these points would be too complicated to resolve.

**Comment by tskir** [comment]
Yeah, admittetly caching implementation in OnToma is pretty basic, I never really considered a scenario where a single instance (+ its cache) would persist for more than few days. For example, for generating the evidence I would create a fresh instance every release to avoid any accumulations of inconsistencies such as this one.

@DSuveges thank you for pointing out & addressing this, I will review the PR

**Comment by DSuveges** [comment]
No problem, thank you @tskir for reviewing the code.

**Comment by d0choa** [comment]
done?

**Comment by DSuveges** [comment]
Merged and released. So, yes.
