### ISSUE TITLE
Dropping `humanApplicability` field from target safety.

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2851]
- [ ] Update parser.
- [ ] Update schema.
- [x] Update ETL/API

**Comment by ireneisdoomed** [comment]
I understood the decision was not to show it in the FE for now, and not to change the data as well.

**Comment by mbdebian** [comment]
> I understood the decision was not to show it in the FE for now, and not to change the data as well.

That's right, the work in the ETL / API is already completed, we just don't expose that attribute on the frontend.

**Comment by ireneisdoomed** [comment]
Thanks @mbdebian. I'll close this then.

**Comment by ireneisdoomed** [comment]
This should be part of the release intentions for 24.02 cc @prashantuniyal02

**Comment by ireneisdoomed** [comment]
After merging the schema and data PRs, what's is ETL territory.
@opentargets/be-team  There are references to the field:
- in the schema https://github.com/opentargets/platform-etl-backend/blob/505709b2414dae5f097dfc7dea2269d663bac701/src/main/scala/io/opentargets/etl/backend/target/Safety.scala#L29
- in the test data https://github.com/opentargets/platform-etl-backend/blob/505709b2414dae5f097dfc7dea2269d663bac701/src/test/resources/target/safety_100.jsonl#L20

**Comment by mbdebian** [comment]
> > I understood the decision was not to show it in the FE for now, and not to change the data as well.
> 
> That's right, the work in the ETL / API is already completed, we just don't expose that attribute on the frontend.

From some conversation back in January, it was my understanding that the changes in the ETL and the API were done, but apparently that's not the case

I'm including this ticket in the release intentions, because the attribute _isHumanApplicable_ is no longer present in the dataset for the current release

**Comment by mbdebian** [comment]
This has been removed from the ETL and it's not present in the API
