### ISSUE TITLE
In-progress upgrade of genetics-app to updated typescript/react/etc.

### ISSUE THREAD

**Issue by riyavsinha** [opentargets/issues#2857]
As a **developer** I want **to be able to build on the genetics app in a strongly typed way leveraging updated features from different libraries** because **it increases developer velocity, reduces bugs, provides IDE support and allows me to take advantage of new features that make coding more convenient. It also reduces the chances of the app falling out of support eventually, if it falls too far behind on major releases of dependencies.**

## Background

Provide any necessary background information to provide context on the issue. 

I have started an in-progress migration of the genetics-app to updated versions of:
- React
- MUI
- react-router
- etc.

and added typescript as well. My fork is here: https://github.com/riyavsinha/open-targets-genetics-app-ts. 

I'm seeking feedback on whether this is something that that you would like to keep separate, or if there's interest in eventually merging it back in or using it canonically. Thank you!

**Comment by carcruz** [comment]
Hello @riyavsinha. 

We appreciate your effort in migrating the genetics app to Typescript. Unfortunately, we are no longer maintaining the genetics app repository. We migrate the codebase of our two applications to a Monorepo (https://github.com/opentargets/ot-ui-apps), and we are also recently scoping to migrate our components to Typescript (https://github.com/opentargets/issues/issues/2871).

If you are willing to move your current refactor to the monorepo, we'll be more than happy to review it and eventually merge it into our code base.

**Comment by riyavsinha** [comment]
Ah, thank you for the update!

It may be helpful to update the link here: https://genetics-docs.opentargets.org/technical-pipeline/github-repositories :)
