### ISSUE TITLE
Developing an automated alert log checking system for the daily runs in the literature pipeline

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2860]
To develop an automated alert log checking system for the daily runs in the literature pipeline
It should send an email/slack message which will ensure the team is aware when the processes are failing.

**Comment by tsantosh7** [comment]
Working on this!!

**Comment by tsantosh7** [comment]
I have created a basic log system for now to track the progress and errors.

**Comment by tsantosh7** [comment]
@prashantuniyal02  the automated alert log checking system for the daily runs in the literature pipeline sends an email message to shared mailbox lit-dev, this is also monitored by other dev team members so we are aware when the processes are failing. 

KIndly let me if you woild like to subscribe to this email?
