### ISSUE TITLE
Enable users to bookmark targets of interest in the new associations page UI

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2863]
Following up from the existing BE implementation discussed in [#2830](https://github.com/opentargets/issues/issues/2830),

as part of the AOTF-UI features we would like to enable users to bookmark targets of interest and update them as new requests are performed. Long term this will protect the API as less traffic will be required.

**Comment:**
The relevant API field is named `Bs` (accepting an array of strings). Should we re-name the argument to something more meaningful? (comment from Jarrod).

**Comment by carcruz** [comment]
Closed as implemented in https://github.com/opentargets/ot-ui-apps/pull/189.
