### ISSUE TITLE
Invalid ChEMBL evidence causes the widget to crash

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2866]
**Describe the bug**
ChEMBL widget for the evidence is crashing due to invalid drug IDs. An example: https://platform.dev.opentargets.xyz/evidence/ENSG00000169174/EFO_0004911

**Observed behaviour**
It seems that only the evidence widget is failing, despite "known drugs" being also dependent from the ChEMBL evidence.

**Expected behaviour**
We should not have any evidence with an invalid CHEMBL ID. These should fall back to invalid dataset, the same way the ETL handles invalid target and disease IDs.

**Additional context**
665 evidence are affected by this problem, with 48 invalid ChEMBL IDs. The full list: 
```
+-------------+
|drugId       |
+-------------+
|CHEMBL2397751|
|CHEMBL4444976|
|CHEMBL3746388|
|CHEMBL5095022|
|CHEMBL5095035|
|CHEMBL4751394|
|CHEMBL5095028|
|CHEMBL5095030|
|CHEMBL3989962|
|CHEMBL4456085|
|CHEMBL3989988|
|CHEMBL5095049|
|CHEMBL5095032|
|CHEMBL2016893|
|CHEMBL4650369|
|CHEMBL4303729|
|CHEMBL4740383|
|CHEMBL5095025|
|CHEMBL4871106|
|CHEMBL3139186|
|CHEMBL4297223|
|CHEMBL5095029|
|CHEMBL5095024|
|CHEMBL1819077|
|CHEMBL3642985|
|CHEMBL5095034|
|CHEMBL5095492|
|CHEMBL4594472|
|CHEMBL1981592|
|CHEMBL5095033|
|CHEMBL5095031|
|CHEMBL4594334|
|CHEMBL4303379|
|CHEMBL4297220|
|CHEMBL4650313|
|CHEMBL2108973|
|CHEMBL4761468|
|CHEMBL5095052|
|CHEMBL4084119|
|CHEMBL3644252|
|CHEMBL5095036|
|CHEMBL4802157|
|CHEMBL4213970|
|CHEMBL3694769|
|CHEMBL4650216|
|CHEMBL4742157|
|CHEMBL4594293|
+-------------+
```

**Comment by d0choa** [comment]
@ireneisdoomed please give us a healthy file and assign @opentargets/be-team

**Comment by ireneisdoomed** [comment]
I've reported this list to Paula from ChEMBL and she has confirmed that these new IDs are part of ChEMBL32, which unexpectedly sneaked into our ChEMBL31-based evidence set.

The intention is to generate a correct file and do a new pipeline run.

**Comment by ireneisdoomed** [comment]
We have identified 2 streams of invalid ChEMBL IDs:
- 17 new molecules that will be available on ChEMBL32 have sneaked in. `CHEMBL5095030` is an example.
- The other 31 refer to drugs that are currently part of ChEMBL but do not meet any of the criteria to include them in our index (MoA/indication/xref with DrugBank). But in ChEMBL drugbase's they do have a MoA that for some reason is not propagating and therefore not exposed. `CHEMBL4444976` is an example.

They don't know the root cause of the second case, so we have agreed to **reuse the 22.11 data**. Evidence is available at `gs://otar000-evidence_input/ChEMBL/json/chembl-2023-01-31.json.gz`.

I had to produce a new evidence set to account for the bug we identified in the 22.11 evidence (#2811)

I did some checks on the data, to make sure no other bug was introduced:
```py
original_evidence = spark.read.json("gs://otar008-chembl/cttv008-25-08-2022.json.gz") # raw chembl submission (August)

new_evidence = spark.read.json("gs://otar000-evidence_input/ChEMBL/json/chembl-2023-01-31.json.gz") # generated by us from original_evidence and the latest stopReasons predictions)

In [7]: new_evidence.count() == original_evidence.count()
Out[7]: True

# no empty predicted categories
In [8]: new_evidence.filter(f.size("studyStopReasonCategories") == 0).count()
Out[8]: 0

# apart from the new field we add, schema remains the same
In [12]: new_evidence.drop("studyStopReasonCategories").schema == original_evidence.schema
Out[12]: True
```

**Comment by d0choa** [comment]
We used the previous data release and this solved the issue. New evidence will come together with ChEMBL 32 in the next release
