### ISSUE TITLE
Add API drawer to PPP widget

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2870]
I noticed that not all PPP widgets have the API drawer option, where the user clicks to display the API query in a playground environment.

Would it be possible to implement it for all widgets?

Thank you!

**Comment by d0choa** [comment]
We probably need a bit of technical/product scoping. At the moment the API playground link is associated to the table component, mostly for historic reasons. In the cases in which the information is not presented in a table (PPP or not), the API link does not exist.

I agree this would be very popular feature, but we need to understand the technical implications. In an abstract way, we are trying to say that the API link belongs to the "widget" rather to the table. That would generalise the functionality.

@buniello assigning to you to see if we can polish an idea of what would this feature look like and what would be the implementation cost

**Comment by buniello** [comment]
yes, we discussed this before and decided not to act on it straight away. Will re- assess.

**Comment by buniello** [comment]
I have re-proposed this issue to the FE team today and it looks like the implementation can be done for PPP project widgets and ENCORE.
