### ISSUE TITLE
Make all scores in the [-1, 1] range in the AOTF target prioritisation

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2880]
Scores that are not in the [-1, 1] range in the AOTF target prioritisation:

- [x] Target in clinic

- [x] Mouse ortholog identity

- [x] Paralogues

We need to make all scores in the [-1, 1] range in the AOTF target prioritisation.

**Comment by Juanmaria-rr** [comment]
Code was fixed for the normalization in the range of [-1,1] regarding the changes required. A new json file was produced and sent to Carlos ('prototype20230217.json').  In the attached file you can check the min and max values for every column of the file produced by the fixed code.
[statisticsPrototype20230217.csv](https://github.com/opentargets/issues/files/10771419/statisticsPrototype20230217.csv)

After talking to @remo87, we agreed on updating the target_engine repo and have a catch-up with the modifications on Monday.

**Comment by Juanmaria-rr** [comment]
@carcruz noticed that the number of targets retrieved in the target was lower than the 23.02 platform version has, so after getting the datasets from the 23.02 version, I have updated the prototype and sent to Carlos to be displayed in the tool. 
Here you can find the new statistics file for this prototype version. 

[statisticsVersion23.02.csv](https://github.com/opentargets/issues/files/10802227/statisticsVersion23.02.csv)

**Comment by prashantuniyal02** [comment]
Can we close this issue @Juanmaria-rr @remo87 ?

**Comment by Juanmaria-rr** [comment]
Yes, I agree!
