### ISSUE TITLE
Home page suggestions show same entity twice

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2885]
The random selection of predefined target, disease, drugs allows for selecting the same element twice:

![Screenshot 2023-02-21 at 12 59 37](https://user-images.githubusercontent.com/5097586/220351259-185ea3ba-3a48-406c-91ea-0cdce4a11336.png)

We would like not to have entities repeated in the home page.

**Comment by prashantuniyal02** [comment]
Completed by Carlos.
