### ISSUE TITLE
Requirements for Genetics Input Support

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2891]
The newly designed Genetics Portal pipeline depends on a number of datasets that are available for processing. As there are a large number of datasets that needs to be pulled together, this ticket will contain a few consideration.

## Prepare GWAS Catalog sumstat ingestion.

1. To reduce price on egress and computation, this process should run on EBI infrastructure.
2. The process should be triggered daily.
3. The process should work incrementally.
4. The process should check the md5 checksum.
5. The process should be based on list of harmonized summary stats: `/nfs/ftp/pub/databases/gwas/summary_statistics/harmonised_list.txt`
6. The process should read the tsv, apply p-value filter, save as partitioned parquet file in gs:// location.

@mbdebian , do you have any feelings about this? I'm not sure how complicated it could be to work with spark, however parquet files can be written by pandas as well. We can write a process that kicks as many single threaded jobs as many new study needs to be processed.

**Comment by mbdebian** [comment]
Yes, running on the EBI will save on computational and networking cost, unless we pull data from a bucket we own and / or is set to _requester pays_.

If we are to trigger the process daily, we need to handle the case where the job was submitted to run on a particular day but it may not complete or run before the next day's one is submitted. I would need to double check with the periodic job scheduling arrangements in the cluster to find out the SLA.

On the concurrency side of things, the recommend approach would be a launcher that divides the work into as atomic and small as possible chunks, and it submits all those tiny jobs to the cluster to guarantee prompt scheduling and completion.

This works for the approach where we use a schedulled job that runs periodically.

It may be the case that we'd like this to react _on-demand_, as new studies show up, for this, we would use an event driven approach.

Regarding _Spark_ vs _Pandas_, it depends on how big of a processing job would be to process a study, or the business logic we need to run. If the _per study_ processing requirements is not that big, and it's quite isolated (low or no dependencies), we could go for pandas based implimentation.

**Comment by DSuveges** [comment]
> Yes, running on the EBI will save on computational and networking cost, unless we pull data from a bucket we own and / or is set to _requester pays_.
For the summary stats ingestion part we would only move data from `/nfs/ftp` do a minor processing (eg. p-value filter) then save the partitioned parquet files under gs:// location.

> If we are to trigger the process daily, we need to handle the case where the job was submitted to run on a particular day but it may not complete or run before the next day's one is submitted. I would need to double check with the periodic job scheduling arrangements in the cluster to find out the SLA.
Oh that's a tricky question. Even if the job itself would not take too long to run, it is possible to not being complete due to job scheduling. 

> It may be the case that we'd like this to react _on-demand_, as new studies show up, for this, we would use an event driven approach.
Not sure how to observe event on /nsf. In theory we should be watching the state of a single txt file, which when changes should kick of a job. But to me, implementing a scheduled job seems to be more straightforward (with the previously mentioned complexity). 

> Regarding _Spark_ vs _Pandas_, it depends on how big of a processing job would be to process a study, or the business logic we need to run. If the _per study_ processing requirements is not that big, and it's quite isolated (low or no dependencies), we could go for pandas based implimentation.
For this particular process the atomic unit would be studies. However there could be significant differences in size between summary stats. I'll need to take a look how these files really look.

**Comment by addramir** [comment]
Can we close it?
