### ISSUE TITLE
Weird behaviour in Download format chips

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2899]
**Describe the bug**
In the Downloads page, chips informing the dataset format keep adding up after using the search bar.  

![image](https://user-images.githubusercontent.com/45119610/223386627-4e286bb6-5ec8-45df-9396-b10c3cd442a5.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/downloads
2. Search for "evidence" - 2 chips are added
3. Clear the search bar, evidence has 4 chips.
4. Search for "evidence" again - 2 more chips are added
5. Clear the search bar, evidence has 6 chips

**Additional context**
Only the last 2 chips are usable, so chips are added on the left.

**Comment by prashantuniyal02** [comment]
This issue has been fixed in the Platform 23.09 release
