### ISSUE TITLE
Search function only parses part of the search term and does not refresh properly (Platform)

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2902]
**Describe the bug**
The search function in the Platform does not always search the whole input term, returning very variable results. Also, the search does not always update when typing in a new term. 

**Observed behaviour**
When searching for a disease term in the Platform, for example 'Glycogen storage disease', the actual understood term is very variable. I have attached some screenshots of the term I typed in, and the variety of results I got (each time, I typed in the same term, glycogen storage disease, and hit return). I also attached a screen recording of the odd search behaviour when trying different terms.

Note, this only happens when I hit return, rather than clicking on the term suggested by the search. I tried this on Chrome and Safari with similar results. 

<img width="1440" alt="Screenshot 2023-03-07 at 18 53 12" src="https://user-images.githubusercontent.com/73692302/223524633-b6b4efd3-a7c5-49e0-81f8-5a09aafb6607.png">
<img width="1440" alt="Screenshot 2023-03-07 at 18 53 29" src="https://user-images.githubusercontent.com/73692302/223524658-476a0a63-1d27-437f-b3dd-0fdf08b2bde7.png">
<img width="1440" alt="Screenshot 2023-03-07 at 18 54 47" src="https://user-images.githubusercontent.com/73692302/223524673-415325a7-940b-434b-b0ce-59dafe4d3fa7.png">
<img width="1440" alt="Screenshot 2023-03-07 at 18 53 56" src="https://user-images.githubusercontent.com/73692302/223524694-127f2b74-5ebd-4719-b65b-6bca16cbc9fc.png">

https://user-images.githubusercontent.com/73692302/223524833-42cf4147-46d2-4fad-b4e1-11f4c5429e32.mov

**Expected behaviour**
The search function should understand the whole of the search term, returning the same list of results every time. It should refresh to show the list of results to the latest search term when a user inputs a new term.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[platform.opentargets.org](https://platform.opentargets.org/)'
2. Type a search term
3. Repeat

**Comment by HelenaCornu** [comment]
Also I just realised the 404 page has a link to the helpdesk. Please could we remove this?

**Comment by prashantuniyal02** [comment]
This issue has been resolved.
