### ISSUE TITLE
Remove Helpdesk and old search on 404 page

### ISSUE THREAD

**Issue by chinmehta** [opentargets/issues#2903]
**Describe the bug**
On "404 not found page" still have old help desk email and old search component.

**Expected behaviour**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to: [Ope Target Platform](https://platform.opentargets.org/)
2. Search for any non realistic term
3. Hitting enter will ends up on 404 page

**Additional context**
![image](https://user-images.githubusercontent.com/22376522/224082156-593c0fe5-3674-4a0d-86e6-8cdca7397d57.png)

**Comment by buniello** [comment]
@chinmehta has worked on a couple of designs for the new "404 not found page" w/o helpdesk email and with new search component. The styles are consistent with the new error pages he has designed recently.
We agreed on an image and a style for the page already (we can re-visit tomorrow in the office as well)
text should be as suggested below (slightly modified from Chintan's text suggestions):
```

404: Page not found 
We could not find anything in the Platform that matches "abcdefg"  -- **(current text for 404 not found)**
You deserve a fresh start. Maybe our [FAQs] or our [Community page] can help!
Or you can
[go back to the Home Page tab]

```

**Comment by prashantuniyal02** [comment]
@chinmehta The Documentation or Community page link do not seem to be working on the 404 page.

![image](https://github.com/opentargets/issues/assets/122870584/e3b36b2f-8e5e-4f18-bbe7-7fa05804eccc)
