### ISSUE TITLE
Google Search Console Verification 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2905]
As already discussed with @carcruz and @chinmehta, we would need to register both Platform and Genetics to the [Google Search console](https://search.google.com/search-console/welcome?utm_source=about-page).

This ticket is created for our records

**Comment by d0choa** [comment]
@buniello did you get access?

**Comment by buniello** [comment]
Not yet, @chinmehta tried but needs @carcruz to take a look

**Comment by LucaFumis** [comment]
As @d0choa was suggesting, it seems that Google Tag Manager can be used for verification. 

<img width="607" alt="Screenshot 2023-09-21 at 10 12 29" src="https://github.com/opentargets/issues/assets/8592363/e3716649-b775-4bb6-906c-239b972d0631">

From what I understand it might then be possible to connect it to Console (probably going via Analytics: i.e. connect Analytics to TagManager first, then Analytics to console?).
https://www.freshegg.co.uk/seo/setting-up-google-search-console/

**Comment by buniello** [comment]
thanks @LucaFumis - let's try to make this happen together next week in the office

**Comment by buniello** [comment]
Both Google Tag Manager and Google Analytics fail to verify our access to the Google Search Console.
After discussion in the office, @mbdebian will take a look at the Google HTML file (needed for the Search console verification as per screenshot above) and will decide whet's the best place to upload the file in our Platform repository.

**Comment by buniello** [comment]
https://github.com/opentargets/ot-ui-apps/pull/259/commits/f2b232a52a57625b50c092c7742734cf7b6572db
