### ISSUE TITLE
Fixing hardcoded release in shared module in evidence datasource parsers

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2907]
In the [evidence parser repo](https://github.com/opentargets/evidence_datasource_parsers), the shared `evidence.py` module has the following [lines](https://github.com/opentargets/evidence_datasource_parsers/blob/7c7b5a0f50cf2296c220d55830b10d69e0310b5c/common/evidence.py#L97):

```python
remote_trait_mappings_url = (
    'https://raw.githubusercontent.com/opentargets/curation/22.09.1/mappings/disease/manual_string.tsv'
)
```

Hardcoding the release in the URL poses a problem in the evidence generation, because to keep it up to date, it needs to be updated all the time. Ideally the curation release should be taken as a parameter and changed dynamically. Maybe we can assume a `latest` release of some sort.

**Comment by ireneisdoomed** [comment]
@prashantuniyal02 Please include this for the release intentions
