### ISSUE TITLE
The 'Gene Prioritisation' page jumps to an error after showing the page for a few seconds

### ISSUE THREAD

**Issue by MayaGhoussaini** [opentargets/issues#2910]
**Describe the bug**
The 'Gene Prioritisation' page jumps to an error message after showing the page for a few seconds. 

**Observed behaviour**
The different sections relevant to the study/locus appear for a few seconds  then disappear and get replaced by an error message.

**Expected behaviour**
The gene prioritisation page should load with the different sections on it. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://genetics.opentargets.org/study-locus/FINNGEN_R6_L12_DERMATITISECZEMA/20_63697100_T_C'
2. The results will appear for a few seconds 
3. An error message appears and everything on the page disappears

**Additional context**
Problem spotted by BMS and eQTL Catalogue team

**Comment by DSuveges** [comment]
The JS console says: `index.8a70f9f1.js:27 TypeError: Cannot read properties of undefined (reading 'gwasCredibleSet__GCST90025992__20_63696914_C_T')`

It seems the credible set dataset has some unexpected type in any of the entries.

**Comment by DSuveges** [comment]
The query looks very strange. It seems all colocalizing credible sets are specified one by one, making the query over 4000 lines long. Can it be a problem?

**Comment by buniello** [comment]
We got another user reporting this bug. @MayaGhoussaini and @d0choa suggested this workaround on slack:
```

In terms of use cases for this page, people mostly use it to find the most likely causal genes at their locus of interest using L2G and whether coloc supports the findings. The credible set part is important but less so. I think truncating that section and adding a message when there is too many credible sets is a fair temporary solution while waiting for the refactored version

```
Will discuss the implication with the FE team - also assigning this to @carcruz for further discussion with the team

**Comment by prashantuniyal02** [comment]
@chinmehta @buniello [This](https://genetics.opentargets.org/study-locus/FINNGEN_R6_L12_DERMATITISECZEMA/20_63697100_T_C) page still shows an error.
![image](https://github.com/opentargets/issues/assets/122870584/f02348a6-405e-4983-b40c-2de7f57c783d)
