### ISSUE TITLE
Text-mining widget 'remembers' detail expansion when clicking through results pages

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2912]
**Describe the bug**
When browsing the Europe PMC text-mining widget on an associations page, the widget 'remembers' which publications of a certain rank were expanded, and displays that expansion for the next set of results when clicking through. This does not occur in the bibliography widget on entity profile pages. 

**Observed behaviour**

https://user-images.githubusercontent.com/73692302/226324816-c4763245-85f9-4386-8a1a-38a408015e1c.mov

**Expected behaviour**
When clicking to see the next set of results, the widget should reset so that the details are not automatically expanded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an associations page, for example https://platform.opentargets.org/evidence/ENSG00000006071/MONDO_0005148
2. Navigate to text-mining widget
3. Expand some of the publications, e.g. 'Show match details' or 'Show abstract'
4. At the bottom of the widget, click to see the next set of results.
5. See error: publications are expanded.

**Comment by prashantuniyal02** [comment]
This issue has been resolved.
