### ISSUE TITLE
Follow up tasks from the AOTF UX testing - Associations page

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2913]
This ticket summarises the prioritised tasks from the first round of [UX testing ](https://docs.google.com/document/d/1nEJTwEy_Uo24ZBftZ3Zp17E78OlO4uKEUxpKxCwLByo/edit#heading=h.xa04c8sxq0ic)for the Associations on the Fly feature (Association Page)
Annalisa and Carlos will lead further prioritisation and implementation work on these.

**MVP I Phase**

- [x] Data source headers may not be explanatory enough. Suggestion: adding links to data sources websites or adding an explanation/tooltip with when hovering on data source name. Annalisa working on the language for these.
- [x] When a list of diseases is returned, it is difficult to see full name of disease. Suggestion: full name shown when hovering.
- [x] Discussion on colours is needed - Carlos to explore different options to decouple associations colour to target prioritisation scores colour 
- [x] Create a new PPP tab for "associations on the fly" feature - with task icon for experimental flag
- [x] Documentation needed (for Annalisa)
- [x] Developing a "Required datasource" functionality for the new association page [#2864](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/gh/opentargets/issues/2864)
- [x] Modify a couple of headers/tabs with style inconsistencies:
1) `OT Genetics Portal` header BECOMES `OT Genetics`
2) `OTAR CRISPR` header BECOMES `OT CRISPR` for consistency
3) `Targets prioritisation` tab BECOMES `Target prioritisation` 
- [x] Adding an option/checkbox to set all the weights to 0 (on/off switch has been suggested). A suggested expansion of this would be to select/deselect all within a single aggregation (e.g. deselect all cancer data)

**Comment by prashantuniyal02** [comment]
Can we make the new association page as the default landing page and then if a user wants, they can choose to switch to the old page?

**Comment by buniello** [comment]
Just wanted to re-iterate on this ticket (for own records) that the from feedback from the partners it is clear that the feature
 `Adding option to save custom state of score sliders which remains consistent across pages` would be the most prioritised before the public release

**Comment by buniello** [comment]
Just a quick update on this ongoing ticket: we have already delivered a couple of tasks from the **MVP II phase** above (e.g. pinning targets) and will possibly deliver the `upload a list of targets` with the 23.12 release

**Comment by buniello** [comment]
A few feedback points from Ellie on the AOTF view:
-make Clingen ‘ClinGen’
- reorder to put Gene Burden next to OT Genetics (utilises UK BioBank and so associations are for similar traits, whereas ClinVar is generally for more rare diseases and so makes sense to be next to GeL PanelApp)
