### ISSUE TITLE
Rename "Inhibition" and "Activation" labels in Direction field of Safety Liabilities

### ISSUE THREAD

**Issue by inessmit** [opentargets/issues#2921]
As a user of the safety liabilities data I would like the data labels under the "Direction" field to be renamed from "Inhibition" and "Activation" to something more elaborate because since the integration of AOP-Wiki data these now also include `[downregulation|decrease|suppression]` and `[upregulation|increase|induction]` respectively.

## Background

The safety liabilities data provide the Direction of target interaction where available as "Inhibition" and "Activation". While these are appropriate for (small) molecule interactions (applicable to the curated Bowes etc. papers), integration of the AOP-Wiki data additionally considers the following related terms:

```
activation_pattern = re.compile(r"(?<!ant)Agonism|(?<!ant)agonist|Increase|Up Regulation|Upregulation|Upregulated|(?<!trans)Activation|Induction", re.IGNORECASE)

inhibition_pattern = re.compile(r"Antagonism|Decrease|Down Regulation|Downregulation|Downregulated|Inhibition|Suppression|reduced production|binding of inhibitor|binding of antagonist", re.IGNORECASE)
```

Especially up-regulation/induction and down-regulation/suppression refer to gene expression/protein level changes rather than molecular interaction, so it would be useful to clarify to the user that these are grouped together with the inhibition/activation.

## Tasks

- Choose new name, e.g. maybe one of "Inhibition or down-regulation", "Inhibition/suppression", "Inhibition/decrease" and "Activation or up-regulation", "Activation/induction", "Activation/increase"
- Rename the data labels (I assume the same way for all data, not distinguishing between curated safety target data vs AOP-Wiki data)

## Acceptance tests

1. When I go to the Safety data on a target page, e.g. https://platform.opentargets.org/target/ENSG00000169083, under 'Dosing effects', I can see the new names under "Direction" when hovering over.
2. Same new labels in downloads

**Comment by BZdrazil** [comment]
@inessmit can we get some stats on how often each one of the terms is used in AOP-wiki?

**Comment by inessmit** [comment]
Inhibition/Activation is also the most common in AOP-Wiki, followed by Increase/Decrease, and then "Up Regulation"

**Term 	Number of key events**
Inhibition	97
Activation	76
Decrease	33
Increase	31
Up Regulation	15
Induction	12
Suppression	7
Agonism	6
Antagonism	6
Down Regulation	6

Of the rows with Increase/Decrease, most are about expression or activity

expression/mRNA	12
activity	10
production	6
translocation	2
binding	1
peptide	1

Others just mention the protein name, e.g. "Decrease, Translocator protein (TSPO)" or "Up Regulation, CD36"

**Comment by BZdrazil** [comment]
Thanks!
