### ISSUE TITLE
Missing data in OT Genetics "Associated studies: locus-to-gene pipeline" csv/tsv table

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#2926]
**Describe the bug**
Users downloading the table for "Associated studies: locus-to-gene pipeline" from a OT Genetics UI page are missing data in the "Study N Cases column"

**Observed behaviour**
When downloading the file associated with an "Associated studies: locus-to-gene pipeline", there is no data in the "Study N Cases" column. However, some of the cells in this column should have values, based on the results of the equivalent API query.

See the Community post here: https://community.opentargets.org/t/question-about-the-tsv-file-of-the-associated-studies-locus-to-gene-pipeline-section/1027

Example for ENSG00000171522 gene and GCST011501 study:

`r$> otargen::studiesAndLeadVariantsForGeneByL2G(genes = "ENSG00000171522", pvalue = 1, l2g = 0) %>% filter(study.studyId == "GCST011501") %>% sele
    ct("study.studyId", "study.nCases")
✔ Connecting the database... [9ms]
✔ Downloading data for ENSG00000171522 ... [5.9s]
  study.studyId study.nCases
1    GCST011501         7045`

**Expected behaviour**
For studies for which this data is available, there should be values in the "Study N Cases" column.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://genetics.opentargets.org/gene/ENSG00000171522'
2. Click on 'CSV' or 'TSV' in the first widget (Associated studies: locus-to-gene pipeline)
3. Open the file
4. See error: missing data in Study N Cases column.

**Comment by LucaFumis** [comment]
From the Slack conversation on this bug: 
The problem seems to be here: https://github.com/opentargets/ot-ui-apps/blob/main/apps/genetics/src/sections/gene/L2GPipeline/L2GPipelineQuery.gql#L14-L23
we don’t specifically request the `nCases` field so it’s missing from the response.
I guess it’s possible that `nCases` was added to the table at a later stage, but the query was not updated

**Comment by LucaFumis** [comment]
Done and merged into `main` branch. Closing.
