### ISSUE TITLE
Designing a public CRISPR widget

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2928]
As we make progress with processing and interpreting CRISPR results from 

Brain CRISPR #2821
BIOGRID #2920

we need to design a public CRISPR widget for the 23.06 release - keeping in mind that the PPP will host both a public and a pre-publication widget.

This issue will be completed with widget specifications once the schema for these datasets is finalised, as discussed with @DSuveges.

Evidence schema (example from Brain CRISPR):
```
{
  "studyId": "Glutamatergic Neuron-CellRox-CRISPRi",
  "datatypeId": "sysbio",
  "datasourceId": "crispr_screen",
  "projectId": "crispr_brain",
  "studyOverview": "CRISPRi FACS screen for reactive oxygen species in human iPSC-derived glutamatergic neurons.",
  "experiment": "WT CRISPRi-iPSCs were transduced with genome-wide CRISPRi-v2 sgRNA libraries. Two days after infection, the cells were selected for lentiviral integration using puromycin (1 g/mL) for 3 days as the cultures were expanded for the screens.",
  "cellType": "Glutamatergic Neuron",
  "contrast": null,
  "diseaseFromSource": "neurodegenerative disease, ageing",
  "diseaseFromSourceMappedId": "EFO_0005772",
  "targetFromSource": "MIS12",
  "pValue": 0.1350578615532632,
  "statisticalTestTail": "lower tail",
  "resourceScore": -3.5780208400785147
}

```

**Comment by DSuveges** [comment]
@buniello for your interest: I have reviewed the ot_crispr dataset schema and made a few changes to make sure the two are more similar. Now it looks like this:

```json
{
  "studyId": "Glutamatergic Neuron-Survival-CRISPRi",
  "datatypeId": "sysbio",
  "datasourceId": "crispr_screen",
  "projectId": "crispr_brain",
  "crisprScreenLibrary": "Genome-wide CRISPRi-v2",
  "studyOverview": "CRISPRi survival screen in human iPSC-derived glutamatergic neurons (standard medium).",
  "cellType": "Glutamatergic Neuron",
  "literature": [
    "34031600"
  ],
  "diseaseFromSource": "essential genes / neurodegenerative disease",
  "diseaseFromSourceMappedId": "EFO_0005772",
  "contrast": "Survival",
  "targetFromSourceId": "SOD2",
  "resourceScore": 0.0029283011705045,
  "statisticalTestTail": "lower tail",
  "log2FoldChangeValue": -24.05642773885583
}
```

- The type of the datasource, consistent with projectscore, is `sysbio`.
- The identifier of the datasource is `crispr_screen` that would pool different sources eg. Brain CRISPR, BioGRID ORCS etc. (similar to gene burden)
- The identifier of the project tells which source the screen was integrated from. In this case `crispr_brain`. This would allow both the user and the frontend to connect the piece of evidence. 
- The studyId identifies the screen in the project. In this case it allows the frontend to generate the link to crisprBrain page: [Glutamatergic Neuron-Survival-CRISPRi](https://crisprbrain.org/simple-screen/?screen=Glutamatergic%20Neuron-Survival-CRISPRi)
- There are other screen specific fields to contextualise the experiment: `crisprScreenLibrary`, `cellType`
- Contrast is either curated and pulled from the disease mapping file or pulled from the `Phenotype` column in the study table. (which is always the case at the moment, as we have no curation for any of the studies).
- `diseaseFromSource` and `diseaseFromSourceMappedId` are all curated by our experts. The mapped identifier is the EFO id. (if the `diseaseFromSource` could be mapped to multiple EFO terms, the evidence is exploded).
- `targetFromSrouce`  - Hits are coming from the already annotated gene lists from CRISPR Brain. Where the annotation for the genes is either positive or negative hit.
- `statisticalTestTail` is inferred by the annotation  positive or negative hit
- `resourceScore` is the p-value of the gene
- `log2FoldChangeValue` this is the phenotype score. I'm not 100% sure if this is indeed log2 fold change.

**Comment by buniello** [comment]
First draft of CRISPR Screens(public) widget - please see data schema above for reference 

**CRISPR Screens** 
CRISPR knockout screens from public CRISPR datasources, associating  "targetFromSourceId" and CRISPR results. Sources: "projectId" (link) e.g. [CRISPRBrain](https://crisprbrain.org/) (will be a comma separated list when data from more sources will be integrated)

**Table**
**Reported disease**: "diseaseFromSource" (Link to “diseaseFromSourceMappedId” disease page - can be multiple links for multiple mappings)
**Study Identifier**: “studyId" (Link link to CRISPRBrain study page: e.g. [Glutamatergic Neuron-Survival-CRISPRi](https://crisprbrain.org/simple-screen/?screen=Glutamatergic%20Neuron-Survival-CRISPRi)) - will have different identifiers from different sources when integrating more sources 
**Contrast/Study overview**:  "contrast”/ "studyOverview" (tooltip: **SCREEN LIBRARY**: "crisprScreenLibrary")
**Cell type**: "cellType"
**Log2 fold change**:  "log2FoldChangeValue"
**Significance**:  "resourceScore" (with tooltip "statisticalTestTail”)
**Source**:  "projectId" (link to source e.g. CRISPRBrain) - we plan to integrate  data from multiple sources with time, so this link can vary depending from the source
**Publication**: "literature" (link to EPMC similar to [OT Genetics widget](https://platform.opentargets.org/evidence/ENSG00000145864/EFO_0003843))

**Comment by buniello** [comment]
@LucaFumis:
 ` "datatypeId": "sysbio" `
Position of new data source on the "Association on the Fly" page: before `Project Score` (first data type for the sysbio aggregation)

<img width="1294" alt="Screenshot 2023-06-05 at 12 33 41" src="https://github.com/opentargets/issues/assets/30833755/aa06ba01-1d4b-4972-bdbc-88fb0a50fdf0">

**Comment by buniello** [comment]
Thanks @LucaFumis for the first version of the CRISPR Screens widget - it looks good! Just a few minor comments, as already discussed on Slack - 
`Contrast / Study overview` : delete full stop at the end
`log2 fold change`: format (i.e. trim)
`source`: format it to CRISPBrain (same as link in the header) 
`diseaseFromSource`: when the record returns "essential genes / neurodegenerative disease" - visualise as [neurodegenerative disease](https://lf-public-crispr--ot-platform.netlify.app/disease/EFO_0005772) (essential genes)
or 
[neurodegenerative disease](https://lf-public-crispr--ot-platform.netlify.app/disease/EFO_0005772) (tooltip: essential genes)

**Comment by LucaFumis** [comment]
Thank you @buniello - I've updated the preview with the changes we've discussed today and the new datasource: looks to be working correctly in both AOTF and classic associations.
I have to fix the table download.

<img width="1176" alt="Screenshot 2023-06-06 at 22 13 52" src="https://github.com/opentargets/issues/assets/8592363/d402d8e7-d7a0-4139-b56e-919e34bda8af">
