### ISSUE TITLE
Incorrect link in documentation for pharmacovigilance

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2930]
In the pharmacovigilance section:
https://platform-docs.opentargets.org/drug/pharmacovigilance#computational-pipelines-and-datasets

The link that points to blacklisted events should use this path:
https://github.com/opentargets/platform-etl-openfda-faers/blob/master/src/main/resources/blacklisted_events.txt

**Comment by d0choa** [comment]
[PR409](https://app.gitbook.com/o/-LC3OlEMulAutIN2QOro/s/-MU4dMxOmLaVNWfVNvpC/~/changes/409/drug) ready for you to review @buniello:

**Comment by buniello** [comment]
approved!
