### ISSUE TITLE
Set Api and Data version information to be dynamically loaded at deploy time

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#2934]
As a **developer** I want **the version of the API to be configurable** because **right now it has to be hardcoded in the source code**

## Background

The API exposes an endpoint called meta which contains the information related to the release versioning. This information is used in the FrontEnd and currently it has to be set in the application.conf in the keys: 

```
meta {
    name = "Open Targets GraphQL & REST API Beta"
    apiVersion {
      x = "23"
      y = "04"
      z = "0"
    }
    dataVersion {
      year = "23"
      month = "04"
      iteration = "0"
    }
  }
```

There's configuration keys in the terraform projects that hold this information and the values should be taken from these.

## Tasks

- [x] Update the API to read the values from a dynamic source
- [ ] Update the terraform keys to inject the values into the API

## Acceptance tests

How do we know the task is complete? 

1. The values exposed in the meta endpoint are the ones set in the terraform config keys

**Comment by mbdebian** [comment]
@remo87 , I'm scoping this one for the upcoming release, as the fix should not be too complex, and it may use the genetics API as an example.
Thanks

**Comment by remo87** [comment]
No need to update terraform as the values were already being injected
