### ISSUE TITLE
Suggest PPP to public platform visitors arriving from restricted IPs 

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2936]
We want to make users landing on the public platform from whitelisted IPs aware they could navigate to PPP.

Considerations:
- This would always be an option for the user and never a forced redirect to PPP.
- The UI (e.g. banner, popup, etc.) would need to be obvious but not intrusive once discarded. 
- We probably don't want this feature to be active by default so we can prevent it from triggering on PPP or private instances. Instead, it could be activated through configuration in the deployment context or by google tag manager.

@buniello and @carcruz can you include any further considerations that I might have missed?

**Comment by buniello** [comment]
assigning this to @prashantuniyal02

**Comment by mbdebian** [comment]
We can easily address this following these steps:
- From the frontend, make a call to the PPP [API](https://api.partner-platform.opentargets.org/), just a _GET_ on '/' will be enough
- If you get HTTP response code **403**, you can't access PPP, thus, **do not show** the pop-up
- **else**, you can access PPP, thus, **show the pop-up**

**Comment by prashantuniyal02** [comment]
This has been implemented
