### ISSUE TITLE
Customise 403 error page when trying to access PPP from unauthorised networks

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2938]
A vague "403 Forbidden" message is returned when accessing PPP from outside the authorised networks.

It could be good to display a page with a message explaining that it requires privileged access and some contact to resolve any access issues.

**Comment by buniello** [comment]
We could display this text:
```

You are trying to access the Open Targets Partner Preview Platform. 
If you are a member of the Open Targets Consortium and would like to request access to this partner-only resource, 
please contact us at partner-support@opentargets.org

```

**Comment by chinmehta** [comment]
FE is planning to create an HTML to serve in case of 403 message. Need some BE help to implement it.

**Comment by buniello** [comment]
Thanks @chinmehta! @remo87 could you please take a look at this?

**Comment by prashantuniyal02** [comment]
@mbdebian, the FE work is done. Over to you for the BE work.

**Comment by mbdebian** [comment]
The backend work is done and deployed

**Comment by prashantuniyal02** [comment]
Going forward we should also display an error message to people losing access to a partner network who left the application tab open or cached. If not, this might create a false impression that things are not working on our end when in fact they lost access to the network.

**Comment by mbdebian** [comment]
The redirection mechanism is implemented on PPP (dev and production) and the latest patch from web team (_v0.4.2) is being deployed in [platform](https://platform.opentargets.org/unauthorized.html)
