### ISSUE TITLE
Improve structure and accessibility of the PPP project specific documentation

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2939]
As a user, I would like to easily access the PPP project specific documentation from the OTAR CRISPR, ENCORE and Validation Lab  widgets. At the moment, the widget headers all link to the Intranet Home Page:
**EXAMPLE from the Encore Widget**:
Interim data from dual-knockout screens generated by the [OTAR2-062 ENCORE project](http://home.opentargets.org/OTAR2062), associating MLH1 and Open Targets ENCORE. Source: [Open Targets](http://home.opentargets.org/)

## Background
We received the feedback below from GSK:

```

We received comments from folk who have tried to look at a couple of genes on the OT Platform that did have some annotation regarding readouts from OTAR-related screens (specifically OTAR2054).  It was really challenging to understand the output that was shared given that they were not a member of the project team.  Providing some information about the experimental context, terms, and metrics utilized such that the data can be meaningfully interpreted by individuals not associated with a given project. 

```

## Tasks

- [x] Review the structure of the PPP project specific documentation on the Intranet (currently project specific documentation are nested in pdf files. [Example for OTAR033](http://home.opentargets.org/sites/default/files/inline-files/PPP_OTAR033%20Keratinocytes_0.pdf) @prashantuniyal02 @sarahyoung3 (already discussed with Prashant)

- [ ] Replace the Source "Open Targets" link in the widget headers with the new PPP specific documentation page, containing clear links to the project specific documentation (FE)

OPTIONAL: review the schema in widgets to assess whether we could improve interpretability by adding more info/new column

**Comment by prashantuniyal02** [comment]
Hi @buniello and @chinmehta, here is the [document](https://docs.google.com/document/d/1B4C1vqad6-8DzWEdEtRgoxE7WMn5Fs6pqCT1PUT7W7Q/edit) containing the links.

**Comment by buniello** [comment]
Thanks for the placeholder links @prashantuniyal02.

@chinmehta, as we briefly discussed already, the unique project links (from doc above) have to be replaced at the top of the OTAR projects, ENCORE and Validation Lab PPP widgets. Please do let me know if you have any questions!

<details>
  <summary>Example of Widget API query</summary>

```

query CrisprQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  disease(efoId: $efoId) {
    id
    evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["ot_crispr"]
      size: $size
    ) {
      rows {
        disease {
          id
          name
          __typename
        }
        projectId
        contrast
        studyOverview
        cellType
        cellLineBackground
        crisprScreenLibrary
        statisticalTestTail
        resourceScore
        log2FoldChangeValue
        diseaseCellLines {
          name
          __typename
        }
        releaseVersion
        __typename
      }
      __typename
    }
    __typename
  }
}


{
  "ensemblId": "ENSG00000168395",
  "efoId": "MONDO_0005180",
  "size": 1
}

```

</details>

<details>
  <summary>API response with **projectId** field to identify unique links to replace in the widget header  </summary>

```

{
    "data": {
        "disease": {
            "id": "MONDO_0005180",
            "evidences": {
                "rows": [
                    {
                        "disease": {
                            "id": "MONDO_0005180",
                            "name": "Parkinson disease",
                            "__typename": "Disease"
                        },
                        "projectId": "OTAR035",
                        "contrast": "Enrichment of gRNAs (KO) in the survival of dopamine neurons against oxidative stress (rotenone)",
                        "studyOverview": null,
                        "cellType": "human iPSC-derived dopaminergic neuron",
                        "cellLineBackground": "KOLF2-C1",
                        "crisprScreenLibrary": "Kosuke v1.1 (Behan et al., 2018)",
                        "statisticalTestTail": "upper tail",
                        "resourceScore": 0.0084696,
                        "log2FoldChangeValue": 0.53881,
                        "diseaseCellLines": null,
                        "releaseVersion": "OTAR035-44256",
                        "__typename": "Evidence"
                    }
                ],
                "__typename": "Evidences"
            },
            "__typename": "Disease"
        }
    }
}

```

</details>

![Screenshot 2023-08-24 at 14 48 33](https://github.com/opentargets/issues/assets/30833755/0c113758-41e2-436d-a938-5b1a27962fbf)

**Comment by prashantuniyal02** [comment]
@chinmehta also update the project links in the widget present in the disease profile page.

**Comment by prashantuniyal02** [comment]
works correctly in the latest PPP dev
