### ISSUE TITLE
Adding file schema/headers to the data downloads page

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2940]
As a user, I would like to have easy access to the schema/format of the files we make available for [download in Platform](https://platform.opentargets.org/downloads).
This issue was raised by multiple users.

There are a couple options we could explore: 

1) adding an column to the data downloads which we could name `view schema` with clickable `json` and `parquet` chips (same as the `format(s`) column)  - when clicking on either chip, a pop up with the correspondent schema opens

2) we could add a `schema` section to the pop-up window that opens when clicking on existing chips in the `format(s)` column

any other ideas??

**Comment by d0choa** [comment]
There was a failed attempt to get this done in #1704. Revisiting the problem with fresh eyes might be good. All the schemas are available in the same JSON used to populate the downloads page, so it's mostly a FE implementation.

My original idea was to have a table with all the columns in all the datasets, so if you search for `disease` you see all the columns in all datasets that have anything to do with `disease` (e.g. `diseaseId`, `diseaseFromSource` etc.). Keep in mind we don't have documentation for every column but that's something we could try to get done collectively and include it in the codebase.

As I said, it would be good to rethink from scratch, whether the above makes any sense to the users.

**Comment by buniello** [comment]
Discussed with @carcruz today - h's going to think about the proposed options

**Comment by buniello** [comment]
Briefly discussed this feature with the FE team today - remains a 'could' for this 23.09 release.

**Comment by buniello** [comment]
@chinmehta and myself have just met to discuss the easiest way forward for this issue. We decided to proceed with option 1. above.
In summary, a new column will be added to the [data downloads page](https://platform.opentargets.org/downloads) - new header is `Schema(s)`. 
The column will display exactly the same chips as the `Format(s)` column but the clicking content will be different. Upon clicking on each chip, a pop up displaying `JSON schema` or `Parquet schema` will appear (same styling as other pop-ups on the page).

The metadata files can be downloaded from here: `gsutil cat 'gs://open-targets-data-releases/23.06/output/metadata/**/*.json' `
Or from the [FTP directory](http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/23.06/output/metadata/) (as explored with Chintan)
`

**Table proposal below:**

<img width="1287" alt="Screenshot 2023-08-25 at 13 12 17" src="https://github.com/opentargets/issues/assets/30833755/4d313474-c367-4428-9212-1cde9aa030d8">



**Pop-up on clicking**

<img width="436" alt="Screenshot 2023-08-25 at 14 51 03" src="https://github.com/opentargets/issues/assets/30833755/d62471af-9221-4839-8fed-64373756f4c1">

**Comment by prashantuniyal02** [comment]
works in the latest dev
