### ISSUE TITLE
Scoping linking out to ProtVar (Variant level) in the Platform

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2948]
We should scope a first iteration of integration of [ProtVar](https://www.ebi.ac.uk/ProtVar/) data/info into the Platform.

**DISCUSSED**:
We can add a "ProtVar" link to all the variants (`genetic associations` data type)  in the Platform that show a `missense variant` record in the `Functional consequence` column. 
The "ProtVar" link will have further information on the functional consequence/mechanism linking a Variant/Target/Disease.

**Task**
- [ ] The `Functional consequence` column will be populated with a "ProtVar" chip link when  a `missense variant` record in  is returned. 
See here Example of a variant query page from [genomics coordinates](https://www.ebi.ac.uk/ProtVar/query?chromosome=19&genomic_position=1010539&reference_allele=G&alternative_allele=C) - aka `"variantId" field` (see API example query below)
- The direct variant links can be found here: https://www.ebi.ac.uk/ProtVar/help#direct-variant-link.

Draft example (please note the chip can alternatively be white filled with blue margins and blue text, this is just a test example) -

<img width="1239" alt="Screenshot 2023-06-05 at 13 02 25" src="https://github.com/opentargets/issues/assets/30833755/fa1beebe-ede2-48d6-9e78-6e5446210cd5">

**Comment by buniello** [comment]
@carcruz you asked me to remind you of this ticket closer to the release

**Comment by buniello** [comment]
The chip looks good - discussing now with the team possible twitching of the tables e.g. including the VEP funct consequence prediction also in a chip. Also discussing if we can add a ProtVar link for stop_gained entries.

**Comment by LucaFumis** [comment]
The chip link to ProtVar has also added to the UniProt Variant widget (new column). QTL column (in OT genetics widget) has also been styled with a chip. All work has been merged.

**Comment by d0choa** [comment]
All working in dev. There will be more follow-ups on variant consequences.
