### ISSUE TITLE
Question wrt to the new literature ETL output for 23.06 release

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2951]
Daniel did a quick comparison between the number of publication (unique pmid/pmcid) per year in the following datasets:

- ETL output in production for the 23.02 release. (old_etl)
- New ETL run (new_etl)
- Ricardo’s test run done a few weeks ago (Ricardos_output)
- The new raw, pre-ETL dataset read from JSON in gs://otar025-epmc/ml02/ (new_raw)

This has led to doubts about literature ETL output because there are 5k less evidence for EPMC. Overall 3k less literature references.

There might be a lot of repeated/updated PMIDs in the old pipeline which are not present in the new run.

**Comment by DSuveges** [comment]
Ok, now the above issue is resolved. The current evidence shows the following numbers:

|                   |    new_evidence |     old_evidence |
|:------------------|----------------:|-----------------:|
| evidence count    | 9.42M           |  5.32M           |
| association count |  1.3M           |   887k           |
| disease count     |  9276           |   8725           |
| target count      | 21867           |  19800           |

**Summary:**
- The number of publications increased.
- The distribution of publications across years looks good.
- The number evidence grew significantly as well as the associatins.
