### ISSUE TITLE
Building a download functionality for the target prioritisation view 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2958]
As a user/partner, i would like to be able to download data/scores from the `target prioritisation view` in a similar way to the `association view` (tsv and json)

## Background

After gathering additional feedback from our partners and discussing the functionality with @carcruz, we realised this was planned but never prioritised. 
The task is feasible for the BE team. It is probably possible to download the `target prioritisation` results through the current `download` tab on the `association view` - together with the associations data.

**Comment by buniello** [comment]
We discussed adding a ProtVar chip linking out to the relevant page. This will prepare the table to the re-design planned for when the directionality datasets will be ready for integration. I will also update the tasks list above as a reminder.

**Comment by prashantuniyal02** [comment]
This task has been addressed in #3063
