### ISSUE TITLE
Drug pages pointing to 404 page in development

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2964]
As reported by @buniello, some drug pages are pointing to a 404 page (e.g. [CHEMBL3353410](https://platform.mbdev.opentargets.xyz/drug/CHEMBL3353410)). We can find the drugs in search but when clicking on them the page tries to load but fails into a 404 page.

When inspecting the API query:

```
query drugQuery {
  drug(chemblId: "CHEMBL3353410") {
    name
    id
		crossReferences {
      source
      reference
    },
  }
}
```

the inspector reports:

```
{
    "data": {
        "drug": null
    }
}
```

However, a direct query to the API reports the proper response:
```
{
  "data": {
    "drug": {
      "name": "OSIMERTINIB",
      "id": "CHEMBL3353410",
      "crossReferences": [
        {
          "source": "DailyMed",
          "reference": [
            "osimertinib%20mesylate"
          ]
        },
        {
          "source": "drugbank",
          "reference": [
            "DB09330"
          ]
        }
      ]
    }
  }
}
```

It looks like some layer of caching is messing up the application but it would be good to discard any other issues.

**Comment by d0choa** [comment]
The problem seems to be still there after the latest deployment

**Comment by mbdebian** [comment]
I'll look into the different caching layers, because the development deployment is not supposed to use any caching on the infrastructure side of things.

**Comment by mbdebian** [comment]
I have implemented an initial solution for this in the infrastructure provisioning
