### ISSUE TITLE
Adjust "Max phase" for drugs with a null and a -1 max phase

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#2969]
**Describe the bug**
A null `maximumClinicalTrialPhase` for a drug has now semantic meaning, i.e. the drug is in preclinical development. Similarly:
- when `maximumClinicalTrialPhase == -1`, this means that the phase is unknown
- when `maximumClinicalTrialPhase == 0.5`, this means that the phase is early phase I
We want to adjust the webapp to reflect this.

**Observed behaviour**
- **Null**: CHEMBL292303 is a drug whose maximum clinical phase is preclinical. Since this is represented with a `null`, the field "Max phase" is missing from the drug card.
![image](https://github.com/opentargets/issues/assets/45119610/30b20945-506b-45a5-8b64-64c454625cf9)

- **-1**: CHEMBL31601 has an unknown maximum phase. Since this is represented with the value `-1`, the field "Max phase" is not really informative.

- **0.5**: CHEMBL4802264 is a drug whose maximum clinical phase is early phase I. Since this is represented with the value `0.5`, the field "Max phase" is not really informative.

**Expected behaviour**
Adjust this in the FE to show the appropriate label:
- **Null**: we want to show `Preclinical` 
- **-1**: we want to show `Unknown`
- **0.5**: we want to show `1 (Early)`

**Additional context**
Related with #2950 
The API is returning the new phases appropriately.

**Comment by d0choa** [comment]
0.5?

**Comment by ireneisdoomed** [comment]
@d0choa Updated, thanks!

**Comment by prashantuniyal02** [comment]
Test these:

- [ ] 0.5: https://platform.mbdev.opentargets.xyz/disease/EFO_0007405 , https://platform.mbdev.opentargets.xyz/disease/EFO_0007046

**Comment by buniello** [comment]
Discussed with @ireneisdoomed: she is very kindly taking care of updating the platform docs with new chEMBL updates re clinical phases and all relevant info the suers may need

**Comment by ireneisdoomed** [comment]
Just reviewed this on our latest dev version. I consider this done.
