### ISSUE TITLE
Clinical signs and symptoms widget crashing in development

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2972]
As noted by @prashantuniyal02, the clinical signs and symptoms widget is crashing in development for pages like [melanoma](https://platform.opentargets.org/disease/EFO_0000756/associations).

The API response is apparently clean (to me), so we might need to diagnose what exactly is causing the widget to crash.

I could confirm the reason for crashing is not the same as #2923.

@chinmehta could you diagnose what could be going on?

**Comment by buniello** [comment]
this is still observed in current deployment

**Comment by buniello** [comment]
thank you @chinmehta for fixing this!

**Comment by prashantuniyal02** [comment]
[Clinical signs and symptoms widget](https://platform.dev.opentargets.xyz/disease/EFO_0000756) is working in the latest dev deployment. 
[#2923](https://github.com/opentargets/issues/issues/2923) is still crashing but as David mentioned the reason is different.
