### ISSUE TITLE
CFTR profile page crashes page in development

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2973]
The CFTR page simply crashes in current development:
https://platform.mbdev.opentargets.xyz/target/ENSG00000001626

Can we diagnose the issue in the FE level potentially failing nicely?

**Comment by mbdebian** [comment]
@chinmehta , would you mind trying different approaches on this? E.g.:
- Look at the console
- The networking exchange
- Cloning the ot-ui-app repository on a different folder and trying from there, to prevent any existing changes in your local that may not be in the reposiroty
- Getting the bundle from the release tag that is deployed in _mbdev_ (ask @remo87 ), and deploying that application in local, behind anything that can serve it to your browser

Please, let us know your findings

Thanks!

**Comment by chinmehta** [comment]
closing duplicate bug. main issue: https://github.com/opentargets/issues/issues/2980
