### ISSUE TITLE
Target profile pages crash in latest development environment 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2980]
Assuringly all target profile pages are crashing in dev. 
Examples:

https://platform.dev.opentargets.xyz/target/ENSG00000105397
https://platform.dev.opentargets.xyz/target/ENSG00000073756
https://platform.dev.opentargets.xyz/target/ENSG00000171862
https://platform.dev.opentargets.xyz/target/ENSG00000132471

With @mbdebian, we discovered this is due to a "new" error (QUICK PROTOCOL ERROR - see screenshot)

![Screenshot 2023-06-12 at 16 05 51](https://github.com/opentargets/issues/assets/30833755/216dfb70-d459-48ca-a678-6e8bbea80dd1)

**Comment by buniello** [comment]
@mbdebian is planning to cycle the infrastructure tonight and will keep us posted

**Comment by mbdebian** [comment]
I re-cycle the infrastructure, no changes have been made apart from moving from _mbdev_ back to _dev_, I don't understand why this is happening.

Is anybody looking into this from a different angle than just the backend?

**Comment by d0choa** [comment]
Pages work in netlify

**Comment by mbdebian** [comment]
Fixed!
