### ISSUE TITLE
Association page is breaking 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2983]
**Describe the bug**

The [association page](https://platform.dev.opentargets.xyz/evidence/ENSG00000133703/MONDO_0015280) is breaking for ENSG00000133703 and MONDO_0015280. The page starts loading then crashes. 

The JS console output:

```
TypeError: Cannot read properties of undefined (reading 'Gene2PhenotypeSummaryFragment')
Uncaught TypeError: Cannot read properties of undefined (reading 'Gene2PhenotypeSummaryFragment')
```

I couldn't find any graphql requests failing. The `EvidenceProfileQuery` certainly looks good.

**Comment by chinmehta** [comment]
this bug is fixed and merged with main, will need FE dev build. https://ot-platform-partner.netlify.app/evidence/ENSG00000133703/MONDO_0015280

**Comment by DSuveges** [comment]
Also, the target page doesn't crash either. Great @chinmehta!

**Comment by prashantuniyal02** [comment]
The [association page](https://platform.dev.opentargets.xyz/evidence/ENSG00000133703/MONDO_0015280) does not seem to be crashing in the latest dev. Hence closing this.
