### ISSUE TITLE
Prepare data export from OT Genetics Portal for Ensembl VEP - schema definition

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#2984]
Open Targets' locus to gene (l2g) prediction can inform VEP users if a queried variant is part of a GWAS loci and if that loci can be linked to a gene. 

**The scope of this ticket includes**:

- [ ] Solidify the expected data format - do we need to wrap study/disease info.
- [ ] Solidify the output schema so downstream work on VEP team's side is unblocked.
- [ ] Prototype logic, however productionized version of the code is not expected to be prepared due to the ongoing efforts on the genetics portal. 

**Formal requirements**:

- No schema in place to comply with.
- Variants are expected to be on GRCh38 (chr, pos, alt/ref alleles)
- Genes are identified by their Ensembl stable id. 
- To avoid losing associations because of obsoleted identifiers, gene symbols are also added. (based on Platform's target index from the corresponding Ensembl version)
- No specific format is defined (json? parquet?)
- No OT url is expected to be prepped if the link can be generated from components.
- Recommended outptu: bgzipped, tabixed .tsv file.

**Starting points**:

- locus/gene pairs returned only if the l2g score is above 0.5
- l2g prediction is exploded to all variants of the credible set.
- As a first iteration, we are only returning gene/variant pairs allowing linking to OT's variant page. The variant page shows all linked study/locus.

**Comment by DSuveges** [comment]
[Gist prototyping](https://gist.github.com/DSuveges/202013223749a028464532782b8d1a03) exported dataset.

**Comment by DSuveges** [comment]
Feedback from the Ensembl team we should change:

- Rename the file to finish in `.gz` instead of `.bz` (renaming is enough)
- Run tabix in a way to include the file header: `tabix -f -b2 -e2 -c chromosome OTGenetics.tsv.gz`

**Comment by d0choa** [comment]
do we close this @DSuveges?

**Comment by DSuveges** [comment]
Yes. I think we can consider the schema finished. We'll open a ticket to set up the new process.
