### ISSUE TITLE
API playground target annotation query crashing in production due to obsoleted endpoint 

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2985]
The target annotation example query from the [Platform API playground](https://platform.opentargets.org/api) crashes.
I have identified the reasons (typos in the query):

<details>
  <summary>Crashing query</summary>

```
query targetAnnotation {
  target(ensemblId: "ENSG00000169083") {
    id
    approvedSymbol
    tractability {
      modality
      id
      value
    }
    safetyLiabilities {
      event
      eventId
      biosample {
        cellFormat
        cellLabel
        tissueLabel
        tissueId
      }
      effects {
        dosing
        direction
      }
      study {
        name
        type
        description
      }
      datasource
      literature
    }
  }
}
```
</details>

<details>
  <summary>Working query</summary>

```
query targetAnnotation {
  target(ensemblId: "ENSG00000169083") {
    id
    approvedSymbol
    tractability {
      modality
      id
      value
    }
    safetyLiabilities {
      event
      eventId
      biosamples {
        cellFormat
        cellLabel
        tissueLabel
        tissueId
      }
      effects {
        dosing
        direction
      }
      studies {
        name
        type
        description
      }
      datasource
      literature
    }
  }
}
```
</details>

@chinmehta could you please replace the "crashing query" with the "working query" in the API Platform playground?

**Comment by prashantuniyal02** [comment]
It might be a good excuse to update all the example queries with the latest endpoints.

**Comment by prashantuniyal02** [comment]
The disease annotation is also not working for the default selected disease as it does not have clinical signs and symptoms.
![image](https://github.com/opentargets/issues/assets/122870584/9a806c02-521d-4267-9204-908ad392fc36)
Replace the disease in the input query: `EFO_0000222`

Query that works.
`query diseaseAnnotation {
  disease(efoId: "EFO_0000222") {
    id
    name
    phenotypes {
      rows {
        phenotypeHPO {
          id
          name
          description
          namespace
        }
        phenotypeEFO {
          id
          name
        }
        evidence {
          aspect
          bioCuration
          diseaseFromSourceId
          diseaseFromSource
          evidenceType
          frequency
          frequencyHPO {
            name
            id
          }
          qualifierNot
          onset {
            name
            id
          }
          modifiers {
            name
            id
          }
          references
          sex
          resource
        }
      }
    }
  }
}
`

**Comment by buniello** [comment]
tagging @chinmehta for this quick change
