### ISSUE TITLE
Problems with the tractability widget in dev

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#2988]
**Describe the bug**
The tractability widget looks off with every target

- [ ] There is a triplication of records under the `small molecule` category
- [ ] The `other modalities` category comes up empty 
![Screenshot 2023-06-19 at 16 09 32](https://github.com/opentargets/issues/assets/30833755/eedc1c5b-69f9-4ed0-adbd-d050c428d3b1)

Carlos has tested the API query in dev and it looks healthy. This is therefore a FE issue.

**Comment by d0choa** [comment]
Working in dev. thanks @chinmehta!
