### ISSUE TITLE
Associations page show same score for all records in development

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#2992]
<img width="1631" alt="Screenshot 2023-06-21 at 11 06 46" src="https://github.com/opentargets/issues/assets/5097586/d9799050-5357-4dcc-8b93-9b67460cb017">

A comparison between development vs production association pages (e.g. TP53) shows a problem in which all rows of the heat map display the same association scores despite them being different.

Luckily the issue appears to be fixed by [@louwen](https://github.com/louwenjjr)'s PR https://github.com/opentargets/ot-ui-apps/pull/161 which we need to review and merge.

**Comment by DSuveges** [comment]
I can't reproduce this issue on [platform.dev.opentargets.xyz](https://platform.dev.opentargets.xyz/target/ENSG00000141510/associations).

![image](https://github.com/opentargets/issues/assets/7122521/8cacc757-778d-4e49-9bfc-9df0481ddd8f)

**Comment by d0choa** [comment]
correct. PR has been merged and issue is fixed. Closing
