### ISSUE TITLE
Next view of the associations page crashing

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2996]
**Describe the bug**
The next view of the associations page crashes in the latest dev deployment for ALL target and disease pages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any target or disease profile page
2. Click on Next button for on associations page
3. The page does not load 

![image](https://github.com/opentargets/issues/assets/122870584/6eeca52d-bed3-411a-adac-05fb6b803350)

**Comment by carcruz** [comment]
Fixed on latest release of the UI
