### ISSUE TITLE
Duplication of entries on pagination of Gene Ontology section in the target profile page

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#2998]
**Describe the bug**
In the Gene Ontology widget in target profile page of APP, the next page duplicates the entries when moving to the next page in the latest dev

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Gene Ontology section in [target profile page of APP](https://platform.dev.opentargets.xyz/target/ENSG00000142192)
2. Select the `Rows per page:` to `100`
3. Click on next page
4. The entries are doubled (Total 200 rows shown instead of 100)

![image](https://github.com/opentargets/issues/assets/122870584/4d6b3e9d-a0ee-4fb6-97d0-9cd010f74d2f)

**Comment by prashantuniyal02** [comment]
### One more pagination issue:

**Describe the bug**
In the bibliography section of the target profile page, the entries do not refresh when moved to the next page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Bibliography section in [target profile page of APP](https://platform.dev.opentargets.xyz/target/ENSG00000142192)
2. Select the Rows per page: to 25
3. Click on next page
4. The entries do not refresh and stay the same.

![image](https://github.com/opentargets/issues/assets/122870584/43c83f40-0749-423f-ab60-5ac3cd2abfcf)
![image](https://github.com/opentargets/issues/assets/122870584/21a8084f-ad72-42e7-a8a3-498d554d7dab)

**Comment by carcruz** [comment]
Fixed on latest release of the UI
