### ISSUE TITLE
Elasticsearch CPU usage

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3007]
The CPU usage for  the elastic search server is going to 100% making platform slow

the CPU consumption of Elastic Search has gone up to a 100 2 times the same day for no apparent reason and it has stayed there for multiple minutes.

<img width="411" alt="image" src="https://github.com/opentargets/issues/assets/15823008/51fe8c15-f380-4809-929f-484a6b997a76">

**Comment by prashantuniyal02** [comment]
@remo87 Can this issue be closed?
