### ISSUE TITLE
Mismatch between scores in classic association and AOTF

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3009]
**Describe the bug**
The scores in classic association do not correspond with the scores in AOTF. The scores in AOTF might be the right ones. 
The query in classic association does not seem to be passing the right weights to the private datasources (with the lock)
Example: https://partner-platform.dev.opentargets.xyz/target/ENSG00000180370/associations

This issue would have been there in the previous PPP release as well.

**To Reproduce**
Screenshots [here](https://docs.google.com/document/d/1L93cwE85MWG8xB0I5QC4yUPuDO6Fq8N22QF6gVnVE2Y/edit).

**Comment by buniello** [comment]
@carcruz did you have the chance to think about this task?

**Comment by prashantuniyal02** [comment]
This issue does not exist in the PPP anymore. [Updated screenshots](https://docs.google.com/document/d/1L93cwE85MWG8xB0I5QC4yUPuDO6Fq8N22QF6gVnVE2Y/edit).
