### ISSUE TITLE
Exploratory update to API

### ISSUE THREAD

**Issue by remo87** [opentargets/issues#3010]
Updating dependency versions and potential Scala 3 update.

**Comment by mbdebian** [comment]
Scoped as a _must_ for the September release !
Thanks @remo87 !

**Comment by mbdebian** [comment]
@remo87 , as discussed, we'll wrap this one up with the PR about the jdk and the Scala version. 

Thanks!

**Comment by mbdebian** [comment]
This up to date not including the docker base image for Java
