### ISSUE TITLE
Including new content/columns on target prioritisation view page

### ISSUE THREAD

**Issue by Juanmaria-rr** [opentargets/issues#3011]
## Background

We would like to include new content in the target prioritisation factors page as a new columns. 

## Tasks

Currently we are interested to include the following column content:

- [ ] Gene essentiality (True = -1, False=0, No data=NA/white)
- [ ] Small Molecule Binder (Yes=1, No=0, No data= NA/white)

**Comment by mbdebian** [comment]
@Juanmaria-rr and @remo87 , I was wondering how things are going with this open issue.
Thanks!

**Comment by remo87** [comment]
The BE side are deployed to dev. It requires a change in the FE because I renamed the field.

**Comment by buniello** [comment]
@carcruz 
Final info details on the two new columns:
1) `Small molecule binder`
- position of column on the heatmap: after the `Ligand binder`column in `tractability'
- tooltip link: `http://home.opentargets.org/aotf-documentation#small-molecule-binder`
- hovering text: `Target binds a small molecule`

2) `Gene essentiality`
- position of column on the heatmap: after the `Genetic costraint`column in `safety'
- tooltip link: `http://home.opentargets.org/aotf-documentation#gene-essentiality`
- hovering text: `Gene is defined as core essential by the DepMap portal`

**Comment by buniello** [comment]
also linking this ticket to a related one: https://github.com/opentargets/issues/issues/3050
