### ISSUE TITLE
targetPrioritisation file typo in Platform 23.06

### ISSUE THREAD

**Issue by mjfalaguera** [opentargets/issues#3012]
Reporting a typo in the ftp targetPrioritisation file on Platform version 23.06. It should be "targetPrioritisation" instead of "targetsPriorisation":

http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/23.06/output/etl/parquet/targetsPriorisation/

**Comment by buniello** [comment]
Hi @chinmehta, when you have a minute could you please look into this typo?

**Comment by d0choa** [comment]
I think @remo87 has this one under his radar. It's not a FE thing

**Comment by mbdebian** [comment]
This is scoped as a _must_ for the September release.
