### ISSUE TITLE
Limit numbers of entities in an answer

### ISSUE THREAD

**Issue by orlandombaa** [opentargets/issues#3014]
Hello everyone!

I'm using your GraphQL data access point. For example, the following code:

```graphql
query TargetDiseases {
  target(ensemblId: "ENSG00000157764") {
    id
    approvedSymbol
    associatedDiseases {
      count
      rows {
        disease {
          id
          name
        }
        datasourceScores {
          id
          score
        }
      }
    }
  }
}
```

This query returns 1220 diseases related to this target. How can I limit the number of diseases in the answer,  directly from the query?

Thank you !

**Comment by prashantuniyal02** [comment]
Hi @orlandombaa, We have a growing [community of open targets users](https://community.opentargets.org/c/data-access/11) where you can post your queries and find answers to technical support questions about accessing Open Targets data. It would be great if you could kindly repost your query on the community page to get a quicker response from the community members.
