### ISSUE TITLE
Issue with the Gecko API endpoint 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3022]
Recording a slack discussion to this ticket, for all of us to follow up: 

We received this [question on the community ](https://community.opentargets.org/t/gecko-function-in-graphql-not-working/1103)about the `gecko` API endpoint. As far as I know the `gecko` endpoint is not used (based on communication with Carlos. 
However, the API endpoint is there, and returns empty responses. I assume this endpoint once served the locus page, but now is replaced by `LocusPageQuery`. There are a number of questions here:
- Does the `gecko` endpoint provides any data? If not, how painful it would be to remove that endpoint or at least remove from the API? Any clues [@be-team](https://opentargets-dev.slack.com/admin/user_groups) [@fe-team](https://opentargets-dev.slack.com/admin/user_groups)?
- When looking at alternatives for this endpoint, I tried to replicate the LocusPageQuery, however I have never got anything for the regional plot, doesn’t matter what regions I tried (which is consistent with the empty locus pages):
```

        "regionPlot": {
            "genes": [],
            "tagVariants": [],
            "indexVariants": [],
            "studies": [],
            "geneTagVariants": [],
            "tagVariantIndexVariantStudies": [],
            "__typename": "Gecko"
        }

```
[@be-team](https://opentargets-dev.slack.com/admin/user_groups), is it possible to check if there’s any data in the storage that should served by this request?
[@Xiangyu Jack Ge](https://opentargets-dev.slack.com/team/U01S8BEL5T9) you are more familiar with this data, do you find strange that[ this locus page](https://genetics.opentargets.org/locus?chromosome=1&end=155442920&selectedIndexVariants=1_154442920_C_A&selectedTagVariants=1_154442920_C_A&start=153442920) shows no association? Can you or someone from the genetics confirm that this page works or not.

**Comment by buniello** [comment]
From @xyg123:
I can’t see anything on that query,  but that’s definitely not right.
I’m working with the COLOC dataset so I a quick filtering reveals there’s definitely associations in the region.  I’ll take a closer look after lunch to see if there’s anything wrong with them
```

COLOC_results.filter(f.col("left_type") == "gwas").filter(f.col("left_chrom")==1).filter((f.col("left_pos") > 153442920) & (f.col("left_pos") < 155442920)).count()
37374
```

**Comment by buniello** [comment]
any updates on this investigation?

**Comment by DSuveges** [comment]
As far as I remember the gecko api is phased out.
