### ISSUE TITLE
Scoping target interactors functionality within AOTF

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3023]
We have started brainstorming on how we could enable access to target networks info within AOTF.
This ticket will record the final scoping and tasks (not for 23.09).

Options were discussed:

- [ ] new column in AOTF with molecular interactions (drawer opens with molecular interactions tabs for each target)
- [ ] building functionality to expand the associations table down with top interactions when a box "show interactions" is ticked  
- [ ] Other

**Comment by buniello** [comment]
Discussed preliminary requirements for: 

Build a UI feature to display interactors of disease-associated targets in AotF

- Data: Target/Sections/Molecular interactions widgets
Use all data sources (IntAct, Signor, Reactome, String)
Interaction Score cut-off (minimum score) eg 0.7

- AotF view
Show a button on each target row as “Show Interactors” (icon)
Visual element containing networks sub-view (modal/drawer)
AotF loaded with the target interactors 
Order by Association score
Display interaction Score
Able to export/download (default, no custom)

**Comment by buniello** [comment]
**4/12/23**: we have carried on with the discussion on how to visualise target networks in Associations on the Fly.
Please see [this document](https://docs.google.com/drawings/d/1FEB6EhEu479v-6kXAxfNj3lC6NVrtwVj2e3kp-lIClE/edit?pli=1) for specific requirements covered so far.

**Comment by carcruz** [comment]
Moving to done since UI development will be done under this issue https://github.com/opentargets/issues/issues/3406
