### ISSUE TITLE
Updating ProjectScore dataset 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3027]
The new manuscript on project score is very close to be published. The dataset is available, and we can update our parsers to ingest. 

- Parsers for generating project-score evidence is [here](https://github.com/opentargets/evidence_datasource_parsers/blob/master/modules/CRISPR.py)
- The generated dataset is here: `gs://open-targets-data-releases/23.06/input/evidence-files/crispr.json.gz`
- The schema definition is [here](https://github.com/opentargets/json_schema/blob/b5971de6a0c187d77659b3302a1372c3ff2cf07b/schemas/disease_target_evidence.json#L204)

The update should include changing the datasource name to projectscore, which will have downstream consequences that needs to be syncronized with the backend and frontend team + documentation updates will also be required potentially.

**Comment by DSuveges** [comment]
There was a decision on introduce this dataset in PPP for the time being. Renaming the dataset doesn't make sense until the released data is consistent across the public and PPP versions. So, for now, the scope only includes getting the data in.

**Comment by DSuveges** [comment]
The publication is out by 11th January. This allows us to scope this task as a regular data update for the public platform.

**Comment by DSuveges** [comment]
Cell types: `gs://otar000-evidence_input/CRISPR/project_score_v2/cell_types.tsv`
Targets with mapped diseases: `gs://otar000-evidence_input/CRISPR/project_score_v2/mapped_diseases.tsv`

**Comment by DSuveges** [comment]
From the updated evidence set the pan-cancer associations are dropped.

**Comment by prashantuniyal02** [comment]
@buniello @DSuveges Wanted to know if the documentation on Project Score was updated before closing the ticket?
