### ISSUE TITLE
Improve efficiency of PIS docker image

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3036]
As a developer I want a PIS docker image that is smaller and faster to build because 1) it sometimes times out building on Travis during the `conda env create` step and 2) if it is smaller it makes it faster to transfer/build/test/deploy.

## Background

The PIS docker image is [here](https://quay.io/repository/opentargets/platform-input-support) and built by Travis upon commits. In order to test a new feature/fix, you may need to wait for this build, before pulling the image to a machine where you can run the container. Having as small an image as possible is good practice. Having a the build time out because the `conda env create` step takes so long is inefficient. 

One possibility is to replace the conda dependency. We could use a slimmer base image and explore the use of a different dependency manager.

## Tasks

- [ ] Investigate a slimmer replacement for conda 
- [ ] Implement the replacement

## Acceptance tests

How do we know the task is complete? 

1. When I run PIS from the docker container, it runs as it would with the existing container.
2. The docker image is smaller
3. The docker image doesn't time out when it builds

**Comment by mbdebian** [comment]
@jdhayhurst , This one is probably a nice background research job for post-23.12 release
