### ISSUE TITLE
Making changes in the summary statistics data model and ingestion logic

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3039]
This ticket collects requested modification to the summary statistics data module. As multiple functions for different datasources generates summary statistics, it is very important to any updates has to be implemented in every affected place:

- [ ] Data class schema
- [ ] GWAS Catalog ingestion
- [ ] Finngen ingestion
- [ ] UKBB ingestion

## Update No1: Adding variant level sample size whenever this detail is available.

- [ ] GWAS Catalog - datasets might contain sample size, but as this column is not harmonized, we have to explore available column names.
- [x] <s>Finngen</s> -No sample count
- [x] <s>UKBB - Neale</s> - Sample count not variant specific
- [x] <s>UKBB - Saige</s> - Sample count not variant specific

## Update No2: Removing confidence intervals.

As these fields are computable from effect size and p-value, and rarely used in bulk, there's no point in calculating them and store with summary stats. We need to drop the schema and the logic in the ingestion.

## Update No3: new filters on single point associations and update in harmonization logic

- [x] Drop the associations with beta == 0 (we really can’t do anything).
- [ ] For the rest of snps if se==0 and p-value!=1 and p-value!=0 -> infer se from p-value and beta, otherwise drop
- [ ] For the rest of snps if p-value==1 or p-value==0 - infer it form beta and se
- [ ] If p-value is too small (0) even after inferring -> replace zero with 2e-308

**Comment by DSuveges** [comment]
Out of the 29.9k summary statistics, the following columns contain sample sizes (with the number of studies the column was used):

```
   4458 n
      2 N
      4 n_analyzed
      3 n_samples
      1 n_total
      1 samplesize
      1 totalsamplesize
```

**Comment by addramir** [comment]
Since FinnGen and UKBB-* are not meta-analyses but studies with good imputation, it is expected that they would have a consistent N across SNPs. 
I suggest adding a sample size column to all studies, even if the sample size remains consistent, in order to prevent format disharmonization. This approach will facilitate uniform usage of this column across all studies in the future.

**Comment by addramir** [comment]
Additional comment: I think we can remove  |-- betaConfidenceIntervalLower: double (nullable = true) and |-- betaConfidenceIntervalUpper: double (nullable = true) columns. 
So the final schema is:

root
 |-- studyId: string (nullable = false)
 |-- variantId: string (nullable = false)
 |-- chromosome: string (nullable = false)
 |-- position: integer (nullable = false)
 |-- beta: double (nullable = false)
 |-- N: integer (nullable = false)
 |-- pValueMantissa: float (nullable = false)
 |-- pValueExponent: integer (nullable = false)
 |-- effectAlleleFrequencyFromSource: float (nullable = true)
 |-- standardError: double (nullable = true)

**Comment by ireneisdoomed** [comment]
@DSuveges @addramir If we remove the confidence intervals from the summary stats, should we drop them from the StudyLocus as well? https://github.com/opentargets/genetics_etl_python/blob/09dd2bc355185d8d2fae5999b0ad8413c22a8735/src/otg/assets/schemas/study_locus.json#L47

**Comment by addramir** [comment]
Can we close this issue?
