### ISSUE TITLE
Stress testing BE infrastructure for public AOTF

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3044]
## Background

We are planning to release AOTF on the public platform and want to make sure that ch and BE infrastructure will be able to process the increase in queries.

## Tasks

- [ ] Stress testing the dev env
- [ ] Making sure the prod env will be able to scale and handle the resulting increase in queries

**Comment by mbdebian** [comment]
@remo87 , we'll approach this by looking at the historical load of CPU, memory and Disk I/O in the ES, CH and API nodes running PPP, as we don't have _request data_ that we could use for feeding a _JMeter_ session. 

We'll collect such data after the release, with the latest updates pending approval in the API, related to GraphQL queries, and scope it within the telemetry efforts.

**Comment by mbdebian** [comment]
We are re-grouping on this after the release.
