### ISSUE TITLE
Creating a database schema diagram highlighting the links between tables 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3046]
I received this email from one of the Partners' Data Manager: 

_We are interested in constructing flexible query with OT API, and had a relative-difficult time to figure out the DB schema. Sarah sent us [api.genetics.opentargets.org/graphql/schema](https://api.genetics.opentargets.org/graphql/schema), which is very helpful. I think a DB schema diagram highlighting the links between tables could provide a deeper insight to help us better understand OT data structure. Is that something available or could be generated?_

Opening this ticket for our records, this may be a nice addition to the new Genetics documentation

**Comment by d0choa** [comment]
There is a spreadsheet from @ireneisdoomed that contains this information. We will need to update it and formalise it in a friendlier format that we could easily update.

**Comment by d0choa** [comment]
This should be done eventually but I don't think we need to keep the ticket. We will need to work out what's the best solution to keep annotation on our data lake, mesh, or whatever we do
