### ISSUE TITLE
Expanding the `export` functionality for the Associations on the Fly page

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3063]
As a user, I would like to be able to export different components from both “Associations on the Fly” and "Target prioritisation" pages. 
At the moment, it is only possible to export the whole table with pre-set weights. 

As discussed with @carcruz, we would like to expand this functionality to include all the features listed below:

- [x] Download the current entity associations (with prioritisation) view with default status
- [x] Download the current entity associations view with customised visualisation properties:
Weights
Required
Pinned (or uploaded list)
Prioritisation view only
Sub-Set of association aggregations
Sub-Set of prioritisation aggregations
- [x] Show share URL option (copy button)
- [x] Allow download of JSON and TSV formats - please note: the filename should contain date and platform version (e.g. MONDO_0004975-associated-targets-16_10_2023-v23.09)
* This schema applies to both table modes (associations and prioritisations)
* The global associations score will always be displayed in downloaded table (order)

Sketched Wireframe:

<img width="648" alt="Screenshot 2023-10-06 at 11 29 08" src="https://github.com/opentargets/issues/assets/30833755/dfba2f86-9b01-4e82-8a78-20d5caf47595">

[AOTF export feature requirements file](https://docs.google.com/drawings/d/1XO_1lCFDp698lS034y27J7JVnDqnkAl1z1_HlpHJk0c/edit?exids=71471483,71471477)

**Comment by chinmehta** [comment]
Adding a Point to story scope:
- When downloading the file, the filename should contain date and platform version.
- Example: MONDO_0004975-associated-targets-16_10_2023-v23.09

**Comment by buniello** [comment]
Proposed disclaimer text: `By clicking on the download tabs from this view, you will export the entire association table (default option). Please expand the advanced option to export your own customised view`

**Comment by buniello** [comment]
Discussed in the FE meeting today: the two `Include custom weight controls` and `Include custom required controls` boxes will be merged into one box named `Include custom controls`
