### ISSUE TITLE
Old association page crashing for a specific disease

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3074]
**Describe the bug**
The [old view of the association page](https://platform.dev.opentargets.xyz/disease/EFO_0003767/classic-associations) is crashing for inflammatory bowel disease EFO_0003767.
The [new AOTF view](https://platform.dev.opentargets.xyz/disease/EFO_0003767/associations) of the same disease does not crash.

**Observed behaviour**
The old view of the association page is crashing for inflammatory bowel disease EFO_0003767.

**Expected behaviour**
The old view should not crash as it does not crash in production.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the old[ association view tab for IDB ](https://platform.dev.opentargets.xyz/disease/EFO_0003767/classic-associations)in the latest dev.

**Comment by d0choa** [comment]
@carcruz reported the problem is the `aggs: null` in the facets API response. @remo87 investigating how far back the issue goes.

I'm suspicious of the drug index changes creating an unintended effect in the facets.

**Comment by remo87** [comment]
it's working now it seems like there was a response cached with the aggregations set to null I cleared the cache and recreated the instances and it's now working. It could have been that either the index was not ready when the first query was or that an index was in a failed state

**Comment by remo87** [comment]
@mbdebian pointed out that we should change the machine type in ES due to increase in the data images. This could have been causing the issue

**Comment by ireneisdoomed** [comment]
@remo87 Is there any sanity check in the data I could do?

**Comment by remo87** [comment]
thanks @ireneisdoomed! Not really sure about a particular sanity check because the data seems to be fine the issue appeared to be in ES. Maybe if we could take a look at some random diseases in platform dev.
