### ISSUE TITLE
Hiding literature evidence from data download section

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3075]
**Describe the bug**
There are 4 chips being displayed in the Target - Disease evidence data download instead of 2.
These are different download options:
One set is for the evidence `23.06/output/etl/parquet/evidence` and
the other set is for the literature evidence `23.06/output/etl/parquet/literature/evidence`

We want to hide the the 2 chips containing the `literature evidence`

**Expected behaviour**
Only 2 chips pointing to parquet and json `evidence` files should be displayed. Need to change a boolean in the config file that displays these.

![image](https://github.com/opentargets/issues/assets/122870584/7b9a346c-d295-4be9-afd0-1666b7d014f3)

**Comment by d0choa** [comment]
I don't know how we are handling the nested literature datasets, but we want to say `"include_in_fe": false,` in the next dataset

https://github.com/opentargets/ot-ui-apps/blob/c2b9c4ba31eb0eee053b9e53c283b7a3858cb8e7/apps/platform/src/pages/DownloadsPage/dataset-mappings.json#L4

**Comment by buniello** [comment]
just a thought: instead of hiding literature evidence, can we add another row on download page:
- target-disease evidence (lIterature) with the two relevant `json` and `parquet` files?

Or is the plan not to provide these literature evidence files to users at all?

**Comment by d0choa** [comment]
The `Target-Disease evidence` row contains all evidence including literature. By including another row we are artificially duplicating the data.

**Comment by buniello** [comment]
@ehsanb29 is looking into this. He is also going to work on the order of chips - `json` and `parquet`for all rows

**Comment by d0choa** [comment]
@chinmehta working on the order of the chips

**Comment by prashantuniyal02** [comment]
Works correctly in the latest dev with literature evidence not present and ordered chips.
