### ISSUE TITLE
Incomplete safety data in the UI

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3079]
**Describe the bug**
Information about the dosing effects of all safety liabilities for all targets is missing in the UI.

**Observed behaviour**
How the target safety dosing effects are reported have recently changed in the data after #2921, practically the data has been renamed. This affects the FE logic, since it searchs for a pattern in the string, and this pattern is now not matched. Code [here](https://github.com/opentargets/ot-ui-apps/blob/19f5a64b665edde3b62b1e07c03094c29f4d8939/packages/sections/src/target/Safety/SafetyTable.jsx#L90).

**Expected behaviour**
If you look at [GABRG2](https://platform.dev.opentargets.xyz/target/ENSG00000113327), the first safety event is increased eating. How the `Dosing effects` column should look like:
- first arrow has to be pointing upwards
- second arrow has to be pointing upwards

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.dev.opentargets.xyz/target/ENSG00000113327
2. Click on Safety
3. Look that all rows in Dosing effects show no information

**Additional context**
The above mentioned ticket was not tracked in the 23.09 release intentions, so these changes were not followed up after changing the data. Apologies for that.

**Comment by prashantuniyal02** [comment]
Works in latest dev version
