### ISSUE TITLE
Making data models more general - introducing single point associations

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3087]
We have a number of datasets with schemas, specific methods that can applied on a given dataset. However, conceptually some of these datasets are very-very similar, functionalities are not shared along the similarities.

- A large majority of the datasets are based on genomic coordinates, however there's no shared way to filter these datasets based on genomic region.
- There are number of datasets that contains single point association, however there's no shared way of applying a p-value filter.

The scope of this ticket to

- [ ] Review the data types, calatolgue these similarities, 
- [ ] Collect methods that that should be available based on these similarities.
- [ ] Define new data classes to build hierarchy of datasets with shared methods.
- [ ] Currently the name of the datasets are inconsistently singular vs plural.- should be fixed

**Comment by addramir** [comment]
can we close this issue?

**Comment by DSuveges** [comment]
I can close this, however still believe this work should be done at some point. But this is not a priority now.
