### ISSUE TITLE
Develop a Pharmacogenomics widget with PharmGKB data

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3098]
We want to integrate Pharmacogenomics data into the Platform, with the aim to inform our users about those variants that have an impact in the response of a drug. This will enable a more personalized approach to drug discovery and development, taking into account how specific genetic backgrounds can influence treatment outcomes.

Our initial plans are to have a first version of this PGx data widget in December, with the intention of keep adding new sources as we become aware of them.

## Background

We focused on using PharmGKB as the central repository of this type of information.
PharmGKB is a project that curates knowledge about the relationships between drugs, diseases/conditions, and genes, including details on genetic variants that influence drug metabolism, efficacy, and adverse effects.

Their section that have this relationships between a variant in a gene and their change in the drug response is what they call “Clinical Annotations”. We have basically worked with this dataset, parsing it and converting it into a data model that is harmonised with the rest of our data.
<img width="1104" alt="Pasted Graphic" src="https://github.com/opentargets/issues/assets/45119610/04fd25da-8a34-43fb-9703-259ecdec3912">

## Data stats
Some exploration on `clinical_annotations.tsv`:
	- 4919 evidence. No type of identifier is used for Genes/Phenotypes/Drugs.
	- All evidence have variant/haplotype information.
		- Almost all (4347) represent a genetic variant.
	- 2592 target/disease associations.
	- 3478 target/disease/drug associations.
	- 653 distinct phenotypes.
	- 852 distinct drugs.
	- 1061 distinct genes.

## Tasks

- [ ] Solidify the data structure
- [ ] Design the widget for the target and drug pages
- [ ] TBD

**Comment by prashantuniyal02** [comment]
The schema details can be found here: #3110

**Comment by DSuveges** [comment]
The pharmacogenomics data has arrived:

```
Total clinical annotations: 5073
Total evidence strings: 24641
        With CHEBI: 20451 (83.00%)
        With EFO phenotype: 8139 (33.03%)
        With functional consequence: 15633 (63.44%)
        With VEP gene: 15633 (63.44%)   
Total RS: 2794
        With >2 alleles: 31 (1.12%)
```

Data is here: `gs://otar012-eva/pharmacogenomics/cttv012-2023-10-12_pgkb.json.gz`
