### ISSUE TITLE
Data missing and incorrect styling in OTVL widget in PPP

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3103]
**Describe the bug**

- [x] 1. OT Validation lab 'biomarker assessments', 'OTVL hit' and 'Primary project hit' are not showing up in the PPP
- [x] 2. Tooltip not displaying any text in 'OTVL biomarker assessment for _Target_?'
- [x] 3. Chips and colours in the widgets are not behaving correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [this](https://partner-platform.opentargets.org/evidence/ENSG00000165392/EFO_1001951) or [this](https://partner-platform.opentargets.org/evidence/ENSG00000133703/EFO_1001951) association evidence page
2. Click on OTVL widget
3. See error

**Additional context**
View [this](https://opentargets-dev.slack.com/archives/C02B9NT33AL/p1696863638723459) comment

**Comment by prashantuniyal02** [comment]
The table (Point 1) and chips (Point 3) are working as expected. 

However the tooltip (Point 2) is not functional.

**Comment by LucaFumis** [comment]
It appears that the `div` element containing the colours legend (i.e. "Expected ... Observerd" etc) for some reasons covers the title "OTVL biomarker assessment...", blocking any mouse event that would trigger the tooltip. 
In fact it's also not possible to select the text there. 
Not sure whether this could have been introduced by the new version of MUI? The containing `grid` sets a top margin to -32px to align things...
