### ISSUE TITLE
Ingest eQTL Catalog

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#3109]
As discussed with @addramir and @DSuveges, ingesting this is the next priority for the Genetics revamp.

Some modifications of the schema might be required.

**Comment by DSuveges** [comment]
So there's a few tings:
- Study type should have `eqtl`, `pqtl`, `sqtl` etc to reflect the detection method.
- There needs to be a column indicating the measured gene. I suggest it could be called `targetId`.
- An other column might be later needed for omics studies for capturing the measured chemical. We are not there yet.
- An other column should capture the tissue of sample collection maybe `tissueId` for UBERON IDs
- For single cell qtls, we need to have `cellTypeId` for cell ontology identifiers.

**Comment by tskir** [comment]
Data ingested: gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/preprocess/eqtl_catalogue
