### ISSUE TITLE
Incorrect number of entries being shown in the multiple widgets on AOTF

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3120]
**Describe the bug**
Incorrect number of entries displayed in multiple widgets ( `OT Genetics`, `ClinVar (somatic)`, `Cancer Biomarkers`, `ChEMBL` ) on AOTF page in the production platform.

**Observed behaviour**
Max 25 entries are being displayed in the ChEMBL widget for disease and target AOTF page. 
ChEMBL widget Example: [melanoma](https://platform.opentargets.org/disease/EFO_0000756/associations)
![image](https://github.com/opentargets/issues/assets/122870584/27dbc878-0ee1-4dde-a670-408b67da643c)
OT Genetics widget Example: [NOD2](https://platform.opentargets.org/target/ENSG00000167207/associations)
ClinVar widget Example: [TP53](https://platform.opentargets.org/target/ENSG00000141510/associations)
Cancer Biomarkers widget Example: [BRAF](https://platform.opentargets.org/target/ENSG00000157764/associations)

**Expected behaviour**
A total of 211 entries should be present (as viewed in API query count)
![image](https://github.com/opentargets/issues/assets/122870584/cd8dd5a1-f7b6-4d8a-b84c-f2150cada572)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a disease or target AOTF page on platform. Example [melanoma](https://platform.opentargets.org/disease/EFO_0000756/associations)
2. Click on the ChEMBL widget for BRAF for instance.
3. You can only view 25 entries.
4. Click on the `API query` in the widget.
5. Run the query and the total correct `count` is 211.

**Comment by prashantuniyal02** [comment]
@carcruz @buniello This issue is being observed in multiple widgets

**Comment by prashantuniyal02** [comment]
Reassigning to the backend team. 
After the summary was removed from the sections in the previous release, the count is not being specified in the API request and by default the API returns 25 entries. 
If the queries specifies the total count, the API returns the correct number of entries.

**Comment by carcruz** [comment]
More information of the issue can be found here: https://github.com/opentargets/issues/issues/3139 
Closing to avoid duplication
