### ISSUE TITLE
QC to flag `trans-qtl credible set` 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3124]
Upon ingesting and processing QTLs, we need to differentiate between cis and trans QTLs. Cis QTLs (associations in the close vicinity of the studied gene) are believed to be more reliable causal associations than further (trans) QTLs. The applied distance is quite arbitrary, but it is in the order of +/-1.5Mbp around the transcription start and stop of the gene.

We need a method that flags transQTLs after window based clumping. I imagine it would work like this:

```python
updated_qtl_study_locus = window_clumped_qtl_study_locus.flag_trans_qtls(
    study_index,
    gene_index,
    window_size
)
```

The implied the method would be part of the `StudyLocus` class, and would need:
- The study index to know which QTL dataset studies which gene.
- The gene index dataset to get the coordaintes for the gene.
- Window around the gene to consider a qtl trans.

Then each study locus, that are located outside of this window around the gene would be considered as trans. This annotation would be added to the `qualityControls` array using the usual instruments provided by the class.

If this method should be part of the STudyLocus dataset is up to debate. There are pros and cons:
- This flag only applied to QTLs, however study locus could be other type.
- If this method will be put here, it is expected to be callable on any gwas study locus resulting zero flagged loci.
- If we decide to create a new dataset for QTL study locus, that would introduce a number of complexities. (the window based clumping has to know if that was a gwas or qtl.)

I personally believe we should not distinguish between gwas and qtls at all. This nature of the study is solely a concern of the study table.  

@ireneisdoomed , @d0choa Please feel free to chip in.

**Comment by ireneisdoomed** [comment]
We have logic for V2G that resembles the task. [VariantAnnotation.get_distace_to_tss](https://github.com/opentargets/genetics_etl_python/blob/6389ff172f8ff3ee487d624fff48bb9e8a4fce57/src/otg/dataset/variant_annotation.py#L241C29-L241C29) extracts all variant/gene pairs within a window. The scoring part is irrelevant.

I have a more general question related to how we want to deal with QTLs. In this case the trait refers to a gene product. We need to introduce a `geneId` column either in StudyIndex or StudyLocus, correct?
- If it is in StudyLocus, we wouldn't need to bring study information to extract the cis/trans flag
- If it is in StudyIndex, studyId can represent something more complex: a trait, a gene, and a tissue. I like this idea, but I think a more granular study would have implications in L2G, some features are aggregations at the study level.

**Comment by DSuveges** [comment]
There are some details under the [main QTL ticket](https://github.com/opentargets/issues/issues/3109), @tskir has been working on. Yes, the SL datamodel is expected to be extended with some extra columns.

**Comment by d0choa** [comment]
I might need to think a bit deeper in the ramifications of this, but cis/trans looks like a property of V2G/L2G. It does not look very natural as a property of a StudyLocus. 🤔

**Comment by d0choa** [comment]
One year after, this looks like a StudyLocus QC now. Renaming the ticket as still valid

**Comment by addramir** [comment]
It is not relevant anymore. WE don't have trans-qtls.
