### ISSUE TITLE
Some widget not loading in the drug profile page

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3126]
**Describe the bug**
Some widget are not loading in the drug profile page in the latest platform and PPP dev deployment. [Example](https://platform.dev.opentargets.xyz/drug/CHEMBL1096882)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [drug profile page](https://platform.dev.opentargets.xyz/drug/CHEMBL1096882)
2. The profile widget do not load.

**Comment by prashantuniyal02** [comment]
This profile page is loading correctly in the dev platform and dev PPP.

**Comment by buniello** [comment]
tested and all is loading now
