### ISSUE TITLE
Generalize how LD references are handled by the etl

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3141]
Currently the ETL has only one source of LD reference: GnomAD. As such, we have a collection of methods to interact with the source. However in the future we might have other LD references available. We have to make sure these other sources are seamlessly integrated. 

**Points that need attention:**

- The combined LD index table that has all linked variants from all ancestries, should be aware all possible sources of LD reference.
- Finemapping processes require access to the raw Ld matrix and LD indices. These methods also has to know how to extract the required data from any available ancestries.

Probaby new layer should be introduced to manage all sources of LD references.

**Comment by ireneisdoomed** [comment]
This could be done similarly to how we operate with Intervals.
The main exception is that Intervals is a join of datasets, whereas the LD index is a combination.
`GnomADLDMatrix.as_ld_index` produces the aggregated dataset, which is incompatible with what you propose here if we were to have several LD sources. It'd be a matter of extracting the aggregation logic out and doing it inside the step, where all individual LD indices are generated.

**Comment by prashantuniyal02** [comment]
Assigning it to @DSuveges & @addramir for now. You can decide who will work on it depending on the team's capacity.

**Comment by d0choa** [comment]
Closing this as old and new LD matrixes are coming into the mix. @addramir keep this context in mind when working on panUKBB
