### ISSUE TITLE
Implement and test cluster autoscaling in Airflow architecture

### ISSUE THREAD

**Issue by tskir** [opentargets/issues#3142]
As mentioned by @ireneisdoomed in [this discussion,](https://github.com/opentargets/genetics_etl_python/pull/216#discussion_r1380101881) certain steps require lots of resources, so it's vital to enable autoscaling to make sure they can run in reasonable time.

This should also make per-job configuration not necessary anymore, simplifying running any workloads.

**Comment by ireneisdoomed** [comment]
Important to note that the LD index generation is likely to be part of the preprocessing part.
