### ISSUE TITLE
Add extra elastic search endpoints to chembl-inputs

### ISSUE THREAD

**Issue by mjfalaguera** [opentargets/issues#3148]
Would it be possible to add the following elastic search endpoints to `http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/input/chembl-inputs/`:

- `chembl_33_activity`
- `chembl_33_assay`
- `chembl_33_document`
- `chembl_33_target_component`

**Comment by remo87** [comment]
To be able to fetch the information we need to specify which fields we're interested in. I'm attaching files with the name of the fields in the indexes.
[activityFields.json](https://github.com/opentargets/issues/files/13349793/activityFields.json)
[assayFields.json](https://github.com/opentargets/issues/files/13349794/assayFields.json)
[documentFields.json](https://github.com/opentargets/issues/files/13349795/documentFields.json)
[targetComponentFields.json](https://github.com/opentargets/issues/files/13349796/targetComponentFields.json)

**Comment by mjfalaguera** [comment]
Let's get things moving and see how it goes with the following ones:

activity:
- "document_year"
- "document_chembl_id"
- "pchembl_value"
- "target_chembl_id"
- "molecule_chembl_id"
- "assay_chembl_id"

assay:
- "confidence_score"
- "assay_type"
- "assay_chembl_id"

document:
- "pubmed_id"
- "year"
- "document_chembl_id"

targetComponent:
- "target_component_synonyms"
- "component_id"

**Comment by prashantuniyal02** [comment]
@mjfalaguera and @polrus : is this issue still relevant?

**Comment by javfg** [comment]
If it is still relevant, let me know. Adding these should be straightforward.
