### ISSUE TITLE
Bug on the PharmGKB data as handled by the data provider

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3149]
We identified a systemic bug in the PharmGKB data as handled by EVA, where the

 `phenotypeFromSourceId`: `null` ("description": "EFO ID of phenotype, mapped through ZOOMA / OXO)

This bug translates into the current version of the Pharmacogenomics widget, so that the `Drug Response Phenotype` field cannot not be hyperlinked to the Open Targets disease page - see [CFTR example](https://platform.dev.opentargets.xyz/target/ENSG00000001626) here.

We will feed back to the EVA team.

**Comment by buniello** [comment]
This bug will be discussed with the EVA team on our monthly catch-up next Monday. Fix will be scoped for the next release/iteration of widget

**Comment by buniello** [comment]
it would be good to scope this for 24.03

**Comment by ireneisdoomed** [comment]
Mappings are handled by EVA, so nothing to be done on our side except from validating the new data.

**Comment by ireneisdoomed** [comment]
`Cystic fibrosis`, the example reported in this issue will be mapped with the new data submission.
EVA has improved their mapping system by directly matching up terms where there is an exact match between the text and an EFO lable. By doing so they've improved their coverage from 33% to 42%. There is a lot of room for improvement still.
I'll keep it open just for QCing purposes once we have the data.

**Comment by prashantuniyal02** [comment]
@ireneisdoomed , has this been resolved?

**Comment by ireneisdoomed** [comment]
Yes, phenotypes are now extracted by us.
