### ISSUE TITLE
Working on a second iteration of the upload functionality 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3170]
As part of the MVP Phase II of the Associations on the Fly project (see [here](https://github.com/opentargets/issues/issues/2913) for complete roadmap up to Phase III), we are developing a functionality for users to upload a custom list of target or diseases for the new associations/target prioritisation pages to return a customised view.
The functionality, in its MVP version, will be released with the 23.12 PPP release and will only allow upload of a txt file.

For the next version of the uploads, we discussed the following additions:

- [x] allowing upload of .csv and .json files (to cover main use case of users wrangling big spreadsheets) 
- [x] allowing selection of targets or diseases (matches) of interest after validation of input 
- [ ] #3259

**Comment by prashantuniyal02** [comment]
- [ ] Allowing users to upload the files in the same format (`.json` or `.tsv)` in which they can download

**Comment by buniello** [comment]
@prashantuniyal02: the 'reset' button was not implemented in this iteration of the upload functionality, so we should make sure this issue is transferred to next release
