### ISSUE TITLE
Allowing single node dataproc cluster in airflow

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3185]
When creating a cluster for the pipeline, we have the flexibility to adjust the number of workers and the way how the process is auto-scaled:

```python
        common.create_cluster(
            CLUSTER_NAME,
            autoscaling_policy=AUTOSCALING,
            num_workers=8,
            # num_preemptible_workers=8,
            master_machine_type="n1-highmem-32",
            worker_machine_type="n1-standard-2",
        )
```

Unfortunately the same function cannot be used to create single node cluters for light-weight jobs. (minimum number of workers is 2) This is not a burning issue, but would be nice to have.

**Comment by d0choa** [comment]
nice to have but probably not priority for now
