### ISSUE TITLE
Context menu for evidence for AOTF

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#3209]
The current implementation of the context menu is as follows:
<img width="347" alt="image" src="https://github.com/opentargets/issues/assets/122870584/627f1888-60c4-4034-a041-8a85683e93fb">

- [x] This can be improved so that there is more characters for the name of the diseases.

**Comment by prashantuniyal02** [comment]
Current implementation:

For target:
![Image](https://github.com/opentargets/issues/assets/122870584/da8c57a0-17e2-4e93-a4cd-906f44e701cc)

For disease:
![Image](https://github.com/opentargets/issues/assets/122870584/e1f0d5e6-0f88-4737-81d4-f21140d38974)
