### ISSUE TITLE
Documentation on target prioritisation view (safety) is incomplete 

### ISSUE THREAD

**Issue by inessmit** [opentargets/issues#3231]
**Describe the bug**
Documentation about safety factors in prioritisation view is not sufficient to reproduce traffic light colour buckets

**Observed behaviour**
- Section on Genetic constraint does not describe which pLOF values were taken to create -1 and 1 buckets
- Gene essentiality does not describe how the -1 and 0 categories relate to the cell line tissues of origins and to the values taken from DepMap. Juan told me it's "essential in one or more tissues". The documentation does not mention this.

**Expected behaviour**
Clear description of how what cut-offs/values were used to create each of the buckets, and what 'essential' exactly means for creating the buckets.

**Additional context**
I believe this issue was also mentioned by a pharma partner in TE feedback meeting on 22 Feb.

This is not to take away from the fact the processing of this data into the prioritisation view is very useful and helpful! So thanks!

**Comment by buniello** [comment]
Thank you @inessmit! I have shared a new doc draft from @Juanmaria-rr - let me know if there is more we can add

**Comment by Juanmaria-rr** [comment]
Documentation of genetic constraint and gene essentiality was amended with more extensive explanations and citing the source of data.
