### ISSUE TITLE
Feedback point on 24.03 release

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3233]
### 1. Enhanced file upload functionality on PPP

- Is there a limit to the number of targets you can upload? If so, would be good to include it
- The wording ‘Please upload a text file’ and ‘drag and drop a .txt file here’ needs changing, as you can now upload different formats
- Need to mention that `id` is required in the file header.

### 2. Bibliography filter

- [x] If you have no publications for the entities you select, the timeframe goes from 0 to 0 which is not expected behaviour. One would expect the timeframe to remain the same from the start date of when we have publications for and our last update. [Test case](https://deploy-preview-327--ot-platform.netlify.app/disease/MONDO_0018997)
- Maybe this is because it reflects the timespan of what is being displayed, in which case makes sense but I'm not sure users would expect this as you want to ask _what publications are there between time x and y that include these entities?_ even if the answer is 0 publications you would still expect the see the timeframe

### 3. Direction of effect UI

- Really like the shield and ! icons, giving both assessments side by side, and the hover over explanation is really explanatory (though the documentation is still needed)
- For ‘?’ when you hover it says ’N/A’ which implies ‘not applicable’ rather than ‘no data available’ so we should clarify this distinction
- #3160 
- used the [PCSK9 example](https://deploy-preview-332--ot-platform.netlify.app/target/ENSG00000169174/associations) and it works really nicely: PCSK9 - decreased gene product = protective against familial hypercholestrolemia from OTG evidence. Really nice to see that on the ChEMBL evidence inhibitors are used for protective and have been developed for treatment. Really shows the value of having this information from genetics that can inform on drug treatment.

### 4. PGx * alleles

- This is looking really nice! This is more straightforward than the rsIDs and the link out to the variant page in PharmGKB works well as a reference. Like the icon to state whether it is the direct or indirect target, and the directionality is captured well in the phenotype column.

### 5. PGx added to Safety widget

- This looks really nice and fits well into the current schema. 
- Is it possible to import the 'dosing effects' via the gene function assessments? This may be too complicated so fine to leave for now. [Test case](https://deploy-preview-335--ot-platform.netlify.app/disease/MONDO_0010130/associations?table=prioritisations)

**Comment by d0choa** [comment]
N/A can mean not applicable, not available, not assessed, or no answer depending on who you ask. Although correct, it might be a bit vague. In the future, we will likely use the same icon when we have different DoE contradicting each other. I would consider adding a label that says `Inconclusive assessment` instead of `N/A` (or something equivalent).

**Comment by remo87** [comment]
After discussion with @prashantuniyal02 it was decided that when have no data in the response we should display the date filter labels as 'YYYY-MM' for both higher and lower limits.
