### ISSUE TITLE
Implement distance to footprint features

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3258]
L2G in production describes several annotations. In an initial stage, we have implemented those that relate to the distance to a gene's TSS.

Quoting @addramir (https://github.com/opentargets/gentropy/pull/545#issuecomment-2004401202):

> To note, in the production we had three more features:
> 
> Average distance to footprint (dist_foot_ave): the same as above but instead of distance to tss - distance to footprint of the gene.
> Neighbourhood score for dist_tss_ave: you calculate the minimal dist_tss_ave across the genes in the locus and for each gene calculate the relative score as: dist_tss_ave_nbh=-log(dist_tss_ave/min(dist_tss_ave)). For the closest gene it should be 0, for the distant genes it should be a negative value. Doesn't work for the cases when the min(dist_tss_ave)=0. Probably a bug in a prod.
> Neighbourhood score for dist_foot_ave: same as above but for footprint.

We should evaluate how the incorporation of these annotations captures a better understanding of the impact to gene regulation.

**Comment by addramir** [comment]
I guess this is done?
