### ISSUE TITLE
Missing name found on disease on PPP

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3262]
**Describe the bug**
There is this weird issue where sometime if you search for an entity, specially a disease on PPP, a 'missing name' disease is being shown. The error is sporadic and I am not able to reproduce it

**Additional context**
A member of one of the consortium partners also experienced the same.
![image](https://github.com/opentargets/issues/assets/122870584/76f9b2c8-9e30-466d-ad8c-d83f89e7568e)

**Comment by prashantuniyal02** [comment]
Hi @opentargets/be-team , this issue still persists and now is being reported by one of our partners.
If you search a disease or target and even though it is present in PPP, the search item is not found and if you go to the exact link, it reaches the missing name page.
Usually happens if you access the page early in the morning say around 8 or 9am UK time as it is not being accessed by anyone and I suspect, the machine go into a sleep mode and it takes a couple of minutes for the correct results to be displayed.

**Comment by javfg** [comment]
That should not be the case, only the dev servers are spun down when unused.

Knowing which partner is having the problem, maybe we can take a look at the web request logs to see it anything is coming from the whitelisted IP range? If not, it might be they are outside of their network.

**Comment by javfg** [comment]
Update:

We redeployed production PPP and the problem persists.

Looking around, We've found some people having similar problems:

https://discuss.elastic.co/t/slow-first-request-on-an-index-after-a-short-amount-of-time/219292
https://stackoverflow.com/questions/39610274/elasticsearch-first-query-is-slow-rest-of-them-are-fast

We've set the `refresh_interval` setting cluster-wide (`cluster.default.index.refresh_interval`) to -1,

https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/#dynamic-cluster-level-index-settings

Not sure if this is for newly created indexes only (which would render it useless), but we'll try to query the server tomorrow morning, to see if there is any change.

Other things we can try: 

* Make sure this does not happen in `ppp-dev`, and if so, check for deployment config differences.
* Change the `index.refresh_interval` manually for certain indexes. Maybe if we can reproduce at will we can query and isolate if a single index is causing this or it is widespread.
* Change the `index.search.idle.after` for indices we know are getting the slowdown, or [field data preloading](https://www.elastic.co/guide/en/elasticsearch/guide/current/preload-fielddata.html), but I'm not sure about that last one.

It would help to find a way to make this reproducible more than once a day in the mornings.

**Comment by javfg** [comment]
Update:

That had no effect, as the setting was defined for indexes on creation time. 

Today we tried a new change: We're setting `index.refresh_interval` to -1 and `index.search.idle.after` to `860000s` (ten days) for all indexes we are storing.

**Comment by javfg** [comment]
Update:

After tinkering a bit with the logs, we found the [API was masking a connection error](https://github.com/opentargets/platform-api/commit/5f7115644cdc9d3ed0cd2cf4c74c17c1b66c3ec0#diff-4ea4c6507afb8851938393cc2002667175a9131a491e1e4731b36dee3f2a252eR34).

Something in the network is causing the long-lasting connection between API and OpenSearch to reset on a long inactivity, and the library is not handing the maintenance of that connection:

https://github.com/Philippus/elastic4s/issues/2806
https://github.com/Philippus/elastic4s/issues/210

@jdhayhurst found [some people having similar problems](https://discuss.elastic.co/t/connection-reset-by-peer-ioexception/257457/4) in the ElasticSearch discuss, and implemented a [custom client with keepalive](https://github.com/elastic/elasticsearch/issues/65213) (opentargets/platform-api#191) which is now deployed, and this morning the partner platform looked alive :tada: 

I've also implemented a reconnection mechanism (https://github.com/opentargets/platform-api/commit/21d116444db24a978a40dd0558835a34aaeef99a) which we can try merging if errors come back. For now, we will hold on this, as it requires some testing and it looks like the problem has been mitigated.

It is important we look into the architecture to figure out what is causing those disconnects.
