### ISSUE TITLE
ChEBI to ChEMBL mapping - unresolved cases

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3265]
With the ChEBI to ChEMBL solution, we have mapped 90% of the high confidence evidence. #3116

The outstanding cases are due to 7 ChEBIs. This is an example shared by @d0choa and Ellie:
![image](https://github.com/opentargets/issues/assets/45119610/1551ae31-7b05-4b66-8b95-ae28fad2658c)

For this case we do have a ChEBI cross reference, but it point to slightly different molecules:
PharmGKB points to [CHEBI:10033](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:10033), the parent structure for warfarin.
ChEMBL points to [CHEBI:87732](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:87732), a stereoisomer. 
PharmGKB's mapping looks more sensible to me, so I'll ask ChEMBL about it.

Independently, my hypothesis is that we can get a full coverage just by using the drug name.

_Originally posted by @ireneisdoomed in https://github.com/opentargets/issues/issues/3116#issuecomment-1835889128_

**Comment by prashantuniyal02** [comment]
Hi @ireneisdoomed, has this been resolved?

**Comment by ireneisdoomed** [comment]
We have phased out ChEBI IDs and we now use their names. The above examples are all mapped now.
