### ISSUE TITLE
Link to CRISPR Screens documentation from AOTF is incorrect

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#3266]
**Describe the bug**
Clicking on the documentation icon for CRISPR Screens on the AOTF page should point to https://platform-docs.opentargets.org/evidence#crispr-screens

**Observed behaviour**
It currently points to 
https://platform-docs.opentargets.org/evidence#project-score

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an associations page e.g. https://platform.opentargets.org/disease/MONDO_0016063/associations
2. Click on the documentation icon which appears when you hover over CRISPR Screens
3. See error

<img width="1440" alt="Screenshot 2024-03-25 at 12 24 21" src="https://github.com/opentargets/issues/assets/73692302/a1bb2b90-8d8a-47ac-8e53-84b8f4e21c54">

**Comment by HelenaCornu** [comment]
Same issue for PROGENy — it currently points to SLAPenrich

**Comment by carcruz** [comment]
Thanks @HelenaCornu! Can you help me to update them [here](https://github.com/opentargets/ot-ui-apps/blob/main/apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js) and create a PR?
