### ISSUE TITLE
Variant Page Implementation - data and FE first scoping iterations summary ticket

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3272]
The team is currently iterating on MVP for datasets and design for a Variant Page, which would be a new addition to the Open Targets (new entity). This task is part of the discussion on how we can build a UI/web application from Gentropy.

We are now working on a page blueprint **[link here]**, which contains dataponts and MVP design for the new page.

This ticket will capture all the above iterations, focusing on data and front-end (with BE iterations to be scoped in between).

**Comment by buniello** [comment]
Some notes from discussions this week on the metadata section (please add/edit where relevant):
- **VEP**: we should add VEP most sever consequence in metadata section of the page. This is currently already in the data and we are focusing on `hgvsp` and `impact`columns for the `transcript_consequences`
- **VEP**: there is some discussion on whether we should also consider `motif_feature_consequences` and `regulatory_feature_consequences` 
- **ProtVar links**: we plan to show a link-out to ProtVar (at the top of the page) when the variant is likely to be found there. If the most severe consequence is in a list of qualifying consequences (e.g. most severe consequence == “missense_variant”,…) we can build a link [like this](https://www.ebi.ac.uk/ProtVar/query?chromosome=20&genomic_position=31257685&reference_allele=C&alternative_allele=A). Daniel to provide a list of consequences for relevant ProtVar assessment.
- **Closest gene feature**: we can use current logic for now (chances are low for a variant to be too far from any gene making to the variant index) and implement a more complete solution later.
