### ISSUE TITLE
Improve liftover procedure using large hail table

### ISSUE THREAD

**Issue by Daniel-Considine** [opentargets/issues#3275]
## Background

Currently we are using the liftover function in hail to convert GRCh37 coordinates to GRCh38. 
This can be done using:
`gs://gcp-public-data--gnomad/release/2.1.1/liftover_grch38/ht/genomes/gnomad.genomes.r2.1.1.sites.liftover_grch38.ht`

Which is a ~700GiB hail table containing all GRCh37 variants and their GRCh38 mapping. 

## Tasks

- [x] Update the way we move between genome builds

**Comment by prashantuniyal02** [comment]
@Daniel-Considine is this still planned?
