### ISSUE TITLE
Implement facet search api

### ISSUE THREAD

**Issue by jdhayhurst** [opentargets/issues#3276]
As a user I want to be able to search for facets. This ticket is about exposing the opensearch index to the user to enable a fuzzy text search of facet label via a new API endpoint. 

The API endpoint will accept a query string and a context (target or disease). It will return search hits. The hits will include the facet label, the target or disease ids, the facet category and the id of the facet label. 

## Background

See https://github.com/opentargets/issues/issues/3239

## Tasks

- [x] define the data models in the API, one for target facets, one for disease facets 
- [x] implement an endpoint enabling the fuzzy text search of the facet label within either the target or disease facet search index

## Acceptance tests

How do we know the task is complete? 

1. The API has an endpoint all

**Comment by prashantuniyal02** [comment]
After some discussion, it might be best to use OR filter within category and an AND filter between categories
