### ISSUE TITLE
Known Drugs widget in PPP does not load for Parkinson's Disease

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#3281]
**Describe the bug**
Known Drugs widget throws an error in the Parkinson's Disease profile page (MONDO_0005180)

**Observed behaviour**
In the PPP, the Known Drugs widget in the Parkinson's Disease profile page shows the error message: "Something went wrong. Please [submit a bug report](https://partner-platform.opentargets.org/) on the Open Targets Community ()"

**Expected behaviour**
The widget should load. Note the widget works in the public platform.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://partner-platform.opentargets.org/disease/MONDO_0005180'
2. Scroll down to 'Known Drugs'
3. See error

**Additional context**
Other disease profile pages I checked load correctly.

(side note why are there empty parentheses in the error message?)

**Comment by buniello** [comment]
high priority issue
