### ISSUE TITLE
Update Gene2Phenotype parser to include the skeletal panel

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3288]
From the Gene2Phenotype page a skeletal panel of causal genes can also be downloaded. This data should be ingested as diease/target evidence. 

## Tasks

- [ ] Explore the new panel.
- [ ] Update parser.
- [ ] Update pipeline configuration.

## Acceptance tests

1. Make sure the new data is ingested.
2. Validate evidence against schema

**Comment by prashantuniyal02** [comment]
released in Platform 24.06
