### ISSUE TITLE
Review ChEMBL34 data updates

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3289]
ChEMBL34 is out with relevant changes that include an update of drugbase. We want to look at this data prior ingestion to:
- identify new fields we could bring
- avoid issues down the line

## Tasks
From the [blogpost](https://chembl.blogspot.com/2024/04/chembl-34-is-out.html), we should look at:
- Increase of **drug-indication coverage** after the inclusion of EMA data (relevant for this https://github.com/opentargets/issues/issues/3065)
- Addition of **orphan** drug flag only available for EMA drugs - interesting to include if coverage is good
- Revision of **prodrug** flag
- Newer considerations to define **maximum phase**. I think the definition hasn't changed.
- Update in the **drug warnings** dataset to capture FDA labels up to Dec 2023.
- Improved strategy to assign a name that could impact this issue https://github.com/opentargets/issues/issues/3217

The @opentargets/be-team  has downloaded the latest indices for us so that we could investigate: `gs://open-targets-pre-data-releases/24.06dev/input/`

The target/disease evidence hasn't been submitted yet. It will be based on this ChEMBL version and it will contain trials up to June 2023.

**Comment by prashantuniyal02** [comment]
Hi @ireneisdoomed , do we have any examples of new drugs from EMA that are not present in FDA?
