### ISSUE TITLE
Searching on Genetics gives a 404

### ISSUE THREAD

**Issue by HelenaCornu** [opentargets/issues#3305]
**Describe the bug**
Searching for a gene, variant, or study on Open Targets Genetics and pressing return leads to a 404 page.

**Observed behaviour**
If I search for a gene, variant, or study and press return, I get a 404 page. This does not happen if I click on the suggested entities from the search bar.

**Expected behaviour**
Pressing return should bring up a page with the list of suggested entities.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'genetics.opentargets.org'
2. Search for an entity, and press return
3. See error

**Additional context**
Issue submitted by external user.

**Comment by chinmehta** [comment]
Not really, this bug is essentially that there was no landing search page for genetics, and we used to not show "search for <term>" option in genetics, it was only for platform. But i think in changes that condition got removed and now it shows that option which was never there.

**Comment by prashantuniyal02** [comment]
This issue can't be resolved in its current state. It will be resolved in due time with the release of the new genetics product.
