### ISSUE TITLE
Validation Lab updates for PPP widget UI

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3310]
This is a duplicate ticket to [#3298](https://github.com/opentargets/issues/issues/3298).

FE comment for the record:
I am sharing here[ the link](https://docs.google.com/presentation/d/1RV8W0nOIgoQ9OqQ7G5d7AI-EOX6irA3XQS5DpOhOu44/edit#slide=id.g2d0e8072d9a_1_10) to a widget mock-up we have discussed last week.
The data team is now working on parsing the data into the agreed schema, and myself/FE will pick the task from there moving forward.

**Comment by buniello** [comment]
closing as duplicate
