### ISSUE TITLE
Remove subtext from evidence page cards

### ISSUE THREAD

**Issue by chinmehta** [opentargets/issues#3330]
**Describe the bug**
Remove subtext from evidence page cards

**Observed behaviour**
Remove subtext from evidence page cards

**Expected behaviour**
No subtext from evidence page cards

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to evidence page
2. See cards with subtext 

**Additional context**

**Comment by prashantuniyal02** [comment]
closed as https://github.com/opentargets/ot-ui-apps/pull/387#issuecomment-2188708922
