### ISSUE TITLE
Updating PPP project tables and links (24.06)

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3338]
As part of PPP 24.06 we should update the project tables - all new info have been added to this [spreadsheet](https://docs.google.com/spreadsheets/d/1-TQGbqieghdBawZ-C_os8GTVmLXWFxRqZNeMVrDFu94/edit#gid=1179867447).

Similarly, we should update the OTAR2061 iFuncOnc (CRISPR widget)[ link](https://home.opentargets.org/ppp-documentation-otar2061) with content for the doc shortcut.

**Comment by prashantuniyal02** [comment]
Released in PPP
