### ISSUE TITLE
Unification of lift over strategies in Gentropy

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3342]
As a **[user|developer|etc]** I want **<describe feature>** because **<reason>**

## Background

Provide any necessary background information to provide context on the issue. 

## Tasks

- [ ] Update ...
- [ ] Configure ...

## Acceptance tests

How do we know the task is complete? 

1. When I go to page XX I see YY. 
2. When I click on 'foo' I see pop-up 'bar'

**Comment by d0choa** [comment]
This could be followed up later on. Closing as no context provided and not urgent
