### ISSUE TITLE
Sorting out alternative data access from google bucket locations 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3343]
We received feedback from users that lack of access to these Google bucket contents may be required to run Gentropy.

- [x] gs://genetics_etl_python_playground/static_assets
- [x] gs://genetics_etl_python_playground/input/Finngen_susie_finemapping_r10/Finngen_susie_credset_summary_r10.tsv
- [x] gs://gwas_catalog_data/curated_inputs
- [x] gs://gwas_catalog_data/manifests
- [x] gs://genetics_etl_python_playground/input/preprocess
- [x] gs://genetics_etl_python_playground/input/Finngen_susie_finemapping_r10/full 

Task is:

- [ ]  going through list of paths and decide which ones are inputs to include in the release, which ones are available in other FTP locations, etc.

**Comment by project-defiant** [comment]
One note on how to set up access to specific objects - https://cloud.google.com/storage/docs/access-control/using-iam-for-managed-folders @prashantuniyal02 FYI

**Comment by project-defiant** [comment]
@buniello do you want to move the objects to the release bucket ? or provide access to the objects directly?

**Comment by prashantuniyal02** [comment]
required permissions provided
