### ISSUE TITLE
Variant index data for backend integration

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3350]
The new variant annotation data is available:

- <s>JSON: `gs://ot-team/dsuveges/variant_index_new_json` (7.72 GiB)</s>
-  <s>Parquet: `gs://ot-team/dsuveges/variant_index_new` (1.01 GiB) </s>
- New data available here: `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/test_variant_index`

### Some stats:

- The dataset contains 7.09M variants, 
- 5.8M of them has allele frequencies (81%)
- 615k has no in-silico predictors (8.6%)
- 484k has no cross-references (6.8%)

### Schema:

```txt
root
 |-- variantId: string (nullable = true)
 |-- chromosome: string (nullable = true)
 |-- position: integer (nullable = true)
 |-- referenceAllele: string (nullable = true)
 |-- alternateAllele: string (nullable = true)
 |-- inSilicoPredictors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- method: string (nullable = true)
 |    |    |-- assessment: string (nullable = true)
 |    |    |-- score: float (nullable = true)
 |    |    |-- assessmentFlag: string (nullable = true)
 |    |    |-- targetId: string (nullable = true)
 |-- mostSevereConsequenceId: string (nullable = true)
 |-- transcriptConsequences: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- variantConsequenceIds: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- amino_acid_change: string (nullable = true)
 |    |    |-- uniprotAccessions: array (nullable = true)
 |    |    |    |-- element: string (containsNull = true)
 |    |    |-- isEnsemblCanonical: boolean (nullable = true)
 |    |    |-- codons: string (nullable = true)
 |    |    |-- distance: long (nullable = true)
 |    |    |-- targetId: string (nullable = true)
 |    |    |-- impact: string (nullable = true)
 |    |    |-- transcriptId: string (nullable = true)
 |    |    |-- lofteePrediction: string (nullable = true)
 |    |    |-- siftPrediction: float (nullable = true)
 |    |    |-- polyphenPrediction: float (nullable = true)
 |-- rsIds: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- dbXrefs: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- source: string (nullable = true)
 |-- alleleFrequencies: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- populationName: string (nullable = true)
 |    |    |-- alleleFrequency: double (nullable = true)
```

### Resolvable entities

In this dataset the following fields can be resolved to existing objects:

- `transcriptConsequences.variantConsequenceIds` -> sequence ontology terms.
- `mostSevereConsequenceId` -> sequence ontology term.
- `transcriptConsequences.targetId` -> target identifier.

### Other

For @gjmcn , some variants can have 5 different cross-references:
```json
[
  {
    "id": "rs1801253",
    "source": "ensemblVariation"
  },
  {
    "id": "604878#0009",
    "source": "omim"
  },
  {
    "id": "VCV000017746",
    "source": "clinVar"
  },
  {
    "id": "10_114045297_G_C",
    "source": "protVar"
  },
  {
    "id": "10-114045297-G-C",
    "source": "gnomad"
  }
]
```

Link generation:

- **ensemblVariation**:  `https://www.ensembl.org/Homo_sapiens/Variation/Explore?v={id}`
- **gnomad**: `https://gnomad.broadinstitute.org/variant/{id}?dataset=gnomad_r4`
- **protVar**: needs parsing - `https://www.ebi.ac.uk/ProtVar/query?chromosome={chr}&genomic_position={pos}&reference_allele={ref}&alternative_allele={alt}`
- **clinVar**:  `https://www.ncbi.nlm.nih.gov/clinvar/variation/{id}/`
- **omim**: `https://www.omim.org/entry/{id}`

**Comment by DSuveges** [comment]
@remo87 , A new variant dataset has been created here: `gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/test_variant_index`

Please use this one, as this dataset has been built by the most recent code + via the actual variant index pipeline implementation. The only mentionable difference is that GnomAD data is used to source other in-silico predictors (spiceai and pangolin) we cannot get from VEP.

```json
  "inSilicoPredictors": [
    {
      "method": "phred scaled CADD",
      "score": 1.44,
      "targetId": "ENSG00000183495"
    },
    {
      "method": "spliceai",
      "score": 0.0
    },
    {
      "method": "pangolin",
      "score": 0.0
    }
  ],
```

**Comment by remo87** [comment]
@DSuveges @d0choa I see in the schema that all the fields are marked as nullable. Is this the case? Are all fields other than the variant id optional?

**Comment by DSuveges** [comment]
The following fields are expected to be mandatory:
```
 |-- variantId: string (nullable = true)
 |-- chromosome: string (nullable = true)
 |-- position: integer (nullable = true)
 |-- referenceAllele: string (nullable = true)
 |-- alternateAllele: string (nullable = true)
 |-- mostSevereConsequenceId: string (nullable = true)
```
The consequence term is always computable, it must be there. Also the genomic location and alleles are expected to be present.

**Comment by remo87** [comment]
I finished the implementation of the change I'm going to deploy to dev so that the change can be tested

**Comment by remo87** [comment]
The new environment is deployed in the url `variant.dev.opentargets.xyz`. This is a sample query:
```
# Write your query or mutation here
query {
  variant(variantId:"11_108288992_T_C"){
    variantId
    chromosome
    position
    referenceAllele
    alternateAllele
    inSilicoPredictors{
      method
      assessment
      score
      assessmentFlag
      targetId
    }
    mostSevereConsequenceId
    transcriptConsequences {
      variantConsequenceIds
      amino_acid_change
      uniprotAccessions
      isEnsemblCanonical
      codons
      distance
      targetId
      impact
      transcriptId
      lofteePrediction
      siftPrediction
      polyphenPrediction
    }
    rsIds
    dbXrefs {
      id
      source
    }
    alleleFrequencies {
      populationName
      alleleFrequency
    }
  }
}
```

**Comment by d0choa** [comment]
The API is not returning a fraction of the variants in the dataset. This is an example of a missing variant 

```
-RECORD 0---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 variantId               | 1_209770915_G_T
 alleleFrequencies       | [{afr_adj, 3.897817222355481E-4}, {ami_adj, 0.0}, {amr_adj, 4.8348106365834006E-4}, {asj_adj, 0.0}, {eas_adj, 0.0013178703215603585}, {fin_adj, 0.0012318642211880647}, {mid_adj, 0.0}, {nfe_adj, 1.335247187635611E-4}, {remaining_adj, 0.0}, {sas_adj, 0.0014212620807276862}]
 position                | 209770915
 referenceAllele         | G
 alternateAllele         | T
 inSilicoPredictors      | [{phred scaled CADD, null, 0.448, null, ENSG00000009790}, {spliceai, null, 0.0, null, null}, {pangolin, null, null, null, null}]
 mostSevereConsequenceId | SO_0001627
 transcriptConsequences  | [{[SO_0001627], null, [Q9Y228], true, null, null, ENSG00000009790, MODIFIER, ENST00000367025, null, null, null}]
 rsIds                   | [rs1468069866]
 dbXrefs                 | [{rs1468069866, ensemblVariation}, {1-209770915-G-T, gnomad}]
only showing top 1 row
```

**Comment by gjmcn** [comment]
@DSuveges The example query above from @remo87 returns 2 `clinVar` entries in `dbXrefs`. How should we handle the case of multiple `clinVar` entries when generating links on the variant page?

**Comment by d0choa** [comment]
@DSuveges just told me this is expected.

You can see how we handle OMIM or UMLS on the disease page. 
https://platform.opentargets.org/disease/EFO_0000756/associations

**Comment by buniello** [comment]
hi @remo87,  will the sequence ontology field resolved in long name e.g. [SO_0001819](http://purl.obolibrary.org/obo/SO_0001819) to _synonymous variant_ for FE to hyperlink long name?

**Comment by remo87** [comment]
> hi @remo87, will the sequence ontology field resolved in long name e.g. [SO_0001819](http://purl.obolibrary.org/obo/SO_0001819) to _synonymous variant_ for FE to hyperlink long name?

These items are going to be included in the next release

**Comment by buniello** [comment]
Tested new release: `variantconsequences` and `targetId` fields are not resolved yet. 
The `variantconsequence` field always returns `[]` and no data (as per resolving pending)
Ricardo is on leave today but i hope he gets this tomorrow

**Comment by prashantuniyal02** [comment]
@remo87 , here is an example of [] in `variantConsequences` which should be present for the following query:

```
query {
  variant(variantId:"OTVAR_1_109607656_cc1bda57abafe82ac6cb5ec620a02a19"){
    variantId
    chromosome
    position
    referenceAllele
    alternateAllele
    inSilicoPredictors{
      method
      assessment
      score
      assessmentFlag
      target {
       id
      }
    }
    mostSevereConsequence {
      id
      label
    }
    transcriptConsequences {
      variantConsequences {
        id
      }
      amino_acid_change
      uniprotAccessions
      isEnsemblCanonical
      codons
      distance
      target {
        id
      }
      impact
      transcriptId
      lofteePrediction
      siftPrediction
      polyphenPrediction
    }
    rsIds
    dbXrefs {
      id
      source
    }
    alleleFrequencies {
      populationName
      alleleFrequency
    }
  }
}
```

**Comment by DSuveges** [comment]
Hi @remo87 , as @buniello has noticed, all `amino_acid_change` fields are null, even for variants that are missense (eg. `2_108771794_C_T`). The reason is that, at some point in the near past, we noticed that this column name is in snake case instead of camelcase. 🤦🏻‍♂️ So, the field was renamed to `aminoAcidChange`. Once you are updating the dataset, could you please change the name of this field?

**Comment by remo87** [comment]
I'm reviewing the variantConsequences to confirm where the problem can be. both target and mostSevereConsequence are resolving

**Comment by remo87** [comment]
> `2_108771794_C_T`

will do!

**Comment by remo87** [comment]
Found the issue with the variantConsequences what happened was that the field name changed from variantConsequenceIds to variantFunctionalConsequenceIds that's why it wasn't being resolved. Also just renamed the field amino_acid_change is now aminoAcidChange a sample query ```

**Comment by remo87** [comment]
I'll preparing the deployment

**Comment by DSuveges** [comment]
There are a handful of planned updates for the next iteration for the data, some might have implications on the API:

- [ ] Adding HGVS identifiers (**new API field is required**)
- [ ] `distance` field is removed (**API needs update**)
- [ ] `distanceFromFootprint` - column is added (**API update**) 
- [ ] `distanceFromTss` - column added (**API update**) (VEP call: `--plugin TSSDistance`)
- [ ] VEP is called with `--distance 500000` to increase the covered area.
- [ ] `appris` column is added to indicate principality of transcript.

As a related effort, I made sure that the distances VEP returns is correct: https://gist.github.com/DSuveges/e5d655492beab70b7607e3bf7f539489

**Comment by DSuveges** [comment]
New version of the variant dataset is prepared. The json files are here:
gs://genetics_etl_python_playground/ds_vep_0720/variant_index.json/

**Some stats:**

- Number of variants: 7,751,357
- Number of variants with hashed alleles: 3,258 (0.042%)
- Number of variants in GnomAD4: 6,736,406 (87%)
- Number of variants with zero genes: 340 (0.004%)
- Mean number of genes in VEP object: 28.69
- Median number of genes in VEP object: 24.00
- Max number of genes in VEP object: 182
- Variants with more than 100 genes in vep: 64,204 (0.828%)

A list of variant ids with a lot of (100+) genes:
```txt
+-----------------+
|        variantId|
+-----------------+
|15_25300584_AAC_A|
| 14_105795065_A_T|
|   16_2070496_T_C|
|   16_2240094_C_T|
|   16_1647975_C_T|
|   16_2088293_C_G|
|   16_2084976_T_G|
|  7_142309691_G_C|
|  7_142752005_G_T|
|   6_31304729_T_C|
|  14_22805380_G_T|
|  19_53899167_C_G|
|   16_2611380_G_C|
|   6_31389653_G_T|
|   16_2065540_C_G|
| 5_141122904_GA_G|
|   16_2422745_A_G|
|  14_22313883_G_A|
|   16_2114853_C_A|
|   16_2048730_A_G|
+-----------------+
```
For @remo87 , @gjmcn  and @jdhayhurst : This dataset has some updates:

- New field in transcripts: `consequenceScore` is a non-nullable float that quantifies the predicted effect of the variant on the transcript. This value is used as a locus 2 gene feature.
- New field in transcripts: `transcriptIndex` is a non-nullable integer from 1 to the number of transcripts, where 1 is being the more relevant. This field should be used to order the genes in the VEP widget and to suggest gene for a variant. The order is a combination of the consequence score + distance from footprint (upon equal score the closer gene has a lower index).
- New field: `hgvsId` is a non-nullable string column providing an other identifier constructed by the the genomic location.

**One example:**

```txt
{
  "variantId": "8_117822564_G_GT",
  "chromosome": "8",
  "position": 117822564,
  "referenceAllele": "G",
  "alternateAllele": "GT",
  "inSilicoPredictors": [
    {
      "method": "loftee",
      "assessment": "HC",
      "score": null,
      "assessmentFlag": null,
      "targetId": "ENSG00000182197"
    }
  ],
  "mostSevereConsequenceId": "SO_0001589",
  "transcriptConsequences": [
    {
      "variantFunctionalConsequenceIds": [
        "SO_0001589"
      ],
      "aminoAcidChange": "-440X",
      "uniprotAccessions": [
        "Q16394"
      ],
      "isEnsemblCanonical": true,
      "codons": "-/A",
      "distanceFromFootprint": 0,
      "distanceFromTss": 289261,
      "appris": "P1",
      "maneSelect": "NM_000127.3",
      "targetId": "ENSG00000182197",
      "impact": "HIGH",
      "lofteePrediction": "HC",
      "siftPrediction": null,
      "polyphenPrediction": null,
      "consequenceScore": 1.0,
      "transcriptIndex": 1,
      "transcriptId": "ENST00000378204"
    },
    {
      "variantFunctionalConsequenceIds": [
        "SO_0001632"
      ],
      "aminoAcidChange": null,
      "uniprotAccessions": [
        "Q96HR3"
      ],
      "isEnsemblCanonical": true,
      "codons": null,
      "distanceFromFootprint": 282302,
      "distanceFromTss": 301851,
      "appris": "P1",
      "maneSelect": "NM_080651.4",
      "targetId": "ENSG00000164758",
      "impact": "MODIFIER",
      "lofteePrediction": null,
      "siftPrediction": null,
      "polyphenPrediction": null,
      "consequenceScore": 0.0,
      "transcriptIndex": 2,
      "transcriptId": "ENST00000297347"
    },
    {
      "variantFunctionalConsequenceIds": [
        "SO_0001631"
      ],
      "aminoAcidChange": null,
      "uniprotAccessions": [],
      "isEnsemblCanonical": true,
      "codons": null,
      "distanceFromFootprint": 298503,
      "distanceFromTss": 298504,
      "appris": null,
      "maneSelect": null,
      "targetId": "ENSG00000239917",
      "impact": "MODIFIER",
      "lofteePrediction": null,
      "siftPrediction": null,
      "polyphenPrediction": null,
      "consequenceScore": 0.0,
      "transcriptIndex": 3,
      "transcriptId": "ENST00000483812"
    },
    {
      "variantFunctionalConsequenceIds": [
        "SO_0001631"
      ],
      "aminoAcidChange": null,
      "uniprotAccessions": [],
      "isEnsemblCanonical": true,
      "codons": null,
      "distanceFromFootprint": 468643,
      "distanceFromTss": 468644,
      "appris": null,
      "maneSelect": null,
      "targetId": "ENSG00000225885",
      "impact": "MODIFIER",
      "lofteePrediction": null,
      "siftPrediction": null,
      "polyphenPrediction": null,
      "consequenceScore": 0.0,
      "transcriptIndex": 4,
      "transcriptId": "ENST00000430457"
    }
  ],
  "rsIds": [],
  "hgvsId": "8:g.117822565dup",
  "alleleFrequencies": [],
  "dbXrefs": []
}
```

**Comment by prashantuniyal02** [comment]
@DSuveges updated in the 14/08 meeting that the process to build this variant index needs work.
