### ISSUE TITLE
`gwas_study_index` data for backend integration

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3357]
Similar to the work on variant index (#3350), we would like to serve a `gwas_study_index` dataset through OS + API.

This dataset is created by different upstream ETL processes ([gentropy](https://github.com/opentargets/gentropy)), but they all write to the same location and contain a [shared schema](https://github.com/opentargets/gentropy/blob/e5c2f3a8796856db75e1e1a66fa17dabb2eb5e59/src/gentropy/assets/schemas/study_index.json) validated within the ETL. So effectively, they can be considered one single dataset that we will like to load:

```
❯ gsutil ls gs://genetics_etl_python_playground/releases/24.06/study_index/
gs://genetics_etl_python_playground/releases/24.06/study_index/eqtl_catalogue/
gs://genetics_etl_python_playground/releases/24.06/study_index/finngen/
gs://genetics_etl_python_playground/releases/24.06/study_index/gwas_catalog/
```

Some stats:
- Parquet size: 114.5 MiB
- Rows (studies): 1_971_058
- Study type breakdown:
```
+---------+-------+
|studyType|  count|
+---------+-------+
|     sqtl| 214987| -> No traitFromSourceMappedIds or backgroundTraitFromSourceMappedIds
|     pqtl|    802| -> No traitFromSourceMappedIds or backgroundTraitFromSourceMappedIds
|    tuqtl| 364493| -> No traitFromSourceMappedIds or backgroundTraitFromSourceMappedIds
|     eqtl|1299310| -> No traitFromSourceMappedIds or backgroundTraitFromSourceMappedIds
|     gwas|  91466| -> Null geneId, Null biosampleFromSourceId, 13_112 Not null backgroundTraitFromSourceMappedIds
+---------+-------+
```
   

### Resolvable entities

Some of these columns are nullable, as described in the table above: 
- `traitFromSourceMappedIds` -> `diseases` . `traitFromSourceMappedId`should be converted to a `diseases` array column containing a list of resolvable `disease` objects.
- `backgroundTraitFromSourceMappedIds` -> `backgroundTraits` Exactly the same as the above.
- `geneId` -> `target`. All Ensembl gene IDs. should be converted into resolvable `target` objects.

*There is a special case for `biosampleFromSourceId. In the future, we might want to resolve this object, but it has some extra complexities that we would like to postpone to a later time.*

The latest stable version of the `study index` aligned with the schema provided above can be found here: `gs://genetics_etl_python_playground/releases/24.06/study_index/`

Some of the sub-datasets do not present every column. I had to use the next option to read everything spark.read.option('mergeSchema', 'true').parquet(... ). In the future, this dataset might come from one single parquet instead of a directory of parquets with compatible schema.

**Comment by buniello** [comment]
Can i please get a `sample` dataset from this so that i can think about scoping the page? Ideally with studies from multiple sources @d0choa @DSuveges

**Comment by d0choa** [comment]
3 examples capturing the majority of the diversity:

GWAS Catalog study:

```
-RECORD 0---------------------------------------------------------------------------------------------------------------------------------
 studyId                            | GCST000124
 projectId                          | GCST
 studyType                          | gwas
 traitFromSource                    | Alzheimer's disease
 geneId                             | null
 biosampleFromSourceId              | null
 nSamples                           | 1489
 summarystatsLocation               | null
 hasSumstats                        | false
 cohorts                            | [null]
 initialSampleSize                  | 753 European ancestry cases, 736 European ancestry controls
 traitFromSourceMappedIds           | [MONDO_0004975]
 publicationJournal                 | Arch Neurol
 publicationDate                    | 2007-11-12
 ldPopulationStructure              | [{nfe, 1.0}]
 backgroundTraitFromSourceMappedIds | null
 qualityControls                    | null
 replicationSamples                 | [{European, 667}]
 nControls                          | 736
 pubmedId                           | 17998437
 publicationFirstAuthor             | Li H
 publicationTitle                   | Candidate single-nucleotide polymorphisms from a genomewide association study of Alzheimer disease.
 discoverySamples                   | [{European, 1489}]
 nCases                             | 753
 analysisFlags                      | null
 ```

A finngen study:
```
-RECORD 0--------------------------------------------------------------------------------------------
 studyId               | FINNGEN_R10_AB1_ACTINOMYCOSIS
 traitFromSource       | Actinomycosis
 nCases                | 101
 nControls             | 363227
 nSamples              | 363328
 projectId             | FINNGEN_R10
 studyType             | gwas
 hasSumstats           | true
 initialSampleSize     | 377,277 (210,870 females and 166,407 males)
 discoverySamples      | [{377277, Finnish}]
 cohorts               | [FinnGen]
 summarystatsLocation  | gs://finngen-public-data-r10/summary_stats/finngen_R10_AB1_ACTINOMYCOSIS.gz
 ldPopulationStructure | [{fin, 1.0}]
 ```

sceQTL study:
```
-RECORD 0--------------------------------------------------------------------------------------------------------
 studyId                            | Cytoimmgen_TCM_STIM_16H_ENSG00000151640
 projectId                          | Cytoimmgen
 studyType                          | eqtl
 traitFromSource                    | ENSG00000151640
 geneId                             | ENSG00000151640
 biosampleFromSourceId              | CL_0000624
 nSamples                           | 100
 summarystatsLocation               | https://ftp.ebi.ac.uk/pub/databases/spot/eQTL/sumstats/QTS000041/QTD000726
 hasSumstats                        | true
 cohorts                            | null
 initialSampleSize                  | null
 traitFromSourceMappedIds           | null
 publicationJournal                 | null
 publicationDate                    | null
 ldPopulationStructure              | null
 backgroundTraitFromSourceMappedIds | null
 qualityControls                    | null
 replicationSamples                 | null
 nControls                          | null
 pubmedId                           | null
 publicationFirstAuthor             | null
 publicationTitle                   | null
 discoverySamples                   | null
 nCases                             | null
 analysisFlags                      | null
 ```

**Comment by d0choa** [comment]
Keep in mind it was not originally designed for the UI. We can change  things.

**Comment by buniello** [comment]
sceQTL study schema needs to be revised, i will suggest according to [this page](https://www.ebi.ac.uk/eqtl/Studies/):

**Comment by buniello** [comment]
Discussed with David - suggestions for the sceQTLs schema - @ireneisdoomed please let me know if you have any Qs.
Main note: the `projectID` as populated in the schema above contains info on the publication in [this table](https://www.ebi.ac.uk/eqtl/Studies/). e.g. in the table, [Cytoimmgen](https://www.nature.com/articles/s41588-022-01066-3) is hyperlinked to a paper with PMID. Can we extract info from that PubMed link?
```

-RECORD 0--------------------------------------------------------------------------------------------------------
 studyId                            | Cytoimmgen_TCM_STIM_16H_ENSG00000151640 -- ENSGid will be converted to `target` object here in string, which is needed for readability
 **projectId**                          | **eQTLCatalog_Cytoimmgen**
**studyType**                          | **sceqtl**
 traitFromSource                    | ENSG00000151640
 geneId                             | ENSG00000151640
 biosampleFromSourceId              | CL_0000624
 nSamples                           | 100
 summarystatsLocation               | https://ftp.ebi.ac.uk/pub/databases/spot/eQTL/sumstats/QTS000041/QTD000726
 hasSumstats                        | true
 cohorts                            | null
 initialSampleSize                  | null
 traitFromSourceMappedIds           | null
 publicationJournal                 | null
 publicationDate                    | null
 ldPopulationStructure              | null
 backgroundTraitFromSourceMappedIds | null
 qualityControls                    | null
 replicationSamples                 | null
 nControls                          | null
**pubmedId**                           | **(from [Cytoimmgen](https://www.nature.com/articles/s41588-022-01066-3) on  https://www.ebi.ac.uk/eqtl/Studies/)**
**publicationFirstAuthor**             | **(from [Cytoimmgen](https://www.nature.com/articles/s41588-022-01066-3) on  https://www.ebi.ac.uk/eqtl/Studies/)**
 **publicationTitle**                   | **(from [Cytoimmgen](https://www.nature.com/articles/s41588-022-01066-3) on  https://www.ebi.ac.uk/eqtl/Studies/)**
 discoverySamples                   | null
 nCases                             | null
 analysisFlags                      | null

```

**Comment by buniello** [comment]
Additional request:

- [ ] FinnGen - `StudyId` files: can I have `FINNGEN_R10` removed from the field string.
- [ ]e.g. in the example above `StudyId` will only return `AB1_ACTINOMYCOSIS`

**Comment by buniello** [comment]
@d0choa from the FinnGen example dataset above I am missing the `traitFromSourceMappedIds` - is that intentional?

**Comment by d0choa** [comment]
It's good that you raised it; we might need to do something about it. You can assume you will have a `disease` object available, but the data might have an issue.

**Comment by remo87** [comment]
@d0choa @buniello I'm having a problem with the data the Gwas Study structure has 24 fields and the types we use in scala 2 are limited to 22. To solve this issue we have 3 options

1. Group some of the fields
2. Add a new definition of the type
3. Upgrade to Scala 3

The fastest solution would be 1. Solution 2 I'm not a big fan because I don't know if we can have some issue with some of the libraries we use. Option 3 would be the best to avoid having this issue in the future; this option is planned as an activity for the summer but it would potentially take a some weeks.

**Comment by d0choa** [comment]
how is this possible? evidence has 60+ fields?

**Comment by remo87** [comment]
I just checked evidence and it's being handled in a different way I was trying to parse the json to a Scala object and thus I was getting the error evidence is not doing this is not parsing the object It's using the JsValue object. I we can go try that for this entity that's an option I hadn't explore thanks @d0choa

**Comment by remo87** [comment]
@d0choa, @DSuveges I found something in the data the cohorts field when it doesn't have items it has a value of `[null]` this is causing issues with the json parser. We would need to either map it to null or an empty array `[]`

**Comment by DSuveges** [comment]
I can take care of that.

**Comment by buniello** [comment]
Tested: gwas_study API is returning data for Gwas Catalog and eQTL Catalogue but NOT for FINNGEN studies

**Comment by buniello** [comment]
NOTE: Finngen studies are still missing from API

**Comment by DSuveges** [comment]
@buniello, unrelated to the absence of the finngen studies in the API, the eQTL catalog and FINNGEN study updates will not available in the data yet. The code has been updated, but until there's a gentropy data release, the only the old version is there, upon release everything will be automatically updated. If any of the proposed change involves schema/API work, we'll run the respective step.

**Comment by remo87** [comment]
the issue is related to the dataset version I don't have the latest gwas study dataset. I'll start updating the data images with the latest version
