### ISSUE TITLE
Study index gentropy ETL step

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3359]
Currently, study indexes are created from different sources (e.g., GWAS Catalogue, eQTL catalog, Finngen) and written in a GCP bucket location. The study indexes are self-contained within the data sources, independent of other datasets, and contain all the necessary study metadata. 

When a release is due, the study indexes are moved to a central location using airflow operators and considered as the final study index.

```
❯ gsutil ls gs://genetics_etl_python_playground/releases/24.06/study_index/
gs://genetics_etl_python_playground/releases/24.06/study_index/eqtl_catalogue/
gs://genetics_etl_python_playground/releases/24.06/study_index/finngen/
gs://genetics_etl_python_playground/releases/24.06/study_index/gwas_catalog/
```
 
We want to expand this functionality to evaluate the study indexes and validate whether the records in them contain valid entities.

We would want 2 main functionalities similar to platform-etl:
- entity validation, with the consequent log of invalid studies and reason
- recover obsoleted IDs by using the respective indexes with a history log

In the context of study index, the fields to ensure validation are:
- `geneId`
-  `backgroundTraitFromSourceMappedIds`
- `traitFromSourceMappedIds`

Additionally, `biosampleFromSourceId` would also require validation, but because it currently contains both UBERON and CL codes, it might require additional considerations before validation.

This might be the first of a series of actions to ensure every dataset is compatible in the context of the Platform-gentropy integration.

**Comment by d0choa** [comment]
On your snippet, you might want to create an invalid dataset as well.

[Code snippet](https://github.com/opentargets/platform-etl-backend/blob/9ba8a4345933175ae2d74102d5473af96a40f727/src/main/scala/io/opentargets/etl/backend/evidence/Evidence.scala#L343) on how the platform-etl does it, in case it's useful for inspiration

Regarding `geneId` and `targetId`. In an ideal world, I agree we should probably use the `targetFromSourceId` and `targetFromSourceMappedId` for consistency. The API will turn `targetFromSourceMappedId` into a fully fletched `target` object.

The nesting of disease is really annoying

**Comment by DSuveges** [comment]
I'm practically taking advantage of the already existing QC flagging instrumentation in study locus class (`update_quality_flag`, which is now moved to the base dataset class, so shared across all datasets we have). Also having a specific set of flags for study QC issues.

```python
(
    StudyIndex.from_parquet(session, study_paths)
    .validate_unique_study_id() # Flagging duplicated study ids
    .validate_study_type() # Flagging non-supported study types.
    .validate_target(gene_index) # Flagging studies with non-recognised EFOs
    .validate_disease(disease_index) # Flagging QTL studies with unresolved gene ids.
)
``` 

The result of all these validations will be collected in the `qualityControls` column and can be sorted into a failed and passed datasets (`.filter(f.size('qualityControls) >0)`).

I think we found the right level of abstraction here... I'm quite happy how it turned out.

**Comment by DSuveges** [comment]
## Disease normalisation

- The list of EFOs from the study index are all mapped to our disease index allowing matching to retired ids as well.
- The source field is called `diseaseFromSourceMappedIds`, the mapped field will be called as `diseaseIds`. Also, the type is a list of strings. 
- `diseaseIds` contains all EFOs that could be matched from `diseaseFromSourceMappedIds`. Meaning _some_ efos might got dropped. 
- Only those studies will be flagged that would have **NO** valid EFOs. So, if out of the 3 EFOs in the source list only one can be mapped, that's OK, the study passes the QC.
