### ISSUE TITLE
Remove classic associations from BE

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3361]
We want to remove the classic associations page from the UI in both Platform and PPP. Consequently, we want to clean up the OT backend to slim down data, images and codebase.

A first scoping session with @jdhayhurst and @remo87 pointed to a few cleaning areas:

- **ETL**—The `AOTFElasticsearch` dataset seems to be available only for the facets (~20Gb JSONL repeated twice). It is not to be confused with `AOTFClickhouse,` which is still required.
- **Open Search** - Similarly, the `AOTFElasticsearch` datasets look there only for the old facets (~10Gb index).
- **API** - The `aggregationFilters: AggregationFilter` parameter in the `associatedTargets` and `associatedDiseases` endpoints won't be required. In the API response of these endpoints, we will no longer require the `aggregations: Aggregations` object.
- **Static assets**—I vaguely remember the Bubbles and Graph views in classic associations requiring some static assets derived from the ontology. These files might not be required anymore, but @opentargets/fe-team can confirm. 
- **FTP/BigQuery** - The datasets are no longer required in these components.

Assigning to @jdhayhurst in the first place for internal consideration in the @opentargets/be-team

**Comment by carcruz** [comment]
PR up in the UI to drop classic association https://github.com/opentargets/ot-ui-apps/pull/408
