### ISSUE TITLE
Update finngen to release 11 in gentropy

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3370]
We want to update Finngen to the latest release (11).
Minimal changes should be made to the Finngen data source parsers.

**Comment by DSuveges** [comment]
As I understand there are a few changes planned for the study index, right? What are these changes?

**Comment by d0choa** [comment]
#3371 can be addressed together with this task

**Comment by d0choa** [comment]
#3378 also links to the Finngen study index and tangentially to #3359

**Comment by ireneisdoomed** [comment]
addressed in https://github.com/opentargets/gentropy/pull/733
