### ISSUE TITLE
Study page FE scoping

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3377]
Please note - details below are going to be discussed in person next week.
See [here](https://genetics.opentargets.org/study/GCST002222) for current Open Targets Genetics study page.

- [ ] Scenario n1 - GWAS Catalog and FinnGen data (see example datasets below)

For `studyType` `gwas` :
- **Page header**: `studyId` (fixed study)

- **Small links below header**: 
**Trait: [link] (+Background trait if present in data) [link] | Source: [link]** 
Example:
1. **Trait link:** 
_Trait_: `traitFromSource` hyperlinked to https://platform.opentargets.org/disease/traitFromSourceMappedIds
& 
for `projectId` `GCST` -- if `backgroundTraitFromSourceMappedIds` is not `null` show _Background trait_: `backgroundTraitFromSource` hyperlinked to `https://platform.opentargets.org/disease/backgroundTraitFromSourceMappedIds`

PLEASE NOTE: the `traitFromSource` and `backgroundTraitFromSource` fields are now resolved into `id` and `name` disease objects.

2. **Source link:** 
- If `projectId` is `GCST`  show _Source_: GWAS Catalog hyperlinked with `https://www.ebi.ac.uk/gwas/studies/studyId`
- If `projectId` is `FINNGEN_R10` show _Source_: FinnGenR10 hyperlinked to  `[https://r10.finngen.fi/pheno/studyID`]

- **Page section: Study Summary**

- If `projectId` is `GCST`
Author:  `publicationFirstAuthor`
Publication date: `publicationYear`
Journal: `publicationJournal`
PubMed: `pubmedId` hyperlinked to `https://europepmc.org/article/med/pubmedId`
Has Sumstats: yes if `hasSumstats` is `true` & no if `hasSumstats` is `false`
N study: ` nSamples`
N  discovery: `initialSampleSize`
N replication: `replicationSamples`
N cases: `nCases`
N controls: `nControls`
Cohorts: `cohorts` - TOOLTIP: LD structure: `ldPopulationStructure`
QC: `qualityControls`
Study flags: `analysisFlags`

- If `projectId` is `FINNGEN_R10`
Author:  `FINNGEN_R10`
Publication date: `2023`
Journal: NA
PubMed: NA
Has summary stats: `yes`
N study: `nSamples`
N  discovery: `discoverySamples` Tooltip: `initialSampleSize`
N replication: `NA`
N cases: `nCases`
N controls: `nControls`
Cohorts: `FinnGen` - TOOLTIP: LD structure: `ldPopulationStructure`
QC: NA
Study flags: NA

GWAS Catalog study:
```

-RECORD 0---------------------------------------------------------------------------------------------------------------------------------
 studyId                            | GCST000124
 projectId                          | GCST
 studyType                          | gwas
 traitFromSource                    | Alzheimer's disease
 geneId                             | null
 biosampleFromSourceId              | null
 nSamples                           | 1489
 summarystatsLocation               | null
 hasSumstats                        | false
 cohorts                            | [null]
 initialSampleSize                  | 753 European ancestry cases, 736 European ancestry controls
 traitFromSourceMappedIds           | [MONDO_0004975]
 publicationJournal                 | Arch Neurol
 publicationDate                    | 2007-11-12
 ldPopulationStructure              | [{nfe, 1.0}]
 backgroundTraitFromSourceMappedIds | null
 qualityControls                    | null
 replicationSamples                 | [{European, 667}]
 nControls                          | 736
 pubmedId                           | 17998437
 publicationFirstAuthor             | Li H
 publicationTitle                   | Candidate single-nucleotide polymorphisms from a genomewide association study of Alzheimer disease.
 discoverySamples                   | [{European, 1489}]
 nCases                             | 753
 analysisFlags                      | null

```
A finngen study:
```

-RECORD 0--------------------------------------------------------------------------------------------
 studyId               |AB1_ACTINOMYCOSIS
 traitFromSource       | Actinomycosis
 nCases                | 101
 nControls             | 363227
 nSamples              | 363328
 projectId             | FINNGEN_R10
 studyType             | gwas
 hasSumstats           | true
 initialSampleSize     | 377,277 (210,870 females and 166,407 males)
 discoverySamples      | [{377277, Finnish}]
 cohorts               | [FinnGen]
 summarystatsLocation  | gs://finngen-public-data-r10/summary_stats/finngen_R10_AB1_ACTINOMYCOSIS.gz
 ldPopulationStructure | [{fin, 1.0}]
```

**Comment by buniello** [comment]
- [ ] Scenario n2 - QTLs

For `studyType` `eqtl`:

- **Page header**: `projectId`

- **Small links below header**:
**Affected gene [link]in cell type [link] \ Source [link]**

_Affected gene_:`traitFromSource` hyperlinked to https://platform.opentargets.org/target/geneId in _cell type_: ` biosampleFromSourceId` (we need a `biosampleFromSourcename` but I think this object will be resolved later). 
_Source_: eQTL Catalog hyperlinked to `https://www.ebi.ac.uk/eqtl/Studies/

- **Page section: Study Summary**
- If `datatype` is `eQTL` 
Author:  `publicationFirstAuthor`
Publication date:  `publicationDate`
Journal: `publicationJournal`
PubMed: `pubmedId`
Has summary stats: `yes`
Summary stats location: `summarystatsLocation`
N study: ` nSamples`
N  discovery: NA
N replication: NA
N cases: NA
N controls: NA
Cohorts: NA
QC: NA
Study flags: NA

sceQTL study:
```

-RECORD 0--------------------------------------------------------------------------------------------------------
 studyId                            | Cytoimmgen_TCM_STIM_16H_ENSG00000151640
 projectId                          | Cytoimmgen
 studyType                          | eqtl
 traitFromSource                    | ENSG00000151640
 geneId                             | ENSG00000151640
 biosampleFromSourceId              | CL_0000624
 nSamples                           | 100
 summarystatsLocation               | https://ftp.ebi.ac.uk/pub/databases/spot/eQTL/sumstats/QTS000041/QTD000726
 hasSumstats                        | true
 cohorts                            | null
 initialSampleSize                  | null
 traitFromSourceMappedIds           | null
 publicationJournal                 | null
 publicationDate                    | null
 ldPopulationStructure              | null
 backgroundTraitFromSourceMappedIds | null
 qualityControls                    | null
 replicationSamples                 | null
 nControls                          | null
 pubmedId                           | null
 publicationFirstAuthor             | null
 publicationTitle                   | null
 discoverySamples                   | null
 nCases                             | null
 analysisFlags                      | null
```

**Comment by buniello** [comment]
EXAMPLES for FE testing: Study identifiers with the most disease identifiers (traitFromSourceMappedIds)
```
GCST008673,53
GCST008910,18
GCST004045,16
GCST008338,11
GCST009244,11
```
Studies with a lot of cohorts
```
GCST90243988,39
GCST90243987,38
GCST90243985,38
GCST90244788,34
GCST90243986,33
```
Studies with a lot of discovery samples
```
GCST90100220,12
GCST008292,10
GCST008293,10
GCST008294,10
GCST010422,9
```
Studies with replication samples
```
GCST90255504,8
GCST90255510,8
GCST90255521,8
GCST90255513,8
GCST90255514,8
```
Studies with background traits backgroundTraitFromSourceMappedIds
```
GCST90026610,4
GCST90274738,4
GCST90026611,4
GCST90274752,4
GCST90026609,4
```

**Comment by buniello** [comment]
The study page will host credible sets widget and we discussed potentially adding widget with a list of gwas studies with same EFO (suggested by Yakov)

**Comment by prashantuniyal02** [comment]
GWAS Credible sets widget on the study page
![Image](https://github.com/user-attachments/assets/359f74e5-a91b-4b1e-82fa-b4fa14603290)


molQTL Credible sets widget on the study page
![Image](https://github.com/user-attachments/assets/b0e18e0f-4a9d-4c01-9bdf-91a465c3da92)

**Comment by buniello** [comment]
Comment on the `flags` for studies and credible sets - we may want to visualise them with a warning symbol + hovering over in both study metadata, shared trait studies and credible set widgets.
@DSuveges would it be possible to get a list of the possible credible sets + study flags strings?
