### ISSUE TITLE
Updating evidence schema

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3381]
As we are introducing variant and study entities (and potentially locusToGene), metadata for them no longer should be stored in the evidence object. However other fields like l2g and credible sets are not yet available. This ticket expected to accumulate all changes required for the upcoming Platform update.

## Evidence fields to drop:

- <s>`variantRsId` - This field should be coming from the resolved variant index.</s> rs identifiers should stay. In some datasets they are very important.
- `variantAminoacidDescriptions` - When relevant, this field should also be available in the index.
- `variantHgvsId` - This field is <s>not yet </s> in the variant index.
- `variantFunctionalConsequenceId` - The most severe consequence id and the transcript specific consequence ids are all available in the variant index.
- `publicationFirstAuthor` - this field in the current ot-genetics schema should be pulled from the study index.
- `publicationYear` - same

## Evidence fields to add:

- `variantIdFromSource`: I think this new field can be included into the schema, where any variant related identifier can be stored similarly the already existing `diseaseFromSourceId`. 
- `locusToGeneId`: We are planning to show feature importance for each evidence, we need to have a resolvable identifier.
- `studyLocusId`: To resolve credible set for gentropy evidence we need to have resolvable identifier.

## Changes we should be considering:

- Currently we are converting all effect sizes to betas in gentropy. Can we make a similar harmonisation in the gene burden evidence as well? We then could drop the following columns from the schema: `oddsRatio`, `oddsRatioConfidenceIntervalLower`, and `oddsRatioConfidenceIntervalUpper`? @ireneisdoomed, what do you think?
- Also, we should be considering adding the burden studies into the study index.

**Comment by ireneisdoomed** [comment]
Unloading the evidence model considering that we will have more indices containing this metadata makes absolute sense to me.

Some notes:
- I would also remove all publication related metadata from the study dataset. They can be resolved with API calls for the time being
- I'll add `locusToGeneId` to the predictions dataset
- To explain each L2G prediction, we'd need to store in a dataset the shap values for all predictions. This is a serialised file, we can't control the schema so easily.
- No problem converting odds ratios to betas, it makes sense.
- If we add the burden studies, shouldn't we add ClinVar RCVs as well?

**Comment by DSuveges** [comment]
> - I would also remove all publication related metadata from the study dataset. They can be resolved with API calls for the time being

100% Agree.

> - I'll add locusToGeneId to the predictions dataset
> - To explain each L2G prediction, we'd need to store in a dataset the shap values for all predictions. This is a serialised file, we can't control the schema so easily.

With @d0choa we were discussing options to represent l2g on the platform, which involves having a separate dataset which would be identified by a l2g_id coming from a study locus id + gene id it was calculcated based on. This table would have all the features + some representation of the feature importance (no detailed plan on this yet). So, the gentropy evidence would be super cryptic: we would have diseaseId, studyId, targetid, studyLocusId, pubmedId, locus2geneId and of course l2g score. :D

> - No problem converting odds ratios to betas, it makes sense.

Good. We can schedule for the next release. 

> - If we add the burden studies, shouldn't we add ClinVar RCVs as well?

I would really not want to. I only consider burden just by looking at the large number of shared fields with the geneticsportal evidence.

**Comment by ireneisdoomed** [comment]
> With @d0choa we were discussing options to represent l2g on the platform, which involves having a separate dataset which would be identified by a l2g_id coming from a study locus id + gene id it was calculcated based on. This table would have all the features + some representation of the feature importance (no detailed plan on this yet). So, the gentropy evidence would be super cryptic: we would have diseaseId, studyId, targetid, studyLocusId, pubmedId, locus2geneId and of course l2g score. :D

If you want to have a dataset with all the features, the most sensible thing to me is merging `L2GPredictions` (studylocus, gene, score), with `L2GFeatureMatrix` (studyLocus, gene, features). We can chat about how you want to represent importances, but just letting you know that to calculate the contributions of each feature individually, the model and the locus2geneId + features is everything you need. And since the model can be downloaded, you could do it on the fly.

**Comment by ireneisdoomed** [comment]
One comment that is actually related with the tasks scoped here. RSIDs are the only variant representation some of our data providers have. And since the schema is used to validate the input data before the variant index is produced,  I don't think we can remove this field from the schema.

**Comment by DSuveges** [comment]
These are the datasources, which are using the variant related fields:

```
+------------------+--------------------------------------------------------------------------------------+
|datasourceId      |sources                                                                               |
+------------------+--------------------------------------------------------------------------------------+
|eva               |[variantRsId, variantFunctionalConsequenceId, variantHgvsId]                          |
|ot_genetics_portal|[variantRsId, variantFunctionalConsequenceId, publicationYear, publicationFirstAuthor]|
|eva_somatic       |[variantRsId, variantFunctionalConsequenceId, variantHgvsId]                          |
|uniprot_variants  |[variantRsId, variantFunctionalConsequenceId]                                         |
|reactome          |[variantAminoacidDescriptions]                                                        |
|orphanet          |[variantFunctionalConsequenceId]                                                      |
|gene2phenotype    |[variantFunctionalConsequenceId]                                                      |
+------------------+--------------------------------------------------------------------------------------+
```

## Results:

- `orphanet` has `variantFunctionalConsequenceId`, which contains annotation if the variant is gain or loss of function.
- `gene2phenotype` has `variantFunctionalConsequenceId` informing if gain or loss of function + type of effect: eg. `Absent gene product`.
- `reactome` has `variantAminoacidDescriptions` its a list of free text term with all known mutation events in the protein.

**Comment by DSuveges** [comment]
@opentargets/be-team , These are the expected modification in the evidence schema:

**New fields**:

- [ ] `studyLocusId` (string, nullable) - this field will allow resolve association and study details in the evidence widget.
- [ ] `locusToGeneId` (string, nullable) - this field will allow resolve l2g details: features, feature importance ets.

**Field to drop**:

- [ ] `variantHgvsId` - we need to notify EVA team to update their parser. Given the variant Id they provide already, this field can be resolved from the variant index.
