### ISSUE TITLE
VEP widget FE scoping

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3386]
This ticket will include scoping iterations for the VEP widget on the variant page.

Please note that at time of issue opening, the variant index data/API is not completed e.g. the data team is working on adding new fields to capture `distance` info from VEP output.
Also, we expect the majority of VEP widgets to consist of just one row.

<details>
  <summary>Example of variant consequences API query</summary>

```
query {
  variant(variantId:"1_150556742_A_AG"){
    transcriptConsequences {
       variantConsequences {
        id
        label
      }
      aminoAcidChange
      uniprotAccessions
      isEnsemblCanonical
      codons
      distance
      target {
        id
        approvedName
      }
      impact
      transcriptId
      lofteePrediction
      siftPrediction
      polyphenPrediction
    }
    }
  }

```
</details>
<details>
  <summary>Example of variant consequences API response</summary>

```
{
  "data": {
    "variant": {
      "transcriptConsequences": [
        {
          "variantConsequences": [
            {
              "id": "SO:0001589",
              "label": "frameshift_variant"
            }
          ],
          "aminoAcidChange": "-567X",
          "uniprotAccessions": [
            "Q6UY14"
          ],
          "isEnsemblCanonical": true,
          "codons": "-/G",
          "distance": null,
          "target": {
            "id": "ENSG00000143382",
            "approvedName": "ADAMTS like 4"
          },
          "impact": "HIGH",
          "transcriptId": "ENST00000271643",
          "lofteePrediction": "HC",
          "siftPrediction": null,
          "polyphenPrediction": null
        },
        {
          "variantConsequences": [
            {
              "id": "SO:0001627",
              "label": "intron_variant"
            },
            {
              "id": "SO:0001619",
              "label": "non_coding_transcript_variant"
            }
          ],
          "aminoAcidChange": null,
          "uniprotAccessions": [],
          "isEnsemblCanonical": true,
          "codons": null,
          "distance": null,
          "target": {
            "id": "ENSG00000237781",
            "approvedName": "ADAMTSL4 antisense RNA 2"
          },
          "impact": "MODIFIER",
          "transcriptId": "ENST00000442435",
          "lofteePrediction": null,
          "siftPrediction": null,
          "polyphenPrediction": null
        },
        {
          "variantConsequences": [
            {
              "id": "SO:0001632",
              "label": "downstream_gene_variant"
            }
          ],
          "aminoAcidChange": null,
          "uniprotAccessions": [],
          "isEnsemblCanonical": true,
          "codons": null,
          "distance": 4728,
          "target": {
            "id": "ENSG00000264553",
            "approvedName": "microRNA 4257"
          },
          "impact": "MODIFIER",
          "transcriptId": "ENST00000581735",
          "lofteePrediction": null,
          "siftPrediction": null,
          "polyphenPrediction": null
        },
        {
          "variantConsequences": [
            {
              "id": "SO:0001632",
              "label": "downstream_gene_variant"
            }
          ],
          "aminoAcidChange": null,
          "uniprotAccessions": [],
          "isEnsemblCanonical": true,
          "codons": null,
          "distance": 3459,
          "target": {
            "id": "ENSG00000203804",
            "approvedName": "ADAMTSL4 antisense RNA 1"
          },
          "impact": "MODIFIER",
          "transcriptId": "ENST00000615012",
          "lofteePrediction": null,
          "siftPrediction": null,
          "polyphenPrediction": null
        },
        {
          "variantConsequences": [
            {
              "id": "SO:0001631",
              "label": "upstream_gene_variant"
            }
          ],
          "aminoAcidChange": null,
          "uniprotAccessions": [],
          "isEnsemblCanonical": true,
          "codons": null,
          "distance": 4723,
          "target": {
            "id": "ENSG00000289457",
            "approvedName": "novel transcript"
          },
          "impact": "MODIFIER",
          "transcriptId": "ENST00000689641",
          "lofteePrediction": null,
          "siftPrediction": null,
          "polyphenPrediction": null
        }
      ]
    }
  }
}

```
</details>

**VEP Widget**
Subheader text: Variant consequence prediction for *FIXED VARIANT ON PAGE* 
Source: [VEP](https://www.ensembl.org/info/docs/tools/vep/index.html)

NOTE: please show `/` for `null` values

HORIZONTAL TABLE VERSION:

1. COLUMN HEADER: TRANSCRIPT (Tooltip: Ensembl canonical transcript) `transcriptId` — 
_PLEASE NOTE:_ this field should be hyperlinked to Ensembl transcript page but don’t have enough info in data to build link
2. COLUMN HEADER: PREDICTED CONSEQUENCE - `variantConsequences label` resolved object hyperlinked to [http://purl.obolibrary.org/obo/`variantConsequencesId`] (tooltip: `impact`) — please note you could re-use VEP chip from ClinVar widget, where predicted consequence object is resolved by identifiers.org already
3. COLUMN HEADER: CONSEQUENCE SCORE - `consequenceScore`
4. COLUMN HEADER: GENE - `approvedName` within ‘target’ object hyperlinked to Platform page for `targetId`
5. COLUMN HEADER: AMMINOACID CHANGE `aminoAcidChange` 
6. COLUMN HEADER: CODING CHANGE `codons` 
7. COLUMN HEADER:  DISTANCE FROM FOOTPRINT `distanceFromFootprint` (this field will be introduced with next data/API release)
8. COLUMN HEADER:  DISTANCE FROM START SITE `distanceFromTss` (this field will be introduced with next data/API release)
9. COLUMN HEADER: LOFTEE PREDICTION - `lofteePrediction`
10. COLUMN HEADER: SIFT PREDICTION - `siftPrediction`
11. COLUMN HEADER: POLYPHEN PREDICTION - `polyphenPrediction`
12. UNIPROT ACCESSION: `uniprotAccessions` (can be more than one separated by comma) hyperlinked to [https://www.uniprot.org/uniprotkb/`uniprotAccessions`](https://www.uniprot.org/uniprotkb/%60uniprotAccessions%60)

**Comment by d0choa** [comment]
While the new data is propagated, the current API column `distance` corresponds to the upcoming `distanceFromFootprint`. It can contain `null` values, but they will be replaced by `0` in the upcoming data. @DSuveges can provide more details if needed.

@buniello if I understood you well, the transcript link can be built like the next:
`http://www.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000139618;t=ENST00000700199`
We would get `ENSG00000139618` from `target.id` and `ENST00000700199` from `transcriptId`. Please confirm is this is what you were after.

Please keep using identifiers.org for sequence ontology and UniProt.

**Comment by d0choa** [comment]
Something important is that we will like this table to be sorted but after discussion with @DSuveges, we are still undecided on how to do it.

**Comment by buniello** [comment]
Thank you @d0choa, yes these are the links i was after. For table sorting, i kept that choice for later, not critical now

**Comment by buniello** [comment]
Comment on widget table sorting @gjmcn: 
a new field has been added to variant index dataset (and soon deployed in API) -  `transcriptIndex`- , a non-nullable integer from 1 to the number of transcripts, where 1 is being the more relevant. This field should be used to order the genes in the VEP widget from most relevant and going down the list.

**Comment by buniello** [comment]
Pending: I decision on whether the two new transcript annotation fields, `maneselect` and `appris` should be presented to users in VEP widget and how (additional transcript annotation column)? Any feedback welcome

**Comment by d0choa** [comment]
Suggested changes in Aug 7th:

- [ ] Gene to be moved to the first column and replace content using `approvedSymbol` instead of `approvedName`
- [ ] Transcript information in a tooltip in the gene column. The tooltip could contain: "Ensembl canonical transcript: <a>ENSTXXXXXX</a>"
- [ ] Consequence score column can be removed as declared uninformative in the meeting
- [ ] Consider improve formatting of integer columns (Distances)
- [ ] Potentially save some width by playing with the headers

**Comment by buniello** [comment]
i agree with the suggested changes above

**Comment by buniello** [comment]
What field should this version of table be sorted on now? In the previous version, table was sorted by scores (which have been removed now). Perhaps we need a sorting arrow with the distances column? @d0choa @gjmcn

**Comment by buniello** [comment]
note from Ellie: 
- for the VEP widget,  I’d like to see the gene column next to the transcript to be able to evaluate whether it is gene coding and thus understand the impact.

**Comment by d0choa** [comment]
Unless I'm missing something, the above comment requires no additional action @gjmcn
