### ISSUE TITLE
Visualisation of hashed variants

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3390]
@gjmcn @carcruz one option for visualisation of hashed variants (there may be more):

for hashed variants e.g. `OTVAR_1_109607656_cc1bda57abafe82ac6cb5ec620a02a19` we could display the standard
_chr_pos_ref_alt_ BUT where `ref` or `alt`  become `INS` or `DEL` (depending on the nature of variant) and the actual allele string is visible with hovering on the `DEL` or `INS` part.

- if long allele is `referenceAllele`, the `ref` part becomes `DEL` (hovering on `DEL` shows `referenceAllele`)
- if long allele is `alternateAllele`, the `alt` part becomes `INS`(hovering on `INS` shows ``alternateAllele`)

example for `OTVAR_1_109607656_cc1bda57abafe82ac6cb5ec620a02a19`:

```
{
  "data": {
    "variant": {
      "variantId": "OTVAR_1_109607656_cc1bda57abafe82ac6cb5ec620a02a19",
      "chromosome": "1",
      "position": 109607656,
      "referenceAllele": "AAATTGTGGTGTATTATGAAAAATATTCAGCTTTGTAGTCAAGCAGCCCAATGCAAATGCAGTCTCTGCTATTTATCTACATGACCTTGGGCAGTTAATTAACTTCTCTGAACTTCAGTTTTTCCATGTGTAAAATGAGGCTAATTAGAAAGGTACCATCTACCTTAAGGTCTTACTGCGTAGATGGGTAAAGGGCGTTGAGATGGTATACACAGTACACCTAGCAGTGACTGGGCTTTGAGTGCTCCGGGAACAGTAAGTGATAGCATTATTACAAGATTAGGAGACAGATGGTTAGGTTAAATAAACTCAGGTTTGACTTTGAAGCCCATACTTGTCTATGATCCCATACTGTCTGAGGTAGGATTGATAAATTATGTCCCTTAGCTTTTTGGAAGCAGCTTTGCAATGATGGTACTAATTCCTGACCACCTTCCCTTGGTTTGCCCTTGTAGTTTGTGTCCCCTGCCTTGGCATCGTGACATAAGATGCTCTAGGTGTAGGAGACTCATTTCTGCTTAGTGGCCTAAGTAGATCCTAGATTACCAGATAGAAAATTCTGCCCTGAAAGAGCCATCATGAATCACATTACTCCTGCGAGAGTGTATGACAGAACTGCAGGGCTATCTTAGGGTTCTGGAAGGAGAGGCTTAGTGTACACCTCAATTAAGAGAACAGGGCTGAGGGCTACTAGGCAGAACACGTCTTTTGAATTTTGCATCTTCAGCCTTGTAGGCTGTAGTGAGCCAGTGTAAAGCAATAGAAAGTCATGACAACTGTGGCAGATCTCCCCATAGCATTAAATTCAAAACATTGCTGAAGCCTAACAAAACAGATCCACAGGCTGAATTCAGTCTGGGTCTCCAGCTTTCAATGCCTGAAATTTTGGGTTGGGTGAGGTTTCTCCCAACCAGAGAGAAGACTGGCTAGAAGATTGCTTAAGCATCAACCCACCCTCTCACCAGTCAGTCTTACTAAGATGCGGAGTCATTAAGCTGGTATTCTGCAGCTCTCTCGAAGCAGGCTTGCACCCCACCATCCTTCCACAACCTCCTAATGACCTCCACGAGCTCAGGAGGCATGGTTCCCTCCTCAATGGAGTCAGCCAGGTTGTTGAGCTGTCGCCCGTCATCCTGTAATGCAGAAACCTGGTTAAGAACTTCACAGGAGTAATAGCTTTCCAGGAGGCTTCTGGGAATACTGCTGAATGGAAATCATTTTACATTACTACGAAGACCTAAGATGGAAGCAGTATCCAGTGAAGATTCTATGTAAGAAAACATACTGTTGAATTTTTGAGTATGCTCCCCAGATGCAGAGGGTGGCACTATACCCAGCCCTGGGGTGTGTCTAAAGCGGGGCAGGGGTCCCAGGTATTTCCTCTCTGGAGTTTCTGGCTTCCATCCTTAGTCTGAAAGTTTACCGCCACAAAACGTGGGTCCTCTGCTGCAGAGAGACTGAAAATGTAAAGGCCAGATTGACCATGAAATAGACAAGATAGAAGACAGGGACCCATCACCTTTGTTCTTCAGCGATTGAAAGCTAGAAAAAGTCCAGTACTAGAAGTAGGGATTTCACTTACAAAAGTTCCATGGCCAGGAACCCAAGGGTAGCAATTTAAATGGTAAAGTAAAAAAGCAGAGGAAGCTGTGAGCAGCTTTATTTTGTAAATATGTGTTATAAAGTAGGGCTTGAGGACAGGCACGGTGGCTCACACCTGTAATCTCAACACTTTCGGAGTCTGAGGCAGGAGGATTGCTTAAGGCCAGGAGTTTGACACCAGCCTAGACAAGATGGCAAGACCCCTTCTCTACAAAAAAATTTTAAAAAATAGCTGGGTGTGGTGGTGCACACCTGTGGTCCCACCTACTGGGGCTGAGGTGGGAGAATCACTTAAGCCTGGGAGGGTGAGATTGCAGTGAGCCATGATCACACCACTGCATTCCAGCCTGGGTAAGAGAGGAAGACCCTGTCCCAGTAAAAATAAGGGTGGATGTTGCTTACTTCTCCAGGACTGCAT",
      "alternateAllele": "A",
```

Variant will be displayed as _1_109607656_DEL_A_ and hovering on `DEL` will show `referenceAllele` string

_Originally posted by @buniello in https://github.com/opentargets/issues/issues/3335#issuecomment-2222275897_

**Comment by project-defiant** [comment]
We might not want to reinvent the naming for the variants, could we display the hgvs genomic annotation instead?  It is already settled convention that would cover all genomic variants - https://hgvs-nomenclature.org/stable/recommendations/summary/

We could specifically state to have `hgvsg`. In case we do not have it in the data structure, this could be easily added by VEP with `--hgvsg` flag.

@DSuveges linking you as this might be data related.
