### ISSUE TITLE
Changes to 'Require' option in order to remove classic-associations

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3395]
**Describe the bug**
Removing the classic-associations, causes issues with the 'Require' option in the associations on the fly. This is because it uses aspects of the classic-associations filters data types.
![image](https://github.com/user-attachments/assets/ad7b90e7-5b30-46aa-90f6-d827d62b02c9)

**Observed behaviour**
The dev crashes on removing the classic association from the BE: #3361 

**Expected behaviour**
We need a way to enable 'Require' option in the AOTF:

1. This can be done by linking facets with the 'Require' option. But currently facets behaviour is 'AND' where the behaviour on the 'Require' option is 'OR'.
2. Use / create another endpoint with just the data types.

**Comment by buniello** [comment]
Discussed on 19/8/24: `require` functionality should be and 'AND'

**Comment by prashantuniyal02** [comment]
Updated discussion on 22/08 - require functionality will be an 'OR' for the 24.09 release. 
Will work on improve the UX at a later stage.

**Comment by prashantuniyal02** [comment]
Tested in dev. The API response matches the 'Require' in platform prod.

**Comment by prashantuniyal02** [comment]
Found a problem with the require:

When `required` is `true`, we still want to use the data for the other columns (for which `required` is `false`) to calculate the association score.

When `required` is `true`, the backend should only drop rows that don't have data in the `required` column. It should not drop columns for the rows for which require is not true.
