### ISSUE TITLE
AOTF feedback

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#3397]
# AOTF feedback

Senior user 1:
- It needs to be clearer that it is an AND filter, and that you can add a string of terms (could be explained in the tool tip?)
- overall, I think ability to use free text is super, but also being able to see the options for what you can search for/hierarchy of terms for example would be really useful as it feels a bit like like searching in the dark and may limit/bias the filters people carry out.
- Target ID as a category is not clear what kind of ID so I would suggest adding (ENSG) at the end of the term - I selected ‘Target ID’ from the list and then typed in ‘PSEN1’ but it didn’t come up with the gene option https://partner-platform.opentargets.org/disease/MONDO_0004975/associations Lots of people won’t use ENSG ids (especially in the states where they tend to use RefSeq) so I think being able to filer for the gene symbol/name is important here but doesn’t seem to work if you have selected a category
- Tractability: I don’t think free text search works here as it is not clear what you can search for; when I select ‘Tractability Small Molecule’ I just want to see my list of targets filtered for the ones that have ‘Green’ scoring for any of the relevant attributes here. 

Senior user 2:
- like to able to switch association to prioritisation with the interactors view open. When showing interactors are we showing only interactors that also have an association score for the same disease?
- the reason I'm asking is I can imagine wanting to know both interactors with association evidence and also interactors without evidence - particularly with a target with poor tractability and I'm thinking about what I might be able to drug nearby to have the same effect - a use case that could be refined once a prototype is in hand, but just to share it might be interactors with a 0.0 association score as well that people could be interested in

**Comment by buniello** [comment]
Hi @chinmehta in the AOTF meeting this morning we were talking about the second bullet point in this ticket (feedback from Ellie):
-  Target ID as a category is not clear what kind of ID so I would suggest adding (ENSG) at the end of the term

**Comment by carcruz** [comment]
Close as Facets feedback will be recalled in further releases
