### ISSUE TITLE
Variant-based evidence API (e.g. clinvar, uniprot)

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3403]
The current variant page design contains two widgets with disease/target evidence based on Uniprot and ClinVar evidence. The data should be pulled out from the current evidence table, however the current API does not allow for this action. We need to allow the retrieval of evidence by `datasourceId` and `variantId`.

**Comment by remo87** [comment]
@DSuveges do we need one or multiple variant ids?

**Comment by d0choa** [comment]
discussed on Aug 7th meeting...

Variant API endpoint will have Uniprot and ClinVar information by using an abstraction that pulls evidence data with a given `variantId` and `datasourceId`.

**Comment by d0choa** [comment]
@remo87 updated in the 14/08 meeting, that he's finishing the last details and API should be ready for testing inminently

**Comment by prashantuniyal02** [comment]
@remo87 deployed this on 14/08

**Comment by buniello** [comment]
this is ready for FE work as discussed @gjmcn
