### ISSUE TITLE
API endpoint to retrieve pharmacogenomics data by variant identifier

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3405]
Pharmacogenomics data so far only accessed by target identifier. However, on the variant page, the pgx widget needs to be populated by variant identifier. The data is not yet available. We've been in conversation with the EVA team, however the data would not be ready for 24.09. The data team can provide a patched dataset.

**Course of action**

- [x] Solidify the schema (where is the `variantId` field, what does it contain exactly) Let Backend team knows. @opentargets/data-team 
- [x] Generate patched dataset. @opentargets/data-team 
- [ ] Update API to expose the new field. @opentargets/be-team 
- [ ] Provide new endpoint to retrieve data from API by variantId. @opentargets/be-team

**Comment by remo87** [comment]
The pharmacogenomics field is exposed in target and drug does this but the item only refers to target. Does this change has to be implemented in target only?

**Comment by remo87** [comment]
I just remember we discussed adding the pharmacogenomics field to the variant query. Am I correct?

**Comment by d0choa** [comment]
As we discussed in the August 7th meeting, having this inside variant is good. We will reuse the same abstraction for drugs and targets.

**Comment by DSuveges** [comment]
@remo87 , the updated data is here: `gs://otar001-core/Pharmacogenetics/json/pharmacogenetics-2024-08-02.json.gz`

The data looks like this:
```
{
  "datasourceId": "pharmgkb",
  "datasourceVersion": "2024-05-05",
  "datatypeId": "clinical_annotation",
  "drugs": [
    {
      "drugFromSource": "ivacaftor"
    },
    {
      "drugFromSource": "tezacaftor"
    }
  ],
  "evidenceLevel": "1A",
  "genotype": "CTT/CTT",
  "genotypeAnnotationText": "Patients with the CTT/CTT genotype (do not have a copy of the CFTR F508del variant) and cystic fibrosis may have decreased response when treated with ivacaftor/tezacaftor combination as compared to patients with the del/del genotype. This genotype is not an indication for use of the combination drug of ivacaftor/lumacaftor according to the FDA-approved drug label for this drug combination and response may depend on the presence of other CFTR variants. Other genetic and clinical factors may also influence response to ivacaftor/tezacaftor.",
  "genotypeId": "7_117559591_TCTT_TCTT,TCTT",
  "literature": [
    "29099344",
    "29099333",
    "28930490"
  ],
  "pgxCategory": "efficacy",
  "phenotypeText": "decreased response",
  "studyId": "1449154729",
  "targetFromSourceId": "ENSG00000001626",
  "variantFunctionalConsequenceId": "SO_0002073",
  "variantRsId": "rs113993960",
  "variantId": "7_117559591_TCTT_TCTT"
}
```
The new field is the `variantId`

**Comment by prashantuniyal02** [comment]
Preliminary testing on 14/08 meeting looks good.
Unblocked @gjmcn for FE work.
