### ISSUE TITLE
Locus Drawer object in Credible Sets Widgets

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3407]
The locus drawer will open from the number field in the `credible set size` column, for both GWAS and molQTLs widget.
if credible sets size is 7, the drawer will contain 7 rows for 7 variants in the locus.

[Credible sets widget ticket](https://github.com/opentargets/issues/issues/3318)

Discussed with @DSuveges and Genetics Team.

Pending `credible sets` API deployment at time of drafting this, we have scoped this object with this schema:
```

"locus": [
    {
      "is95CredibleSet": true,
      "is99CredibleSet": true,
      "logBF": null,
      "posteriorProbability": 0.8281915098204469,
      "variantId": "3_50557710_C_T",
      "pValueMantissa": null,
      "pValueExponent": null,
      "beta": null,
      "standardError": 0.9999996011812708,
      "r2Overall": 1.0000000000000027
    },
```
**TABLE/DRAWER:**

1. HEADER: VARIANT ID - `variantId`
2. HEADER: P-VALUE - `pValueMantissa` & `pValueExponent` (Table will be sorted/sortable by this column)
3. HEADER: BETA - `beta` - Tooltip: Beta with respect to the ALT allele
4. HEADER: SE `standardError`-Tooltip: Standard Error: Estimate of the standard deviation of the sampling distribution of the beta
5. HEADER: LD (r2) - `r2Overall` - Tooltip: Linkage disequilibrium with the queried variant
6. HEADER: POSTERIOR PROBABILITY - `posteriorProbability` - Tooltip: Posterior inclusion Probability from fine-mapping that this variant is causal
7. HEADER: LOG(BF) - `logBF`
8. HEADER: IS IN 95% CREDIBLE SET - `is95CredibleSet`

**Comment by d0choa** [comment]
We are not considering representing as much data, but this is an equivalent view for inspiration: 
https://r11.finngen.fi/region/I9_HYPTENS/20:58876654-59376654

**Comment by d0choa** [comment]
A few comments from @addramir:

- There will be top-level information about the study-locus (credible set widgets) additional to the table
- `is95CredibleSet` column is not required in the table
- `variantId` and `posteriorProbability` are not nullable. Everything else is optional.

**Comment by d0choa** [comment]
As discussed on August 7th, we will make progress on the credible set API endpoint while @gjmcn is away, so it simplifies the  locus drawer implementation

**Comment by buniello** [comment]
I would still keep the `is95CredibleSet` field in table (same as current OTG) as not all variants are in the 95% (but they all are in 99%).

**Comment by buniello** [comment]
@gjmcn - please pause implementation on this  for now

**Comment by buniello** [comment]
this task is not planned anymore as replaced by [this](https://github.com/opentargets/issues/issues/3436)
