### ISSUE TITLE
Hashing long variant identifiers in the ETL

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3409]
## Context

The variant identifier generated from `chr_pos_ref_alt` problematic, as some in/dels can be very long, so the resulting string cannot be used as identifier. The alternative for such variants was to generate hash from the alleles and the variant id would look like this: `OTVAR_chr_pos_#HASH`. At this point, the logic lives in gentropy, however it poses some integrative issues as these variants coming from ClinVar exclusively.

## The problem

ClinVar, Uniprot evidence are pulled from the evidence table by their `variantId`, which means that for long alleles these sources has to have the hashed identifier already, however gentropy shouldn't touch these datasets. It implies the ETL also does hashing... which doesn't sound right.

## Proposed solution

- To avoid discrepancies in the hashing, duplication in code, the hashing logic should be in the ETL, especially considering this being an integrative step.
- The evidence files should have a field like `variantIdFromSource` that the ETL either leaves unchanged or hashes them when creating the real variantId
- The same function should be applied on the variantId in the variant index.

**While the implementation is not in place, there can be some interim solution:**

- We can be fine with that long variants are not linked to variant page (however, can break the cross-refs)
- We can patch ClinVar and Uniprot data, so the variant Id is hashsed when the alleles are long. 

Tagging @d0choa for ssuggestions.

**Comment by prashantuniyal02** [comment]
To be implemented after the 24.09 Platform release

**Comment by DSuveges** [comment]
@remo87 , this is the current implementation of this functionality in gentropy:

```python
    @staticmethod
    def hash_long_variant_ids(
        variant_id: Column, chromosome: Column, position: Column, threshold: int = 100
    ) -> Column:
        """Hash long variant identifiers.

        Args:
            variant_id (Column): Column containing variant identifiers.
            chromosome (Column): Chromosome column.
            position (Column): position column.
            threshold (int): Above this limit, a hash will be generated.

        Returns:
            Column: Hashed variant identifiers for long variants.

        Examples:
            >>> (
            ...    spark.createDataFrame([('v_short', 'x', 23),('v_looooooong', '23', 23), ('no_chrom', None, None), (None, None, None)], ['variantId', 'chromosome', 'position'])
            ...    .select('variantId', VariantIndex.hash_long_variant_ids(f.col('variantId'), f.col('chromosome'), f.col('position'), 10).alias('hashedVariantId'))
            ...    .show(truncate=False)
            ... )
            +------------+--------------------------------------------+
            |variantId   |hashedVariantId                             |
            +------------+--------------------------------------------+
            |v_short     |v_short                                     |
            |v_looooooong|OTVAR_23_23_3749d019d645894770c364992ae70a05|
            |no_chrom    |OTVAR_41acfcd7d4fd523b33600b504914ef25      |
            |null        |null                                        |
            +------------+--------------------------------------------+
            <BLANKLINE>
        """
        return (
            # If either the position or the chromosome is missing, we hash the identifier:
            f.when(
                chromosome.isNull() | position.isNull(),
                f.concat(
                    f.lit("OTVAR_"),
                    f.md5(variant_id).cast("string"),
                ),
            )
            # If chromosome and position are given, but alleles are too long, create hash:
            .when(
                f.length(variant_id) > threshold,
                f.concat_ws(
                    "_",
                    f.lit("OTVAR"),
                    chromosome,
                    position,
                    f.md5(variant_id).cast("string"),
                ),
            )
            # Missing and regular variant identifiers are left unchanged:
            .otherwise(variant_id)
        )
```

**Comment by remo87** [comment]
@DSuveges I have a couple of questions:
- Does this mean that we need to process the variant index entries to hash the id?
- Also every evidence input that has the variantId field needs to be hashed? or do we need hash some specific evidence input.

**Comment by DSuveges** [comment]
@remo87 , 
- Yes, the hashing process will only happen in the ETL, so any sources that have `variantId` (variant index, evidence, pharmacogenetics needs to be processed. 
- The resulting column should be `variantId`. I'm wondering if for evidence the old column should be renamed into `variantFromSourceId`... What do you think?

**Comment by d0choa** [comment]
I'm not sure we want to add a variant index step to the platform ETL, just because of this. 

My first instinct was to apply the hashing in evidence and pharmacogenetics, and gentropy would handle the hashing of the `variantIndex`. It's true the two codebases would need to be aligned, but they need to be for many other reasons.
