### ISSUE TITLE
susie_finemapper-No overlapping variants in the LD Index

### ISSUE THREAD

**Issue by klaythompson37** [opentargets/issues#3410]
**Describe the bug**
"No overlapping variants in the LD Index" when running susie finemapper step 
**Observed behaviour**
A clear and concise description of what happened.
when using study index and study locus file, returned no overlap error 
**Expected behaviour**

**To Reproduce**
Steps to reproduce the behaviour:

**Additional context**
I wonder if this is a bug,  this line seems only take the very first line from the study locus object: https://github.com/opentargets/gentropy/blob/397f1e99f1c12c48ae0c91887e10640115fa492e/src/gentropy/susie_finemapper.py#L97.
Is that the reason for the error, this step only takes in a row instead of a full spark df of study locus?

**Comment by Daniel-Considine** [comment]
Hi @klaythompson37, thanks for showing an interest. 

> "No overlapping variants in the LD Index" when running susie finemapper step

This error will occur whenever there is no overlap between the summary statistics and the default gnomad LD index we use. Currently we're using gnomad 2.1.1, and we'll update this as better options become available. If this is unexpected, it could be that you're using an ancestry with poor coverage in gnomad? 

> Is that the reason for the error, this step only takes in a row instead of a full spark df of study locus?

The fine mapping pipeline is in active development, and one of the challenges we've had is extracting LD block matrices via hail across multiple loci in parallel. For now we are doing this by submitting each row of the `StudyLocus` dataframe as an individual batch job in GCP. In the future the code will also allow to fine map iteratively over a whole table, say if you have a small subset of loci you would like to run locally.
