### ISSUE TITLE
Incorrect parsing of the pharmacogenetics schema

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3411]
**Describe the bug**
The schema showed in the Downloads section for the Pharmacogenetics dataset does not conform to the data.

**Observed behaviour**
![image](https://github.com/user-attachments/assets/94de2240-2876-490b-9ea6-004d3af01ca1)

There is also a repetition of the downloadable formats.

**Expected behaviour**
The actual schema of that dataset is:
```
root
 |-- datasourceId: string (nullable = true)
 |-- datasourceVersion: string (nullable = true)
 |-- datatypeId: string (nullable = true)
 |-- directionality: string (nullable = true)
 |-- evidenceLevel: string (nullable = true)
 |-- genotype: string (nullable = true)
 |-- genotypeAnnotationText: string (nullable = true)
 |-- genotypeId: string (nullable = true)
 |-- haplotypeFromSourceId: string (nullable = true)
 |-- haplotypeId: string (nullable = true)
 |-- literature: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- pgxCategory: string (nullable = true)
 |-- phenotypeFromSourceId: string (nullable = true)
 |-- phenotypeText: string (nullable = true)
 |-- studyId: string (nullable = true)
 |-- targetFromSourceId: string (nullable = true)
 |-- variantFunctionalConsequenceId: string (nullable = true)
 |-- variantRsId: string (nullable = true)
 |-- isDirectTarget: boolean (nullable = true)
 |-- drugs: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- drugFromSource: string (nullable = true)
 |    |    |-- drugId: string (nullable = true)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/downloads
2. Search the Pharmacogenetics dataset
3. See error

**Comment by javfg** [comment]
The repetition seems to be related to some state in the web not clearing properly on pagination. If you go back and forth the formats available keep growing.

**Comment by buniello** [comment]
I thunk we observed this behaviour in the past as well, @chinmehta may remember

**Comment by prashantuniyal02** [comment]
@javfg and @remo87 I have created a separate issue for the repeated chips behaviour as this is a repeating issue and happens with most of the release. Would be great to resolve it once and for all - #3420

**Comment by remo87** [comment]
In the latest release the format should be ok. I just checked and it was fine. But we do have another issue and that's the generation of the downloads.json file which is why the pharmacogenomics chips are not showing.

**Comment by remo87** [comment]
You should now see the update version in dev

**Comment by ireneisdoomed** [comment]
I can see it now! 
![image](https://github.com/user-attachments/assets/a9b77194-e896-4b73-af96-37785dee1592)

**Comment by prashantuniyal02** [comment]
Closing as this issue has been resolved in dev
