### ISSUE TITLE
Variant search - UI

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3414]
Including variant as an entity will involve:

- [x] Updating the search to include allow including variants and related entities
- [x] Updating the search suggestions
- [x] Updating entities in the homepage search bar to include variants

The backend work is included here: #3365

**Comment by buniello** [comment]
@gjmcn for the search suggestions on the homepage, I would now have 1 link for each entity: gene, disease, drug and variant. Keeping two of each makes it too busy for the eye (referring to what discussed yesterday)

**Comment by gjmcn** [comment]
@buniello I agree, but I think the home search page will likely get some design updates for the next release anyway so I suggest we cover that in a different ticket.
