### ISSUE TITLE
New FE behaviour for the require and facets functionality within AOTF

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3422]
Once [this backend issue](https://github.com/opentargets/issues/issues/3395) is completed, the AOTF UI should be adapted to new behaviour for the `require` functionality.

This ticket will follow up FE progress.

- [x] Change 'Require' to 'Include'
- [x] Add a tooltip: This results in an 'OR' filtering between the data sources
- [x] Adding a (beta) in the Search disease/target specific filter heading (facets heading)
- [x] Change a column in the facets category to `Target ID (ENSG)`

**Comment by prashantuniyal02** [comment]
Hey @chinmehta , could you please modify the facets tooltip to 

- [ ] in the target page

```
Please search by disease or filter by disease category. Example: Measurement
AND filter across categories; OR filter within a category
```

- [ ] in the disease page

```
Please search by target or filter by target category. Example: Enzyme
AND filter across categories; OR filter within a category
```

**Comment by chinmehta** [comment]
Adding tooltip on input label is not recommended ui, as discussed we are adding an info button next to facets.
![image](https://github.com/user-attachments/assets/ca2b42f7-5595-407e-af9e-7aa0e3288d81)

**Comment by prashantuniyal02** [comment]
modified to include all the text in the Tip
