### ISSUE TITLE
Add Finngen as a gene burden evidence source

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3424]
24.09 incorporates ~400 evidence resulted from LoF burden analyses made on the Finnish biobank. We need to update the widget and docs to add Finngen as a new source

## Background
The data has been integrated without any changes needed other than specifying Finngen as a datasource
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/92e24d73-9682-4d90-9c68-edde1b64edda">

Practically all of the associations covered by Finngen were not present in other burden results. This is by looking at the direct associations only. Some examples that will be useful to check the FE:
```
+---------------+-------------+---------+                                       
|       targetId|    diseaseId|  sources|
+---------------+-------------+---------+
|ENSG00000001626|MONDO_0009061|[FinnGen]|
|ENSG00000004939|MONDO_0008315|[FinnGen]|
|ENSG00000012504|   GO_0036273|[FinnGen]|
|ENSG00000027001|MONDO_0002135|[FinnGen]|
|ENSG00000034971|  EFO_0004190|[FinnGen]|
|ENSG00000034971|  EFO_0004235|[FinnGen]|
|ENSG00000034971|  EFO_0005752|[FinnGen]|
|ENSG00000034971|   GO_0009410|[FinnGen]|
|ENSG00000048828|  EFO_0000221|[FinnGen]|
|ENSG00000070444|MONDO_0015597|[FinnGen]|
|ENSG00000072818|  EFO_0003779|[FinnGen]|
|ENSG00000072818|  EFO_0004705|[FinnGen]|
|ENSG00000072818|  EFO_1000627|[FinnGen]|
|ENSG00000074657|  EFO_0003951|[FinnGen]|
```

## Tasks

- [ ] Add FinnGen to the widget subheader (after AstraZeneca PheWAS and Genebass) with a link to `https://www.finngen.fi/en`
- [ ] Update docs. Unfortunately we don't have a manuscript to reference these results

**Comment by prashantuniyal02** [comment]
Works in dev

![Image](https://github.com/user-attachments/assets/7c6c0e46-463c-4d36-854a-d9187e339aed)
