### ISSUE TITLE
Credible Set Page Scoping ticket and widget

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3436]
We have discussed development of a credible set planning page within our merged product.
Please see here for current [study-locus page in OTG for reference.](https://genetics.opentargets.org/study-locus/GCST004365_195/1_154445939_T_C)

In our MVP, the page will contain 
1. Lead variant association summary+credible set summary + study summary
2. Credble set summary widget (previous locus drawer schema)
3. Co-loc with GWAS SNPs - future scoping
4. Co-loc with QTLs - future scoping
5. L2G info/widget - future scoping 

The users will access the table through a tab within the **gwas credible sets widget**, with text `credible set view` - see screenshot below. The tab should be placed either at the beginning of credible set widget (before the `Lead Variant` column).

<img width="1152" alt="Screenshot 2024-09-04 at 18 55 18" src="https://github.com/user-attachments/assets/3559fa46-a510-46fe-8dcd-cc12f468c451">

For each row in the credible set widget, there will be a `studylocusId`  associated to the variant in Lead Variant column. 

<details>
  <summary>E.g for variant in screenshot first row</summary>

```
query test {
  credibleSets (variantIds: "17_63945614_C_T") {
    studyLocusId
    locus {
      posteriorProbability
      pValueMantissa
      pValueExponent
      logBF
      beta
      standardError
      is95CredibleSet
      is99CredibleSet
      r2Overall
    }
    }
  }

```
</details>

- [ ] To build the **credible set page**, credible set API is queried by `studyLocusId` for each row, see query and response below.

<details>
  <summary>Sample `studylocusId` query</summary>

```
query sample {
  credibleSets (studyLocusIds: "-3584816504539422163") {
    variant {
      id
      rsIds
      referenceAllele
      chromosome
      position
    }
    chromosome
    position
    region
    beta
    zScore
    pValueMantissa
    pValueExponent
    effectAlleleFrequencyFromSource
    standardError
    subStudyDescription
    finemappingMethod
    credibleSetIndex
    credibleSetlog10BF
    purityMeanR2
    purityMinR2
    locusStart
    locusEnd
    sampleSize
    studyType
    qtlGeneId
      study{
      studyId
      nSamples
      traitFromSource
      publicationJournal
      publicationDate
        hasSumstats
      pubmedId
        diseases {
          name
          id
        }
    }
    locus {
       posteriorProbability
      standardError
      is95CredibleSet
      is95CredibleSet
      r2Overall
      pValueMantissa
      pValueExponent
      logBF
      variant{
        id
        }
    }
    }
  }
```
</details>

<details>
  <summary>Sample `studylocusId` response</summary>

```
{
  "data": {
    "credibleSets": [
      {
        "variant": {
          "id": "17_63945614_C_T",
          "rsIds": [
            "rs80338958"
          ],
          "referenceAllele": "C",
          "chromosome": "17",
          "position": 63945614
        },
        "chromosome": "17",
        "position": 63945614,
        "region": "chr17:60516274-67930962",
        "beta": 3.7662,
        "zScore": null,
        "pValueMantissa": 3.532,
        "pValueExponent": -20,
        "effectAlleleFrequencyFromSource": 0.000600773,
        "standardError": 0.409306,
        "subStudyDescription": null,
        "finemappingMethod": "SuSie",
        "credibleSetIndex": 1,
        "credibleSetlog10BF": 12.9741666326,
        "purityMeanR2": null,
        "purityMinR2": null,
        "locusStart": null,
        "locusEnd": null,
        "sampleSize": null,
        "studyType": "gwas",
        "qtlGeneId": null,
        "study": {
          "studyId": "FINNGEN_R10_G6_MYOTDIS",
          "nSamples": 408650,
          "traitFromSource": "Myotonic disorders",
          "publicationJournal": null,
          "publicationDate": null,
          "hasSumstats": true,
          "pubmedId": null,
          "diseases": []
        },
        "locus": [
          {
            "posteriorProbability": 0.360682222719958,
            "standardError": 0.409306,
            "is95CredibleSet": true,
            "r2Overall": null,
            "pValueMantissa": 3.532,
            "pValueExponent": -20,
            "logBF": 39.613840815027,
            "variant": {
              "id": "17_63945614_C_T"
            }
          },
          {
            "posteriorProbability": 0.308067113635019,
            "standardError": 0.409629,
            "is95CredibleSet": true,
            "r2Overall": null,
            "pValueMantissa": 4.151,
            "pValueExponent": -20,
            "logBF": 39.4561611744815,
            "variant": {
              "id": "17_63747701_G_A"
            }
          },
          {
            "posteriorProbability": 0.299572323152559,
            "standardError": 0.410102,
            "is95CredibleSet": true,
            "r2Overall": null,
            "pValueMantissa": 4.272,
            "pValueExponent": -20,
            "logBF": 39.4281993818778,
            "variant": {
              "id": "17_64007142_G_A"
            }
          }
        ]
      }
    ]
  }
}
```
</details>

- [ ] Page Header
Proposed format: ` Credible set around lead_variant_id for study Id`- (decision to move from _traitid_ to _study Id_ was discussed in a scoping meeting).
hence
**Credible set around `variant Id`  for `studyId`** 
Subheader links: Study ID: `studyId` which will be hyperlinked to our own study page in a separate tab | Variant Id: `variant Id` hyperlinked to our own variant page in separate tab

- [ ] Section 1: lead variant association summary- see section [here](https://genetics.opentargets.org/study-locus/GCST004365_195/1_154445939_T_C).

**For `variant Id`**
_Lead Variant Summary:_
P-value: `pValueMantissa` & `pValueExponent`
Beta: `beta`
Standard Error: `standardError`
EAF: `effectAlleleFrequencyFromSource`
Posterior Probability:  `posteriorProbability`
GRCh38:`region`
RSID: `rsid`

_Credible Set Summary_
Finemapping Method: `finemappingMethod`
Credible set index: `credibleSetIndex`
Purity min: `purityMinR2`
Start: `locusStart`
End: `locusEnd`

Note:
IN A FUTURE DATA ITERATION: QC Flag: `QC flag` (description tat can be even colour coded)

_Study details:_
(from study object)
Author:` publicationFirstAuthor`
Year:   `publicationDate`

Trait: `traitFromSource` (when study type is `gwas`) 
Disease: `disease name(s)` hyperlinked to `diseaseId (s)` to Platform disease page.

or

Affected gene: target `approvedsymbol` hyperlinked to platform target page (`id`)
Affected cell/tissue: `biosampleName`  hyperlinked to `biosampleId` 
(when study type is `qtl`)

Journal: `publicationJournal`
PubMed:  `pubmedId` hyperlinked to https://europepmc.org/article/med/pubmedId
Sample size: `nSamples`
Has sumstats: `hasSumstats`

- [ ] **Variants in credible set widget**

[placeholder sub-header text]: Variants tagging this lead variant. Source: Open Targets 

For each “locus” object 
```

"locus": [
    {
      "is95CredibleSet": true,
      "is99CredibleSet": true,
      "logBF": null,
      "posteriorProbability": 0.8281915098204469,
      "variantId": "3_50557710_C_T",
      "pValueMantissa": null,
      "pValueExponent": null,
      "beta": null,
      "standardError": 0.9999996011812708,
      "r2Overall": 1.0000000000000027
    }
```

1. Variant Id - `variantId`
2. P-value- `pValueMantissa & pValueExponent` (Table will be sorted/sortable by this column)
3 Beta- `beta` - Tooltip: `Beta with respect to the ALT allele`
4. Standard Error `standardError`-Tooltip: `Standard Error: Estimate of the standard deviation of the sampling distribution of the beta`
5. LD (r2) - `r2Overall` - Tooltip: `Linkage disequilibrium with the queried variant`
6. Posterior probability - `posteriorProbability` - Tooltip: `Posterior inclusion Probability from fine-mapping that this variant is causal`
7. LOG(BF) - `logBF`

**Comment by buniello** [comment]
I have updated this ticket upon today's discussion (4/9/24).
More discussions on page content will take place within the next few days.

**Comment by buniello** [comment]
As mentioned above, the credible set page will also contain:

3. Co-loc with GWAS SNPs - scoping in progress
4. Co-loc with QTLs - scoping in progress

We shaped these two widgets on 11/09/24 (notes with me). When the [colocalisation API will be ready](https://github.com/opentargets/issues/issues/3441), i will add instruction for FE widget development here.

Current data schema for colocalisation is:
```
root
 |-- leftStudyLocusId: long (nullable = false)
 |-- rightStudyLocusId: long (nullable = false)
 |-- chromosome: string (nullable = false)
 |-- colocalisationMethod: string (nullable = false)
 |-- numberColocalisingVariants: long (nullable = false)
 |-- h0: double (nullable = true)
 |-- h1: double (nullable = true)
 |-- h2: double (nullable = true)
 |-- h3: double (nullable = true)
 |-- h4: double (nullable = true)
 |-- log2h4h3: double (nullable = true)
 |-- clpp: double (nullable = true)

```

[placeholder comment]

**Comment by buniello** [comment]
Additional column will be added to credible set summary: `confidence` (with the star system for quality). 
More info here (from #3556):  
For @opentargets/fe-team : In the credible set table, a new column will be introduced: confidence. This field captures how "good" a credible set is, not how good the l2g prediction, or how strong the association. The values in this field are enum, that can be translated to stars:

"SuSiE fine-mapped credible set with in-sample LD" -> 4 stars
"SuSiE fine-mapped credible set with out-of-sample LD" -> 3 stars
"PICS fine-mapped credible set extracted from summary statistics" -> 2 stars
"PICS fine-mapped credible set based on reported top hit" -> 1 star
"Unknown confidence" -> zero stars
The text can be shown in tool-tips. 

Also, the confidence field can be shown on other tables with credible sets: evidence or study page, maybe coloc.

**Comment by buniello** [comment]
We discussed a couple of small changes to this page:

- [ ] Re-organisation of the metadata section to:
1. Credible set summary 2. Lead Variant  3 Study.  -- these can also be visualised in three columns (currently they are organised into two for consistency with other pages). Also, the credible set summary only shows fields where they are not N/A, meaning that number of fields is variable in that section.

- [ ] Study summary to contain new fields (from `study object`). These include link to disease page through `disease Id` for `gwas` and additional study fields for `qtl`.

_Study details:_
Author:` publicationFirstAuthor`
Year:   `publicationDate`

Trait: `traitFromSource` 
Disease: `disease name(s)` hyperlinked to `diseaseId (s)` to Platform disease page
(when study type is `gwas`) 

or
Type: `study type`
Affected gene: target `approvedsymbol` hyperlinked to platform target page (`id`)
Affected cell/tissue: `biosampleName`  hyperlinked to `biosampleId` 
Condition: `condition`
(when study type is `qtl`)

Journal: `publicationJournal`
PubMed:  `pubmedId` hyperlinked to https://europepmc.org/article/med/pubmedId
Sample size: `nSamples`

**Comment by buniello** [comment]
Discussed today 16th Oct: 
1. adding a `disease` field in **study summary** with `disease name(s) hyperlinked to diseaseId (s`) to Platform disease page (when study type is gwas) - ALREADY in scoping notes above
2. PMID field in study section could be visualised with publication drawer

**Comment by gjmcn** [comment]
Plot is done, but some polishing still required:

- Tooltip
    - tune size of tooltip to account for row spacing changes recently added to the tooltip component
    - (ideally) allow 'normal' tooltip to explain labels (as do for the column headers in the table) - tooltip values can already have normal tooltips.
- Enforce 'nice' tick values on y-axis
