### ISSUE TITLE
Create biosample index to resolve Tissue/cell type entities

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3445]
As discussed with @Tobi1kenobi and @DSuveges, we want to create an index containing all the valid tissue/cell type entities for the Open Targets Platform. This will help with validation and resolve labels, ontology, etc.

The most immediate use case is to resolve all the biosample identifiers' eQTL catalogue studies at the API level.  In the future, this data can be used for many other use cases: baseline expression, literature-mining, etc. Currently, the QTL study index contains the `biosampleId` (e.g. UBERON code), but we will rely on the index to retrieve labels or any additional data.

![Screenshot 2024-09-06 at 10 51 38](https://github.com/user-attachments/assets/eb2aa2a7-7f33-461f-a42c-f956db5b82c9)

A few tasks:

- [x] create relevant datasource parsers (e.g. UBERON, CL)
- [x] #3478
- [x] create `biosampleIndex` step to call the parsers and write the single index. Deciding on a reasonable data model.
- [x] develop a `qc` method in the `studyIndex` that flags studies with invalid biosample entities
- [x] add the relevant qc flag to the `study_validation` logic/configuration
- [ ] once the dataset is generated - @remo87 can help to load it in the genetics instance and expose the API (separate ticket)

**Comment by Tobi1kenobi** [comment]
This has taken a little longer than expected as I initially wrote everything for owl but have since shifted to JSON ontology files. But the code should all be in  https://github.com/opentargets/gentropy/compare/alegbe-biosample_index

Would like to test it against the study index currently in gentropy before I make a pull request but unsure of best way to do this

**Comment by addramir** [comment]
Is it related to tissue/cell line catalogue we previously discussed?
