### ISSUE TITLE
Validation of StudyIndex and CredibleSet datasets

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3451]
As a **user** I want **run validation before the data release is produced** because **I want to ensure data we generate is correct.**

## Background

The ETL run with steps: 
- `study_validation`
- `credible_set_validation`
was performed on data from buckets:
- `gwas_catalog_data`
- `finngen_data/r11`
- `ukb_ppp_eur_data`
- `eqtl_catalogue_data`

The results from the validation can be found in:
- gs://genetics_etl_python_playground/releases/24.09/study_index
- gs://genetics_etl_python_playground/releases/24.09/invalid_study_index
- gs://genetics_etl_python_playground/releases/24.09/credible_set
- gs://genetics_etl_python_playground/releases/24.09/invalid_credible_set

## Tasks

valid study_index count: 1977110
invalid study_index count: 10663
valid credible_set count: 2254759
invalid credible_set count: 1063068

The analysis was performed at 2024-09-11

## Study index validation
| | | |
|-|-|-|
| |qualityControls|count|
|0|Composite association|1956|
|1|Study not found in the study index|31106|
|2|Explained by a more significant variant in high LD (clumped)|39012|
|3|LD block does not contain variants at the required R^2 threshold|46738|
|4|Palindrome alleles - cannot harmonize|71184|
|5|Incomplete genomic mapping|90306|
|6|Variant inconsistency|90311|
|7|No mapping in GnomAd|90739|
|8|Variant not found in LD reference|139463|
|9|Non-unique study locus identifier|167939|
|10|Subsignificant p-value|788981|

## Credible set validation

| | | | |
|-|-|-|-|
|id |qualityControls|projectId|count|
|0|Target/gene identifier could not match to reference.|Randolph_2021|1|
|1|Target/gene identifier could not match to reference.|Aygun_2021|1|
|2|Target/gene identifier could not match to reference.|Naranbhai_2015|1|
|3|Target/gene identifier could not match to reference.|Peng_2018|2|
|4|Target/gene identifier could not match to reference.|van_de_Bunt_2015|2|
|5|Target/gene identifier could not match to reference.|Fairfax_2012|3|
|6|Target/gene identifier could not match to reference.|UKB_PPP_EUR|3|
|7|Target/gene identifier could not match to reference.|Kasela_2017|4|
|8|Target/gene identifier could not match to reference.|Gilchrist_2021|5|
|9|Target/gene identifier could not match to reference.|Braineac2|5|
|10|Target/gene identifier could not match to reference.|Schwartzentruber_2018|6|
|11|Target/gene identifier could not match to reference.|Perez_2022|7|
|12|Target/gene identifier could not match to reference.|iPSCORE|7|
|13|Target/gene identifier could not match to reference.|PISA|8|
|14|Target/gene identifier could not match to reference.|PhLiPS|11|
|15|Target/gene identifier could not match to reference.|Steinberg_2020|15|
|16|Target/gene identifier could not match to reference.|Walker_2019|15|
|17|Target/gene identifier could not match to reference.|Fairfax_2014|15|
|18|Target/gene identifier could not match to reference.|CEDAR|17|
|19|Target/gene identifier could not match to reference.|OneK1K|21|
|20|Target/gene identifier could not match to reference.|CAP|21|
|21|Target/gene identifier could not match to reference.|GEUVADIS|22|
|22|Target/gene identifier could not match to reference.|GENCORD|25|
|23|Target/gene identifier could not match to reference.|Bossini-Castillo_2019|25|
|24|Target/gene identifier could not match to reference.|Lepik_2017|26|
|25|Target/gene identifier could not match to reference.|Alasoo_2018|30|
|26|Target/gene identifier could not match to reference.|Nathan_2022|38|
|27|Target/gene identifier could not match to reference.|Cytoimmgen|39|
|28|Target/gene identifier could not match to reference.|HipSci|40|
|29|Target/gene identifier could not match to reference.|Nedelec_2016|40|
|30|Target/gene identifier could not match to reference.|CommonMind|50|
|31|Target/gene identifier could not match to reference.|BrainSeq|53|
|32|Target/gene identifier could not match to reference.|ROSMAP|56|
|33|Target/gene identifier could not match to reference.|FUSION|69|
|34|Target/gene identifier could not match to reference.|BLUEPRINT|82|
|35|Target/gene identifier could not match to reference.|TwinsUK|83|
|36|Target/gene identifier could not match to reference.|Quach_2016|104|
|37|Target/gene identifier could not match to reference.|Schmiedel_2018|119|
|38|The identifier of this study is not unique.|GCST|142|
|39|No valid disease identifier found.|FINNGEN_R11_|165|
|40|Target/gene identifier could not match to reference.|GTEx|1317|
|41|No valid disease identifier found.|GCST|7968|

**Comment by project-defiant** [comment]
@ireneisdoomed @d0choa @DSuveges @Daniel-Considine @xyg123

**Comment by DSuveges** [comment]
This one is really suspicious:
```
38 | The identifier of this study is not unique. | GCST | 142
```

**Comment by d0choa** [comment]
Many of these should be PICS sum stats vs PICS top hits. We will probably rescue many of them once the inclusion criteria are added

<!DOCTYPE html>
9 | Non-unique study locus identifier | 167939
-- | -- | --

**Comment by project-defiant** [comment]
The duplicated studyIds -> 
```
+------------+-----+
|     studyId|count|
+------------+-----+
|GCST90096899|    2|
|GCST90096897|    2|
|GCST90096898|  128|
|GCST90096895|    2|
|GCST90096894|    2|
|GCST90096896|    2|
|GCST90096900|    2|
|GCST90096892|    2|
+------------+-----+
```

**Comment by d0choa** [comment]
Looking at the studies as well. An interesting number of QTLs are missed due to obsoleted Ensembl IDs. Perhaps, we could implement additional logic to rescue some of them but not a priority for now 

```
In [45]: df.filter(f.array_contains(f.col("qualityControls"), "Target/gene identifier could not match to reference.")).groupBy("studyType", "traitFromSourc
    ...: e").count().sort(f.col("count").desc()).show(truncate = False)
+---------+------------------------------------------------+-----+
|studyType|traitFromSource                                 |count|
+---------+------------------------------------------------+-----+
|eqtl     |ENSG00000288884                                 |106  |
|eqtl     |ENSG00000288884.1_7_128661095_128663479         |90   |
|eqtl     |ENSG00000285476                                 |60   |
|eqtl     |ENST00000610032                                 |51   |
|eqtl     |ENSG00000286996.1_3_39423802_39424870           |50   |
|eqtl     |ENST00000444946                                 |47   |
|eqtl     |ENSG00000256427                                 |47   |
|eqtl     |ENSG00000286996                                 |46   |
|eqtl     |ENSG00000285762                                 |46   |
|eqtl     |ENSG00000182230                                 |46   |
|eqtl     |ENST00000367055                                 |45   |
|eqtl     |ENST00000616861                                 |42   |
|eqtl     |ENSG00000259820                                 |39   |
|tuqtl    |ENSG00000112096.grp_2.downstream.ENST00000367054|39   |
|eqtl     |ENSG00000228139                                 |39   |
|eqtl     |ENSG00000259820.1_8_134792020_134798272         |37   |
|eqtl     |ENSG00000228906                                 |36   |
|eqtl     |ENSG00000261490                                 |33   |
|eqtl     |ENST00000538183                                 |32   |
|eqtl     |ENSG00000280374                                 |31   |
+---------+------------------------------------------------+-----+
only showing top 20 rows
```

**Comment by d0choa** [comment]
We can continue discussing, but I think this task is done.

Numbers will change when variant validation (#3452) and study/credible set inclusion are implemented, and we will have additional numbers to validate.
