### ISSUE TITLE
Implementing validation step to flag study loci where any of the tags are not in the variant index

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3452]
It is important to exclude credible sets from ingestion in the platform where any on the tagging variant don't have valid variant identifier. Such discrepancy can potentially lead to failing pages and failing graphql queries.

**Steps to implement:**

- [ ] Implement business logic into studyLocus dataset that flags rows where variants are found which are not in the provided variant index.
- [ ] Add the function call in the relevant step in the ETL pipeline.
- [ ] QC result.

**Comment by project-defiant** [comment]
@DSuveges should we close it? We still have to implement the logic to the ETL (scoped by this issue)
