### ISSUE TITLE
Migrate pan-UKBB LD matrixes from AWS to GCP

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3455]
We would like to have panUKBB LD matrixes to improve our finemapping process.

3 ancestries: EUR, AFR, CSA

s3://pan-ukb-us-east-1/ld_release/UKBB.EUR.ldadj.bm
s3://pan-ukb-us-east-1/ld_release/UKBB.AFR.ldadj.bm
s3://pan-ukb-us-east-1/ld_release/UKBB.CSA.ldadj.bm
and
s3://pan-ukb-us-east-1/ld_release/UKBB.EUR.ldadj.variant.ht
s3://pan-ukb-us-east-1/ld_release/UKBB.AFR.ldadj.variant.ht
s3://pan-ukb-us-east-1/ld_release/UKBB.CSA.ldadj.variant.ht (edited) 

@prashantuniyal02 This is going to be costly, so we will need estimates on transfer cost and storage. We can move to auto-class, and the expectation is that we might only access the data once every quarter. But let's try to make this happen

**Comment by prashantuniyal02** [comment]
Hi @addramir , I have started the transfer of all variant.ht and UKBB.CSA.ldadj.bm to our GCP.
You can start with that ancestry. I just need to monitor any associated costs for the next couple of days.

**Comment by addramir** [comment]
Hi @prashantuniyal02 , thank you! could you please also move EUR (nfe)? It is priority 1.

**Comment by prashantuniyal02** [comment]
@addramir , I have also moved the UKBB.EUR.ldadj.bm file to gs://panukbb-ld-matrixes GCP bucket

**Comment by prashantuniyal02** [comment]
pan-UKBB LD matrixes for all the 3 ancestries are present in our GCP bucket: `gs://panukbb-ld-matrixes`

**Comment by prashantuniyal02** [comment]
Moved all the 3 ancentries build 38 to `gs://panukbb-ld-matrixes/ukb-diverse-pops-public-build-38`
