### ISSUE TITLE
L2G feature list discussion

### ISSUE THREAD

**Issue by xyg123** [opentargets/issues#3458]
As a **developer** I want **to select the best set of features for L2G predictions** because **it will ensure that the most relevant features are used for accurate and robust gene prioritisation in the Gentropy L2G model**.

## Background

For the new implementation of L2G in Gentropy, we have not yet included all features from the original L2G model.

- Full feature list from original L2G can be found here: [Original L2G Feature List](https://docs.google.com/spreadsheets/d/1tp_nK71SN0FIj7eUbD_k4T5GtZOUT6H7btmH_yL-xsc/edit?gid=0#gid=0)
- The feature importance for the full list is available here: [L2G Feature Importance](https://genetics-docs.opentargets.org/our-approach/prioritising-causal-genes-at-gwas-loci-l2g#feature-importance)

Existing feature list from current Gentropy L2G implementation is here:
[Current Gentropy L2G Feature List](https://docs.google.com/spreadsheets/d/1wUs1AprRCCGItZmgDhc1fF5BtwCSosdzFv4NQ8V6Dtg/edit?gid=0#gid=0)

We want to have a discussion regarding which of these features should be added to the Gentropy implementation. For example, features relevant to **gene footprint distance** have been requested by partners. Additionally, we want to reach a consensus on how the scores for these features should be generated. The finalised features and their scoring methodology will be added to the feature list documentation.

## Tasks

- Schedule a meeting or discussion to review the feature lists.
- Document the rationale behind feature selection and scoring methods.

## Acceptance tests

How do we know the task is complete?

1. A final list of features to implement in Gentropy will be created.
2. Documentation will be updated to include each feature’s relevance and the method for deriving score-based features.

**Comment by xyg123** [comment]
**Summary of feature list discussion:**
Will add currently missing features from the genetics portal implementation, this includes:

- molQTL neglog(p-values)
- Neighbourhood features for distance-based features.
- Footprint distance features.
- Will also add the interval features, although doubts were raised regarding their relevance.
- Gene count within 500kb window of studyLocus

The following features will not be included:

- Distance features related to sentinel variants 
- Polyphen features.
- Protein attenuation.

Additional features to be scoped after the release:

- Credible set size/ top posterior probability at a studyLocus, to indicate performance of finemapping.
- QTL direction of effect (betas).
- ABC model.
-

**Comment by ireneisdoomed** [comment]
There was also the VEP feature, which implemented a scoring of the most severe functional consequence for a variant/gene. Will this be dropped as well?

**Comment by xyg123** [comment]
> There was also the VEP feature, which implemented a scoring of the most severe functional consequence for a variant/gene. Will this be dropped as well?

No, we are keeping them.  Apologies, I thought these were already implemented.
