### ISSUE TITLE
Odds ratios are not harmonised in the GWAS Catalog curated association ingestion

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3461]
As reported by Jake Fremier, in the PICSed, curated GWAS Catalog association pile, betas are not following the expected distribution:
![image](https://github.com/user-attachments/assets/6775bddb-d226-42db-96b9-a6f831933da1)

When looking into the issue, apparently betas are harmonised, however odds ratios are ignored. As the association effect is stored in the same column regardless if it was OR or beta, ORs just propagated as is. The required logic is already in the GWAS Catalog datasource code, just needs to be "turned on".

When it has happened, make sure sufficient testing is also added to the codebase.

**Comment by DSuveges** [comment]
The fix has been prototyped. The before data:

```python
(
    spark.read.parquet('/Users/dsuveges/project_data/gentropy/credible_set/gwas_catalog_PICSed_curated_associations')
    .filter(
        (f.col("beta").isNotNull()) & 
        (f.col('beta') > -1.5) & 
        (f.col('beta') < 1.5)
    )
    .select('beta')
    .toPandas()
    .hist(bins=100)
)
```

![image](https://github.com/user-attachments/assets/b0f0e7f5-174b-49fc-bca2-71b2a5d66b0b)

Which becomes:

```python
(
    beta_harmonised_df
    .filter(
        (f.col("beta").isNotNull()) & 
        (f.col('beta') > -1.5) & 
        (f.col('beta') < 1.5)
    )
    .select('beta')
    .toPandas()
    .hist(bins=100)
)
```

![image](https://github.com/user-attachments/assets/ccb54c97-e201-4f17-ac01-a9a63c3a2677)

**Comment by project-defiant** [comment]
The one thing I am not getting from this is that the distribution reported initially looks swapped a bit different then the one you were @DSuveges able to reproduce.

**Comment by jfreimer** [comment]
@project-defiant the plots I initially sent were just from a subset of studies that we were interested in looking at rather than the full catalog which is probably why the distribution looks different.
