### ISSUE TITLE
Move L2G gold standard to the curation repo

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/issues#3463]
As a **developer** I want **to have the raw L2G gold standard in the curation repo** because **it is a static file that is subject to versioning.** Having it in the curation repo makes sense. It now lives in GCS, and moving it removes some overhead to deal with it  in Gentropy.

## Background

This file was initially maintained in its own repo https://github.com/opentargets/genetics-gold-standards/tree/master

## Tasks

- [ ] Upload to the curation [repo](https://github.com/opentargets/curation)
- [ ] Document
- [ ] Update dependency management in Gentropy

**Comment by addramir** [comment]
I think this issue could be/should modified depending on our logic for training the model. Lets make this decision as soon as we have credible set level feature matrix.

**Comment by addramir** [comment]
Can this issue?

**Comment by project-defiant** [comment]
@addramir we should still maintain old Gold standard somewhere (not exactly on the google bucket). I have done some of this as a part of https://github.com/opentargets/curation/pull/36, but wanted to wait for us to see if the last week workshop will result in some proper feedback on this.

**Comment by addramir** [comment]
I still consider it as some kind of static asset. We can curate it from sourse as a DAG or simply compile this file manually and store as static asset.
