### ISSUE TITLE
Scope gentropy POS loading strategy (JSON vs Parquet)

### ISSUE THREAD

**Issue by d0choa** [opentargets/issues#3470]
Currently, all data generated by gentropy is parquet-only. This is different from platform-etl, which produces both Parquet and JSON.

As of today, we use JSON to load to OpenSearch. If we keep doing this and there is no alternative to load parquet, we need to define a strategy, whether in the gentropy level or as a tool to convert formats that can be plugged to the orchestration.

**Comment by javfg** [comment]
I think this summarizes it pretty well. Removing any data conversions from ETL is good separation of concerns, as:

1. PIS grabs a bunch of data from many sources and puts them in a specific place
2. ETL generates our dataset from the source at that specific place, and puts it in another specific place, in a standard format (parquet)
3. POS distributes that dataset to the many  targets that need it, converting it if needed

We can see this as a core (ETL), with two outer layers, one input (PIS), and one output (POS).
