### ISSUE TITLE
PIS transformation extraction: `homologues` step

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3482]
# Description

The `homologues` step writes files into two subfolders:

`target-inputs/homologue/gene-dictionary` and `target-inputs/homologue/homologies`

The files in the `gene-dictionary` folder are JSON files fetched from:

```
https://ftp.ensembl.org/pub/release-${ensembl_version}/json/${species}/${species}.json
```

with `${species}` being: `caenorhabditis_elegans`, `canis_lupus_familiaris`, `cavia_porcellus`, `danio_rerio`, `drosophila_melanogaster`, `macaca_mulatta`, `mus_musculus`, `oryctolagus_cuniculus`, `pan_troglodytes`, `rattus_norvegicus`, `sus_scrofa`, `xenopus_tropicalis`, `homo_sapiens`.

# Transformations PIS was doing

PIS was running:

```
jq -r '.genes[] | [.id, .name] | @tsv'
```

on the files, extracting those two fields and building a TSV file with them.

# Tasks

- [x] Figure out where to put this transformation
- [ ] Implement transformation
- [x] Test output is equal to the one legacy PIS generates

**Comment by d0choa** [comment]
This is the function to apply the transformation: 
https://github.com/opentargets/platform-etl-backend/blob/11a1f67ce194d079603543f5f96b76c9963e35e8/src/main/scala/io/opentargets/etl/backend/target/Target.scala#L312

**Comment by remo87** [comment]
The transformer has been implemented to turn the json files into json lines file and extract the name and id fileds

**Comment by remo87** [comment]
After testing against the ETL I found that the previous input was scaping the separator `\t` which meant that the ETL had to do additional processing to extract the data. This will be corrected in the new output which will mean we need to update the [Ortholog](https://github.com/opentargets/platform-etl-backend/blob/11a1f67ce194d079603543f5f96b76c9963e35e8/src/main/scala/io/opentargets/etl/backend/target/Ortholog.scala) file. Also I need to do a small update in the ontoform to correct the output format from json to tsv
