### ISSUE TITLE
PIS transformation extraction: `openfda` step

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3483]
# Description

The `openfda` step downloads a [list of event files](https://api.fda.gov/download.json) and then downloads all the `events` in that file, using the `jq` query:
```
jq -r '.results.drug.event.partitions[].file' download.json
```
It's a big amount of zip files to download (1542 files at the moment of opening this issue). They contain a single JSON file inside.

# Transformations PIS was doing

PIS extracts the JSON file from the zips, and then generates a JSONL file with each entry inside of the `results` array, like so:

```
jq -c '.results[]' output.json
```

the output file gets a UUID4 as its name.
Then, the ETL picks files like `/fda-inputs/*.jsonl` to process.

# Tasks

- [x] Figure out where to put this transformation
- [x] Implement transformation
- [x] Test output is equal to the one legacy PIS generates

**Comment by remo87** [comment]
The new transformator is going to output the file to parquet instead of json lines wich would give us savings of 90% aprox disk space. This will require updating the reference.conf file in the ETL, but thanks to the way the ETL is built the actual logic shouldn't be affected.
