### ISSUE TITLE
24.09 only partially released, missing GCS data

### ISSUE THREAD

**Issue by dhimmel** [opentargets/issues#3492]
There's a [blog post](https://blog.opentargets.org/open-targets-platform-24-09-release/) about the 24.09 release and the notes are listed at https://platform-docs.opentargets.org/release-notes.

But I cannot access any GCS data for the release?

```sh
$ gsutil -u my-project stat 'gs://open-targets-data-releases/24.09/output/etl/parquet/targets/**'
No URLs matched: gs://open-targets-data-releases/24.09/output/etl/parquet/targets/**
```

Perhaps there's usually a delay from platform data update to GCS availability and I haven't noticed until now?

**Comment by javfg** [comment]
Hi @dhimmel,

The release date are being uploaded, I'll get back to you as soon as they are available.

Sorry for the delay!

**Comment by javfg** [comment]
The data should be there now. @dhimmel can you please check and get back to us to confirm?

**Comment by dhimmel** [comment]
Yes, the command above now returns output like:

```
gs://open-targets-data-releases/24.09/output/etl/parquet/targets/part-00199-b2a23987-7e43-4651-a89c-1eb34ec9f9f5-c000.snappy.parquet:
    Creation time:          Thu, 19 Sep 2024 14:21:20 GMT
    Update time:            Thu, 19 Sep 2024 14:21:20 GMT
    Storage class:          NEARLINE
    Content-Length:         452100
    Content-Type:           application/octet-stream
    Hash (crc32c):          x10EEQ==
    Hash (md5):             gZN+MDagZBM5cs2i0T9GgA==
    ETag:                   CNu0vpeaz4gDEAE=
    Generation:             1726755680262747
    Metageneration:         1
```

Thanks @javfg
