### ISSUE TITLE
The DAG for harmonisation and fine-mapping of UKBB-PPP

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3493]
The closest to finish DAG. Includes steps for harmonisation, locus breaker and collection.

- [x] Add the step for locus breaker and locus collection - [Step is called: LocusBreakerClumpingStep](https://github.com/opentargets/gentropy/blob/dev/src/gentropy/locus_breaker_clumping.py)
- [ ] Modify the fine-mapper step here - https://github.com/opentargets/gentropy/pull/764
- [x] Lets keep postprocessing here. https://github.com/opentargets/gentropy/blob/dev/src/gentropy/credible_set_qc.py

**Comment by project-defiant** [comment]
Linking current DAGs: 
- [harmonisation] (https://github.com/opentargets/orchestration/blob/dev/src/ot_orchestration/dags/ukb_ppp_eur_harmonisation.py)
- [fine-mapping done by Kirill ](https://github.com/opentargets/orchestration/blob/dev/src/ot_orchestration/dags/ukb_ppp_finemapping.py)

**Comment by addramir** [comment]
Not sure whether merge finemapping dag to harmonisation is a good idea. The data is hamronised and unlikly to be changed but we may want to rerun FM several times with diffrent parameters.

**Comment by addramir** [comment]
Ok, sounds good. Do you need any help here?

**Comment by project-defiant** [comment]
Just point me to the QC step
