### ISSUE TITLE
PIS transformation extraction: `disease` step `EFO`

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3496]
# Description
This is for the `disease` step, which downloads four ontologies and transforms them.

# Transformations PIS was doing
PIS downloaded the OWL version, converted it to JSON using Apache Jena, then ran transformations: [reference](https://github.com/opentargets/platform-input-support/blob/master/plugins/helpers/EFO.py)

There is now a [JSON version](https://github.com/EBISPOT/efo/releases) (`efo_otar_slim.json`) of the ontology, so we only need to transform from that one.

# Tasks

- [ ] Figure out where to put this transformation
- [x] Implement transformation
- [x] Test output is equal to the one legacy PIS generates

**Comment by javfg** [comment]
While implementing this, I found:

* Many definitions are going to be different, as the JSON file does not include multiple definitions and old PIS was choosing the last one in the list as the main definition. When I discussed this with the EFO team, they said they are not sure they want more than one definition and will [evaluate dropping the extra](https://github.com/EBISPOT/efo/issues/2290). So I think choosing the one in the JSON is the correct way forward for us anyway.

* There are 7 entities with more than one `label` field in EFO. I've [opened a report](https://github.com/EBISPOT/efo/issues/2292) for them. This changes the output from old PIS in the following: (only showing relevant fields)

```diff
1903c1903
< {"code":"http://www.ebi.ac.uk/efo/EFO_0007409", "label":"Ornithine transcarbamylase deficiency"}
---
> {"code":"http://www.ebi.ac.uk/efo/EFO_0007409", "label":"ornithine carbamoyltransferase deficiency"}
```

```diff
26363,26365c26363,26365
< {"code":"http://purl.obolibrary.org/obo/OBI_0001620", "label":"latitude"}
< {"code":"http://purl.obolibrary.org/obo/OBI_0001621", "label":"longitude"}
< {"code":"http://purl.obolibrary.org/obo/OBI_1110021", "label":"infect"}
---
> {"code":"http://purl.obolibrary.org/obo/OBI_0001620", "label":"latitude coordinate measurement datum"}
> {"code":"http://purl.obolibrary.org/obo/OBI_0001621", "label":"longitude coordinate measurement datum"}
> {"code":"http://purl.obolibrary.org/obo/OBI_1110021", "label":"infection process"}
```

* There is an entry with an empty synonym that was being captured by old PIS but not anymore (I've also [reported this](https://github.com/EBISPOT/efo/issues/2291) to EFO team):

```diff
2807c2807
< {"code":"http://www.ebi.ac.uk/efo/EFO_0008451", "synonyms":{"hasExactSynonym":["","ADL","Katz ADL index"]}}
---
> {"code":"http://www.ebi.ac.uk/efo/EFO_0008451", "synonyms":{"hasExactSynonym":["ADL","Katz ADL index"]}}
```

* old PIS was missing many obsolete terms that are annotated in the ontology. This is due to a bug in the order of the filtering, which was dropping some entries that had obsolescence information early and then missed it.

```diff
12642c12642
< {"code":"http://purl.obolibrary.org/obo/GO_0006810"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0006810", "obsoleteTerms":["GO_0044765"]}
12662c12662
< {"code":"http://purl.obolibrary.org/obo/GO_0007165"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0007165", "obsoleteTerms":["GO_0023014"]}
12686,12687c12686,12687
< {"code":"http://purl.obolibrary.org/obo/GO_0008150", "obsoleteTerms":["EFO_0003936"]}
< {"code":"http://purl.obolibrary.org/obo/GO_0008152"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0008150", "obsoleteTerms":["EFO_0003936","GO_0044699"]}
> {"code":"http://purl.obolibrary.org/obo/GO_0008152", "obsoleteTerms":["GO_0044710"]}
12734c12734
< {"code":"http://purl.obolibrary.org/obo/GO_0009410"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0009410", "obsoleteTerms":["GO_0042493"]}
12743c12743
< {"code":"http://purl.obolibrary.org/obo/GO_0009987"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0009987", "obsoleteTerms":["GO_0044763"]}
12770c12770
< {"code":"http://purl.obolibrary.org/obo/GO_0019538"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0019538", "obsoleteTerms":["GO_0044267"]}
12798,12799c12798,12799
< {"code":"http://purl.obolibrary.org/obo/GO_0032501"}
< {"code":"http://purl.obolibrary.org/obo/GO_0032502"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0032501", "obsoleteTerms":["GO_0044707"]}
> {"code":"http://purl.obolibrary.org/obo/GO_0032502", "obsoleteTerms":["GO_0044767"]}
12819c12819
< {"code":"http://purl.obolibrary.org/obo/GO_0036211"}
---
> {"code":"http://purl.obolibrary.org/obo/GO_0036211", "obsoleteTerms":["GO_0006464"]}
14787c14787
< {"code":"http://purl.obolibrary.org/obo/HP_0045075"}
---
> {"code":"http://purl.obolibrary.org/obo/HP_0045075", "obsoleteTerms":["HP_0000535"]}
```

This run was done one [EFO v3.70.0](https://github.com/EBISPOT/efo/releases/tag/v3.70.0), latest version at the moment.

**Comment by d0choa** [comment]
They all look like improvements. No concerns from what I can see
