### ISSUE TITLE
PIS transformation extraction: `so` step

### ISSUE THREAD

**Issue by javfg** [opentargets/issues#3499]
# Description
The `so` step downloads the [sequence ontology](https://github.com/The-Sequence-Ontology/SO-Ontologies/tree/master/Ontology_Files).

# Transformations PIS was doing
PIS was downloading the OWL version and using Apache Jena to convert it to JSONL. There is a JSON version, so we can use that one to avoid Jena and transform it into JSONL directly.

The query PIS used to convert Jena's output into JSONL is:
```jq
'.["@graph"][] | select (.["@type"] == "owl:Class" and .id != null)|.subClassOf=([.subClassOf]|flatten|del(.[]|nulls))|.hasExactSynonym=([.hasExactSynonym]|flatten|del(.[]|nulls))|.hasDbXref=([.hasDbXref]|flatten|del(.[]|nulls))|.inSubset=([.inSubset]|flatten|del(.[]|nulls))|.hasAlternativeId=([.hasAlternativeId]|flatten|del(.[]|nulls))|@json'
```

But we must adapt it to the `so.json` version, as it is not the same as Jena's output.

# Tasks
- [ ] Figure out where to put this transformation
- [ ] Implement transformation
- [x] Test output is equal to the one legacy PIS generates

**Comment by remo87** [comment]
Json files are exposed in a github [repo](https://github.com/The-Sequence-Ontology/SO-Ontologies/tree/master/Ontology_Files)

**Comment by remo87** [comment]
The Json file needs to be mapped the structure is different to the owl file. I'll be using the extractor to extract 3 different inputs and create a new step in the ETL to process the inputs and produce the SO in the correct format.

**Comment by remo87** [comment]
The extractor changes are done and the mappings are being processed

**Comment by remo87** [comment]
After discussing with @d0choa the mapping has been simplified and the output now only contains id and label which are the only fields being exposed by the API
