### ISSUE TITLE
Scientific validation of the release data

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3500]
We need to figure out the plan how we scientifically validate the data we produce. 
@xyg123 could you please add the summary we discussed yesterday?

**Comment by xyg123** [comment]
Sure, here's the notes I took yesterday:

# Gentropy Benchmarking

## Additional QC + Benchmarking Steps
- Go through individual output columns and ensure constraints are met.

### Study Index
- Duplicated `studyIds`.

### Fine Mapping
- Sum of posteriors < 1.
- Direction of effect, formatting, etc.

### Colocalisation
- Add validation for COLOC: `h4/clpp` between 0-1.

### L2G
- Score between 0-1.
- Enrichment of drug targets.
- Density plot of score distribution.

- Interesting stories, gene targets, double check they are being picked up by L2G.
- Can we use the ready-curated gene lists in the AMP?

## All Outputs
- Correlation with previous release?
- Consider a set of studies to refer back to (e.g. IBD) and cross-compare between releases.
  
- Can we identify shared top hits/credible sets between Gentropy and genetics portal?
  - Do we have resources to do this?
  
- Where are the discrepancies? (e.g. beta directions)

- Some of these issues already existed in the genetics portal.
  - Yakov and Prashant to go through community page and GitHub issues to see what can be addressed or closed.

## Additional Considerations
- Consider a publication letter to address the issues with working with curated top-hits: _“it’s ruining my pipelines 🙁”_

- Ask Tobi to look at some `studyLocusIds` related to IBD.

**Comment by addramir** [comment]
As discussed with @xyg123 and @project-defiant:
1) Implement the logic of direct and indirect associations after evidence is calculated
2) Run enrichment on indirect associations for old OTG and new associations
3) Compare old and new assosiatnos
