### ISSUE TITLE
In silico predictions widget color-coding scoping

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3503]
We discussed building an extra layer of visualisation to the new Platform+Genetics pages, where possible.

One example is:

- [ ] Add color-coding of in-silico predictions (variant page), following the [Varsome model](https://varsome.com/variant/hg38/rs746753722?annotation-mode=germline).

Assigning this to @carcruz for initial screening

**Comment by buniello** [comment]
Discussed with @carcruz today: this task is part of a bigger choice of standard colour palette for the current UI

**Comment by prashantuniyal02** [comment]
Hi @DSuveges, adding you to the ticket here as the colour ranges would need to be based on relevant data information.

**Comment by buniello** [comment]
I am happy to think about FE for this, but to do so we do need relevant data info e.g. spectrum of possible predictions + scores.
Perhaps @d0choa can help with the data part if data team is unavailable.

**Comment by d0choa** [comment]
```
In [18]: vi.select("variantId", f.explode("inSilicoPredictors").alias("insilico")).select("variantId", "insilico.*").groupBy("method").agg(f.max("score"),f.min("score"), f.avg("score"), f.count(
    ...: "score")).show()
+------------------+----------+----------+--------------------+------------+
|            method|max(score)|min(score)|          avg(score)|count(score)|
+------------------+----------+----------+--------------------+------------+
| phred scaled CADD|      81.0|     0.001|   7.926892685654786|     2729051|
|          polyphen|       1.0|       0.0|  0.4647227910506272|      472978|
|          pangolin|      0.91|     -0.96|0.001308917283231304|     1848077|
|            loftee|      null|      null|                null|           0|
|max alpha missense|       1.0|    0.0052|  0.3763211886690869|      292624|
|              sift|       1.0|       0.0| 0.12029911277119161|      514254|
|          spliceai|       1.0|       0.0|0.011721640635882175|     1435497|
|              null|      null|      null|                null|           0|
+------------------+----------+----------+--------------------+------------+


In [22]: vi.select("variantId", f.explode("inSilicoPredictors").alias("insilico")).select("variantId", "insilico.*").groupBy("method", "assessment", "assessmentFlag").count().show(truncate = Fal
    ...: se)
+------------------+--------------------------+--------------+-------+
|method            |assessment                |assessmentFlag|count  |
+------------------+--------------------------+--------------+-------+
|sift              |deleterious_low_confidence|null          |157738 |
|max alpha missense|ambiguous                 |null          |28551  |
|max alpha missense|likely_pathogenic         |null          |84332  |
|phred scaled CADD |null                      |null          |2729051|
|pangolin          |null                      |null          |1848077|
|polyphen          |unknown                   |null          |17955  |
|loftee            |LC                        |null          |18072  |
|sift              |tolerated_low_confidence  |null          |49905  |
|sift              |deleterious               |null          |176464 |
|polyphen          |possibly_damaging         |null          |83432  |
|polyphen          |benign                    |null          |228745 |
|max alpha missense|likely_benign             |null          |179741 |
|spliceai          |null                      |null          |1435497|
|loftee            |HC                        |null          |121552 |
|polyphen          |probably_damaging         |null          |142846 |
|sift              |tolerated                 |null          |130147 |
|null              |null                      |null          |12     |
+------------------+--------------------------+--------------+-------+

```

**Comment by d0choa** [comment]
## SIFT
The SIFT (Sorting Intolerant From Tolerant) method is a computational tool used to predict whether an amino acid substitution in a protein might impact the protein's function.

SIFT generates a score from 0 to 1 for each substitution:

- Scores ≤ 0.05 indicate that the substitution is predicted to be deleterious (likely harmful to protein function).
- Scores > 0.05 suggest that the substitution is likely to be tolerated (probably has little to no effect on protein function).

## LOFTEE
LOFTEE (Loss-Of-Function Transcript Effect Estimator) is a bioinformatics tool developed to predict whether genetic variants lead to loss-of-function (LoF) in protein-coding genes. It’s particularly useful for identifying variants that might disrupt gene function completely, which can have significant consequences in genetic diseases and phenotypes.

LOFTEE categorizes LoF variants as either high-confidence or low-confidence based on the filtering criteria. Only high-confidence LoF variants are typically considered true LoF events.

(WIP)

**Comment by d0choa** [comment]
## CADD

CADD (Combined Annotation Dependent Depletion) is a computational tool used to score genetic variants based on their predicted deleteriousness.

- 0-10: These scores are generally considered to indicate tolerated or benign variants that are likely to have little or no impact on protein function.

- 10-20: Scores in this range suggest that the variant is potentially deleterious. These variants are more likely to affect protein function, but the evidence is moderate.

- 20-30: Variants with these scores are typically deleterious and likely to have a significant impact on protein function. A score of 20 means that the variant is among the top 1% of likely deleterious variants in the human genome.

- More than 30: Variants with scores over 30 are considered highly deleterious. For example, a CADD score of 30 indicates that the variant is in the top 0.1% of potentially damaging variants, suggesting it has a very high probability of impacting protein function.

**Comment by d0choa** [comment]
Together with @DSuveges we are producing a normalised/scaled view of all the methods. Once implemented, a new score from 0 to 1 for each method would be "comparable" across methods. Generally speaking, it will translate into:

- [0-0.25) - Likely benign
- [0.25-0.75) Uncertain
- [0.75-1) - Likely deleterious  

Once the data is ready we will provide more information
