### ISSUE TITLE
Visualising QC flags for studies and credible sets 

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3504]
This ticket will summarise discussions and decisions on visualisation options for QC flags (studies and credible sets).

One options could be adding a warning (when warning is needed) and showing QC flags string on hovering - for this, i would need to take a look at all available flag strings.

[Study index flags ](https://github.com/opentargets/gentropy/blob/a29222ed8d9bb8d023981626917eca6e659d2335/src/gentropy/dataset/study_index.py#L25)

[Study locus flags](https://github.com/opentargets/gentropy/blob/a29222ed8d9bb8d023981626917eca6e659d2335/src/gentropy/dataset/study_locus.py#L36)

**Comment by prashantuniyal02** [comment]
Duplicate of #3626
