### ISSUE TITLE
Use major ancestry in PICS fine-mapping

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3514]
As previously discussed several times the logic/math behind combining multiple ancestries in PICS fine-mapping is incorrect. PICS will benefit from using the same approach as used now in susie - use only major ancestry. In the future we can think about refining the logic, but for now it is better to be as correct as possible.

**Comment by DSuveges** [comment]
Essentially we need to do LD annotation as lead variant was coming from a study with 100% Europeans instead of 70%. There's already a method to get the major ancestry from the ld popultation field in the study index.
