### ISSUE TITLE
validate_lead_pvalue in study locus fillters all StydyLoci but it shouldn't

### ISSUE THREAD

**Issue by addramir** [opentargets/issues#3529]
validate_lead_pvalue flaggs all CSs. However it is possibile to have secondary signal CSs from SuSiE with lead variants <1e-6 and it is valid.
The easiest fix is to have separate thresholds for PICS (genome-wide significant) and SuSiE (for example 1e-5 or 1e-6).

**Comment by d0choa** [comment]
Let me think about this.

**Comment by DSuveges** [comment]
Oh, I really don't like the idea: the checks performed on the aggregated data should be applicable on the full dataset. If different sources have different expectations to comply, then these checks should be performed at the source. I know doing qc is more ideal in one place, but this is not really a qc on the credible set object as a whole, rather a qc on the susie or the pics-ed credible sets.

**Comment by addramir** [comment]
In this case, this filter should be dropped from the QC and added to data specific postprocessing.

**Comment by d0choa** [comment]
Agreed. @addramir if you can scope the datasource-specific logic we could close this ticket

**Comment by addramir** [comment]
https://github.com/opentargets/gentropy/pull/788
