### ISSUE TITLE
PheWas Plot scoping phase

### ISSUE THREAD

**Issue by buniello** [opentargets/issues#3537]
We have discussed the possibility to implement a PheWas plot from credible sets.

This ticket will incorporate scoping of such visualisation, also taking into account the existing datasets and how we could query them easily to fit into a particular page.

- Example from [FinnGen (with linkout to OTG as well)](https://r11.finngen.fi/variant/1:36393562-T-C) for variant - we could so something similar for credible sets, genes and variants. NOTE: we need to consider our CS p-value cutoffs.

**Comment by d0choa** [comment]
We had a similar discussion in the past. When discussing PheWAS, different people understand different things:
a) a plot to visualise the effect of variants across many traits (or credible sets alternatively)
b) an analysis that helps identify new associations when accounting for the relationships between traits.   

We are potentially interested in both, but this ticket aims to address a)

For a) The genetics portal presented information derived from the summary statistics. This feature was costly, as many data points needed to be carried over from the summary statistics. For b) The platform used to ingest the PheWAS catalog, which was eventually deprecated as it wasn't updated. Having a method to perform this analysis would make sense, but it's hard to assess how many new signals would be identified.

**Comment by buniello** [comment]
Notes from 13/11 scoping meeting:

1. **VARIANT PAGE PLOT:** Even w/o full summary statistics (just with cred sets), we can have a 'non-canonical' PheWas on variant page by plotting `diseases` associated with each `lead variant` from credible set table. 
This would be a modified version of this Phewas [plot in OTG](9b68d-46591).
- notes: we can represent `beta` directionality (+/-) when applicable with `arrow up` and `arrow down` (similar to OTG style). When beta is not available, we show circle instead.
- @carcruz suggested implementing the plot with the **section view toggle** option (table/plot)

@d0choa @addramir please add more here if needed

**Comment by buniello** [comment]
1. **CREDIBLE SET PAGE PLOT:** In a second iteration, we could build the same plot as above but on **credible set page** by plotting 
EFO `traits` (which need to be added back to the co-loc table) associated with the `Lead variant` filed in the **co-loc widget**
This would still be a modified version of this Phewas [plot in OTG](9b68d-46591).
- notes: we can represent `betaRatioSignAverage` (new directionality field) in a custom way based on this data points:
When betaRatioSignAverage in 9-1, -0.99) show Opposite directionality (fixed cred set vs co-loc)
When betaRatioSignAverage in (-0.99,0.99) or betaRatioSignAverage == null show Inconclusive directionality 
When betaRatioSignAverage in [0.99, 1] -> Same directionality

[more to add here when implementation starts]

**Comment by gjmcn** [comment]
@buniello, for the variant page plot, `study.diseases` is an array so each row of the table could potentially have multiple corresponding points on the plot. Is this ok? There is also the string `study.traitFromSource` which we could use instead but I don't know if this is appropriate and also this seems to be more granular or a less formal name so we could end up with lots of labels on the x-axis.

**Comment by buniello** [comment]
@gjmcn I think we want this plot to be EFO based, so using the `disease` data point is the right way to go. Also, each study can report results on multiple diseases so it's ok to have multiple points for each row. I tag @addramir for further comments (if needed)
