### ISSUE TITLE
Introducing a star system for credible sets

### ISSUE THREAD

**Issue by DSuveges** [opentargets/issues#3556]
As there are a huge number of available credible sets for variants/diseases/associations, we need to came up with some method to highlight our confidence in their varying quality. This ticket captures an initial attempt to do so.

Based on a previous discussion with @d0choa and @addramir the first prototype will implement a four star system where the following qualities are considered:

- 4 star: susie finemapped studies with in sample ld (eQTL catalogue, finngen)
- 3 star: susie finemapped studies with out sample ld (GWAS Catalog, UKB PPP)
- 2 star: PICS finemapped credible sets from summary statistics (GWAS Catalog)
- 1 star: PICS finemapped credible sets based on curated top loci from GWAS Catalog

The star assignment is captured upon integrating credible sets at the ETL, and based on the presence of certain QC flags. The resulting values are stored in the confidence column, [similarly as for CinVAr evidence](https://github.com/opentargets/json_schema/blob/51ca6f6a92c667513e5cb229d4c9fe7aea517e26/schemas/disease_target_evidence.json#L1772).

**Comment by ireneisdoomed** [comment]
@DSuveges Will this be propagated in the evidence? https://github.com/opentargets/issues/issues/3453#issuecomment-2383170912

**Comment by DSuveges** [comment]
It will be shown in the evidence widget, but I don't think we would score the disease to target confidence based on this.

**Comment by d0choa** [comment]
I agree—not for now. However, I would still name the column `confidence` of the type `list[str]` so it's consistent with evidence, and we can reserve the option to do it later. Also, it will simplify life in FE.

Also, we could consider whether the variants not in the LD reference alter our confidence in the credible set. I have no strong opinions just wondering.

**Comment by DSuveges** [comment]
For @opentargets/fe-team : In the credible set table, a new column will be introduced: `confidence`. This field captures how "good" a credible set is, not how good the l2g prediction, or how strong the association. The values in this field are enum, that can be translated to stars:

- `"Finemapped in-sample LD"` -> 4 stars
- `"Finemapped out-sample LD"` -> 3 stars
- `"PICS summary statistics"` -> 2 stars
- `"PICS top hit"` -> 1 star

The text can be shown in tool-tips. @d0choa , @buniello do you have any comment? 

Also, the confidence field can be shown on other tables with credible sets: evidence or study page, maybe coloc.
