### ISSUE TITLE
Summary Statistics QC step should return studyIndex

### ISSUE THREAD

**Issue by project-defiant** [opentargets/issues#3557]
As a **[user|developer|etc]** I want **<describe feature>** because **<reason>**

## Background

The expected schema of the studyIndex should add two columns
- sumStatQCPerformed - bool
- sumStatQCValues - Array<struct<key: str, v:float>>

Provide any necessary background information to provide context on the issue. 

## Tasks

- [ ] Update ...
- [ ] Configure ...

## Acceptance tests

How do we know the task is complete? 

1. When I go to page XX I see YY. 
2. When I click on 'foo' I see pop-up 'bar'

**Comment by addramir** [comment]
Overlaps with https://github.com/opentargets/issues/issues/3534
