### ISSUE TITLE
UI Components Refactor

### ISSUE THREAD

**Issue by carcruz** [opentargets/issues#3577]
# UI Components Refactor

EPIC: #3574 

### **Description:** 
Refactor key components as part of the UI refresh, including updates to the Table, SectionItem, and SectionSummary components. The goal is to improve functionality, maintainability, and visual consistency across the application.

### **Acceptance Criteria:**
- Start using the new table component implemented for client and server-side widgets.
- Optional features for the table are added, such as column control and column-specific filters.
- The SectionItem and SectionSummary components are updated to:
  - Support a view switch for different display modes.
  - Redefine the loading state for a smoother user experience.
  - Review and improve modularity for child components, with lazy-loading where applicable.

### **Features**
1. Implement the new table component with client and server-side capabilities.
2. Add optional features to the table, including column control and filters.
3. Update the SectionItem and SectionSummary components:
   - Introduce view switching.
   - Improve the loading state.
   - Enhance modularity and implement lazy-loading.

**Comment by chinmehta** [comment]
Current status of the task:

- [x] Start using the new table component implemented for client widgets.
- [ ] Start using the new table component implemented for server-side widgets.
- [x] Optional features for the table are added, such as column control and column-specific filters.

- The SectionItem and SectionSummary components are updated to:
  - [x] Support a view switch for different display modes.
  - [ ] Redefine the loading state for a smoother user experience.
  - [ ] Review and improve modularity for child components, with lazy-loading where applicable.
