### ISSUE TITLE
Genetics Variant page review

### ISSUE THREAD

**Issue by prashantuniyal02** [opentargets/issues#3601]
## General
- Displaying numeric data:
  - use numeric option in appropriate table columns (right-align, monospace font).
  - format large integers with commas wherever appropriate
  - round decimals wherever appropriate
- Fix sorting where possibility of NA in column - comparator function should return 0 when both values nullish; nullish values should be larger/smaller than all other values dependent on intuitive sort direction for column

### Header:
Widget order? 
- [ ] In silico (V) > VEP (V2G) > ClinVar (V2D) > Uniprot (V2D) > GWAS (V2L2D) > molQTL (V2G) > Pharmacogenetics (V2D2Dr)

### Metadata:
- ~~most severe consequence gene(s)?~~ [May be in 2.0]
- ~~Allelic frequency. Visualisation is odd. Numbers are relevant even on a log scale. Shall we be able to change from natural to log scale? Toggle?~~

### Overall about widgets:
- Save horizontal space [review data & number of rows]
-  Make sure top 25 rows is not an issue anywhere - pagination issues
- ~~Should we reuse the concept from Genetics of representing "V" "V-G" "V-D" in the top-right of the widgets? [not to be used in genetics widgets]~~
- Categorical filter of columns would help in many places (Table component work). e.g. Affected tissue / cell etc.

### In silico predictors:
- Description: [to be discussed offline]
- Tooltip for methods
- Format methods name
- Ideas?
- color ranges would need to be based on some information - @DSuveges to talk to FE #3503 

### Variant effect predictor:
- Description: [to be discussed offline]
- [ ] Compress Aminoacid change + Coding Change + Uniprot accession columns. When aminoacid change is not NA show within the predicted consequence column: `missense variant [R121Q]^?` Tooltip: Uniprot accession: [P19438](Link to uniprot using identifiers.org)

### GWAS Credible sets and molQTL credible sets (these changes also apply to the GWAS credible sets widget in the study page):
- Description: [to be discussed offline]
- [ ] Confidence (star system) #3605 
- [ ] Enhance [view] button UI. Title "View" and chavron?
- [ ] LD column? Drop
- [ ] Top L2G - (update to match the API )
- [ ] L2G score (continuous filled bar)
- [ ] Allow sorting by numeric columns (incl. posterior probability) (default p-value)
- [ ] Affected tissue/cell: to show actual tissue label (not the ID) (e.g. blood plasma) 
- [ ] molQTL source : Source [Open Targets](link to Open targets homepage)
- [ ] To add the condition to molQTL table

### PheWAS plot:
- to be scoped

**Comment by d0choa** [comment]
@chinmehta one extra bit:
- [ ] the default order of the VEP widget it would be by the column `transcriptIndex`. This column is not shown in the table, and we don't want it shown in the table (as it is derived from the combination of 2 existing columns). It means the user can not return to the original sorting if they start resorting to the table, but we think we are OK with that.

**Comment by d0choa** [comment]
Another small request:

In the VEP widget, we would like to expand the query to include the `biotype`

```
query VariantEffectPredictorQuery($variantId: String!) {
  variant(variantId: $variantId){
    id
    transcriptConsequences {
      variantConsequences {
        id
        label
      }
      aminoAcidChange
      uniprotAccessions
      codons
      distanceFromFootprint
      distanceFromTss
      target {
        id
        approvedSymbol
        biotype #### New column
      }
      impact
      consequenceScore
      transcriptIndex
      transcriptId
      lofteePrediction
      siftPrediction
      polyphenPrediction
    }
    referenceAllele
    alternateAllele
  }
}
```

Using the new response, we would like to be able to tag in the `Gene` column all genes that have `biotype` == `protein_coding`.

The most immediate UI I could think of is a chip displaying `protein coding` after the gene name and the tooltip. Probably an unfilled chip is more appropriate than the filled one, as we don't want to bring all the attention to it.

![Image](https://github.com/user-attachments/assets/e6cc203a-d9fd-4327-bad8-0a168d252e6c)

I'll gather more feedback from @buniello and others next week, but this should do the job.

**Comment by d0choa** [comment]
There is also a bug in the pharmacogenetics widget.

The next page shows no rows, but the API has some reasonable responses.

https://deploy-preview-524--ot-platform-partner.netlify.app/variant/7_117642566_G_A

There are some suspicious nulls in the `phenotypeFromSourceId` column that perhaps might cause this issue:

```
"pharmacogenomics": [
        {
          "genotypeId": "7_117642566_G_A,G",
          "isDirectTarget": false,
          "drugs": [
            {
              "drugFromSource": "ataluren",
              "drugId": "CHEMBL256997"
            }
          ],
          "phenotypeFromSourceId": null,
          "genotypeAnnotationText": "Patients with the rs77010898 AG genotype and cystic fibrosis may have improvement in chloride transport when treated with ataluren as compared to patients with the GG genotype. Randomized clinical trials found improvement in chloride transport, but did not find evidence for improved pulmonary function after 2 weeks of treatment. Other genetic and clinical factors may also influence changes in chloride transport and improvement of pulmonary symptoms in patients with cystic fibrosis.",
          "phenotypeText": "improvement in chloride transport",
          "pgxCategory": "other",
          "evidenceLevel": "3",
          "studyId": "1447954397",
          "literature": [
            "21233271",
            "18722008",
            "24836205",
            "20622033"
          ]
        },
```

Feel free

**Comment by d0choa** [comment]
One thing to try here (probably in separate PR) is to use a header of 2 rows in the credible set widgets.

For GWAS credible set:

| 2nd row header        | 1st row header |
| --------------------- | -------------- |
| More details          |                |
| Lead variant          |                |
| P-value               |                |
| Beta                  |                |
| Trait                 | Study          |
| Diseases              | Study          |
| Identifier            | Study          |
| Posterior probability | Fine-mapping   |
| Method                | Fine-mapping   |
| Confidence            | Fine-mapping   |
| Credible set size     | Fine-mapping   |
| Top gene              | Locus2gene     |
| Score                 | Locus2gene     |

For molQTL credible set:

| 2nd row header        | 1st row header |
| --------------------- | -------------- |
| More details          |                |
| Lead variant          |                |
| P-value               |                |
| Beta                  |                |
| Type                  | Study          |
| Affected gene         | Study          |
| Affected tissue/cell  | Study          |
| Condition             | Study          |
| Posterior probability | Fine-mapping   |
| Method                | Fine-mapping   |
| Confidence            | Fine-mapping   |
| Credible set size     | Fine-mapping   |
