### ISSUE TITLE
evidence_datasource_parsers: Update PROGENy.py module

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/issues#713]
There are several small changes that need to be done for the PROGENy.py evidence-generating module:
- [x] **Most importantly**: The json writing currently does not work properly and the evidence is therefore generated by saving the `print` output to the screen to a file
- [x] Should the 196 rows in the file be filtered by p-value? Only 140 rows have an adjusted p-value < 0.05. 
- [x] Add cancer type mappings:
```
'KICH': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0000335', 'label': 'kidney chromophobe'}, # EFO label: chromophobe renal cell carcinoma
'KIRP': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0000640', 'label': 'kidney renal papillary cell carcinoma'}, # EFO label: papillary renal cell carcinoma
'COREAD': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0005406', 'label': 'colorectoral adenoma'} # EFO label: colorectal adenoma
```
- [ ] There is a note in the module that "Pathway mapping has to be updated for JAK, STAT and Trail".
- [x] 3 of the 14 pathways (Androgen, Estrogen and WNT) have been added later and should be referenced using this manuscript: https://www.biorxiv.org/content/10.1101/532739v1
- [x] Check genes for PI3K pathway, currently both are mapped to the same gene:
`'PI3K': ['PIK3CA', 'PI3K(Class1)']` 
- [ ] Identify reactome pathway IDs for `Hypoxia` and `Trail`
- [ ] Confirm that `MAPK` and `p53` are supposed to both map to `R-HSA-2559580:Oxidative Stress Induced Senescence`
- [x] Activity is currently set as unknown - set to up- or down-regulated? Based on paper (p. 3, bottom right):
```
Positive logFC = activating driver mutation
Negative logFC = pathway suppression
```

**Comment by ireneisdoomed** [comment]
1. In rewriting the Progeny parser, the mappings between tumour type and EFO ID that were inside the parser have been revised and moved to [a table](https://github.com/opentargets/evidence_datasource_parsers/blob/master/resources/cancer2EFO_mappings.tsv) shared with intogen and slapenrich, with the same use case.

2. As for the data issues in the mapping of the reported pathway and its identifier in Reactome, we have also moved them to [a table](https://github.com/opentargets/evidence_datasource_parsers/blob/master/resources/pathway2Reactome_mappings.tsv) but they have not yet been reviewed. 
These will be addressed for the 21.06 release, if not for 21.04.

3. As they have been included in the systematic analysis done by Luz y Julio, we have decided not to apply any filtering on the p-value.

4. As for the activity comment, the `targetModulation` field in the schema covers this piece of information. Fold change is the number of times a gene is over or under expressed compared to some baseline. Therefore it seems reasonable to consider targets with a log FC > 0 as up-regulated and with a log FC < 0 as down-regulated.

**Comment by ireneisdoomed** [comment]
Note on the above mentioned point 4: PROGENy compares pathways activities between normal and tumor samples. Therefore, the value for the fold change refers to pathways and not targets. It would not be right to extrapolate this value to all targets involved.

**Comment by ktsirigos** [comment]
@ireneisdoomed  can this be closed?

**Comment by ireneisdoomed** [comment]
@ktsirigos No, # 2 is still not done. I'm adding it to 22.02.

**Comment by ireneisdoomed** [comment]
Regarding the pathway to Reactome ID mappings that we are unsure about, I've come up with suggested mappings and have contacted Chuqiao from Reactome to ask for feedback:

> PROGENy informs about pathway activity from gene expression data. The way we expose this in the Platform is by linking these pathways to the corresponding ID in Reactome. As I said, I've gone through these mappings and I would like to know your opinion to see if there are more fitting IDs:
Trail: R-HSA-109581 (Apoptosis). This is how Apoptosis is referred to in their publication.
-Hypoxia: R-HSA-1234158 (Regulation of gene expression by Hypoxia-inducible Factor)
-MAPK: R-HSA-9652817 (Signaling by MAPK mutants). The current mapping is R-HSA-2559580 (Oxidative Stress Induced Senescence). What do you think?
-p53: R-HSA-5633007 (Regulation of TP53 Activity).The current mapping is R-HSA-2559580 (Oxidative Stress Induced Senescence). What do you think?
-JAK-STAT: R-HSA-877300 (Interferon gamma signaling). The publication mentions the perturbation to be "Interferon-induced JAK-STAT". What do you think?
This is the PROGENy paper for context. https://www.nature.com/articles/s41467-017-02391-6.pdf

Until we conclude something , we are removing the placeholders for these cases where we are unsure. This is how the evidence will look in 22.02:

![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/a76a03ef-152a-416a-9a48-b9a4f2217dcd)
